### ISSUE TITLE
Localization/translation?

### ISSUE THREAD

**Issue by Repsionu** [nielsfaber/alarmo#1]
I know that this superb project is still in early beta stage :-)
But for everyday use by family it would be nice to have native language setup (OK thanks to lokalise we have a frontend native language for Alarm Panel at least)- as some of them are smart enough to add/delete something (with permissions but not enough English knowledge :-( )
That would make a great WAF effect :-)
Best, JR

**Comment by nielsfaber** [comment]
I am currently changing the frontend quite a bit, all texts in the panel will be loaded from a localize file.
So preparations are being made for supporting multi-language UI.

I think its still a bit early-stage to start rolling out translations though...
Chances are that the files need to be revised often.

Eventually this is up to the volunteers/enthousiasts themselves to decide... 
I will keep you posted if I have made more progress here.

**Comment by nielsfaber** [comment]
Are you still interested in using Alarmo and helping out with the translation?
I think in the meantime the 'dust has settled', the UI will not change much now.

**Comment by mccoy88f** [comment]
Hi, i can help you to translate in italian if you want.
Contact me if you want :-)

**Comment by nielsfaber** [comment]
@mccoy88f if you want to contribute with a translation, please take this file as starting point: https://raw.githubusercontent.com/nielsfaber/alarmo/main/custom_components/alarmo/frontend/localize/languages/en.json

If you replace all texts by Italian translation, it can be added.
You can also propose improvements for the original English file.

**Comment by mccoy88f** [comment]
Ok i Will work on It this night 💪

**Comment by mccoy88f** [comment]
Is there a way to test it locally on my ha? I have a alpha version :-)

**Comment by nielsfaber** [comment]
> Is there a way to test it locally on my ha? I have a alpha version :-)

Yes there is, but it is not trivial.
If you make a full checkout of this repository, you can make changes to the frontend.
You will need to have node.js / npm + some packages to be able to work with it.
If you run `npm install` and then `npm start` (from the /frontend/ directory), the script should automatically recompile the typescript files when you make a change.
You could replace the `en.json` with your italian version, or add yours and update the `localize.ts`.

If you don't want to go through this trouble, you can also just open a PR with your `it.json`. 
You can see the results when a next update is released.

**Comment by nielsfaber** [comment]
I will close this issue since the translation of @Repsionu is now in place.
More translations are always welcome, if help is needed let me know.

**Comment by mccoy88f** [comment]
Hi.
This is the translation in italian.
After the next update i will verify and correct it if needed.
My user on github is mccoy88f and my name is Antonello Migliorelli
Thanks a lot for your work
If there is something more to translate please let me know

Il giorno mer 16 dic 2020 alle ore 08:16 Niels Faber <
notifications@github.com> ha scritto:

**Comment by mccoy88f** [comment]
This is my italian translation add to next version to test it:
https://pastebin.com/tTdxaZH2
Thanks
