### ISSUE TITLE
Two (or more) kind of push messages

### ISSUE THREAD

**Issue by Sag06** [nielsfaber/alarmo#10]
Not sure if people do, but I use two categories for push messages. Both with Telegram groups. One "triggered alarm", very loud sound and another low sound notification to rest of notifications like armed, no armed, etc.  Push messages "when something changes in the alarm" could be heart dangerous IMHO. I would like two targets for push messages at least and the possibility to choose among them.  By now I have a workaround with automations.

**Comment by nielsfaber** [comment]
Please upgrade to v1.1.0.
It allows you to customize notifications.

I'm thinking about adding a feature to adapt the target based on the code that was entered.
If Mr. and Mrs. Sag06 have their own pincode for arming/disarming, I could make sure the right person gets the message.
I see it useful in my own house, but would like to know if it opens some doors for others as well...

**Comment by nielsfaber** [comment]
I'm closing this issue because the requested functionality is added now.
Let me know if you have issues setting it up.
