### ISSUE TITLE
Logs?

### ISSUE THREAD

**Issue by lancelon** [nielsfaber/alarmo#100]
Love the integration thanks so much for it. It's so slick compared to good old bwalarm. The only thing I'm missing is the tablet friendly arm/disarm screen that bwalarm had.

Quick query: is there a log anywhere for Alarmo? The documentation makes reference to it but I can't find one anywhere.

Thanks

**Comment by nielsfaber** [comment]
Alarm Iogs should appear in the home assistant log.
It’s not very common for a component to have it’s own separated log, but it may be added at some point.

Alarmo focuses on the easy of configuration rather than providing a GUI for operation of the alarm (as BWalarm does).
There are many Lovelace cards available which you can use to create your own panel. It seems like the way forward.
I might consider adding an Alarmo-specific keypad card since I think the default one has some quirks.

**Comment by lancelon** [comment]
Thanks.  The reason I wondered if it had separate logs I noticed an employee tried to arm the alarm yesterday and it wouldn't arm because of open sensors but couldn't see that the reason got spat out anywhere. I had a look in the HA logs but couldn't see anything.

**Comment by nielsfaber** [comment]
This is what should be logged when you arm the system:
> 
2021-01-20 18:38:44 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Alarm is now arming. Waiting for 30 seconds.

Followed by this message (after the exit delay) in case there are open sensors:
> 
2021-01-20 18:39:14 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot transition from state arming to state armed_away, there are open sensors

The details of which sensors + their states can be found in the entity attributes:
![image](https://user-images.githubusercontent.com/16861605/105213742-5dd95400-5b4f-11eb-909c-bbb006dc08c1.png)

I recommend to either send a push message or having a wall panel display for sharing this info with the end-user.

**Comment by lancelon** [comment]
> 2021-01-20 18:38:44 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Alarm is now arming. Waiting for 30 seconds.

Interesting - Alarmo doesn't seem to log a thing on my system, as I thought. I'm looking at this URL:
http://homeassistant.local:8123/config/logs

Is it possible you've got some kind of logging enabled as the dev that users don't automatically have setup?

**Comment by nielsfaber** [comment]
You can set the log level in configuration.yaml. Also you can use a custom log level for components.
E.g.:
```
logger:
  default: info
  logs:
    custom_components.alarmo: debug
```
Most useful loggings for alarmo have log level `info`.
I use `debug` for development purposes/troubleshooting.

**Comment by nielsfaber** [comment]
I'm closing this issue, assuming that your question is answered.
Please use GitHub issues only for bugs and feature requests.
Questions can be asked through the forum thread: https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910
