### ISSUE TITLE
Alarm area groups

### ISSUE THREAD

**Issue by photoventures** [nielsfaber/alarmo#1002]
It would be useful to have "area groups", so that one single panel can activate or control multiple areas. At the moment the practical definition of areas is closer to an independent alarm panel (each). This is limiting for users that may want to have one code/panel for a few areas (perimeters) and another for one or two odd areas that might be accessed from the other area but be treated differently.

It would also be helpful to apply the same mode to different areas at once, without requiring doing so with every single one of them separately.

### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Proposal
Support groups of areas that share a common code and panel, or can be armed all at once.

**Comment by kitty99hub** [comment]
push request to not been closed ;)

**Comment by kitty99hub** [comment]
Push
