### ISSUE TITLE
Triggering while disarmed

### ISSUE THREAD

**Issue by jsamr** [nielsfaber/alarmo#1003]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.7.3

### Bug description

Alarmo triggered while it was disarmed after host reboot. It was a "graceful" reboot, no power outage. 

![image](https://github.com/user-attachments/assets/ea7041ff-3291-4edd-91ad-506d28b9cb62)

### Steps to reproduce

- Disarmed from a lovelace card;
- Shut down host during night;
- Booted host this morning;
- Alarm was triggered after an associated sensor was activated later this morning.

**Comment by jsamr** [comment]
@nielsfaber But as shown in the screenshot, the alarm has been triggered while it was disarmed; this is the behavior I am not expecting. I am confused as to how a change in a sensor state would affect this behavior?

**Comment by jsamr** [comment]
OK, so it seems the logbook is incomplete. It is lacking this "armed night" entry that can be seen in the history chart below:
![image](https://github.com/user-attachments/assets/af0b43c4-054d-4758-a3ba-2a77173bcc2b)

This is what is confusing me:

1. I haven't enabled the alarm at this time;
2. No logbook entry for this state change, as can be seen in the above screenshot.

I understand there is little context to make this ticket actionable. I will report if this happens again.

**Comment by nielsfaber** [comment]
It would be useful if you manage to reproduce what happened this morning.
Something must have armed the alarm and something must have triggered it later, so multiple things went wrong.
For the triggering of the alarm it may be wise to check if your sensors are configured to trigger the alarm in the unavailable state, this is a per-sensor setting.
For the unexpected arming I have no idea, perhaps some automation or MQTT command?
If you have any clues something is wrong on alarmo’s side, please share your findings.

**Comment by jsamr** [comment]
@nielsfaber I don't have any automations set up to automatically arm this device; that is what baffles me. Because it seems to have armed itself after the host was booted again (it went offline for the entire night), my intuition was that it could have been something related to persistence. Indeed, it had been armed in "night mode" the evening before this incident, and had afterward been disabled. Is there any persistence layer that Alarmo uses which may have been faulty? Although definitely interested, I haven't written custom components yet, so I am not well versed in internal HA and HACS concepts.
