### ISSUE TITLE
Alarmo didn't warn when Door/Windows is open

### ISSUE THREAD

**Issue by SmyBleck** [nielsfaber/alarmo#1004]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

 1.10.4

### HA Version

2024.7.3

### Bug description

Hi,
I think since last update, Alarmo didn't work when it detect my captor (door or windows) are open
In Alarmo configuration, when i open a door > It detect but don't launch actions

### Steps to reproduce

Activate alarmo with notification when door or windows is open when alarm is ON
Open a door
Alarmo didn't warn an intrusion

**Comment by Stubbs** [comment]
I'm also seeing the same thing on 1.10.0, except I only get it when I bypass the exit deloy & go straight to armed.
