### ISSUE TITLE
Sensor pulse count

### ISSUE THREAD

**Issue by michalkrejci1** [nielsfaber/alarmo#1007]
### Checklist
- [ Sensor pulse count] I checked for similar existing requests (both open and closed) before posting.
- [ yes, profi alarm systems have this option ] My request is generic, other users may benefit from it too.

### Proposal
Please consider whether it would be possible to add a "pulse count" option somewhere, preferably in the advanced settings for an individual sensor.

I have used this feature on some "HW" alarms and some sensors can do it too (hw jumper - two pulse=alarm)

If I'm typically using a PIR that can't do some sort of false alarm filter, it would be absolutely perfect if this system added this functionality.

That is, the number of pulses a sensor has before its signal is considered valid.

Many thanks for considering this functionality.
Michal

**Comment by marazmarci** [comment]
Some preliminary detection delay* could be more useful for motion sensors to filter out false positives, similar to the entry delay, but with the difference that if it stops detecting motion before the delay expires, it won't trigger the alarm.

(*: alternatively, it could be described as hold time or debounce time)

**Comment by michalkrejci1** [comment]
Hi, yes. That sounds reasonable, basically a spider crawls over the PIS and creates a single pulse, should the pulse occur before the resetable timer expires it will trigger an alarm, if not within x seconds the timer will restart.

That would be about right.

Thank you, Michal
