### ISSUE TITLE
Add automation start/stop to alarm state change actions

### ISSUE THREAD

**Issue by trantoriana** [nielsfaber/alarmo#1009]
Hi,

In addition to simply turning on a light or a switch it would be great to be able to start or stop a existing automation as part of the alarm state events.

Allowing this make a far more versatile way of enabling sound, flashing lights, media playing, etc all at the users discretion and imagination.

Thanks for consideration,

Trant

**Comment by kitty99hub** [comment]
Hi,
good idea, I would love to be able to use it too.
Thanks

**Comment by kitty99hub** [comment]
push request to not been closed ;)

**Comment by kitty99hub** [comment]
Push
