### ISSUE TITLE
Consider adding Area column to Sensors list

### ISSUE THREAD

**Issue by luckypants123** [nielsfaber/alarmo#101]
Really like how 1.5 is shaping up!

Just a thought as I was adding sensors to an area - it isn't immediately apparent at a glance which currently configured sensors are assigned to specific areas. Maybe an additional column between Arm Modes and Enabled? 

| Entity          | Arm Modes |  Area  | Enabled |
|-----------------|:---------:|:------:|:-------:|
| vehdoor contact |    Away   | Garage |   True  |
| front door      | Away      | Home   | True    |

Or some implementation of the dropdown selects you use in other places?

Just a thought. Great work on this.

**Comment by nielsfaber** [comment]
100% agreed on this one.
Just wanted to push out the beta to get some feedback for the final touches.

In the areas view there’s already a summary of assigned sensors and automations, ideally I want to make them links that bring you to a filtered view of the sensor/actions pages.
This would probably go well with a dropdown on the top for filtering by area, and highlighting sensors which are unassigned.

Stay tuned for more and let me know if you have more ideas 🙂

**Comment by nielsfaber** [comment]
Hi,
Small update on this.

On the sensors + actions page I added filter buttons:
![image](https://user-images.githubusercontent.com/16861605/105742158-6d83de80-5f3b-11eb-966e-1f119971d0d9.png)

On the areas page I added shortcuts to these filters:
![image](https://user-images.githubusercontent.com/16861605/105742206-7ecceb00-5f3b-11eb-8e5f-be41cee5c2b9.png)

It should look the same for you if you update to the v1.5.0 (non-beta) release 👍

**Comment by luckypants123** [comment]
Nice! That should work a treat - I’ll update tonight!
