### ISSUE TITLE
Support for Multi-Device Notifications

### ISSUE THREAD

**Issue by romakev** [nielsfaber/alarmo#1018]
Hello,
I would like to propose an enhancement for the Alarmo notifications.

Currently, when we want to send a notification to multiple devices, we have to create separate notifications for each target device. This method is cumbersome and complicates notification management, especially when dealing with numerous devices.

Requested Feature:

I propose adding the ability to send a notification to multiple devices in a single action. Here are a few ideas on how this could be implemented:

- Add a field in the interface where multiple destination devices can be selected.

-Allow sending the same notification to all selected devices simultaneously.

This would simplify notification management and improve user experience by reducing the need for duplications and multiple configurations.

Thank you in advance for your consideration.

Best regards,

Romakev

**Comment by roblamoreaux** [comment]
Have you looked into notification groups?

I use a notification group called Alarmgroup for this.
