### ISSUE TITLE
Not able to open the administration page

### ISSUE THREAD

**Issue by apocaliss92** [nielsfaber/alarmo#1021]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.8.3

### Bug description

When I try to open the page, it gets as blank with the following error in console

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "settings-row" has already been used with this registry

Could it be this plugin declares something conflicting with other plugins?

### Steps to reproduce

Just open the administration page

**Comment by nielsfaber** [comment]
> Could it be this plugin declares something conflicting with other plugins?

Yes, this is most likely the cause.
Any idea which other plugin could be causing this?

**Comment by apocaliss92** [comment]
Scheduler card v4 broke this for me

**Comment by nielsfaber** [comment]
I updated alarmo with custom elements that have unique naming. I hope that updating to v1.10.5 will solve the issue for you.
Note that after updating you might need to clear your cache before the changes are adopted by your browser. The version number is displayed in the top-right corner of the alarmo configuration panel.
Please try updating and close the issue if this is resolved for you.

**Comment by apocaliss92** [comment]
Thank you very much for the fix, seems working now!
