### ISSUE TITLE
Separate Code Requirement for each arm mode

### ISSUE THREAD

**Issue by FrankGiesecke** [nielsfaber/alarmo#1026]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
It would be great if the setting "Require code for arming/disarming" can be defined for each arm mode.

I'd like to secure all arm modes except the 'armed_home' mode with a code.

### Additional info
The reason for this is, that I want to enable my kids to activate the 'armed_home', even if they can not handle the code. In my setup, this can only be done from any device inside of our home.
All external device are unable to access home assistant in a direct way.

**Comment by FrankGiesecke** [comment]
This is still requested

**Comment by FrankGiesecke** [comment]
This is still requested

**Comment by jamesg226** [comment]
A great workaround would be a button card that triggers an automation with a code to alarm hode. I am doing this with Aqara Zigbee buttons to set the alarm into home mode with an auto code that can only be used to set the alarm.
