### ISSUE TITLE
Force trigger alarm

### ISSUE THREAD

**Issue by DevSecNinja** [nielsfaber/alarmo#1029]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I would like to force trigger the alarm. I have made an actionable notification that pops up on my iPhone and watch when the front door opens that gives options to arm home, arm away but I would like to make an option to force trigger in case I didn't open the front door.

### Additional info
Allow an action like `ALARMO_FORCE_TRIGGER`.

**Comment by DevSecNinja** [comment]
Not stale

**Comment by nielsfaber** [comment]
You can already do this via service `alarm_control_panel.alarm_trigger`

**Comment by DevSecNinja** [comment]
Thanks @nielsfaber! Alarmo works really well, thanks for making it!
