### ISSUE TITLE
Double (same) sensor activation

### ISSUE THREAD

**Issue by AriaGen** [nielsfaber/alarmo#1032]
I have cats, and while most the time they don't activate the PIR's, they do. so I love that I can group sensors, so that 2 in the same group have to be activated for a trigger, I would like to propose the option for the 2/3 (optional) activations to be of the same sensor within that time frame, which will allow for a false positive of the cats but if someone is actually hanging around in the same room I will get a trigger.

**Comment by nielsfaber** [comment]
I don't have cats or dogs, so personally I have no experience with this.
How would one ensure that a pet walking around in the house would only trigger a sensor once in a timeframe?
In principle they could walk back and forth all day long hence the alarm would still be triggered on the second movement, right?

Additionally this feature would delay the triggering of the alarm also in case of a real burglar entering the house.
I have sensors that remain triggered for around 30 seconds after moment is detected, so a time filter would have to be set higher than this. 
In this time the burglar could already have made his way through the house, so I wouldn't be comfortable setting a time filter like this.
What are your thoughts about this?

**Comment by AriaGen** [comment]
Sorry for thr delay getting back to this, I've not had the time.

I guess with your first question, you can't, It may depend on the animal you keep and how active they are over the night,. My cats are ether out "hunting" or asleep on the sofa. I'm also pretty confident, that really most of my sensors don't typically pick them up too. Since setting up the duel sensors, they've only ever triggered it once.

For me, my sensors are quite rapid, so I think a rapid, double hit, in theory, would trigger an activation faster than waiting for the intruder to enter another room and hit a 2nd sensor.

I feel like if we could group the ones seprately from the duel sensor thing, or set up as a per sensor basis, then would still be able to keep the sensors that I beleive the cats can activate.

Thanks for taking the time to have a think about my request :)
