### ISSUE TITLE
Event triggers alarm

### ISSUE THREAD

**Issue by cappa88** [nielsfaber/alarmo#1033]
Hi,

First of all, I want to thank you for your hard work on Alarmo! I've been using it with my Home Assistant setup, and it’s been incredibly helpful.

I wanted to offer a small suggestion, though I’m not sure if it would be feasible to implement. Currently, when activating the alarm, there’s a countdown period (N seconds to leave the house). I was wondering if it would be possible to introduce an option where the alarm could be triggered not by a timer, but by a specific event instead. For example, the alarm could arm itself when a door is closed, or N minutes after the door is closed, or even based on any other event.

I believe this additional flexibility could make Alarmo even more versatile. I understand that this might not be easy to implement, but I thought it might be a useful improvement to consider.

Thanks again for your hard work and dedication!

**Comment by AriaGen** [comment]
Under sensor advance options,
For example, If I close my front door during the arming timer countdown, it bypasses the rest of the timer and skips straight to armed.

![image](https://github.com/user-attachments/assets/99c7a8de-507b-4ef8-80f8-68f4f7d7306c)

**Comment by cappa88** [comment]
Thank you for your reply!

I understand that the arming timer can be bypassed if I close the door during the countdown. However, this approach still doesn’t fully address my use case. Even with the maximum arming delay of 5 minutes, I’m still constrained by a time limit to leave the house once I press the activation button. After I close the door, the alarm is immediately armed.

What I’m suggesting is slightly different. I would like the alarm to arm after a certain amount of time has passed with the door remaining closed, rather than arming immediately when the door is closed. This way, once I press the activation button, I would have as much time as I need to leave the house. If I need to re-enter within that time frame, I wouldn’t need to disarm and rearm the system. I could simply open the door to interrupt the arming process, and the timer would automatically restart once the door is closed again.

This would provide more flexibility, as I wouldn’t be forced to disarm the alarm for quick tasks like re-entering the house. I hope this explanation better clarifies my suggestion!

Thanks again for considering this.

**Comment by AriaGen** [comment]
Ohh okay, Sorry I must have mis-understood. What you're after then is more of a unlimited exit delay timer then.

May I suggest a possible tempary solution until the devs get back to you. Maybe a automation in HA, a input_boolean helper that you switch on, then the automation just awaits your door to close then pass the arm code through to the panel.

Like so?

`
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.wait_for_door
    from: "off"
    to: "on"
condition: []
action:
  - wait_for_trigger:
      - type: not_opened
        platform: device
        device_id: 4b6b254449ee07fa7a64032528a5bf7f
        entity_id: b575342c08975b413cdea7227d0306da
        domain: binary_sensor
    continue_on_timeout: false
  - action: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.house_alarm
    data:
      code: "0000"
`
