### ISSUE TITLE
Deprecated constant which will be removed in HA Core 2025.10

### ISSUE THREAD

**Issue by codyc1515** [nielsfaber/alarmo#1035]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.10.0b5

### Bug description

There are constants used that will be deprecated in HA Core 2025.10.

### Steps to reproduce

Happens on boot.

### Relevant log output

```shell
Logger: homeassistant.const
Source: helpers/deprecation.py:197
First occurred: 08:04:51 (2 occurrences)
Last logged: 08:04:51

STATE_LOCKED was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'alarmo' custom integration
STATE_UNLOCKED was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'alarmo' custom integration
```

**Comment by nielsfaber** [comment]
Thanks for reporting this issue. I made a fix for it (https://github.com/nielsfaber/alarmo/commit/eb9f73df6f26f51f2f4c1d227b2d6fbd65d4fa92) and will include it in the next release.
