### ISSUE TITLE
Trigger alarm when open windows get closed (not only when closed windows get open)

### ISSUE THREAD

**Issue by hajar97** [nielsfaber/alarmo#1038]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Currently alarm is only triggered when windows are open from close state. In advanced settings it is possible to ignore initially open state of the window when arming. For such windows, it then should be possible to trigger alarm when they get closed while initially they were open during the arming.

### Additional info
Either trigger alarm on windows regardless of their initial state (preferred). So if they were closed and got opened when armed alarm should trigger. But equally if they were open when armed, alarm should trigger when they are closed.

Alternatively, make it configurable if to raise alarm when initially open windows get closed (less preferred).

**Comment by nielsfaber** [comment]
In alarmo a window being closed is considered safe, likewise a window being open is considered unsafe.
If you want to invert this, you will have to use a template binary sensor that will have the opposite state.
See https://www.home-assistant.io/integrations/template/.

**Comment by hajar97** [comment]
If house is armed inside, e.g. night arm then indeed there can be people inside to close the window (considered safe). But if house is locked outside, nobody is supposedly in the house, if someone closes the window it should trigger the alarm. Is it possible to add a feature that would enable configuration controling if Alarmo reacts to Toggle of window (open or close) or only to open?On 19 Oct 2024, at 07:22, Niels Faber ***@***.***> wrote:﻿
In alarmo a window being closed is considered safe, likewise a window being open is considered unsafe.
If you want to invert this, you will have to use a template binary sensor that will have the opposite state.
See https://www.home-assistant.io/integrations/template/.
