### ISSUE TITLE
Create Event for triggered alarm like failed_to_arm

### ISSUE THREAD

**Issue by lexusburn** [nielsfaber/alarmo#1046]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Instead of using the internal feature to send a notification, i would like to handle it with home assistant default automations. Because then i can do something like call ai, write a custom message and do something more.
But i would like to get the triggered sensors, like you do with {{open_sensors}}

### Additional info
none

**Comment by nielsfaber** [comment]
Its literally described in the documentation how you can do this.
See https://github.com/nielsfaber/alarmo?tab=readme-ov-file#advanced-actions
