### ISSUE TITLE
Templating stopped working

### ISSUE THREAD

**Issue by VNRARA** [nielsfaber/alarmo#1047]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.15

### HA Version

2024.10.2

### Bug description

Templates in notification messages stopped working. It shows all as raw text now.

### Steps to reproduce

Create a notification with templates in it.

**Comment by KameDomotics** [comment]
Is it possible to add this feature?
