### ISSUE TITLE
Codes - alternative names

### ISSUE THREAD

**Issue by Solandus** [nielsfaber/alarmo#1048]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Add an alternative name field to codes that can be used e.g. for notifications.
Think of having two people with the exact same name. Makes it difficult to manage (how do you know which one is which). By adding an alternative name that can be used in notifications, you could have a clear view with distinctive names for managing the codes but having nice not awkward sounding alternative names for notifications.

### Additional info
Add a second "alternative name" field under the normal "name" field in code managing.
Having another placeholder "Changed By Alternative" in actions - notifications.

**Comment by nielsfaber** [comment]
I'm sorry but I don't really understand the request.
In alarmo the main use of the name/code combination is that it is possible to identify the person based on the code which was entered.
As a consequence the names should be distinctive. 
Why should a different name be used in notifications than the name defined in the code management? Wouldn't it be more confusing?

**Comment by Solandus** [comment]
Let us assume we have two Williams in one household. To differentiate them in code management I would call them William 1 and William 2. This would cause notifications send to an Speaker with a greeting message always to say "Hey William 1", "Hey William 2". Which you can do but isn't very nice.
Vice versa I could call both codes just "William" but with them having different codes, it's not very handy to have two entries called "William" in the code management list, how would I know who is whom.

**Comment by nielsfaber** [comment]
As said, in alarmo the name is mainly used to identify which person armed/disarmed the alarm.
If a notification would state "Alarm was armed by William" it is not very informative in case there could be 2 Williams.
Hence I think adding a field for alternative names for usage within notification doesn't really help.
I still would suggest to use unique names, also in the code configuration. 
Whether you call them "William 1" and "William 2" or "William A." and "William B." is up to your own preference.
