### ISSUE TITLE
french translation

### ISSUE THREAD

**Issue by Patrick44fr** [nielsfaber/alarmo#105]
Hello, I am an alarm user who is really great. I saw that there was an evoution in development to change languages, it's really very good.

I put at your disposal the file translated into French
well done for the job. 

excuse my broken english
[fr_json.txt](https://github.com/nielsfaber/alarmo/files/5860431/fr_json.txt)

**Comment by nielsfaber** [comment]
Could you make a pull request for the translation?
You can simply click "create file" [here](https://github.com/nielsfaber/alarmo/tree/main/custom_components/alarmo/frontend/localize/languages)
Thanks!
