### ISSUE TITLE
Wildcard not filling in for disarming

### ISSUE THREAD

**Issue by thenextbutton** [nielsfaber/alarmo#1052]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.6

### HA Version

2024.10.3

### Bug description

Notification for Disarming does not fill in the wildcard information, I use the same template for armed and disarmed.

on arming the notification comes through as 'Motion Sensors are set to Armed away' on disarming I receive 'Motion Sensors are set to '

### Steps to reproduce

service: notify.everyone
entity_id: null
data:
  message: Motion Sensors are set to {{arm_mode}}
  title: "{{ now().strftime('%H:%M %a %d %b %Y') }}"

**Comment by nielsfaber** [comment]
Not a bug. Disarmed state has no arm mode.
