### ISSUE TITLE
"Armed Away" disarms itself the moment the exit delay hits zero

### ISSUE THREAD

**Issue by Obioban** [nielsfaber/alarmo#1053]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

1.10.06

### HA Version

2024.10.3

### Bug description

"Armed Away" disarms itself the moment the exit delay hits zero.

"Armed Home" works normally/as you'd expect (arms when the exit delay hits zero). 

### Steps to reproduce

Armed the alarm. 
Wait the exit delay. 
Watch alarmo be disarmed. 

### Relevant log output

```shell
Log is useless. It just says, "Alarmo was disarmed" with no context as to what is causing it to occur.
```

**Comment by nielsfaber** [comment]
Install the alarmo-card, it will show the reason why arming failed.
