### ISSUE TITLE
Doesn’t Show Z2M Binary Door Sensors

### ISSUE THREAD

**Issue by duckdude555** [nielsfaber/alarmo#1054]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.6

### HA Version

2024.10.3

### Bug description

Transitioned my Zigbee devices (including Aqara binary door/window sensors) to Zigbee2MQTT. Sensors show up properly in the MQTT integration as a “door” sensor and with an entity ID prefix of “binary_sensor”, but none of the sensors show up in the list to add in Alarmo. 

List of few binary_sensors, none show up in Alarmo as sensors I can add:
![IMG_0055](https://github.com/user-attachments/assets/4618c3e8-d578-4461-a594-f6450d85427a)

Select sensor details:
![IMG_0056](https://github.com/user-attachments/assets/68995057-7645-4b24-9779-f4a962e98cea)

Please let me know what else I can provide. Thank you!

### Steps to reproduce

Add Aqara door sensor via Z2MQTT

### Relevant log output

```shell
N/A
```

**Comment by nielsfaber** [comment]
Could you check the sensors page in Alarmo? **All** binary sensors should show up here, especially if you click this banner
![image](https://github.com/user-attachments/assets/aa565a5f-59df-4d8a-bffd-1f24087339e0)
Are you sure the sensors are not already included in alarmo?

**Comment by duckdude555** [comment]
Well, this is embarrassing. Yes - I checked the sensors page and removed the filters and verified they didn’t show up yesterday, but checking this morning they now appear! Odd that they took ~12 hours to appear, but that very well could be an Z2M issue. Thank you!
