### ISSUE TITLE
Delay-config not working correctly on subsequent zones

### ISSUE THREAD

**Issue by bf8392** [nielsfaber/alarmo#1058]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.6

### HA Version

2024.10.4

### Bug description

I have multiple zones configured, and when I arm master, or the two subsequent zones, they have a delay without having it configured. It only happens for "armed away"

### Steps to reproduce

Make multiple zones (3) and activate "armed away". Configure a delay of zero for armed away on all three zones...arm all of them seperately (some will still have a delay on arming)

### Relevant log output

```shell
none found
```

**Comment by nielsfaber** [comment]
> Make multiple zones (3) and activate "armed away". Configure a delay of zero for armed away on all three zones...arm all of them seperately (some will still have a delay on arming)

Here's my attempt to reproduce this.

**Zone 1 configuration:**
<img src="https://github.com/user-attachments/assets/43786bcf-242d-4fd2-9b85-8a7e0c40fdbc" width="75%" height="75%">

**Zone 2 configuration:**
<img src="https://github.com/user-attachments/assets/a378fe90-1190-4eb2-a55b-4b840c3c821b" width="75%" height="75%">

**Zone 3 configuration:**
<img src="https://github.com/user-attachments/assets/fc8a84db-66e5-486c-acf6-cfaead4ee870" width="75%" height="75%">

**Arming test:**
https://github.com/user-attachments/assets/bab4245e-d2aa-4e18-9497-37ab97109ae4

For me all works instantly as expected. I am not experiencing any bug here.
Perhaps what you are experiencing is some processing delay of the hardware on which HA is running? I don't know how much delay we are talking about. Videos and screenshots may help illustrating the issue.

Please try to isolate the issue, for example by making dummy zones without any sensors in it (as I did for this test). Maybe it is dependent on your usage. 
I cannot really help with this issue without more insight.
