### ISSUE TITLE
Only trigger alarm on movement / opening, not when sensor becomes unavailable (less safe, also less annoying)

### ISSUE THREAD

**Issue by iroQuai** [nielsfaber/alarmo#1059]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
**Current behavior:**
Alarm triggers when binary sensor state turns to "on" (movement, open, etc), but also when sensor becomes unavailable (for instance when battery is empty)

**Proposed behavior:**
Alarm only trigger when binary sensor state turns to on, but not when sensor becomes unavailable. 

### Additional info
**Reason:**
for some reason the alarm triggered multiple times now in the middle of the night because a sensor was off the zigbee grid for a short time. Wakes me up for nothing :(

I tried fixing the zigbee network, but it's not 100% successful. Also the changes in temprature influence the battery of some sensors too so they suddenly seem empty.

**Less secure**
I do realize this option is less secure: this way if someone tampers with a sensor or the zigbee network itself, the alarm won't go off. For me, this would be a trade off that is worth while: getting waked by a false positive too many times is annoying, and I really do not expect someone to mess with this alarm installation on purpose; it's just an extra measure for sneak ins or break ins, but a serious alternative for a real alarm installation for us. 

As long as the security trade off is stated clearly, I think this would be an interesting option to offer. 

Hopefully I'm not the only one that looks for something like this!

**Comment by nielsfaber** [comment]
Just turn off this setting to do so:
![image](https://github.com/user-attachments/assets/43be434d-0cf2-4706-a682-ddf0e9ea374f)

**Comment by iroQuai** [comment]
Wow I missed that completely!! Thanks a lot :)
