### ISSUE TITLE
Error en Alarmo en Mensaje de alarma disparada con Echo Dot en español

### ISSUE THREAD

**Issue by ParabolicArts** [nielsfaber/alarmo#1065]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

 v1.10.6

### HA Version

Core 2024.11.1 Supervisor 2024.11.2

### Bug description

YAML:

service: notify.alexa_media_bajo_echo_dot_de_parabolicarts
entity_id: null
data:
  message: "¡Se ha disparado la alarma! Causa: {{open_sensors|lang=es}}."
  title: Alarma Noche Disparada

ERROR:

Something went wrong!
Message format incorrect: string value is None for dictionary value @ data['actions'][0]['entity_id']

Response error: 400

Please [report](https://github.com/nielsfaber/alarmo/issues) the bug.

### Steps to reproduce

El error te lo notifica Alarmo al intentar guardar .

**Comment by nielsfaber** [comment]
We speak English here.
