### ISSUE TITLE
V1.10.7 not working with HA.2024.10.3

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [nielsfaber/alarmo#1067]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

1.10.6

### HA Version

2024.10.3

### Bug description

V1.0.7 not works with 2024.10.4.

Again nothing about this is stated in the release notes and also not got prevented that the update shows up on HA versions below 2024.11. This is now 3rd time it is happening like this 

### Steps to reproduce

Try to update to V1.10.7 with HA version below 2024.11

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:09:41 (1 occurrences)
Last logged: 08:09:41

[281471611787088] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 1436, in async_download_repository
    await self.async_install(version=ref)
  File "/config/custom_components/hacs/repositories/base.py", line 884, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 931, in async_install_repository
    raise HacsException("The version of Home Assistant is not compatible with this version")
custom_components.hacs.exceptions.HacsException: The version of Home Assistant is not compatible with this version

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hacs/update.py", line 88, in async_install
    await self.repository.async_download_repository(ref=version or self.latest_version)
  File "/config/custom_components/hacs/repositories/base.py", line 1438, in async_download_repository
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Downloading nielsfaber/alarmo with version v1.10.7 failed with (The version of Home Assistant is not compatible with this version)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 463, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 90, in async_install
    raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: Downloading nielsfaber/alarmo with version v1.10.7 failed with (The version of Home Assistant is not compatible with this version)
```

**Comment by nielsfaber** [comment]
The minimum required HA version for this release is mentioned in the hacs.json file: https://github.com/nielsfaber/alarmo/blob/64368ff62b8e7452f45e0fda414a5652a1403be4/hacs.json#L7
If you use HACS, it should not show the 1.10.7 release as update candidate.
If you install manually, you will need to do the compatibility check manually as well.
Note that the release notes does contain a mentioning of HA 2024.11, but I agree that it does not explicitly mention this requirement.

**Comment by smarthomefamilyverrips** [comment]
@nielsfaber I am using HACS but still get notified about the update, so somehow seems it not works to not offer this update to people who are using a version of HA below 2024.11.x

**Comment by nielsfaber** [comment]
I don’t know how the HACS.json file works then.
I admit that in the past I sometimes forgot to update this file prior to making a release, but now I give it extra attention.
If this mechanism doesn’t work fine, we need to report it to the maintainer of HACS.
I don’t think mentioning in the compatible version in the releae notes is enough, I believe 9/10 people blindly update to the latest greatest (and I don’t blame them).

**Comment by smarthomefamilyverrips** [comment]
@nielsfaber I am proud then that I am that 1 out of 10 actually reading the release notes :) .... unfortunately my knowledge not is that great to know why HACS still offers this update then if you are doing the correct steps to prevent this from happening??? Anyway as said for me personal this being mentioned in release notes would stop my from trying to update and potentially braking my system.
