### ISSUE TITLE
Enabled Modes missing from Edit Sensor screen

### ISSUE THREAD

**Issue by tomm1ed** [nielsfaber/alarmo#1082]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

 v1.10.7 

### HA Version

2024.12.5

### Bug description

Trying to setup Alarmo but unable to setup any sensor because even though both Armed Home and Armed Away are enabled no 'Enabled Modes' are visible in the 'Edit Sensor' screen

### Steps to reproduce

Go to sensor tab
Select Sensor
Click Add to Alarm
Click on Sensor with Red Exclamation mark
<img width="610" alt="Scherm­afbeelding 2024-12-31 om 07 29 59" src="https://github.com/user-attachments/assets/84bc2533-bf03-4948-9f90-bff4940be002" />
Be unable to save because no Mode is selectable
<img width="586" alt="Scherm­afbeelding 2024-12-31 om 07 25 52" src="https://github.com/user-attachments/assets/980bb950-7cfd-4e37-8dcc-c22afb57c928" />

Tested with both Safari and Firefox (Mac and Windows)

**Comment by dynamicpete** [comment]
Hi @tomm1ed ,
I have the same problem.
Your've marked the issue as completed, but what exactly is the solution?

Thanks in advance,
Peter

**Comment by tomm1ed** [comment]
> Hi @tomm1ed , I have the same problem. Your've marked the issue as completed, but what exactly is the solution?
> 
> Thanks in advance, Peter

When creating a new Area make sure to select ‘Copy from Alarmo’:

![IMG_5713](https://github.com/user-attachments/assets/7ac8b80f-1c24-4fc3-acbc-d0311db02888)

**Comment by tomm1ed** [comment]
> > When creating a new Area make sure to select ‘Copy Settings from Alarmo’:
> 
> Thanks a lot, that helped!

You’re welcome! Like Eek the Cat says ‘it never hurts to help ‘ :)
