### ISSUE TITLE
Adding an area is not immediately reflected in the modes list

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#109]
Fairly minor one this one. If you add an the area at the bottom of the general page and then try and modify that area in the modes section you will find that it isn't listed as one of the areas. You need to change page and come back again

**Comment by nielsfaber** [comment]
This will be fixed by https://github.com/nielsfaber/alarmo/commit/441006270b47fbd67f49ceac5c515bc16bac8eb2
Thanks for reporting!

**Comment by nielsfaber** [comment]
Updating to v1.5.1 should fix this problem.
Please close the issue if the update indeed solved your issue.

**Comment by stefanolson** [comment]
Thanks. It works!
