### ISSUE TITLE
Lost translation file

### ISSUE THREAD

**Issue by Repsionu** [nielsfaber/alarmo#11]
Yesterday I localized **et.json**, submitted but no I can not find it anywhere- forgot to save/publish? :-(

**Comment by nielsfaber** [comment]
Seriously? I haven't received any PR or anything.
AFAIK the only way for you to make changes in this repo is via PR..
I must say I'm still working on the structure of the localize file.. This morning I shuffled some stuff up again.
Would strongly advise you to wait one or two weeks more to avoid breaking changes.
