### ISSUE TITLE
Can't arm Master and/ or Area alarms

### ISSUE THREAD

**Issue by vdiogo** [nielsfaber/alarmo#111]
Installed v1.5 and configured some areas and now I can't make any of the arm options to work. I can set the armed status through Programmer Tools which updates the card on lovelace though
![image](https://user-images.githubusercontent.com/24878195/105878166-a1710980-5ff8-11eb-8b4c-253cfa94d649.png)

**Comment by nielsfaber** [comment]
Can you check the supported_features attributes of your alarm_control_panel entities?

**Comment by vdiogo** [comment]
> Can you check the supported_features attributes of your alarm_control_panel entities?

Sorry, how do I do that? Mind du that I have another alarm card which is working since a while and prior updating Alarmo to this version the other card was also working fine

**Comment by nielsfaber** [comment]
If you go to Developer Tools -> States you can see the attributes of your alarm entities.
I cannot see what's going on based on the screenshot you have shared, i need to have a look "behind the scenes".

**Comment by vdiogo** [comment]
Maybe it's this?
![image](https://user-images.githubusercontent.com/24878195/105880630-7b009d80-5ffb-11eb-882f-a60bb1dcd747.png)

**Comment by nielsfaber** [comment]
Yes.
Seems that the master cannot be armed because of this:
> The available arm modes for the Master Alarm are determined from the areas. Only arm modes which are in common for all areas are available for the Master Alarm.

https://github.com/nielsfaber/alarmo#commands

Since the master has supported_features=0, it does not have any arm modes enabled.
Do all areas have arm away / arm home enabled?

**Comment by vdiogo** [comment]
All areas have arm away/ arm night enabled, which makes me wonder why are the options on Lovelace showing Armed Away and Armed Home (not Night)?

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/24878195/105882359-76d57f80-5ffd-11eb-890b-b2bb0f6a684f.png">

**Comment by nielsfaber** [comment]
> All areas have arm away/ arm night enabled, which makes me wonder why are the options on Lovelace showing Armed Away and Armed Home (not Night)?

You have to define yourself which buttons are visible, they are not related to the entity configuration.

**Comment by vdiogo** [comment]
> > All areas have arm away/ arm night enabled, which makes me wonder why are the options on Lovelace showing Armed Away and Armed Home (not Night)?
> 
> You have to define yourself which buttons are visible, they are not related to the entity configuration.

I see what you mean (thank you for clarifying): fixed that but behaviour remains (buttons don't work in Lovelace).

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/24878195/105886753-af2b8c80-6002-11eb-852f-5f3868e30269.png">

**Comment by vdiogo** [comment]
Restarted HA and it's now working :)
