### ISSUE TITLE
No alarm notifications after upgrade to v1.5

### ISSUE THREAD

**Issue by henriklund** [nielsfaber/alarmo#112]
After upgrade to v1.5 I no longer get notifications when an alarm has been triggered.

Alarmo _does_ detect the alarm (and provides the correct sensor) and shows the alarm (as triggered) on the control panel. However, the defined notification does not pop up on my phone. I have verified that notifications can be sent from HomeAssistant (done through a test Node-RED flow), and received by my mobile.

YAML code:
![image](https://user-images.githubusercontent.com/8402745/105914541-c7b19c00-602e-11eb-9f2a-a524e76f496c.png)

**Comment by NikkiePleasure** [comment]
Same problem for me.
I have also an action for "arming", but nothing happens after updating to 1.5.

Anyway, thank you for your great work

**Comment by uros76** [comment]
Same here, no notifications working through alarmo after latest update. 
If I create automation script it works fine. But I liked the integration of all alarm parts through alarmo...

**Comment by nielsfaber** [comment]
Working on it!

**Comment by nielsfaber** [comment]
I made a fix for this: https://github.com/nielsfaber/alarmo/commit/6ef325314660e60679bdf898e4c85271b85a24d5
Will create a new release for it soon.

**Comment by NikkiePleasure** [comment]
> I made a fix for this: [6ef3253](https://github.com/nielsfaber/alarmo/commit/6ef325314660e60679bdf898e4c85271b85a24d5)
> Will create a new release for it soon.

Tested on my Installation and it works again!
Thank you for your fast support and great component

**Comment by nielsfaber** [comment]
Updating to v1.5.1 should fix this problem.
Please close the issue if the update indeed solved your issue.

**Comment by henriklund** [comment]
I can confirm update resolves the issue.

Excellent work! :)
