### ISSUE TITLE
Dutch translation not working on all parts

### ISSUE THREAD

**Issue by bobvmierlo** [nielsfaber/alarmo#113]
When switching the UI to Dutch I noticed that some parts didn't translate accordingly.
To be more specific everyting in the 'Modes' panel, and everything related to the 'Master configuration' and the popup modal.
Seeing as your Dutch it will be easy for you to figure out the parts that didn't translate.

**Comment by nielsfaber** [comment]
Even the menu items in the top are fixed on English 😉 
WIP

**Comment by nielsfaber** [comment]
I added the menu tabs now, as well as the title in the top.
Also this dropdown was not in the translations, I added it:
![image](https://user-images.githubusercontent.com/16861605/106312882-a2f43900-6267-11eb-9d2d-dfd2f7c63549.png)

It seems that these were the last items.

> To be more specific everyting in the 'Modes' panel, and everything related to the 'Master configuration' and the popup modal.

These were already in dutch for me.

**Comment by nielsfaber** [comment]
Closing, assume all is OK now.
