### ISSUE TITLE
Can't disarm master

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#114]
Originally put this in a different issue, but it's really a separate issue:
Arming master works, Disarming doesn't. When I disarm from the master alarm card nothing happens. If I manually go and disarm both house and garage then that works. Hopefully I'm missing something :-)

**Comment by nielsfaber** [comment]
I will take a look into this

**Comment by nielsfaber** [comment]
You didn't miss something, I just forgot to test this function in combination with pincode.
And it turned out to fail always, since the pincode was not propagated to the areas.

The fix is on its way: https://github.com/nielsfaber/alarmo/commit/ba4125a9cb6d9de91cd7971cb7bc4ad8e08314c0

**Comment by nielsfaber** [comment]
Updating to v1.5.1 should fix this problem.
Please close the issue if the update indeed solved your issue.

**Comment by stefanolson** [comment]
Thanks. It works!
