### ISSUE TITLE
MQTT command not working after 1.5.0

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#117]
I have just upgraded to 1.5.0 from 1.4.1
I always arm (home and away) the system with a panel at the entry with the MQTT Alarm Panel App and after the upgrade, the alarmo/command topic seems to be ignored by Alarmo.
When I try to arm through the panel, I could see the alarmo/command topic being published at the broker as ARM_HOME or ARM_AWAY, but nothing happens.
It worked smoothly on 1.4.1.
Alarmo changes the alarmo/state topic accordingly.

**Comment by nielsfaber** [comment]
Duplicate ussue

**Comment by nielsfaber** [comment]
See https://github.com/nielsfaber/alarmo/issues/112

**Comment by tremebundo** [comment]
I see #112, but I do not see the same synthoms.
Is not reading and not executing what an MQTT command says caused by the same bug as not sending notifications?
Excuse my ignorance. I do not know anything about coding.

Thanks a lot for your effort.
