### ISSUE TITLE
Not executing triggers

### ISSUE THREAD

**Issue by fierland** [nielsfaber/alarmo#118]
when i try to update or save an Action I get the error:

Something went wrong!
Message format incorrect: string value is None for dictionary value @ data['area']

Response error: 400

If i go to YAML mode and change none to Alarmo it can be saved again. 

in v1.5.0, v1.5.0b

**Comment by fierland** [comment]
one addition. Changing area to Alarmo made it possible to save the action but could not edit it any more in the GUI. I edited the config file and changed the area's to numeric value of the Alarmo (only area) area, using a Notification as an example. Now it works fully again. 

Creating a new action will fill in the area with correct value, seems only an issue for existing Actions.

**Comment by nielsfaber** [comment]
Sorry for this, my latest release contains quite some Easter eggs (due to the drastic changes).
I will look into this

**Comment by nielsfaber** [comment]
This is taken care of by https://github.com/nielsfaber/alarmo/commit/b6dde71286d1bb9c56499225dc50a322cd7ce623

For next time: please don't try to manually change the area field. Every area has a unique ID (like '11201212'), assigning it with the name of an area may not give the desired behaviour. 
I'm planning to update the GUI a bit to hide some fields from YAML that are not meant to be touched.

**Comment by nielsfaber** [comment]
Updating to v1.5.1 should fix this problem.
Please close the issue if the update indeed solved your issue.

**Comment by fierland** [comment]
Seems ok but hard to test any more. The issue was in action that where ibn place before the introduction of the area's :-)
