### ISSUE TITLE
Alarmo 1.5 and 1.5.1

### ISSUE THREAD

**Issue by Gizmo149** [nielsfaber/alarmo#120]
when I installed V1.4.1 the 'Alarmo' entry in the side bar had four entries, General, Sensors, Codes and Action. When I upgraded to v1.5.0b I had the same four entries bur General was a blank page.

I reverted back to 1.4.1 and had four full pages again. I then upgraded to v1.5.0 (not beta) and experienced the same issue.  Even though 'General' was blank I was still able to  set sensors, codes and actions. 

I've just upgraded to 1.5.1 and now I am unable to select any of the four pages and the text of the 'tabs' is squashed together? I notice that the Alarmo page on the side bar is still reporting 1.4.1 though, is there another element I need to upgrade?

regards

Darren

**Comment by nielsfaber** [comment]
If the alarmo panel doesn’t show v1.5.1 in the top, you need to refresh/empty your browser cache.

**Comment by Gizmo149** [comment]
Many thanks. Thought I'd tried that. Seemed to take a couple of minutes

Regards

Darren

Ps. Think the system is fab and can't wait to get it all configured properly

**Comment by nielsfaber** [comment]
The cache usage of HA is quite aggressive yes. The whole point of showing the version number in the top is to see that you’re viewing the actual version.
Please close this issue if your problems are fixed by this

**Comment by Gizmo149** [comment]
Thanks. It does seem to have resolved the issue and I will close first
thing. Brilliant support!

Darren
