### ISSUE TITLE
No General page and cannot add sensors

### ISSUE THREAD

**Issue by Bpasop** [nielsfaber/alarmo#122]
Hi, i've had Alarmo work fine on 1.4.1 but when I did upgrade to 1.5 and later till 1.5.1 I can't use it anymore. I even uninstalled en reinstalled it several times. But the bug keeps coming back. 
The first problem is that the general page is complete empty. So I can't make any adjustments. 
The second one, when I try to add a sensor I can select it but I can't add it to my setup. The button got highlighted but there is nothing happening when I pushed on it.
Is there an other why to get everything up and running again. I tried it via HACS and manual install both ways I get these strange behaviors. 
Ps. in the top right corner it still says 1.4.1 even trough I updated to 1.5.1.

**Comment by nielsfaber** [comment]
Refresh your browser cache please

**Comment by Bpasop** [comment]
I thought I refreshed my cache the right way but I didn't. Thanks for the help.
