### ISSUE TITLE
Sensor is open and still Armed Away is possible

### ISSUE THREAD

**Issue by vdiogo** [nielsfaber/alarmo#123]
I've setup multiple zones in one of which I have a door sensor with related arm modes "Night" and "Away".

Issue is that whilst I'm not able to set the alarm to Night when the door sensor shows the door as open (which is expected) I am however able to set the alarm to "Away" without any issues (both for the zone alarm and for the Master alarm).

While doing some troubleshooting on node-red (using the HA state node) I am also not able to collect data for any of the attributes of either alarms (when arming to "Nigh" or to "Away"). Would expect open_sensors would show the open door.
<img width="467" alt="image" src="https://user-images.githubusercontent.com/24878195/106382596-887da500-63b8-11eb-8cbf-ac237c456f0e.png">

Is this expected behaviour?

**Comment by nielsfaber** [comment]
It seems that the sensor is not correctly linked to the area and is completely ignored. Ofcourse this is not how it should work!
Could you share a screenshot of the sensor configuration page of this entity in Alarmo?

**Comment by vdiogo** [comment]
Many thanks for prompt reply. Here you go:
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/24878195/106383455-f8425e80-63bd-11eb-957b-4d3f05997d99.png">

**Comment by nielsfaber** [comment]
The configuration looks OK, so that's not the problem.
Are you sure the alarm can proceed to `armed_away` with the sensor active?
In your first screenshot the alarm is in `arming`, that is not the same as `armed_away` (this state is meant for allowing you to leave the house, so you can still open/close doors).
Could you make some test to demonstrate the failure?

**Comment by vdiogo** [comment]
You are right, the alarm will not arm to "Away" also (I forgot to disclaim the exit delay which is set to 60sec)

**Comment by nielsfaber** [comment]
In that case, I don't really understand the problem you are pointing out.

**Comment by vdiogo** [comment]
You are correct, no issue. Will close the ticket
