### ISSUE TITLE
yaml notification editor partly offscreen on mobile

### ISSUE THREAD

**Issue by bobvmierlo** [nielsfaber/alarmo#126]
When opening the yaml editor in the notifications the textbox and more are partly offscreen and can't be dragged in screen of zoomed out either.
Check screenshot below:

![image](https://user-images.githubusercontent.com/38190383/106392649-1e362600-63f3-11eb-9a1c-b4a4b5bc5a37.png)

While the UI editor seems fine:
![image](https://user-images.githubusercontent.com/38190383/106392674-31e18c80-63f3-11eb-98e1-1084535cea76.png)

**Comment by nielsfaber** [comment]
The YAML editor is not intended for mobile devices.
It is a component managed by HA, so I cannot solve this.
