### ISSUE TITLE
FORCE without IOS or Android?

### ISSUE THREAD

**Issue by RyanBlace** [nielsfaber/alarmo#129]
Hi!

Is there a way to force arm (as in an open sensor) without using IOS or Android? 

I'm using a custom keypad by each entry door and a Telegram bot to arm and disarm. To arm, I'm using something like this for Telegram:

<pre>
  - alias: Telegram set alarm to armed_away.
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: /arm_away
      - platform: event
        event_type: telegram_callback
        event_data:
          command: /arm_away
    condition: '{{ states.alarm_control_panel.alarmo.state != "armed_away" }}'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.alarmo
        data:
          code: !secret alarm_code_telegram
</pre>

However, I can't work out how to get ALARMO_FORCE_ARM or ALARMO_RETRY_ARM to Alarmo without using the IOS or Android integrations.  Something like "alarm_control_panel.alarm_arm_away_forced" doesn't exist for the stock panel. Is there some trick you can think of to allow FORCE from an HA automation?

Thank you for this work. It has saved me literally hours and hours of effort.

**Comment by nielsfaber** [comment]
Hi Ryan,
You can setup a code as “override code”.
Entering this code on arming would result into the automatic bypassing of any sensor that is blocking.
It seems to be a good match for your use-case.

I’m also planning to introduce a service (`alarmo.arm`) which can be used to force-arm (even if your alarm doesn’t require a code for arming) and for skipping the delay.
There is a Alarmo-card in the making (which is currently a copy-exact of the Alarm Panel Card in Lovelace), which will support these options as well.

**Comment by RyanBlace** [comment]
Fantastic. This is exactly what I need.

```
Is override code
Entering this code will arm the alarm in force
```

I'm thinking out loud... I wonder if it would be nicer to have each existing user have two alarm codes. One normal and one for forcing.  It would be nice to know who forced the arming without duplicating each existing user. The forcing code would be optional. 

Anyway, this is great. And, thanks again for such an awesome effort! 🥇

**Comment by cipnt** [comment]
It would be great if this functionality was available directly as a service, without the need for special codes. For example `alarm_arm_force` or `alarm_force_arm` could be used in custom automations:
```
action:
  - service: alarm_control_panel.alarm_arm_force
    target:
      entity_id: alarm_control_panel.alarmo
```
