### ISSUE TITLE
Motion sensor registered for armed away triggers the alarm in armed home 

### ISSUE THREAD

**Issue by steenmaigaard** [nielsfaber/alarmo#130]
I armed my alarm as "armed home" before I went to bed, but this morning the alarm was triggered even though the sensor only is enabled for armed away, I tripple checked the configuration, no mistake there.

![Udklip](https://user-images.githubusercontent.com/50239051/106700435-235ac700-65e5-11eb-8993-135b4e88c13a.PNG)

Regards Steen

**Comment by nielsfaber** [comment]
From the code I cannot see how such scenario can occur.
I will have to investigate.
Are you able to reproduce the problem?

**Comment by steenmaigaard** [comment]
It turns out to be an issue occuring during the customization of the automation , I re-installed Armo completely and now it works fine

**Comment by nielsfaber** [comment]
Ok, let's consider that an incident then. I will close this issue for now.
If such issue occurs again, please let me know.
