### ISSUE TITLE
Accidentally Integrated twice

### ISSUE THREAD

**Issue by m-theredhead** [nielsfaber/alarmo#132]
Hello,

I am currently running Alarmo 1.5.2.   While playing with integrations today, I accidentally clicked on the Alarmo integration.    It seems to have added a second device on the integrations page.

![Alarmo1](https://user-images.githubusercontent.com/44811348/106972371-f6ee9a00-670d-11eb-8c09-a747b0c567f2.JPG)

Comparing them, I can see the first is my original as it has an alarmo entity

![Alarmo2](https://user-images.githubusercontent.com/44811348/106972413-0ec61e00-670e-11eb-8c62-ea91fb37971f.JPG)

and the second does not:

![Alarmo3](https://user-images.githubusercontent.com/44811348/106972431-14bbff00-670e-11eb-9686-1cedfc2db3c4.JPG)

Unfortunately, I can't see how to delete the second entity.   Any ideas?

**Comment by m-theredhead** [comment]
After looking at it more, I realized I couldn't arm the alarm any more.   I didn't save the log, but it noting that the alarm did not have a unique id and it was confused.

I ended up removing the integration and adding it back and starting fresh.    Everything is working again.

Seems like a check might be useful to prevent this from happening.

**Comment by nielsfaber** [comment]
I don't know how to prevent the integration from being installed twice.
I will have to investigate.

**Comment by danuals** [comment]
Same here, 2 devices but can’t delete the unused one

**Comment by nielsfaber** [comment]
The truth is that I don't know either.
My approach would be going to the `.storage` folder and remove the second integration from `core.config_entries` and `core.device_registry`.
But only touch these files if you know what you're doing (and when HA is not running).

I did not find a way yet to hide the button or block a second installation.

**Comment by nielsfaber** [comment]
This issue has been fixed in the meantime.

**Comment by danuals** [comment]
> The truth is that I don't know either.
> My approach would be going to the `.storage` folder and remove the second integration from `core.config_entries` and `core.device_registry`.
> But only touch these files if you know what you're doing (and when HA is not running).
> 
> I did not find a way yet to hide the button or block a second installation.

I just deleted the integration then re-installed, all settings were preserved.
