### ISSUE TITLE
FR: Ability to send notifications or trigger automations based on who disarmed the alarm

### ISSUE THREAD

**Issue by EpicMount** [nielsfaber/alarmo#133]
Not sure if this is output already but it would be nice to be able to trigger a notification detailing who disabled the alarm, i.e. child returning home from school or the dog walker/cleaning lady arriving.  You could even extend that further by allowing advanced HA automations to be linked, i.e. turning on music in the house of I'm the only one home when I arrive and I disarm the alarm by using the pin entered in Alarmo as a trigger.

**Comment by nielsfaber** [comment]
You can enter `{changed_by}` in the notification message, it will be replaced by the name of the user who disarmed/armed (depending on the event).

**Comment by EpicMount** [comment]
Thanks, I tried entering {changed_by} into the message however it just appends the notification exactly how it's written, without the name of user who changed it.

**Comment by nielsfaber** [comment]
Sorry, I should have said `{{changed_by}}`
I chose to go with double brackets for some reason.
Sorry for wasting your time.

**Comment by EpicMount** [comment]
No worries. That did the trick. Thanks!
