### ISSUE TITLE
Register in log who made the change

### ISSUE THREAD

**Issue by zbuh** [nielsfaber/alarmo#134]
1st I don't know if this is possible by HA guidelines.

Currently i'm using NFC tags to disarm alarms (alarmo entities)
I wrote as tag_id, each user PIN.
So I can send notifications like this: "Alarm disarmed by {{changed_by}}"

but this could be improved if the entity saved that information in the log. because that's persistent information that we can check at any time in the future, while notifications are volatile.

Currently its saved like: "Home changed to Disarmed by service alarm_control_panel.alarm_disarm"
Probably the Alarmo users must be linked to HA users...

Another option can be a special service from Alarm to do this...

**Comment by nielsfaber** [comment]
I have no idea how to make the logbook entries look pretty.
AFAIK this is handled by HA internally.
I agree that it would be nice, also to be able to say that Alarmo triggered the siren etc. 👍

**Comment by zbuh** [comment]
Just to give you some props:

![image](https://user-images.githubusercontent.com/190734/108513114-0c40f800-72ba-11eb-8027-6d59bb1f65f5.png)

This is now possible with HA automations.

My car auto disarms garage alarm on arrival

**Comment by nielsfaber** [comment]
There's some ongoing improvements for this, see also here: https://github.com/home-assistant/architecture/issues/473# and here: https://github.com/home-assistant/frontend/pull/8231
Still from the backend-side I don't really know how to implement this.
I assume you just made an automations for this job? 
The HA code of automations is really not that transparent, I took a look before but couldn't make much sense of it.

**Comment by zbuh** [comment]
Yes, It was an automation, that was triggered by de "device" Honda, and disarmed the Alarmo

**Comment by nielsfaber** [comment]
Once again I tried to pick this up, but no success.

```
self.hass.async_create_task(
    self.hass.services.async_call(
        "input_boolean", "turn_off", {"entity_id": "input_boolean.my_switch"}, context=Context(id="6698f2533feb32dc9c1dc99f61a02301")
    )
)
```

No matter which variation of context input I try, it always shows up in the logbook like this:
![image](https://user-images.githubusercontent.com/16861605/122666325-e0247d80-d1ac-11eb-8cd2-400c54e3bd48.png)

The code used by HA for automations is very complex to understand, so I am stuck at this point.
I also asked for help on the discord channel of HA, but no response.
