### ISSUE TITLE
Small improvement - Use state translation instead of value

### ISSUE THREAD

**Issue by zbuh** [nielsfaber/alarmo#136]
When using a notification like this: "Alarm is now {{arm_mode}}"

the current output is. for example: "Alarm is now armed_away"

It would be better if the replacement used the translation for that state: "Alarm is now Armed Away"

**Comment by nielsfaber** [comment]
The translations are only available in the GUI, not in the automation itself.
I made a small change that will at least improve the formatting, but translation is not possible as far as I know.

**Comment by Tosko4** [comment]
As workaround you could work with a template and check through the states

If armed_away
   Send this message
Elseif armed_home
   Send that message

Etc..
