### ISSUE TITLE
Alarmo not found in integrations

### ISSUE THREAD

**Issue by masterfixedit** [nielsfaber/alarmo#137]
Hi,

I've installed Alarmo with HACS. After reboot I should find Alarmo under Configuration --> Integrations --> Add integrations but Alarmo is missing.
Any ideas? Am i missing something?

**Comment by nielsfaber** [comment]
This is usually solved by clearing your browser cache.

**Comment by masterfixedit** [comment]
So simple... 😄 
Thanx for the tip!
