### ISSUE TITLE
Theme support in header

### ISSUE THREAD

**Issue by brandondb1** [nielsfaber/alarmo#139]
As I was changing themes in HA, I noticed that the header in the Alarm Panel wasn't the same as the other panels (in my case it was a rather jarring green versus dark grey).  In the alarm-panel.js file, where the styles are laid out, if you change the CSS names as follows, it picks up the theme colors properly:

      ha-app-layout,
      app-toolbar,
      paper-tabs {
        background: var(--app-header-background-color);
        color: var(--app-header-text-color);
      }

Just thought I'd point this out.  Thanks again for all the great tools !

**Comment by nielsfaber** [comment]
This should be fixed by https://github.com/nielsfaber/alarmo/commit/498264f02d7d7376a5b8c91d9ca1bcdaed69239f
