### ISSUE TITLE
Is it possible to run two different alarmo's?

### ISSUE THREAD

**Issue by neldonado** [nielsfaber/alarmo#141]
Is it possible to run two instances of Alarmo? I have Alarmo setup for my house, but I would like a second alarm for my guest house, on the property, running separately from my main home alarm. My house may be armed but the guest house may not, for example.

**Comment by nielsfaber** [comment]
You can setup multiple areas and arm/disarm them independently (or simultaneously).
There’s no need for installing Alarmo multiple times.

**Comment by neldonado** [comment]
> 
> 
> You can setup multiple areas and arm/disarm them independently (or simultaneously).
> There’s no need for installing Alarmo multiple times.

WOW. Thank you for the quick reply. this is awesome!
