### ISSUE TITLE
Help with homekit

### ISSUE THREAD

**Issue by l3keboy** [nielsfaber/alarmo#143]
Just installed Alarmo, but I can't enable the alarm using HomeKit. Just me or is it not jet supported?

**Comment by l3keboy** [comment]
Nevermind, my mistake =)

**Comment by cnmarch6** [comment]
If you set up arm with code then you can’t arm via HomeKit cos you need to enter the code (dumb HomeKit still) 
Vice vs with disarm

**Comment by l3keboy** [comment]
Well you can if you give HomeKit your code using the entity_config in the HomeKit bridge integration via YAML.

https://www.home-assistant.io/integrations/homekit/

**Comment by cnmarch6** [comment]
> Well you can if you give HomeKit your code using the entity_config in the HomeKit bridge integration via YAML.
> 
> https://www.home-assistant.io/integrations/homekit/

Sweet, learn something everyday.

**Comment by jakubgt** [comment]
> > Well you can if you give HomeKit your code using the entity_config in the HomeKit bridge integration via YAML.
> > https://www.home-assistant.io/integrations/homekit/
> 
> Sweet, learn something everyday.

Can you post the config.yaml entry you added? I cannot get mine to work
