### ISSUE TITLE
Can not add entities to perform actions on

### ISSUE THREAD

**Issue by xyboox** [nielsfaber/alarmo#144]
![Screenshot at Feb 22 16-03-38](https://user-images.githubusercontent.com/642584/108719091-d5701980-7527-11eb-985b-8d7f1145f45a.png)
When trying to add an entity, the "+" button ( indicated in the screenshot ) does nothing regardless of the selections above it. Any idea?

**Comment by nielsfaber** [comment]
That's weird, looks like the whole dropdown list has disappeared.
I assume you have some `switch` entities in your HA setup?
Could you check for an error message in the browser logs (by opening a developer panel)?

**Comment by xyboox** [comment]
ok... weird enough... it now works properly. I will keep an eye on it, as I know for sure I've tried several times before with same result until just now :)
Yes, I do have lots of switches in the setup.
Thanks anyway. Will keep you posted should the issue pops up again.

**Comment by nielsfaber** [comment]
Please re-open if the issue comes back.
