### ISSUE TITLE
Extend to manage/monitor locks (Feature Request)

### ISSUE THREAD

**Issue by kevinsaucier** [nielsfaber/alarmo#148]
Great job on this integration!  Seems to work well and it's easy to configure.  One of the things I'd love to see is the ability to tie automatic locks into the security scheme.  For instance, right now, I lock all doors (via Node Red) when Alarmo goes to armed_home, armed_away, or armed_night.  Generally, this works fine, but sometimes a door isn't shut completely so the lock can't engage.  It would be great if I could tie locks into the Alarmo 'arm' process so that it would notify me if locks don't lock properly just like it does if a window or door is open (failed to arm).  Not a huge issue but figured I'd submit it, since I didn't see it out there.

Thanks for all your hard work!

**Comment by jazzyisj** [comment]
You can create a binary sensor template that turns on if the alarm is armed but a lock is not locked and add that sensor to alarmo.

```
{{ states('alarm_control_panel.alarm') in ['armed_home','armed_night','armed_away']
   and states.lock|selectattr('state','eq','unlocked')|list|count > 0 }}
```

**Comment by nielsfaber** [comment]
Hi @kevinsaucier,
As I interpret your request, it consists of two parts:
1. Automations for closing/opening your locks when arming/disarming the alarm
2. Monitoring of the states of the locks while the alarm is armed

I think the first part is very user-specific and is therefor best solved using automations (as you already have in place).
To connect part 1 and 2 you need to add some delay for the arming, to allow the locks to be closed before the sensors are monitored.

For part 2 of your request there are two options:
1. Alarmo adds support for registering `lock` entities in addition to `binary_sensor` entities as sensors.
2. You could define [template binary sensors](https://www.home-assistant.io/integrations/binary_sensor.template/) that add entities to Alarmo which represent the open/closed state of each lock (similar to @jazzyisj's suggestion).

I personally don't have electronic locks, and I guess this is the main and only reason why Alarmo does not have native support for monitoring locks.
If it would help you, this support can be added. But it requires some adaptions in multiple places of the code.
While the support is not in place, I'd say adding the template sensors is your best bet.

**Comment by kevinsaucier** [comment]
Thanks @nielsfaber and @jazzyisj .  I would have thought that monitoring/automating the status of doors being locked when arming the alarm would be a pretty general request that would benefit the group but, if that's not what you're seeing, I'm definitely not advocating for you to put in additional work that only suits a very low percentage of the user base.

I'll look into adding support via @jazzyisj 's suggestion and add a little more logic to Node Red to manage it.  Thanks again!

**Comment by jeroenterheerdt** [comment]
I'd like to get support for locks as well as covers (garage doors). Honestly, I think this is not a very specific ask. I know we can use the template binary sensors, but still.
