### ISSUE TITLE
Cannot open the UI behind a reverse proxied HA

### ISSUE THREAD

**Issue by aleksandrov1995** [nielsfaber/alarmo#15]
This is with the new version of alarmo.

Opening the UI locally works as expected. I have websockets support enabled in the Nginx Proxy Manager, and HA also does not have issues establishing websockets. However, if accessed externally, this is what i get in the dev console when i try to open the UI:

`alarmo:1086 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at HTMLElement.render (alarmo:1086)
    at HTMLElement.update (alarmo:186)
    at HTMLElement.performUpdate (alarmo:148)
    at HTMLElement._enqueueUpdate (alarmo:148)
render @ alarmo:1086
update @ alarmo:186
performUpdate @ alarmo:148
_enqueueUpdate @ alarmo:148
async function (async)
_enqueueUpdate @ alarmo:148
requestUpdateInternal @ alarmo:148
set @ alarmo:148
(anonymous) @ chunk.6291eb9f40d952ac49d9.js:1
l @ chunk.6291eb9f40d952ac49d9.js:1
_setProperties @ chunk.6291eb9f40d952ac49d9.js:1
value @ chunk.6291eb9f40d952ac49d9.js:1
performUpdate @ app.8efb5ced.js:10288
_enqueueUpdate @ app.8efb5ced.js:10288
async function (async)
_enqueueUpdate @ app.8efb5ced.js:10288
requestUpdateInternal @ app.8efb5ced.js:10288
set @ app.8efb5ced.js:10288
value @ app.8efb5ced.js:43529
value @ app.8efb5ced.js:39299
performUpdate @ app.8efb5ced.js:10288
_enqueueUpdate @ app.8efb5ced.js:10288
async function (async)
_enqueueUpdate @ app.8efb5ced.js:10288
requestUpdateInternal @ app.8efb5ced.js:10288
set @ app.8efb5ced.js:10288
commit @ app.8efb5ced.js:10288
commit @ app.8efb5ced.js:10288
update @ app.8efb5ced.js:10288
__commitTemplateResult @ app.8efb5ced.js:10288
commit @ app.8efb5ced.js:10288
a @ app.8efb5ced.js:10288
H.render @ app.8efb5ced.js:10288
update @ app.8efb5ced.js:10288
performUpdate @ app.8efb5ced.js:10288
_enqueueUpdate @ app.8efb5ced.js:10288
async function (async)
_enqueueUpdate @ app.8efb5ced.js:10288
requestUpdateInternal @ app.8efb5ced.js:10288
set @ app.8efb5ced.js:10288
commit @ app.8efb5ced.js:10288
commit @ app.8efb5ced.js:10288
update @ app.8efb5ced.js:10288
__commitTemplateResult @ app.8efb5ced.js:10288
commit @ app.8efb5ced.js:10288
update @ app.8efb5ced.js:10288
__commitTemplateResult @ app.8efb5ced.js:10288
commit @ app.8efb5ced.js:10288
a @ app.8efb5ced.js:10288
H.render @ app.8efb5ced.js:10288
update @ app.8efb5ced.js:10288
performUpdate @ app.8efb5ced.js:10288
_enqueueUpdate @ app.8efb5ced.js:10288
async function (async)
_enqueueUpdate @ app.8efb5ced.js:10288
requestUpdateInternal @ app.8efb5ced.js:10288
set @ app.8efb5ced.js:10288
value @ app.8efb5ced.js:41533
(anonymous) @ app.8efb5ced.js:41533
s @ core.bcfce4ca.js:1
(anonymous) @ core.bcfce4ca.js:1
(anonymous) @ core.bcfce4ca.js:1
_handleMessage @ core.bcfce4ca.js:1
(anonymous) @ core.bcfce4ca.js:1`

**Comment by nielsfaber** [comment]
I have no idea about this.
For me it works fine with DuckDNS / letsencrypt.

Could you try installing the 'shopping_list' integration + card?
That one also uses Websocket API to communicate between the card and the backend, my implementation is pretty similar.
I would like to know if that works normally.

If so, I can probably fix it 👍

**Comment by aleksandrov1995** [comment]
I just installed it and it works:

![image](https://user-images.githubusercontent.com/12535078/99377876-6c955780-28cf-11eb-9f4b-d627192ce2e9.png)

**Comment by nielsfaber** [comment]
Okay great! That means it will be fixable.
The problem is: how can I reproduce your scenario..

I will take a look at the differences of my implementation vs. the one of the shopping_list card.

**Comment by aleksandrov1995** [comment]
Well, I am using the Nginx proxy manager addon in HA and using my own domain.

Nothing fancy really, just reverse proxing the 8123 from ha to 443.

**Comment by nielsfaber** [comment]
Are you sure this is due to websockets?
I have a feeling you have a caching problem, and you're just looking at an old version of the frontend.

I tried to follow the trail, but `alarmo:1086` is an empty line and `alarmo:186` as well.
So the logging does not make any sense to me..
Could you try a hard (cache) refresh of your browser?

**Comment by aleksandrov1995** [comment]
Silly me, i should have done that first. I am so sorry for wasting your precious time to look into this. After all, this was the issue.

**Comment by nielsfaber** [comment]
No harm done. Glad it was a simple fix.
You can buy me a coffee sometime 😄
