### ISSUE TITLE
[Feature request] - groups as action targets/entities

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/alarmo#151]
As groups support using "switch.turn_off" and "switch.turn_on" 
- would be nice to have possibility to use not groups also as action targets/entities

**Comment by nielsfaber** [comment]
This can be added and seems like a good addition.
There is only some intelligence needed to detect which entities are contained in the group (a group could also contain cover / climate entities etc. which don't work with turn_on/turn_off actions).

**Comment by nielsfaber** [comment]
This is finally added in v1.7.0.
Note that a group only shows up, if the entities in that group are of the supported type (so switches, lamps, etc.).
