### ISSUE TITLE
[Feature request] - per sensor type configurable actions (notifications too?)

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/alarmo#155]
Idea: to have possibility configure actions per sensor type
* to close valve(s) and/or turn off switch(es) in case of water leak, 
* another one in case of fire/smoke alarm.

**Comment by nielsfaber** [comment]
> another one in case of fire/smoke alarm.

I agree to this one.

> to close valve(s) and/or turn off switch(es) in case of water leak,

This is no responsibility of an alarm system.

**Comment by Masterz69** [comment]
Actually not agree with You. Nowadays - water leak is a big issue, no less if compare with smoke/fire. 
Same kind of environmental disaster. 

Standalone alarm systems (like DSC) allow to connect water leak sensors and treat them as separate kind of alarm.

**Comment by knaksbrig** [comment]
+1 for this feature please.

I have both internal and external sounders and ideally only need to action the internal sounder when the smoke alarm sensors trigger.

BTW, I installed Alarmo yesterday after adding a Konnected board about a month ago and not getting round to setting up the automations etc. With Alarmo, my alarm system was up and running within minutes!  Thanks for your work on this.

**Comment by rindlerblabla** [comment]
Agree that it would be nice to have different actions for environmental sensors than the contact/motion sensors!
