### ISSUE TITLE
alarm triggered without sensor activation, after being previoulsy triggered by multiple sensors

### ISSUE THREAD

**Issue by dncex** [nielsfaber/alarmo#156]
This is the sequence of what have happened:
Day 1 h20.00; while alarm is ARMED HOME, sensor 1 is activated and alarm is triggered (OK)
Day 1 h20.01; also sensor 2 is activated (alarm stay TRIGGERED...ok)
Day 1 h20.05: alarm is then DISARMED by me, after I've seen the notification (notification was about sensor 1)
Day 2 h22.00: while alarm is ARMED HOME, alarm si triggered: the notification says that the sensor 2 was activated. And here is the problem: according the the HA history/logbook, the sensor 2 wasn't activated at that time (nor either).

I am using: alarmo 1.5.3 and HA 2021.2.3.
Other info: I have around 10 PIR sensor (platform mqtt).

BTW: the component is great... I've been using it for some weeks without any problem!

**Comment by nielsfaber** [comment]
that's very curious, haven't heard it before.
Is this something you're able to reproduce or its just a single incident?
I don't see any part in the code the points to this, so I was hoping you could help with some testing to pin it down.

**Comment by dncex** [comment]
I've tried to reproduce the error, but I didn't succeded.
I'm sorry but I think it was my mistake!

**Comment by nielsfaber** [comment]
No problem, let's call it an incident for now.
Let me know if the problem occurs again.
