### ISSUE TITLE
Alarmo doesn't detect vibration sensor [Aqara DJT11LM].

### ISSUE THREAD

**Issue by quadrophenianl** [nielsfaber/alarmo#158]
Hi Niels,

First of all, thanks for this great integration!

I only have one issue, and that is the fact that I can't select the **Aqara vibration sensor [DJT11LM]** to the list of sensors. I did some search on the issues and the documentions over here, but as far as I'm concern a vibration sensor should be compatible with Alarmo.

Am I missing something?

Anyway, I hope to hear from you soon!

Take care!

**Comment by nielsfaber** [comment]
Thanks for liking Alarmo!

Alarmo is compatible with all binary_sensor entities. 
The device_class property is used for detecting the type of the sensor:
![image](https://user-images.githubusercontent.com/16861605/111973652-03348800-8aff-11eb-9e8b-464eb59e5ceb.png)

Could you check it for your vibration sensor?
(vibration is a [valid ](https://www.home-assistant.io/integrations/binary_sensor/) device_class).

You can always use this switch to have ALL binay_sensors selectable (also sensors missing the device_class property):
![image](https://user-images.githubusercontent.com/16861605/111973865-39720780-8aff-11eb-8546-a6577ac79308.png)

**Comment by quadrophenianl** [comment]
Thanks for your quick response, @nielsfaber!

Unfortunately there is no vibration device class for this sensor. I guess this one is useless for now. Any plans to add other sensors like this one to the integration? Of is it possible to edit the sensor in a kind of way that I can use it in Alarmo?

This was actually the only vibration sensor I could find with Zigbee protocol. Do you know any alternative vibration sensors which are compatible with Alarmo?

Thanks again!

**Comment by quadrophenianl** [comment]
I think I already found one: https://www.zigbee2mqtt.io/devices/TS0210.html

**Comment by nielsfaber** [comment]
I think you should refer your question to zigbee2mqtt as the problem is caused there.
You can also use [customize](https://www.home-assistant.io/docs/configuration/customizing-devices/) to manually give your entity the correct device class.

**Comment by MarcAroni81** [comment]
@quadrophenianl 
Fixed it this way:

```
binary_sensor:
  - platform: template
    sensors:    
      door_vibration:
        friendly_name: "Door Sensor Vibrated"
        value_template: >-
          {{ is_state('sensor.<nameofyouraquarySensortAction>', 'vibration')
             or is_state('sensor.<nameofyouraquarySensortAction>', 'tilt')
             or is_state('sensor.<nameofyouraquarySensortAction>', 'drop')
          }}
```

**Comment by bpatel111** [comment]
Hi Marc

I am having issues with the same sensors. Problem I have is, when you drop/tilt/vibrate this sensor, it returns an empty string. Did you have any issues with that? How did yo solve it? Or have set this sensors incorrectly and it is returning following:
```
action: null
angle: 8
angle_x: 6
angle_x_absolute: 84
angle_y: -75
angle_y_absolute: 165
angle_z: 14
battery: 97
linkquality: 168
sensitivity: high
strength: 50
voltage: 2995
friendly_name: VS_KITCHEN_DOOR_action
icon: 'mdi:gesture-double-tap'
```
Please let me know if you have any suggections.
Thank you

**Comment by MarcAroni81** [comment]
Hi BPatel,

the Aqara sensor is just posting an action within the very same second of happening. After that, its state string is: unavailable.

Thats why I created my own binary sensor which sensor state = true in the moment of action of the vibration sensor which possible states are: vibration, drop, tilt.

**Comment by varadujagan** [comment]
> @quadrophenianl
> Fixed it this way:
> 
> ```
> binary_sensor:
>   - platform: template
>     sensors:    
>       door_vibration:
>         friendly_name: "Door Sensor Vibrated"
>         value_template: >-
>           {{ is_state('sensor.<nameofyouraquarySensortAction>', 'vibration')
>              or is_state('sensor.<nameofyouraquarySensortAction>', 'tilt')
>              or is_state('sensor.<nameofyouraquarySensortAction>', 'drop')
>           }}
> ```

when i tried this but no result 
```
binary_sensor:
    - platform: template
      sensors:    
        door_vibration:
          friendly_name: "Hall Door Vibration"
          value_template: >-
            {{ is_state('sensor.hall_door_vibration_action', 'vibration') 
                or is_state('sensor.hall_door_vibration_action', 'tilt') 
                or is_state('sensor.hall_door_vibration_action', 'drop')
            }}
```

when i manually change the state to vibration in Developer Tools, then the template is working properly. 
but when the vibration is detected, nothing changes in the binary sensor. 
what is wrong with my template or any other solution

**Comment by bpatel1111** [comment]
Hi

I have been using this as a binary sensor  and it is working fine:
``
platform: template
sensors:
  kitchen_door:
    friendly_name: "Back Door"
    delay_off:
      minutes: 1
    device_class: vibration
    value_template: >
      {{ state_attr('sensor.vs_back_door_action', 'action') in
         ('vibration', 'tilt', 'drop') }}
``
