### ISSUE TITLE
Missing Mode Selection

### ISSUE THREAD

**Issue by Puntoboy** [nielsfaber/alarmo#159]
New Alarmo install. 

Had it installed a few months ago but couldn't work out how the siren worked. Just updated it to the latest version and added a couple of new sensors. Now I'm getting this error where I'm unable to select a mode 

![image](https://user-images.githubusercontent.com/11718878/111980349-14c96000-8afe-11eb-82f5-c0114e92bd74.png)

But the option is missing so I can't see it.

![image](https://user-images.githubusercontent.com/11718878/111980385-23b01280-8afe-11eb-9bc3-2c2e6d4dc184.png)

any ideas?

**Comment by nielsfaber** [comment]
There should be a dropdown with the available arm mode (away, home, night etc).
Could it be that for the alarm setup itself (in tab "General") you didn't enable any modes yet?

![image](https://user-images.githubusercontent.com/16861605/111980810-18adb000-8b07-11eb-9f2d-8e7713c65ca8.png)
Greyed out items are disabled.

**Comment by Puntoboy** [comment]
It's there for the other sensors I added when I installed it, but not for the two I just added.

![image](https://user-images.githubusercontent.com/11718878/111980992-f6179900-8afe-11eb-8ec6-f4c30bb02c93.png)

**Comment by nielsfaber** [comment]
Could you check your browser console log for possible errors?
See here if you don't know how to find it: https://balsamiq.com/support/faqs/browserconsole/

**Comment by Puntoboy** [comment]
![image](https://user-images.githubusercontent.com/11718878/111982046-62df6300-8b00-11eb-9216-1f14e6b105a9.png)

I've tried both FireFox and Edge. Same issue.

**Comment by Puntoboy** [comment]
Ah it's OK. I went back and checked the config. I also created new areas where these modes weren't enabled. Sorted now :) 

Whilst I have this topic, I still can't get my head around how the siren works. Where does the siren get set in the config?

**Comment by nielsfaber** [comment]
If you go to tab "Actions", you can configure an action like this:
![image](https://user-images.githubusercontent.com/16861605/111990950-0be38900-8b14-11eb-82ef-f776dff93423.png)
