### ISSUE TITLE
Inverted functionality

### ISSUE THREAD

**Issue by aleksandrov1995** [nielsfaber/alarmo#16]
I have something strange going on (i did a hard refresh this time!) and with the new version the functionality for requiring a pin for arming/disarming is inverted for me.

E.g. if i turn on the require pin for arming, then it doesn't require pin for arming, but instead for disaming. Same thing happens if i turn the other one on, disarming becomes arming.

I hope all this makes sense.

I dont know if i should open a new issue, but also, if the leave time is set to None, the alarm will not Arm. (tested for arm home/arm night)

**Comment by aleksandrov1995** [comment]
There is more I can report, I tried the mqtt settings, but nothing is being published for state changes, I didn't have the time to check for commands.

**Comment by nielsfaber** [comment]
As for: 

> I have something strange going on (i did a hard refresh this time!) and with the new version the functionality for requiring a pin for arming/disarming is inverted for me.
E.g. if i turn on the require pin for arming, then it doesn't require pin for arming, but instead for disaming. Same thing happens if i turn the other one on, disarming becomes arming.

It was reported somewhere else as well. I just patched that. It was wrong in the code.

About this:
> I dont know if i should open a new issue, but also, if the leave time is set to None, the alarm will not Arm. (tested for arm home/arm night)

I can reproduce this issue.
It gives me:
```
2020-11-18 20:58:17 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_arm_away
/config/custom_components/alarmo/alarm_control_panel.py:422: RuntimeWarning: coroutine 'AlarmoEntity.async_arm' was never awaited
```

I missed an `await` statement for an async function call.
So, you can consider it fixed as well.

About this:
```
There is more I can report, I tried the mqtt settings, but nothing is being published for state changes, I didn't have the time to check for commands.
```
That would surprise me a bit.
The MQTT implementation is very basic and it works fine here.
Perhaps it was not enabled correctly (MQTT needs to be enabled before use).
Could you check the setting?

**Comment by aleksandrov1995** [comment]
> As for:
> 
> > I have something strange going on (i did a hard refresh this time!) and with the new version the functionality for requiring a pin for arming/disarming is inverted for me.
> > E.g. if i turn on the require pin for arming, then it doesn't require pin for arming, but instead for disaming. Same thing happens if i turn the other one on, disarming becomes arming.
> 
> It was reported somewhere else as well. I just patched that. It was wrong in the code.

I was the one who reported it.

> About this:
> 
> > I dont know if i should open a new issue, but also, if the leave time is set to None, the alarm will not Arm. (tested for arm home/arm night)
> 
> I can reproduce this issue.
> It gives me:
> 
> ```
> 2020-11-18 20:58:17 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_arm_away
> /config/custom_components/alarmo/alarm_control_panel.py:422: RuntimeWarning: coroutine 'AlarmoEntity.async_arm' was never awaited
> ```
> 
> I missed an `await` statement for an async function call.
> So, you can consider it fixed as well.

   Thanks !

> About this:
> 
> > There is more I can report, I tried the mqtt settings, but nothing is being published for state changes, I didn't have the time to check for commands.
> 
> That would surprise me a bit.
> The MQTT implementation is very basic and it works fine here.
> Perhaps it was not enabled correctly (MQTT needs to be enabled before use).
> Could you check the setting?

I had to change the default alarmo/state to something different and save, then it all worked, even if i make it alarmo/state again.
But with the default and just turining it on, it wasn't publishing anything.

**Comment by nielsfaber** [comment]
> I had to change the default alarmo/state to something different and save, then it all worked, even if i make it alarmo/state again.
But with the default and just turining it on, it wasn't publishing anything.

That's valuable info, thanks.
I think i already know what's going on then.
Will let you know if I made a fix. You will probably not be able to reproduce it though.

**Comment by aleksandrov1995** [comment]
> > I had to change the default alarmo/state to something different and save, then it all worked, even if i make it alarmo/state again.
> > But with the default and just turining it on, it wasn't publishing anything.
> 
> That's valuable info, thanks.
> I think i already know what's going on then.
> Will let you know if I made a fix. You will probably not be able to reproduce it though.

Yeah, since i changed it, i don't think i will be able to reproduce it.

**Comment by nielsfaber** [comment]
[Release v1.1.2](https://github.com/nielsfaber/alarmo/releases/tag/v1.1.2) contains fixes for all bugs you reported here.
Please confirm all works as you expected now, and close the issue if all is solved.
Thanks for reporting the bugs!

**Comment by aleksandrov1995** [comment]
Thanks for the fixes, everything works as expected now.
