### ISSUE TITLE
HomeKit with bridge + alarm_control_panel error msg

### ISSUE THREAD

**Issue by sindudas** [nielsfaber/alarmo#160]
Every Integration of HomeKit added on bridge mode and "alarm_control_panel" enabled produces that messages in log:

> 2021-03-22 13:28:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemCurrentState: value=0 is an invalid value.
> 2021-03-22 13:28:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemTargetState: value=0 is an invalid value.

**Comment by nielsfaber** [comment]
You're posting this in the wrong place.

**Comment by sindudas** [comment]
Maybe not well expressed.

These error message seems to be produced by lack of some variables, I think.

> default_current_states = loader.get_char(
            "SecuritySystemCurrentState"
        ).properties.get("ValidValues")
        default_target_services = loader.get_char(
            "SecuritySystemTargetState"
        ).properties.get("ValidValues")

This code is from [homeassistant/homekit](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/type_security_systems.py)

Maybe Alarmo need to setup this "state"s to be fully compatible with HomeKit integration use.
