### ISSUE TITLE
Alarm Triggers Twice

### ISSUE THREAD

**Issue by wdwithmp** [nielsfaber/alarmo#165]
Hi Mate, Just updated to 1.5.5 and tried and was doing some testing, the trigger happens twice, so this is causing the node red flows to fire twice. For example, when you open the door it triggers, so the node red flow fires, then after the time delay it gets triggered again, so the node red flow fires again 

![AlarmO](https://user-images.githubusercontent.com/71815308/112928709-7327bb80-915a-11eb-83f3-67c1fe947a85.jpeg)

I have allowed 20sec to arm and disarm for testing

this does not happen for armed_away or armed_night, the event fires only after the 20sec countdown is complete

**Comment by nielsfaber** [comment]
> For example, when you open the door it triggers, so the node red flow fires, then after the time delay it gets triggered again, so the node red flow fires again

Can you explain what you mean by "it gets triggered again"?
I'm not a node-red user so the screenshot doesn't tell me much.
Could you share a screenshot of the alarmo entity logbook in HA?

I would expect that triggering only occurs once in the transition from `pending` -> `triggered` state.
The alarmo entity cannot return to `pending` from `triggered` state and reach `triggered` again, so I'm not sure how consecutive triggers could ever occur.

> this does not happen for armed_away or armed_night, the event fires only after the 20sec countdown is complete

What do you mean by this exactly? Normal state flow is `armed_away` -> `pending` -> `triggered`, unless a sensor is configured to trigger without delay.

**Comment by wdwithmp** [comment]
Hi Mate,
thanks for the reply, after reading your comment, I went back and checked the NodeRed flow and figured out the issue. Basically I was checking the states
arming
armed_away
armed_home
triggered
but my if-else condition had not taken into account the "pending" state, so what was happening was if it was none of the above stated it assumed "triggered" so even when it was in "pending" state it caused the "triggered" condition to run and then when it changed from "pending - > triggered" it caused the "triggered" condition flow to fire again

apologies for not checking it over and over again to see if there was a issue first before opening a ticket mate.
