### ISSUE TITLE
Feature request: Audible countdown timer media player (TTS)

### ISSUE THREAD

**Issue by dannymertens** [nielsfaber/alarmo#166]
Hi,

In my previous solution I got a audible countdown timer that was working true a media player (google mini, Sonos...) I more or less could recreate this with an automation but its not completely seamless so maybe an option to add to a future version?

**Situation...**

- Arming the alarm audible countdown till armed in seconds...
- Disarming the alarm during the arming fase (mistakes, needed pauze to get something you forgot...)
- Countdown before alarm triggers
- disarming the alarm
- warning message before alarm triggers
- Open doors, windows...
- .....

**Comment by LongThanMa** [comment]
I hope for the same thing too. I wish for an option to choose MP3 file in the create action, so I can choose my own audio file for an event. I tried to create an automation for that but I couldn't do it. If anyone knows how to do it, please let me know. Thank you in advance.

**Comment by nielsfaber** [comment]
It seems to me that this should be already possible, only not through the automations editor within Alarmo, but with external automations.

If I understand the request correctly, the question is about allowing the user to create notifications that don't use the `notify.xxx` services of HA, but also the `tts.xxx` services?

**Comment by dannymertens** [comment]
Hallo Niels,

That's more or less true and I do this now with an automation, but is not completely reliable and not that correct to build to be honest

My idea is when you arm, disarm, trigger the alarm that you get a audible countdown true your speakers, 

Something like this, 

"The alarm will activate in (timeout) seconds, the alarm is now activated"

"The alarm will be triggered in (timeout) seconds..."

"The alarm is disarmed"

....
