### ISSUE TITLE
Alarmo Card not showing up in 'Add New Card'

### ISSUE THREAD

**Issue by EpicMount** [nielsfaber/alarmo#171]
I have updated to the latest release, 1.5.5 which is supposed to add the custom card however when I try to add the card from Lovelace, I do not have the custom Alarmo card as an option.

![image](https://user-images.githubusercontent.com/53345292/113438196-132d5100-93b6-11eb-8e1c-df46b96ce1e2.png)

**Comment by nielsfaber** [comment]
Try emptying your browser cache.
(Ofcourse you also need to restart HA after updating Alarmo)

**Comment by EpicMount** [comment]
Thanks, I did reboot a couple of times which didn't solve the problem however I did clear the cache and restart my browsers which seemed to have solved the problem.

**Comment by EpicMount** [comment]
I had closed this as it appeared to be working on my desktops and wall tablets however, I was not able to get my phone apps to work correctly.  In order to fix, you need to delete the data for the app by going into your settings and clearing the cache, otherwise, you will get 'Entity not found' on your dashboards.
