### ISSUE TITLE
Custom element not found: alarmo-card

### ISSUE THREAD

**Issue by RichardDMartinez** [nielsfaber/alarmo#172]
Hello. I just installed Alarmo for the first time today (v1.5.5) and I really like how well put together this integration is. I have it working well with HA's Alarm Panel Card, but I want to use the alarmo-card instead, But when I try to add the alarmo-card to a dashboard, there is no "Custom: Alarmo Card". If instead I click "Manual", then when I enter 

type: 'custom:alarmo-card'

I get "Custom element not found: alarmo-card".

**Comment by nielsfaber** [comment]
Hi,
Multiple people have addressed this issue as well.
So far all of them managed to solve it by clearing their browser cache.
Could you try this as well?
Perhaps switching to another browser, or opening a private tab would work in the same way.
If the problem still persists we can look at other possible issues.

**Comment by seanmccabe** [comment]
Did as above, issue resolves

**Comment by RichardDMartinez** [comment]
Yes, clearing the browser cache worked. Thank you for the quick response.
