### ISSUE TITLE
Alarmo Card is not loaded

### ISSUE THREAD

**Issue by Stromber03** [nielsfaber/alarmo#177]
Hi, When I want to configure an alarmo card. I have the following error:
Invalid configuration
type: 'custom:alarmo-card'

**Comment by nielsfaber** [comment]
You could try to clear your browser cache, for some users this caused the card to show up.
Otherwise, you should assign the entity to the card, see also here: https://github.com/nielsfaber/alarmo#configuration

**Comment by Stromber03** [comment]
Great,  it works.
I just added the entity attributes to make it work.

Thanks you

Le dim. 11 avr. 2021 à 05:56, Niels Faber ***@***.***> a
écrit :
