### ISSUE TITLE
[Feature Request] - Add Disarm Service

### ISSUE THREAD

**Issue by seanmccabe** [nielsfaber/alarmo#178]
Although can do this with an alarm panel call, would be helpful to have the "Disarm" as a service the same as arm.
Again for doing push notification actions, as well as in my case, using NFC tag to disarm.

**Comment by nielsfaber** [comment]
What would be the difference between `alarm_control.panel.alarm_disarm` vs a `alarmo.disarm` ?
I don't see the added value (other than a shorter name) in adding this.

**Comment by seanmccabe** [comment]
I suppose it is partially consistency, if there is an _alarmo.arm_, why not _alarmo.disarm_?
If there is an arming service, would expect there to be a disarming service.

Also to avoid confustion, alarm_control_panel gives the impression of using the alarm_control_panel in lovelace (its really an HA issue with that naming convention), but can be helped by this integration.

**Comment by nielsfaber** [comment]
This service is added in v1.5.7.
As said, `alarm_control.panel.alarm_disarm` and `alarmo.disarm` have the same behaviour.
