### ISSUE TITLE
Change 'Arm Home' to 'Arm Stay'

### ISSUE THREAD

**Issue by EpicMount** [nielsfaber/alarmo#179]
Hi,
I've had 3 different people accidentally set off the alarm by hitting the 'Arm Home' button and then opening the door and triggering the countdown when they left.  It appears that 'Arm Home' to the average person not used to the system means 'arm the house'.   Is it possible for me to change the button text to 'Arm Stay' and if so, how?

**Comment by nielsfaber** [comment]
The alarm states are [defined by](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#states) Home Assistant, so they are out of my control.
Although I don't like the naming convention either (especially regarding `armed_custom_bypass` and `pending` states), we will have to live with it.
The labels on the buttons in the card (I assume you're talking about the Alarmo Card), are also internally in HA defined and translated to over 30 languages.
So a short answer to your question is: no, its not possible to have the arm buttons changed.

I think its easier to explain your family members how the alarm works and which button does what.
You could also opt for avoiding the "Armed Home" state and only use "Armed Away" and "Armed Night". IMO these labels are pretty easy to distinguish and in my personal use-case sufficient for my needs.

**Comment by EpicMount** [comment]
Thanks for the response.  The issue I have is with those who wouldn't be using the system regularly, i.e. cleaning service or contractors despite my explicit instructions for them to press 'Arm Away' when they're leaving.  I think I'll take your advice and just remove 'Arm Home' and keep 'Arm Night' since like you said, it is essentially the same thing.
