### ISSUE TITLE
Sensors and not binary ones

### ISSUE THREAD

**Issue by cob94440** [nielsfaber/alarmo#184]
Hello. I m using delta dore door sensor.
They gives me sensors and not binary sensors.
Si i Can t see them
Using tydom plugin.
How Can i add my sensors to alarme.
Thanks for your help

**Comment by nielsfaber** [comment]
Security sensors typically are binary devices (on/off, open/closed etc.)
If your tydom integration does not support this, you may need to add template sensors to convert to a binary state.
Take a look here: https://www.home-assistant.io/integrations/binary_sensor.template/
