### ISSUE TITLE
[Bug] Error when installing in HA Dev

### ISSUE THREAD

**Issue by a1ad** [nielsfaber/alarmo#186]
Hi,

We are testing a new supported keypad in the dev version of homeassistant and we want to test the keypad with alarmo and create some automations and blueprints:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4560
https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4758

But i got an error when installing alarmo (v1.5.6)

![afbeelding](https://user-images.githubusercontent.com/29516835/115855501-99740a80-a42b-11eb-9e2c-4268537d9225.png)

![afbeelding](https://user-images.githubusercontent.com/29516835/115855565-abee4400-a42b-11eb-8cf5-660acdadb8ee.png)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 260, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alarmo/init.py", line 77, in async_setup_entry
    await async_register_card(hass)
  File "/config/custom_components/alarmo/card.py", line 37, in async_register_card
    hass.data[DATA_EXTRA_MODULE_URL].update(url_set)
AttributeError: 'UrlManager' object has no attribute 'update'

**Comment by nielsfaber** [comment]
The errors seem to indicate that you already had it installed and attempted to install a second instance.

**Comment by a1ad** [comment]
i already removed alarmo through the HACS gui, do i need to clean up some folders?

**Comment by a1ad** [comment]
@nielsfaber just checked, no folder left in custom_component, reinstall repo, restart HA, install alarmo -> same problem.

**Comment by a1ad** [comment]
Follow up: just created a new HA docker dev:
- install hacs
- install alarmo
-> same problem

**Comment by nielsfaber** [comment]
Ooff, sounds bad.
I think a breaking change was made to HA core.
I’m not running the latest dev version, but I will take a look when I have the time.

**Comment by nielsfaber** [comment]
I could reproduce your issue by switching to the dev branch.
I made a fix in https://github.com/nielsfaber/alarmo/commit/0edb3deef72857e2e854168f5d615899384cd1ca
You could manually update the files, otherwise I will create a release in approx a week (with also some other changes).

**Comment by a1ad** [comment]
Great, thanks for the quick fix, confirmed working.

**Comment by a1ad** [comment]
Hey @nielsfaber, ik was aan het denken.. zou het niet intressant zijn om het nieuwe HA keypad apparaat "native" te ondersteunen in Alarmo. Als je dat iets lijkt contacteer me via Discord: AES#2599, zo niet dan houden we het gewoon bij blueprints om zo te proberen koppelen met Alarmo en negeer je dit bericht maar :-)

**Comment by a1ad** [comment]
oh no, maybe there is more wrong, i cant choose the alarmo panel, only the new ancillary keypad:
![afbeelding](https://user-images.githubusercontent.com/29516835/116003694-5074af80-a5ff-11eb-9ceb-3c069e79765d.png)
