### ISSUE TITLE
Open sensors variable contains english words

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#188]
I have defined a notification that use a tts notify entity to tell that Alarmo could not be armed because of an open sensor.
It works. But the words I pass to he action are in spanish, plus the 'open sensors' variable. {{open_sensors}} contains the words of the name of the open sensors + "is open".
So, the result is a mix of spanish and english words, which is quite funny but a little annoying.
Is there any way to get only the name of the open sensor?
Thanks in advance.

**Comment by rindlerblabla** [comment]
Have you seen this solution?https://github.com/nielsfaber/alarmo/issues/51
