### ISSUE TITLE
Feature Request: Add option to bypass sensors when arming

### ISSUE THREAD

**Issue by laithalsunni** [nielsfaber/alarmo#193]
It would be nice if we can bypass the sensors that stopped the alarm from arming when the arming feal. for example when arming night and need to have a window open when the wither is nice outside. the window may not be the same every day, so the option to bypass it for that arming instance only will be great.

**Comment by nielsfaber** [comment]
This function is already in Alarmo. You can use the following:

1.  Use the `alarmo.arm` service with property `force: true`. All sensors which are active when arming will be bypassed and ignored until the next time you disarm the alarm.
2.  Use the [actionable notifications](https://github.com/nielsfaber/alarmo#actionable-notifications). You will get a push message on your phone when the alarm could not arm. In the message you can click a button "Force Arm" (same effect as item 1)
3. You can configure a window sensor with option "bypass automatically". If the window is closed when arming, it will be watched, if the window is open while arming, it is ignored until next time.

Are you missing something?
