### ISSUE TITLE
Issue With Latest Home Assistant Firmware 2021.5.0b5

### ISSUE THREAD

**Issue by soundslikeluke** [nielsfaber/alarmo#194]
This issue has occurred which stops Alarmo from Starting up when you look at the page it just shows up as loading and doesn't ever load. In the integration page, it says the error failed to set up. I am on the latest Alamo Version. I love this addon it is amazing. If it is just me having this issue I will reinstall it to see if it makes a difference. 

 This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmo/card.py:37
Integration: Alarmo (documentation, issues)
First occurred: 6:28:49 (1 occurrences)
Last logged: 6:28:49

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alarmo/__init__.py", line 77, in async_setup_entry
    await async_register_card(hass)
  File "/config/custom_components/alarmo/card.py", line 37, in async_register_card
    hass.data[DATA_EXTRA_MODULE_URL].update(url_set)
AttributeError: 'UrlManager' object has no attribute 'update'

and I also get this error 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:87
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:42:52 (5 occurrences)
Last logged: 6:50:19

[139795058424608] Received invalid command: alarmo/users

**Comment by nielsfaber** [comment]
I think you need to update to v1.5.7 (which was released 2 days ago).
This error suggests you don’t have the latest changes yet

**Comment by soundslikeluke** [comment]
That was it. Sorry To bother you. For some reason, it didn't show up that it needed an update but I did find the latest version and it is working perfectly.
