### ISSUE TITLE
How to use button scaling?

### ISSUE THREAD

**Issue by fludstank** [nielsfaber/alarmo#195]
Is there documentation on how to scale up the button sizes for the lovelace card? I tried adding `button_scale: 2.5` in the lovelace code editor, but it didn't seem to do anything.

**Comment by nielsfaber** [comment]
Probably a cache issue.
You need to clear your browser cache or click "reload resources".

**Comment by fludstank** [comment]
That did it...had to clear the browser cache twice and restart HA for it to work. Also, not to be a pest, but is there a way to separate the scale of the arming buttons and the scale of the code buttons? I really like the larger code buttons but the arming buttons are a little overwhelming when scaled to 2.5x IMO.

Love this project and the continued progression forward!

**Comment by nielsfaber** [comment]
I’m hearing these cache related problems quite often.
Would it be better to have the Alarmo-card as a separate plugin?
I thought an “all in one” installation would be easiest for users, but it seems to give frustration.

**Comment by fludstank** [comment]
That could be a really cool option! It would give a lot of flexibility as far as the scaling goes to be able to scale the status/arm/disarm buttons independent of the scaling of the code entry buttons, plus for those of us that use it as a sub-card inside of a conditional card, it would help maximize screen real estate on smaller screens. I think you might be really on to something! And then I would imagine the code wouldn't be too hard to re-use for a unified card option for those that like the current way.

**Comment by nielsfaber** [comment]
What I meant was to have alarmo-card outside of alarmo itself, so it is a separate installation.
Please see here for more info: https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/473

I will close this issue since your problem appears to be solved.

**Comment by pickonedev** [comment]
button_scale is working but, but it is changing the icon size as well, making the button different from the others..
![Untitled](https://user-images.githubusercontent.com/34201387/157012149-719416e0-f427-4319-a374-5f93f106c930.jpg)
.
