### ISSUE TITLE
Alarm not disarming/arming after update to 2021.5

### ISSUE THREAD

**Issue by ShayaanF** [nielsfaber/alarmo#197]
When I restart HA (have updated to latest version (core 2021.5), the alarm starts in an "Unknown" state as per the Alarmo card in Lovelace.
![image](https://user-images.githubusercontent.com/26008692/117227169-d9e46880-addb-11eb-8ec2-4575af4e070b.png)

Eventually it settles back to Disarmed, and then trying to use "arm home" or "arm away" both result in no action. I thought I fixed it by reinstalling the addon which worked for one click -- but after that, no longer worked and the buttons went dead.

There's nothing in the logs to reflect that, either -- it doesn't pick up any of the clicks on the card so no action is taken.

**Comment by ShayaanF** [comment]
So I've wiped the installation completely, and there's a little benefit -- Arm Away works, Arm Home does not. Not really sure why, nothing triggering in the logs.

**Comment by ShayaanF** [comment]
Some added info...  If I add a trigger delay to arming, the buttons work -- but don't actually execute. 
![image](https://user-images.githubusercontent.com/26008692/117228374-8889a880-adde-11eb-926d-5aa247180647.png)

If there's no trigger delay on the "Arm Home" -- the button does nothing. 

If I add a trigger delay, it goes to "Arming", and then results back into a "Disarmed" state.

**Comment by ShayaanF** [comment]
Same thing happens with an automation -- it will use the trigger delay to start, and then result in a disarmed state. So it's not just the card.

**Comment by ShayaanF** [comment]
Aaaaaand I"m an idiot, again.

One of the sensors was open (side door) and it would default back to arming. Will be closing this but thanks for watching me make a fool of myself :)

**Comment by nielsfaber** [comment]
Don’t worry about a false report.
What I see from your screenshot is that you’re not actually running the Alarmo-card (but the alarm panel card that comes with Lovelace).
This card has no icon in the top-right corner.

I think switching to this card would help you a lot because it focuses on providing useful feedback when something is up.

**Comment by ShayaanF** [comment]
> Don’t worry about a false report.
> What I see from your screenshot is that you’re not actually running the Alarmo-card (but the alarm panel card that comes with Lovelace).
> This card has no icon in the top-right corner.
> 
> I think switching to this card would help you a lot because it focuses on providing useful feedback when something is up.

I've made that change, as well. Thanks again.
