### ISSUE TITLE
No pending trigger in automation

### ISSUE THREAD

**Issue by a1ad** [nielsfaber/alarmo#198]
Hi,

I am trying to create a automation to tie a keypad with alarmo but i cant find the pending state? The only states that available are:
![afbeelding](https://user-images.githubusercontent.com/29516835/117274426-52d7d480-ae5d-11eb-8052-f0bcc931c006.png)

I need pending to tie it up with the "entry_delay" keypad service.

**Comment by nielsfaber** [comment]
I didn't make this list.
I recommend to trigger on 'state' change of the alarm_control_panel entity.

**Comment by a1ad** [comment]
ok, what are the available states i can use?

**Comment by nielsfaber** [comment]
check the documentation.
Github issues are not meant for help questions.

Use the forum for that: https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910
