### ISSUE TITLE
Alarmo Card Missing HA 2021.5.1

### ISSUE THREAD

**Issue by hockey6611** [nielsfaber/alarmo#199]
After updating from 2021.4 to 2021.5.1 the alarmo panel card appears missing. Previously added cards to lovelace now show red, with missing card. The card is not available from the UI picker, and entering the YAML does not work either. I am running Alarmo v1.5.7, and HACS 1.12.3.

The Alarmo integration itself appears to be working. I have tried reinstalling the integration with HACS as well with no success.

![image](https://user-images.githubusercontent.com/28613898/117510137-87c95180-af59-11eb-930e-3b5aeda50d62.png)

**Comment by hockey6611** [comment]
Very strange... After leaving home assistant a couple of hours, the card has returned, and I no long have an issue. If anyone understands why this happened please comment. I will close the issue.

**Comment by mattbruman** [comment]
Having same issue but only on the android app, cleared cache and it still wont show up.

**Comment by hockey6611** [comment]
I never had the issue on mobile. Only on desktop browser. I did have the missing car a couple of additional times but a simple refresh, and it reappeared. I didn't even clear cache.

Sorry I don't have more to offer. Did you clear the app cache and data, and log back in?
