### ISSUE TITLE
Duplicated Notifications

### ISSUE THREAD

**Issue by albersag** [nielsfaber/alarmo#200]
When creating a General Panel, and you have several Areas, i receive same notification duplicated as 5 times . For arming, fired alarm etc.. (General + 4 Zones) in my case.

It should be notified only once. Testing with Try it feature in every Notification just send one notification as expected.

Using latest 1.5.7 and HA 2021.5.1

**Comment by nielsfaber** [comment]
Buenos días Alberto.

Could you share the configuration you used?
You should be able to connect a notification to an area, or the master alarm if you want to keep it centralized.
Sounds like the notification is set up to respond to any area.

**Comment by albersag** [comment]
Hi Niel!

I did not attach this notification to any area. Im using a General Panel for all the areas

name: Alarma Armada
modes: []
triggers:
  - state: armed
actions:
  - service: notify.mobile_app_le2123
    service_data:
      message: Alarma armada
area: null

Should i attach to one of them only?

**Comment by nielsfaber** [comment]
Area null seems OK, as it implies that the notification is fired once the "master" is armed (so all areas are armed).
I didn't manage to reproduce your problem, for me the notification triggers only once.
Currently I have no idea what is different in your setup compared to mine.

**Comment by nielsfaber** [comment]
In v1.6.0 many changes have been made regarding the implementation of the notifications.
I suggest to update to this version, hopefully all problems are solved now.
