### ISSUE TITLE
Feature Request: Integration with ZHA Alarm Panel

### ISSUE THREAD

**Issue by Gamerayers** [nielsfaber/alarmo#202]
With the ZHA Alarm panel now working, I am hoping that there would be an easy integration between Alarmo and the ZHA alarm panels.  I want to use that ZHA Alarm panel to control state (armed, disarmed, etc.) and Alarmo to control the actual state of the alarm so that I didn't need to program all the door sensors and methods of status manually.  I can them together using automation, but this seems to defeat some of the purpose.

Any chance for support of ZHA Alarm panels in the future?

**Comment by Gamerayers** [comment]
ZHA Alarm Panel is the ability to use a keypad style alarm panel with Zigbee (ZHA).  Specifically ones like the centralite 3400(image).  Find more details about it here: https://github.com/home-assistant/core/pull/49080
Since this has it's own alarm interface, I can use it, with automation, to control Alarmo, but it would be easier to integrate directly with it.
![image](https://user-images.githubusercontent.com/59520501/117807762-0cea8a00-b22a-11eb-8ed2-2054add64098.png)

**Comment by mattbruman** [comment]
> Hmmm. I understand. The issue comes back to the way that Zigbee and the alarm panels work with the security code. The code itself is part of the message and there is 2 way communication for disarming. Therefore, use of the ZHA alarm panel is required to control the panel. And a physical panel is required by me for what I want for my security system.
> 
> Wish there was a way to integrate with Alarmo.

Just create automations that keeps the panels in sync, thats my plan for now

**Comment by Gamerayers** [comment]
So interesting, there is a state defined in the keypad for 'arming'.  Meaning, while the time isn't 0 between state changes, it provides an update of the arming time such that Alarmo could know that it is arming.  For now, I can simply link the 2 together, but really think it would be cool to have it as an option in Alarmo.

![image](https://user-images.githubusercontent.com/59520501/117969792-e134d600-b2f5-11eb-8370-c8331194db8b.png)

**Comment by kloodhu** [comment]
U would really grateful if you could integrate the zha physical alarm panel somehow into Alarmo.

**Comment by nielsfaber** [comment]
I do think this keypad is a good companion for Alarmo.
I would need such a device to be able to properly create and test support for it. 
There is not really any documentation (both in ZHA as zigbee2mqtt) that gives me a good overview of the integration.
Unfortunately I don't have it (I use Nest Hub for arming/disarming alarmo) so I'm afraid I cannot really fulfill this request.

**Comment by nielsfaber** [comment]
For who is still interested in this: I made a blueprint to connect a zigbee2mqtt keypad to Alarmo: https://community.home-assistant.io/t/zigbee2mqtt-control-alarmo-via-keypad/420016. 
It can probably modified to support other keypads, ZHA, Zwave, etc.
I think it's better to leave this outside of Alarmo, since the implementation is device-specific.

**Comment by hesspoint** [comment]
It is a physical keypad that connects with zigbee to home assistant via zha. 

Here is an example https://youtu.be/99JtDOz9_B8
