### ISSUE TITLE
Accommodate for changed actionable notifications in iOS app 

### ISSUE THREAD

**Issue by bobvmierlo** [nielsfaber/alarmo#203]
The actionable notifications have been changed within the iOS app making categories deprecated soon. Do you need to accommodate for this change to solve the retry/force arm functionality?
See [the blog post](https://www.home-assistant.io/blog/2021/05/10/ios-20215)

**Comment by bobvmierlo** [comment]
commenting to delete stale label

**Comment by bobvmierlo** [comment]
Commenting to delete stale label again

**Comment by nielsfaber** [comment]
@bobvmierlo what needs to be updated according to you?
I only had to update the documentation a bit for the changes in HA, but in Alarmo this needs to be set through YAML by the user.

**Comment by bobvmierlo** [comment]
You are right, I didn't check the documentation after opening the issue. Seems clear to me and it seems to work perfectly.
