### ISSUE TITLE
Alarmo card wont load on Android App

### ISSUE THREAD

**Issue by mattbruman** [nielsfaber/alarmo#204]
Getting Custom element doesn't exist: alarmo-card
but only on android app, I tried clearing the app cache, I don't think there is a way to clear the browser cache. It is working fine on desktop browser. I read through others issues that had a similar issue but I don't see a solution. Any logs I can provide?

**Comment by CommittotheIndian** [comment]
I have at as well but in my HA instance web browser.

**Comment by mattbruman** [comment]
So only way I could get it to load was clearing the app data completely. The android app really needs a way to clear the lovelace cache.

**Comment by nielsfaber** [comment]
Unfortunately this is a caching issue, which is out of my control.
Please check this post https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/473

I will close this issue, please vote if you think things should change.
