### ISSUE TITLE
avaible arm states on card popup

### ISSUE THREAD

**Issue by Ryckie** [nielsfaber/alarmo#206]
Hello,
I have the following issue.
I do not have armed home state enabled. I only use night and away.
I am able to define that in the states so it does only show these 2 options.
But now my issue is, when clicking on the card and it opend up the popup. It shows the arm modes; home, away.
How can I change this please?
![image](https://user-images.githubusercontent.com/63733138/118408172-9a900480-b684-11eb-9bda-83d37bf123b0.png)

**Comment by nielsfaber** [comment]
This is a bug in HA.
I cannot fix it for you.
