### ISSUE TITLE
Trigger alarmo manually - (alarm_control_panel.alarm_trigger)

### ISSUE THREAD

**Issue by jagannew** [nielsfaber/alarmo#207]
Hi... I Installed Alarmo, it is very nice and easy to use. thank 
but I'm facing some issues in triggering the alarm manually by using:alarm_control_panel.alarm_trigger" command

after checking the documentation, I got that this option is not available in alarmo , please try to include this feature. 
in case of any emergency, some peoples have to trigger the alarm manually (even though it is not armed )

**Comment by nielsfaber** [comment]
Please see here:
https://github.com/nielsfaber/alarmo/issues/67
It is basically the same request.
If needed, some extra function can be discussed, but so I think the behavior you are looking for can be made already.

**Comment by jagannew** [comment]
> Please see here:
> #67
> It is basically the same request.
> If needed, some extra function can be discussed, but so I think the behavior you are looking for can be made already.

i have already go through the always-on function but my request is I want to make one trigger button to trigger the alarm even throw alarm is off. 
the situation where I'm going to use 
1. when I got a camera notification from the home assistant I want to have one option to trigger the alarm
2.  want to configure one Zigbee button, when that button is pressed alarm will be triggered

I hope u understand my request
