### ISSUE TITLE
Feature: Always ON sensors (not only environmental ones)

### ISSUE THREAD

**Issue by Ryckie** [nielsfaber/alarmo#209]
I would like to be able to define some door/window sensors that can directly trigger the alarm.
This is useful for windows that aren't supposed to open.

**Comment by nielsfaber** [comment]
You can just clear the sensor type and then you have the “always on” setting available.
I don’t know what more functionality you would expect?

**Comment by Ryckie** [comment]
I would like to be able to have a zone that is always on.
Now environmental sensors are always on. (smoke, heat, co) --> I would like to be able to turn this zone off manually or be able to turn off a sensor.
And also a self made group like fire doors. They should always be under alarm. Also when master is disarmed. But they should be able to be turned off temporally also.
Can you provide something like that?
