### ISSUE TITLE
Allow open while arming - no warning if left open

### ISSUE THREAD

**Issue by onkytonk** [nielsfaber/alarmo#210]
I have “Allow open when arming” activated on my front door sensor. However, today we left it open, and exited through the garage. Wondering if there should be a “timeout” where after a certain time, it should then warn you that a trigger is still open. 

Hope that makes sense. 

Luckily we have a security door, and that was locked.

**Comment by nielsfaber** [comment]
The "allow open while arming" option is only intended for motion sensors, which will reset themselves in 1-2 mins after being activated.
Its a bad choice to use it for a door.
The option is automatically hidden for you if you set the correct sensor type.

A door sensor should never be ignored by an alarm system if you ask me.
