### ISSUE TITLE
Issue Adding Sensors to Areas

### ISSUE THREAD

**Issue by soundslikeluke** [nielsfaber/alarmo#212]
For some reason the latest version of Alarmo is not allowing me to add sensors into different areas. When I try to add a sensor in automatically adds the sensor to No Area and when I try to move it from there it refuses to move the sensor. On the drop down menu when it allows you to select the area it shows the option but you can select it or save it.  

I am running the Latest version of Alamo v1.5.7

Home Assistant Environment 
Host Operating System | Home Assistant OS 5.13
Update Channel | stable
Supervisor Version | supervisor-2021.04.3
Docker Version | 19.03.15

**Comment by nielsfaber** [comment]
Sorry for the late response.
Do you still have this problem?
How does your area setup look like (do all areas have a valid configuration)?

**Comment by nielsfaber** [comment]
https://github.com/nielsfaber/alarmo/issues/181
seems to describe the same issue

**Comment by nielsfaber** [comment]
Closing since OP is not responding, assuming that issue is resolved in the meantime.
Please re-open if you still have problems.
