### ISSUE TITLE
Feature Request: Logbook

### ISSUE THREAD

**Issue by arfrater** [nielsfaber/alarmo#215]
Hi, testing alarmo at the moment I have noted once I dismissed the alarm triggered notification on my phone  I cant check or go back to see what triggered (sensor) the alarm activation. I would like to know if possible a panel on the admin page for logging alarmo actions (who armed/disarmed what sensor triggered the alarm ETC) I think that would be helpful in the administration of the alarm system.

**Comment by nielsfaber** [comment]
The logbook you are referring to is already part of HA, there is no need for duplicating it in Alarmo.
See: https://www.home-assistant.io/integrations/logbook/

You can already read back when Alarmo was armed, disarmed triggered etc, similarly you can check when which sensors changed when.
The only thing that is not in place, is that some context is shown in the logbook regarding what caused the triggering.
There is an open request for implementing this, see: https://github.com/nielsfaber/alarmo/issues/134

**Comment by arfrater** [comment]
Hi, yes I agree, I was more referring to the admin panel having a extra tab for logging events from alarmo or maybe the option to add addition tabs Just a thought that's all Thanks for the reply.

**Comment by e-p-s** [comment]
same here. i belive this is noone reading anymore because the issue is closed. and my newest problem is that logbook is completly empty.
