### ISSUE TITLE
Service alarm_control_panel.alarm_trigger does not work on alarmo entity

### ISSUE THREAD

**Issue by crossbow012** [nielsfaber/alarmo#217]
Rather than creating a template binary sensor to achieve my goal, I was attempting to trigger alarmo directly from an automation during an alarm condition that can't be achieved otherwise.

However the service alarm_control_panel.alarm_trigger does not work on an alarmo entity.

If alarmo is an integration of the alarm_control_panel domain, it should work with all services available in that domain?

**Comment by nielsfaber** [comment]
This service is not supported, since alarmo is supposed to be triggered via sensors.
> If alarmo is an integration of the alarm_control_panel domain, it should work with all services available in that domain?

No. Same holds for `alarm_arm_night` etc. Service support varies between integrations, its not mandatory in HA.

**Comment by crossbow012** [comment]
No problem. I ended up achieving what I wanted with a template binary sensor anyway.
