### ISSUE TITLE
Hide Alarmo configuration panel from non-administrator users

### ISSUE THREAD

**Issue by Necrolust** [nielsfaber/alarmo#22]
I think it'd be a good idea to hide the Alarmo configuration panel for users that are not home assistant administrators.

Currently a non-admin user can just go in and create a code and have full control of the alarm.

**Comment by nielsfaber** [comment]
I am considering to have Alarmo automatically generate users based on the accounts in HA (ofcourse without code yet).
The 'administrator' toggle switch can then be used to give a user access to the panel.
Others will see only a message.
I'm not sure if a HA admin should be necessarily be a Alarmo admin (maybe there are exceptions).
This behaviour was actually in place in v1.0.0. I removed it (temporarily) when doing some big construction works.

**Comment by nielsfaber** [comment]
I (re-)added this functionality in v1.3.2.
You either need to:
- Be logged in with administrator account in HA, or
- Have user defined in Alarmo with a name matching to your HA account and have this user marked as administator

for access to the panel.

Please try it out, and close the issue if the functionality is what you were looking for.

**Comment by Necrolust** [comment]
Functionality works as expected, one UI issue is you can still see the bold formatting:

![image](https://user-images.githubusercontent.com/42605421/100699917-152fd500-3401-11eb-868c-788d17a47fa1.png)

**Comment by nielsfaber** [comment]
woops. As you can imagine i was logged in as admin when creating this. Never saw the sentence myself..
will fix it.

hope the instruction is clear for you.

**Comment by Necrolust** [comment]
Yup looks good. Will close this issue now.
