### ISSUE TITLE
Feature request - Allow bypass per alarm mode

### ISSUE THREAD

**Issue by Tosko4** [nielsfaber/alarmo#220]
So I have a feature request, hope it's not too complicated.

When I arm my home to armed_away, i want all sensors to be closed before i can enable alarm.
When I arm my home to armed_home, some sensors should be bypassed if already open uppon turning this alarm mode on.

Currently the bypass counts to ALL enabled modes (so armed_away, home, night etc).

Can you please make it so I can choose per mode if bypass is allowed or not?

**Comment by nielsfaber** [comment]
I cannot deny that this setting can be useful (e.g. to keep a window open on a summer night).
I would have to shuffle some things around to make this possible though.

**Comment by Tosko4** [comment]
Thanks for the consideration. On a hot day, i have the windows open upstairs. When turning on the night or home mode, i have to run upstairs first. Close all windows, and then turn on the alarm. My dashboard is downstairs, dont have a screen upstairs yet. And phone not always on me.

I could use the override function, but then if a window is closed and then opened again, I would need to turn off the alarm before my house alarm goes berserk hahah.

Thanks mate!

**Comment by timota** [comment]
really looking for this feature. Will be extremely useful. Looking forward when it will be implemented.

**Comment by TheZoker** [comment]
+1 for this request, would be really useful!

**Comment by ConsoleCriminal** [comment]
+1 Goes a bit with #260 : The difference I would have in config here (apart other automations) is that I want to allow upstairs windows open with arm_away, but not with arm_vacation...

**Comment by nielsfaber** [comment]
coming soon!

![image](https://user-images.githubusercontent.com/16861605/128630079-901ca6aa-80b2-4ad1-92e0-724eda0dbfe4.png)

**Comment by Tosko4** [comment]
You made me curious what custom will have for options. But nice! Thank you for working on this FR @nielsfaber

**Comment by nielsfaber** [comment]
I just released v1.7.0 which contains this feature. 
Please let me know if it satisfies your needs.

@Tosko4  'custom' refers simply to the arm mode 'custom' (aka custom_bypass), nothing special. I guess most users don't make use of it (I do, for allowing my robot vacuum to clean without triggering motion sensors).

**Comment by pdeswardt** [comment]
Is there are chance to add more wildcards to the message notifications please ( not talking about the {{sensor_opens}} one, but rather something like {{sensor_name}} ). This is to indicate which sensor caused the alarm to trigger, thereby identifying the "zone" where there was an intrusion ?

Thanks

**Comment by nielsfaber** [comment]
@pdeswardt wrong place for discussing this.

@Tosko4 I assume the added functionality is OK for you and the issue can be closed.

**Comment by Tosko4** [comment]
Yes, sry forgot to post
