### ISSUE TITLE
error in 1.6 actions (When using "Try it")

### ISSUE THREAD

**Issue by cokeman0** [nielsfaber/alarmo#225]
Hi

Trying to add a siren to an (new) action, and with turn on.

![image](https://user-images.githubusercontent.com/6389802/121365981-63d2a480-c939-11eb-8236-89763da82e3c.png)

**Comment by nielsfaber** [comment]
Missing some context to be able to help.

If I set it up like this, it saves without problems:
![image](https://user-images.githubusercontent.com/16861605/121408993-49142600-c961-11eb-822d-bd9846b0c6f6.png)


How did you set up the action?
Perhaps you could switch to the YAML view and see if all looks as it should?

**Comment by cokeman0** [comment]
Again, same a different bug I have reported today, both new and when editing as existing action.

Yaml:
- service: switch.turn_on
  entity_id: switch.warning_device_6

getting this error, when trying to save:
![image](https://user-images.githubusercontent.com/6389802/121410143-91801380-c962-11eb-86f5-2768d8fc7177.png)

**Comment by nielsfaber** [comment]
Yup, I'm seeing this too:
![image](https://user-images.githubusercontent.com/16861605/121411411-e4a69600-c963-11eb-88ac-8fefa45a383e.png)

I will check it out.

**Comment by nielsfaber** [comment]
I found the problem, will also be fixed with the upcoming release. https://github.com/nielsfaber/alarmo/commit/fec767d97f322186f1eca3e6136f9f29d569208d
