### ISSUE TITLE
Alarm activates and deactivates automatically

### ISSUE THREAD

**Issue by Jolly-Roger82** [nielsfaber/alarmo#23]
I installed alarm and have set it up as I wanted. But sometimes the system armes itself and triggers without any one of us arming the system before.

Very annoying when all of a sudden the sirens go off at home.

**Comment by Mugge66** [comment]
I have the exact same thing ?

**Comment by nielsfaber** [comment]
That sounds pretty bad!
Could you guys check the log for details?
Or did you find some pattern when this happens?
(Ofcourse) I didn’t see this behavior myself, and I don’t know where to look for it..

**Comment by nielsfaber** [comment]
Please update to v1.2.0, because I changed / improved some things that may have an effect on this bug.

Also consider to enable debug logging for alarmo, by adding to `configuration.yaml`:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```

**Comment by nielsfaber** [comment]
Closing due to no response.
