### ISSUE TITLE
No longer possible to perform an Action on a Script

### ISSUE THREAD

**Issue by craigmcgowan** [nielsfaber/alarmo#231]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
It appears that from 1.57 onwards, it is no longer possible to perform an Action, on a Script. This used to be possible up to 1.57 so that a script could be triggered when an alarm event occured

### Actual behavior
Initially when updating to a newer version, the script would no longer show in the section where you create actions. And trying to readd a script in UI mode is not possible as the selector only allows the selection of certain domains - script not being one of them. 

I have not been able to see anywhere in either Github or the Home Assistant forum that this behaviour is by design.

**Comment by nielsfaber** [comment]
I will check it out.

**Comment by nielsfaber** [comment]
For me it is possible to select my `script` as entity for the action:
![image](https://user-images.githubusercontent.com/16861605/122160922-1098ae80-ce71-11eb-9024-2befa26c5eca.png)
So, I am not able to reproduce the behaviour as you mention it.
You also don't provide steps I can follow to reproduce it, so I am unable to help.

The only improvement I see is that you shouldn't be able to select action "turn on" or "turn off" for a script.
Now you have to switch to yaml and manually set the service the same as the entity_id, like this:
```
- service: script.notification_script
  service_data: {}
  entity_id: script.notification_script
```

I will fix this in the upcoming update.

**Comment by nielsfaber** [comment]
GUI fixes are on their way https://github.com/nielsfaber/alarmo/commit/c707c687d4f5913ff341a11f5b7e02ada09c406b

**Comment by nielsfaber** [comment]
@craigmcgowan Perhaps your issue is about notifications, rather than actions?
There is already an open issue about that, see https://github.com/nielsfaber/alarmo/issues/236
