### ISSUE TITLE
UI Home/General

### ISSUE THREAD

**Issue by Extreme79** [nielsfaber/alarmo#232]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
To see a page that fit the screen 😂

### Actual behavior
The page exceed the screen and it's impossibile to use. I must rotate the device to use it

### Steps to Reproduce
I see the UI issue Everytime, via app or browser, clicking on Alarmo in the left side menu. No specific steps to describe
![Screenshot_20210612-154447](https://user-images.githubusercontent.com/33934444/121778734-88788780-cb98-11eb-8f3b-8d8c907d53d5.jpg)

**Comment by nielsfaber** [comment]
Hmm strange.
For me it looks like this on an iPhone 8 (which has quite a narrow screen):
![image](https://user-images.githubusercontent.com/16861605/121779430-de026380-cb9b-11eb-9ac6-a68b2e6444c7.png)

So it seems to be browser/device related.

**Comment by Extreme79** [comment]
I forgot to describe the device 😸
OnePlus 8T updated with latest Android 11.
The issue is only in the general/main screen. All others tabs are normally displayed (sensors,codes...)
This happen to me with HA app, with chrome and Firefox.

**Comment by nielsfaber** [comment]
It doesn't look pretty for me either, if I make my chrome browser window really small.
I will check it out, hopefully I can make it "adjust to fit" as it should do.

**Comment by adrienvsj** [comment]
Hello @nielsfaber 

I have the same problem with my Xiaomi Mi 10T pro.
