### ISSUE TITLE
enabling or disabling a notification or action creates response error 500

### ISSUE THREAD

**Issue by muddro1** [nielsfaber/alarmo#233]
### Checklist
- [ X] I checked for similar existing issues (both open and closed) before posting.
- [ X] I am running the latest version.

### Expected behavior
To enable or disable notifcation or action

### Actual behavior
Received error 500 on disabling and enabling

### Steps to Reproduce
Enable or disable notification or acrion

**Comment by nielsfaber** [comment]
I'm seeing the same, I will pick this up.

**Comment by nielsfaber** [comment]
This is fixed by https://github.com/nielsfaber/alarmo/commit/4d74a1d3f5dae2e736f8682b7eaec283edccd705
Will be included in the next update.
