### ISSUE TITLE
Feature Request: Clear Alarm instead of Disarm

### ISSUE THREAD

**Issue by muddro1** [nielsfaber/alarmo#234]
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
currently it seems you can only disarm an alarm that goes off. Would be nice to clear the alarm, but leave the alarm on, instead of disarming and rearming.

### Additional info
[some example of how the new functionality should look like]

**Comment by nielsfaber** [comment]
missing
> [some example of how the new functionality should look like]

HA does not have support for "clear alarm", so it would be an Alarmo-special.
I could add it to the actionable notifications, and to the alarmo-card.
What do you have in mind?

**Comment by muddro1** [comment]
Well basically when an alarm goes off, the button in the panel allows you to disarm it. I would love for there to be a second button on the panel that just says clear the alarm. I guess you could manually set it to turn off any alarms that had already been triggered, but the alarm status would stay armed. An integration into the notifications would be ideal as well with similar functionality.
