### ISSUE TITLE
Feature Request: notification actions

### ISSUE THREAD

**Issue by muddro1** [nielsfaber/alarmo#235]
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
Although can partially be done in yaml, adding in interactive notifcation with an ability to disarm or clear a trigger. I was able to easily get the button in, but unsure of what value would need to be returned in order to disarm.

### Additional info
[some example of how the new functionality should look like]

**Comment by muddro1** [comment]
Just realized you had some notifications already programmed in. Think it would be great to have a disarm action as well so can disarm without having to open HA.

**Comment by nielsfaber** [comment]
This is already in place.
In the same way as described in the [documentation](https://github.com/nielsfaber/alarmo#actionable-notifications), you can assign action `ALARMO_DISARM`  to add a button to a notification for disarming.
