### ISSUE TITLE
Notification TTS script not working in ver 1.6.1

### ISSUE THREAD

**Issue by cokeman0** [nielsfaber/alarmo#236]
### Checklist
- [X ] I checked for similar existing issues (both open and closed) before posting.
- [ X] I am running the latest version.

### Expected behavior
That my TTS script will work (it did before upgrading to 1.6

### Actual behavior
Displays an error:
![image](https://user-images.githubusercontent.com/6389802/121921152-06739480-cd39-11eb-9935-e277be4d22a0.png)
Also tried without the '' in "service: script.sonos_say", same issue

**Comment by nielsfaber** [comment]
Should be fixed by https://github.com/nielsfaber/alarmo/commit/c707c687d4f5913ff341a11f5b7e02ada09c406b
