### ISSUE TITLE
Smoke detector arming the alarm

### ISSUE THREAD

**Issue by lasse9000** [nielsfaber/alarmo#237]
![Screenshot_20210614_222846_io homeassistant companion android](https://user-images.githubusercontent.com/37941684/121955491-53b72c80-cd60-11eb-9bb5-c5677d883f26.jpg)

### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version.

### Expected behavior
[What you expected to happen]
Then the smoke detector og any other always on sensor is triggered and the alarm is disarmed. The alarm should still be disarmed. 
### Actual behavior
[What actually happened]
Today I cooked a meal and a little smoke hit the detector and it went of as I should, but the sirene didn't start, so something is wrong there. But 10 minutes later then I walked around the house the alarm triggered, and the sirene starts (so it works) without anybody has armed it. So it must have got armed then the smoke dector went of. 

### Steps to Reproduce
[Explain how to see the behaviour]
Set the alarm in "disarmed mode" and trigger an environmental sensor and the alarm get "trigged" but action(Triggered) does not run but the alarm enters "armed mode".

Hope it makes sens.

**Comment by cokeman0** [comment]
https://github.com/nielsfaber/alarmo/issues/224

Here you find the issue with not triggering the siren

**Comment by nielsfaber** [comment]
I cannot reproduce.
For me the alarm goes to "triggered" state as it should.

**Comment by lasse9000** [comment]
> I cannot reproduce.
> For me the alarm goes to "triggered" state as it should.
> 
> Also your screenshot doesn't show the system is armed (this would be state "armed away" or similar).
> 
> Only thing I see weird is the transition to "pending", I wouldn't expect that.

That's what I mean. The first triggered 3:35:00 is the smoke detector trigger the alarm. The pending is then i enter the hall with a motion detector. Some how the alarm got armed in between. No idea how and it not in the log.
