### ISSUE TITLE
Logging needs enhancement :-)

### ISSUE THREAD

**Issue by fribse** [nielsfaber/alarmo#239]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Proposal
It would be very nice if the info loglevel included WHO armed / disarmed the alarm.
Having finally the ability to have multiple codes (the BIG selling point of Alarmo) makes it possible to identify the user that affected the alarm easily.
Having it shown in the logfile would make this even better.

### Additional info
I've made a 'logbook' card for Alarmo, and it shows events for the device perfectly, but it only shows that it was activated (and in what mode) and deactivated.

THANKYOU for working with Thanksmister on the alarmpanel integration, it works VERY VERY WELL!

**Comment by nielsfaber** [comment]
I agree that logging can be improved.
I will see what I can do regarding this.

**Comment by fribse** [comment]
Looking forward to news on this :-)

**Comment by nielsfaber** [comment]
In v1.7.0 I made some changes in the logging, including mentioning of the user whose code was entered for arming/disarming.
Most useful logs are visible by enabling INFO log level.
This can be set in configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: info
```
Hope this helps you.

**Comment by fribse** [comment]
Thanks, I'll test it out!

**Comment by fribse** [comment]
Hi @nielsfaber 
I finally remembered to do some proper testing, it looks great. Only issue I found was that if it fails to arm (due to a mandatory sensor being open) it will just say it's disconnected, not that somebody tried to arm it :-)
