### ISSUE TITLE
[feature request] trigger time (and siren duration) less that a minute

### ISSUE THREAD

**Issue by Extreme79** [nielsfaber/alarmo#24]
Hi.
As subject says, could be useful to let the user to choose a siren duration under the minute.
I use an interior siren and a 1min duration is too much (imagine during the night a false alarm that turn on the siren for a minute..) :D
The best this could be a base value available as entity that define the siren duration, so we can change the duration with an automation (armed night set duration to 15s or less, armed away to a minute).

**Comment by nielsfaber** [comment]
You mean the trigger duration?
Usually the siren is on while the alarm is triggered.
You can already set it to 15 seconds.
There is a secret option that if you click on the label next to the slider, it changes from minutes to seconds.

If you want this trigger duration to be configurable per-mode, I can add something for that.

**Comment by Extreme79** [comment]
yes sorry, I mean trigger duration :)
Title edited.

**Comment by nielsfaber** [comment]
So something like this would help you?
![image](https://user-images.githubusercontent.com/16861605/99940692-fda37d00-2d6c-11eb-911b-30b4b8fdaca4.png)

Then just click on the minutes as i said, and it changes to seconds.

Do you need anything additional?

**Comment by Extreme79** [comment]
This appear ok to me. 
Probably for a common user a min/max choose by a radio option could be better/mor intuitive, but strictly for me it's ok the click too.

Additional:
I think about my old system. there was an option to use the siren as a sound notification (500ms single activation on arm, 500ms double activation on disarm). I never used that because I always used automation with my own logic to notify arm/disarm (to avoid unwanted sound at certain times), but probably could be useful for some users. Take this as a suggestion with low priority, absolutely not "mandatory"

**Comment by nielsfaber** [comment]
I'm closing this issue assuming your original question is answered, and I need to clean up the list a bit..
As for sound notifications, I am considering to expand the Actions editor with the option to add secondary/closing action, which will be on leaving a state or after time delay.
My recommendation (for now) would be to create a  HA script/automation which executes a sequence:
1. Turn on siren
2. Wait x time
3. Turn off siren

You can choose to trigger this sequence on changes of the alarmo entity, or set up an action in Alarmo that executes this script.
