### ISSUE TITLE
No input field for Message in Notification (v1.6.2)

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/alarmo#240]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version. (v1.6.2)

### Expected behavior
Possibility to enter Message text during creating/changing Notification.

### Actual behavior
No input field for Message in Notification.

![image](https://user-images.githubusercontent.com/15225823/122910111-8499f180-d35e-11eb-8f06-9756c85b405a.png)

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by nielsfaber** [comment]
This seems to be related to HA caching and lazy-loading.
It might be resolved by refreshing the page, or going into another page in HA (which has a text field).
