### ISSUE TITLE
Physical panel arm and then disarm immediately the alarm

### ISSUE THREAD

**Issue by bubez81** [nielsfaber/alarmo#242]
a strange thing happens to me, I have configured alarmo to work with a classic system with push-button panel and also managed by a konnected pro card via mqtt. I can launch armed and disarmed but if I try to use the physical keypad it activates and immediately deactivates the alarm

With mqtt I have only a topic that tell me if the alarm is armed or not armed (ON OFf)
And a topic to send the command (ON OFf)

![image](https://user-images.githubusercontent.com/19486458/123507241-aa7a0b80-d668-11eb-9869-000dc058df22.png)

![image](https://user-images.githubusercontent.com/19486458/123507246-b36add00-d668-11eb-9709-dcafbe34c361.png)

**Comment by nielsfaber** [comment]
I'm missing some info to be able to help you.
Maybe try `mosquitto_sub -t konnected_officio/# -v` or some other MQTT inspector to see what's going on.

**Comment by bubez81** [comment]
Ok I'll try! can I ask for security which is the listening topic for the status and which one to launch the commands? it is not very clear to me

**Comment by nielsfaber** [comment]
Status topic = state (output from Alarmo)
Command topic = listening topic

**Comment by bubez81** [comment]
nothing happens in mqtt because the keypad does not communicate via mqtt but directly with the alarm. It is as if homeassistant sees the alarm disarmed and forces the disarm mode without letting the alarm switch itself ON

**Comment by nielsfaber** [comment]
I'm not sure how to help you, I don't really understand the issue.
Maybe you could make some screenshot or video to show what's going wrong?
