### ISSUE TITLE
Typo in Supported Commands Wiki

### ISSUE THREAD

**Issue by EdwardSoaresJr** [nielsfaber/alarmo#243]
On this page https://github.com/nielsfaber/alarmo there is a typo in the supported command to ARM_HOME. It is listed as ARMED_HOME which is incorrect.

![Screen Shot 2021-06-28 at 1 17 19 AM](https://user-images.githubusercontent.com/10336569/123596168-08b10680-d7af-11eb-9235-a1f68d0fa970.png)

**Comment by nielsfaber** [comment]
Well spotted sir!
I just fixed it.

Note that you are invited to make improvements to the documentation where you see them.
I'm rather busy with maintaining the code, so the documentation doesn't quite get the attention it needs.
