### ISSUE TITLE
Bypassed sensor desabeling

### ISSUE THREAD

**Issue by Mib68** [nielsfaber/alarmo#244]
Hi,

Can I suggest to change the use of bypassed sensors, when we activated alarm with an open windows (for exemple) this windows sensor it's in bypassed sensor, but when we closed this windows, the windows sensor didn't go out of bypassed sensor.

It is possible to allow this fonctionnality to go out of bypassed sensor when for this exemple the windows was closed. (useful in this season while I have à lot of windows open at night, but if my children closed the windows the sensor not trigger the alarm)

Thanks a lot (I'm sorry for my bad english, this isn't my mother language)

**Comment by nielsfaber** [comment]
> Can I suggest to change the use of bypassed sensors, when we activated alarm with an open windows (for exemple) this windows sensor it's in bypassed sensor, but when we closed this windows, the windows sensor didn't go out of bypassed sensor.

This setting should give you exactly that effect:

![image](https://user-images.githubusercontent.com/16861605/124170606-ee757200-daa7-11eb-89c5-abeb84effac7.png)

> It is possible to allow this fonctionnality to go out of bypassed sensor when for this exemple the windows was closed. (useful in this season while I have à lot of windows open at night, but if my children closed the windows the sensor not trigger the alarm)

I don't understand this.
If the sensor is bypassed (using the setting above) you can open+close the window, it will not trigger the alarm.
If you want to be able to open the window without being bypassed, you need to remove it from the alarm.

**Comment by Mib68** [comment]
@nielsfaber I'd like to have the possibility to activate the alarm with a window open but if the windows closed and open back it's trigger the alarm.
In france we have windows tilt and turn then in summer we will stay wndows open during the night to cold the house.
But if a burglar would come in home he closed the window an open it again to come in. (but with the option Bypass automatically the alarm wouldn't trigger.

**Comment by nielsfaber** [comment]
If you really want this, you should clear the type of the sensor empty and select the ‘allow open’ setting.
This is intended for motion sensors but has the effect that the initial state is ignored.

**Comment by Mib68** [comment]
Yes thats work great thanks
