### ISSUE TITLE
Auto-rearm/clear option

### ISSUE THREAD

**Issue by brgerig** [nielsfaber/alarmo#247]
In some cases, it would be great to have the ability for the alarm system to go back from triggered to armed after a sensor has cleared. This would be particularly useful for environmental sensors like water or smoke. After the condition clears, the triggered state is generally irrelevant. As far as I can tell, the only way to reset the system is to disarm and rearm it.

### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
A couple of proposals:

One useful option could be to have a setting for an entire arm mode where the armed state is reset/trigger is cleared when the open sensor closes. I like to have a vacation mode where I can have someone check on my house but not have to worry about disarming things. I like getting the notifications about the doors opening and closing, but it would be great to have that reset back to its arm state when the doors close.

Another useful option would be to have a setting on specific sensors or classes of sensor to reset the state. Particularly useful for environmental sensors.

Final useful option could be an actionable notification to reset the state of the alarm. I believe I saw this in another feature request.

### Additional info
I think that about covers my thoughts on it. I've just started using Alarmo, so I very well could be missing something. Thanks for such great work!

**Comment by nielsfaber** [comment]
I think this would compromise the security of the alarm.
I will not add such function.

Better to give people who may enter your house a means to disarm and arm the alarm.
