### ISSUE TITLE
MQTT Error - missing parameter

### ISSUE THREAD

**Issue by sparkydave1981** [nielsfaber/alarmo#249]
### Checklist
- [ ] I checked for similar existing issues (both open and closed) before posting.
- [ ] I am running the latest version.

### Expected behavior
No errors

### Actual behavior
Error as per below:

```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 9:36:50 AM (1 occurrences)
Last logged: 9:36:50 AM

Exception in async_message_received when handling msg on 'paradoxdCTL/hassio/Arm': 'disarmed' Traceback (most recent call last): File "/config/custom_components/alarmo/mqtt.py", line 251, in async_message_received await entity.async_alarm_disarm(code, skip_code) File "/config/custom_components/alarmo/alarm_control_panel.py", line 322, in async_alarm_disarm (res, info) = self._validate_code(code, STATE_ALARM_DISARMED) File "/config/custom_components/alarmo/alarm_control_panel.py", line 283, in _validate_code if state == STATE_ALARM_DISARMED and not self._config[const.ATTR_CODE_DISARM_REQUIRED]: KeyError: 'code_disarm_required'
```

### Steps to Reproduce
Using Alarmo with MQTT.

Partial contents of alarmo.storage file:

```
{
    "version": 3,
    "key": "alarmo.storage",
    "data": {
        "config": {
            "code_arm_required": false,
            "code_disarm_required": false,
            "code_format": "number",
            "disarm_after_trigger": false,
            "master": {
                "enabled": true,
                "name": "master"
            },
            "mqtt": {
                "enabled": true,
                "state_topic": "paradoxdCTL/in",
                "state_payload": {
                    "disarmed": "{\"password\":\"REDACTED\",\"Command\":\"disarm\",\"Subcommand\":\"0\"}",
                    "armed_away": "{\"password\":\"REDACTED\",\"Command\":\"arm\",\"Subcommand\":\"0\"}",
                    "armed_home": "{\"password\":\"REDACTED\",\"Command\":\"sleep\",\"Subcommand\":\"0\"}"
                },
                "command_topic": "paradoxdCTL/hassio/Arm",
                "command_payload": {
                    "disarm": "disarmed",
                    "arm_home": "armed_home",
                    "arm_away": "armed_away"
                },
                "require_code": true,
                "event_topic": ""
            }
```

**Comment by nielsfaber** [comment]
Sorry for the delay. Please give me a week or two to look at this.

**Comment by nielsfaber** [comment]
I'm having trouble to reproduce the issue.
For me the problem does not occur when arming/disarming through MQTT.
I changed my config to match yours exactly.
Could you provide more info for reproducing this?

**Comment by sparkydave1981** [comment]
Probably not related but upon restarting HA I get this in the log:
Logger: custom_components.alarmo.alarm_control_panel
Source: custom_components/alarmo/alarm_control_panel.py:361
Integration: Alarmo (documentation, issues)
First occurred: 4:14:28 PM (1 occurrences)
Last logged: 4:14:28 PM

Cannot go to state armed_away from state None.

The error this Git issue relates to seems to come up when disarming the system so I'm check back with more log data soon now that i have debug enabled

**Comment by nielsfaber** [comment]
> Cannot go to state armed_away from state None.

This error occurs if you try to arm the alarm while it is being initialized.
Probably due to your MQTT command topic being retained (which is a very bad idea)?

**Comment by sparkydave1981** [comment]
I don't have any settings for MQTT retain that I can see.

So far haven't seen the original error again

**Comment by nielsfaber** [comment]
The retain setting would be at the sending side, so in your case the Paradox system.
It is quite easy to test actually.
If you subscribe with a MQTT client to the command topic and you see a message directly (instead of after arming through Paradox), it retains its data.
Could be done using `mosquitto_sub -t 'paradoxdCTL/hassio/Arm' `.
On debian/ubuntu you can install this command via `sudo apt-get install mosquitto-clients`.

Having the command topic retained is a very bad idea, because it could cause the system to be armed/disarmed when you don't desire this (example by restarting HA).
It is also written in the [documentation](https://github.com/nielsfaber/alarmo#command-topic).
Alarmo will already make sure that the system keeps its previous state after restarting HA, so retained command data is not needed.

**Comment by sparkydave1981** [comment]
I tried looking for the MQTT retain setting for my Paradox alarm interface but didn't see where to disable it.

Meanwhile I just updated HA from 2021.8.8 to 2021.9.0 and upon restart noticed the previous error once again.  I'm starting to think it only shows up on restart.

```
2021-09-02 07:43:03 ERROR (MainThread) [homeassistant.util.logging] Exception in async_message_received when handling msg on 'paradoxdCTL/hassio/Arm': 'disarmed'
Traceback (most recent call last):
File "/config/custom_components/alarmo/mqtt.py", line 259, in async_message_received
await entity.async_alarm_disarm(code, skip_code)
File "/config/custom_components/alarmo/alarm_control_panel.py", line 322, in async_alarm_disarm
(res, info) = self._validate_code(code, STATE_ALARM_DISARMED)
File "/config/custom_components/alarmo/alarm_control_panel.py", line 283, in _validate_code
if state == STATE_ALARM_DISARMED and not self._config[const.ATTR_CODE_DISARM_REQUIRED]:
KeyError: 'code_disarm_required'
```

**Comment by sparkydave1981** [comment]
An update on this one, but unfortunately not any help...

I recently disabled MQTT in Alarmo and instead created a few normal HA automations to send the required MQTT messages upon triggers from either the Paradox alarm changing states or Alarmo changing states.  Using this method I've had no problems at all with the two systems staying in sync. ie: if I arm/disarm the Paradox system, HA see's the state change via MQTT and triggers Alarmo to change respectively, and vice versa with Alarmo changing the Paradox system.  

So I don't know why Alarmo was having issues doing this with it's inbuilt MQTT functionality but this test basically tells me the issue isn't due to the MQTT messages with the Paradox system.  At this point I don't mind having the synchronisation automations in native HA but it doesn't help find the bug.

Any ideas what to try to test Alarmo?

**Comment by nielsfaber** [comment]
If I remember correctly, you are using [this project ](https://github.com/maragelis/ParadoxMqtt32)to integrate Paradox with mqtt.
From the code ([link](https://github.com/maragelis/ParadoxMqtt32/blob/master/src/main.cpp#L334), [link)](https://github.com/maragelis/ParadoxMqtt32/blob/master/src/main.cpp#L382) I see that indeed retained messages are used. for the armed/disarmed status.

This means that as soon as you restart HA, Alarmo is requested to arm (or disarm) immediately, while Alarmo is built to recover its state prior to the rebooting, but also needs to wait for all sensor states to be known before it can do so.

I see 2 options here:

1. Reprogramming your ESP on Paradox side for removing the retained flag on output messages.
2. Changing Alarmo to ignore incoming MQTT messages during initialization.

**Comment by nielsfaber** [comment]
I made some changes to handle this problem (https://github.com/nielsfaber/alarmo/commit/943c14988fe967ebf3e4b0817c5d681f28583510).
Since I haven't been able to reproduce the problem myself (even with retained command topic), I will update you when the changes are released, hope you can test it and confirm it solves the problem.

**Comment by nielsfaber** [comment]
v1.7.3 is now released which contains the changes.
Please test it and see if it resolves the problems.
