### ISSUE TITLE
[feature request] multi-partition

### ISSUE THREAD

**Issue by Extreme79** [nielsfaber/alarmo#25]
Hi.
I my previous domotic system I was able to define multiple alarm partitions, individually configurable and usable: I was able to define wharehouse / house1 / house2 partitions, each with its sensors/users/settings.

This feature could be so useful in a large installation.

**Comment by nielsfaber** [comment]
Unfortunately I don't have the luxury of living in a palace.
It's hard to imagine how such a system would work and be practical.
Would you need multiple `alarm_control_panel` entities?
Or when arming, choose which 'zones' you want to arm?
Could you share an example?

**Comment by Extreme79** [comment]
Yes, different alarm control panel entities, I suppose. I've a developer skill (little bit rusted unfortunately) in my background, but a newbie of home assistant so I still have to fully enter in the hass logics/elements :)
I apply this to my case, because I own an house with two flats (mine and parents), with a laboratory and I'm transferring all the domotic logics to Home Assistant.
So my parents need to have an alarm control panel, same for me, same for ther other building.
But this is valid also for a large flat, where a specific zone need to be armed h24 for fire or water leaks (defining a partition with specific sensors and specific siren, as example).
I think you can see this as multiple instances of Alarmo, probably (or better, a single instance of Alarmo with multiple alarm_control_panel capabilities)
Be free to ask me more if you need to better understand.. my english could be better :)

**Comment by nielsfaber** [comment]
I need to ask for some patience from your side.
As you can imagine, this change has quite an impact.
I prefer to improve the basics of Alarmo first, create a stable baseline.
I also would like to know if multiple users are looking for this functionality, before starting to make effort on it.
Hope you can understand this.

**Comment by Extreme79** [comment]
Hi!
Sorry for my late reply, busy days.
I understand, that surely take alot of effort. What I can suggest is to take in mind this type of upgrade when you will develope the base Alarmo, to avoid implementations that can potentially block the development of the multi-partition feature.
Probably the multi-partition (to be seen like more physical alarm central units) is not an essential requirement for most people, but only for those that have a large/multiple building; anyway this can be useful also for a most common case, as example home+garage where you can define an alarm partition for home and another one for garage, with different arming time and users. I remember that this feature was requested during the time (also by me :) ) in the bwalarm thread where I finally met alarmo :) .

I want to suggest you a feature-in-feature: with multiple partition you could define different partitions types working ad the same time, like "h24 silent armed partition" or an "health care partition" (that works in inverse way, that trip when no motion/opening were detected in a certain time, useful to monitor old people).. and similars

**Comment by c0m3r** [comment]
I would support this feature as well. Currently I have set up two manual alarms, one for the main house and one for a garden house/bar we have. I wouldn't need different users or passcodes etc. Personally I think being able to setup multiple instances of alarmo would be the simplest solution rather than trying to factor in multiple requirements.

**Comment by i-o-m-a** [comment]
> I need to ask for some patience from your side.
> As you can imagine, this change has quite an impact.
> I prefer to improve the basics of Alarmo first, create a stable baseline.
> I also would like to know if multiple users are looking for this functionality, before starting to make effort on it.
> Hope you can understand this.

Yes, me too looking for such functionality

**Comment by i-o-m-a** [comment]
When You plan to implement it?

**Comment by nielsfaber** [comment]
@i-o-m-a I’m not a company or professional so I don’t want to commit to plannings.
In the coming 2 weeks I have some free time so I might start with this.

The plan is to add the ability to Alarmo to define areas, each with their own timings.
Alarmo will create multiple alarm_control_panel entities, one for each area.
Sensors (and automations) can be assigned to an area.

There will always be a ‘master’ alarm_control_panel which can be used to arm all zones (and it will sync its state based on the areas).
Assigning areas will be optional, so it remains possible to assign all sensors under the master entity.

Right now I don’t see a need for having dedicated pincodes and such per area.
I would like to keep some things centralized.

Feedback on this is very welcome!

**Comment by i-o-m-a** [comment]
Thank You! Look like the plan is the same as i tried to configure in HA using alarm_control_panel(s) :)
Yes, i think that dedicated pincodes per area not needed.
Actually the missing part of alarm_control_panel with multiple alarm_control_panel(s) is ability to select zone while arming or disarming.

**Comment by luckypants123** [comment]
I would love this. I currently have 2 panels - one for the home, and one for the detached garage. I’d love the opportunity to switch that over to this component if you find time to make it work!

**Comment by nielsfaber** [comment]
I just released v1.5.0 which should provide this functionality.
Please check out my [announcement](https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/264?u=neliss) in the HA forums about this as well.
Let me know if something is missing or unclear.

**Comment by mariomazon** [comment]
With a single zone operation (or even with multipple zones/areas), is there any way to select differente groups of sensors to act when armed_home and differente ones to act when armed_away, for example ? With basic alarm, we can achieve this with something like:

condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away

Think about armed-home when we are home and want only the first floor to trigger, and when armed-away, we want both first-floor and second-floor windows, for example.

Is there any way to achieve this ? I don't think differente zones/areas are the same thing. Thank you

**Comment by mariomazon** [comment]
Sorry, I've missed the buttons to select away X home in each sensor configuration ! As a sugestion, it may be possible to make advanced settins of each sensor based on the away / home selection ? For example, I can set an sensor that will be "immediate" when armed_home, but not when armed_away.

 Thank you !

**Comment by nielsfaber** [comment]
@mariomazon 
> As a sugestion, it may be possible to make advanced settins of each sensor based on the away / home selection ? For example, I can set an sensor that will be "immediate" when armed_home, but not when armed_away.

Alarmo uses a slightly different approach.
The delay settings are defined per arm mode.
The sensor [type](https://github.com/nielsfaber/alarmo#sensor-types) defines whether it has a delayed or immediate trigger response.
For larger alarm systems it becomes messy if each sensor has its own timings..

**Comment by nielsfaber** [comment]
Closing due to lack of response.
