### ISSUE TITLE
Disarm with NFC or Biometric

### ISSUE THREAD

**Issue by mani94321** [nielsfaber/alarmo#250]
is there any way to disarm with NFC tag in addition to password option. Means system should require code to disarm but if some specific NFC tag is scanned, it disarms the system without entering the code

**Comment by nielsfaber** [comment]
> is there any way to disarm with NFC tag in addition to password option. 

No this is not supported.
I think each tag reader in HA has different behaviour so it will be hard to implement it in a generic way.
I don't have such reader so I am not able to test this myself.

You may be able to create an automation to disarm alarmo based on trigger from the NFC reader, but the code needs to be provided for the service call.

**Comment by a8ree** [comment]
I've done this previously with the standard HA alarm. I will update when I've migrated this across. It shouldn't be very difficult - just not had time to do it yet

**Comment by a8ree** [comment]
Here is a copy of my node red flow

[{"id":"b79ee612.ad5248","type":"server-events","z":"f53a69ee.af0328","name":"Tag Scanned","server":"789409ed.7ceb48","version":1,"event_type":"tag_scanned","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"},{"property":"event_type","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"}],"x":90,"y":140,"wires":[["a71297af.296fe8","e1168bb7.e9a908"]]},{"id":"b1e5eb2f.1b4ff8","type":"api-current-state","z":"f53a69ee.af0328","name":"Is Disarmed?","server":"8ca832e4.1e6b4","version":2,"outputs":2,"halt_if":"disarmed","halt_if_type":"str","halt_if_compare":"is","entity_id":"alarm_control_panel.master","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"x":550,"y":120,"wires":[["9a300ca9.94c8b"],["b356c73f.b72598"]]},{"id":"9a300ca9.94c8b","type":"api-call-service","z":"f53a69ee.af0328","name":"Arm alarm","server":"8ca832e4.1e6b4","version":3,"debugenabled":true,"service_domain":"alarmo","service":"arm","entityId":"alarm_control_panel.master","data":"{\"code\":12271}","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":770,"y":80,"wires":[[]]},{"id":"b356c73f.b72598","type":"api-call-service","z":"f53a69ee.af0328","name":"Disarm Alarm","server":"8ca832e4.1e6b4","version":3,"debugenabled":false,"service_domain":"alarmo","service":"disarm","entityId":"alarm_control_panel.master","data":"{\"code\":12271}","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":780,"y":160,"wires":[[]]},{"id":"a71297af.296fe8","type":"debug","z":"f53a69ee.af0328","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":300,"y":220,"wires":[]},{"id":"e1168bb7.e9a908","type":"switch","z":"f53a69ee.af0328","name":"Tag ID","property":"payload.event.tag_id","propertyType":"msg","rules":[{"t":"eq","v":"4A-E8-26-03","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":280,"y":140,"wires":[["b1e5eb2f.1b4ff8"]]},{"id":"2e2ec9a2.a12f16","type":"comment","z":"f53a69ee.af0328","name":"NFC Alarm","info":"","x":110,"y":80,"wires":[]},{"id":"6361daa2.40ed74","type":"inject","z":"f53a69ee.af0328","name":"Test Arm","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":570,"y":60,"wires":[["9a300ca9.94c8b"]]},{"id":"a25ab4ef.149c68","type":"inject","z":"f53a69ee.af0328","name":"Test Disarm","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":570,"y":200,"wires":[["b356c73f.b72598"]]},{"id":"789409ed.7ceb48","type":"server","name":"Home Assistant","version":1,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true},{"id":"8ca832e4.1e6b4","type":"server","name":"Home Assistant","version":1,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]

It waits for the NFC to be scanned then checks the current alarm state before choosing to arm / disarm. I've left some inject nodes in to assist with testing.

Hope this helps

**Comment by nielsfaber** [comment]
Closing due to lack of response.
Assuming OP found another way to do this.
