### ISSUE TITLE
HomeKit integration

### ISSUE THREAD

**Issue by fvgarrel** [nielsfaber/alarmo#252]
Currently I cant activate the alarm via HomeKit. Is it possible to add something like the original Alarm Panel? https://www.home-assistant.io/integrations/homekit/

**Comment by nielsfaber** [comment]
You should be able to just add the `alarm_control_panel` entity to the HomeKit integration and it shows up for controlling.
If that doesn’t work, I wouldn’t know what is wrong on the side of Alarmo.
I don’t know what changes I can/should make for making it HomeKit-compatible.
I am not a HomeKit user myself, so I am unable to test it myself.

**Comment by nielsfaber** [comment]
@fvgarrel  Any updates on this?

**Comment by fvgarrel** [comment]
@nielsfaber Yes, it work like the original alarm. I configured HomeKit via UI and there is no possibility to configure the code. When I configure HomeKit via yaml it worked.
