### ISSUE TITLE
[Feature request] Require multiple sensors before triggering

### ISSUE THREAD

**Issue by RonniHolst** [nielsfaber/alarmo#253]
As topic says - Missing the option to force that multiple sensors needs to be trigged before the alarm goes on.

Example, 2 motion sensors needs to be trigged within 10 minuttes before the alarm goes on.

**Comment by nielsfaber** [comment]
I think this is too complicated and user-specific.
Also it seems unnecessary to me as long as the sensors work reliable.
I don't think such feature fits well with Alarmo.
If you really want such functionality, you will have to make it using template binary_sensors or similar.
This was once discussed in the HA forum thread for Alarmo.

**Comment by RonniHolst** [comment]
Okay - thanks

**Comment by nielsfaber** [comment]
Since multiple users seem to have interest in this feature, I will reconsider adding this in a future release.

Could you please let me know which level of flexibility is desired?
So far I am planning to allow the user to define a time window (eg 10 mins) during which 2 sensors need to be triggered.

I am doubting whether it is also needed to have users define which sensors are considered as a ‘group’ for which 2 consecutive are needed.
I think for environmental sensors (fire, water, …) this feature is not desired.
For all others maybe yes, or does it depends on door/motion/tamper sensor type?

**Comment by RonniHolst** [comment]
Well in my case it started with some of my motions sensors is to sensitive - with mean that they will trigger the alarm (evey if the motions sensors are away from the window and so on). 
Then I have a talk with my friend that have a "commercial" alarm system, and he just told me that multiple sensors needs to be triggede before the alarm will go on.

So if you can create 2 different groups of sensors (one for environmental sensors, and one for doors/motions/sound whatever) and make a time trigger combined with each group - it would be awesome!

Because if you are thief you would go to multiple rooms, and open at least a door within a small time frame. 
Maybe also a combo where one trigger is detecting, then it could example swittch on the light - wait for some minutes, and see if another sensor is opened - and then activate the alarm.

**Comment by josh-79** [comment]
I have the same problem with my motion sensors. It happens very rarely. But about once a year, a motion detector in our basement is falsely triggered (not a specific one). I have not yet been able to determine the exact reason. Maybe a spider crawls over the sensor or something similar happens.

Therefore, I would also find it very useful if at least 2 sensors must be triggered within x minutes. Other commercial smarthome providers have already integrated this option in their systems (for example Loxone).

**Comment by Joepie007v2** [comment]
Hi,
I am also interested in this feature. I know this from Zipato (z-wave controller). There you can choose a sensor and choose a group number.
I have 2 motion sensors in the hallway, but one of them was very sensitive for the robot vacuum or when we still had a 🐈. By both sensors I choose group 1 and 10 seconds. So both sensors must detect motion within 10 seconds to report motion. 
See attached picture, thought it was a nice feature.

![EA7702C9-18A6-4F8E-8465-1284A86169D9](https://user-images.githubusercontent.com/59317222/136658646-e2c55fbd-d48b-48d6-b947-ebabd06b044c.jpeg)
