### ISSUE TITLE
Change Localization

### ISSUE THREAD

**Issue by mattexpa** [nielsfaber/alarmo#255]
### Proposal
Change the german translation for the remove button on Lovelace Card to something more short to be responsive on mobile devices.

(Normally it resizes correctly but while using old safari on Ipad 3 for Wallpanel use it doesn't and just cuts off text)

### Additional info
Maybe add mdi:backspace or just change it to letter "C"

**Comment by nielsfaber** [comment]
There is no German translation for alarmo yet.
See https://github.com/nielsfaber/alarmo/tree/main/custom_components/alarmo/frontend/localize/languages

All texts are English except for some which are defined within HA.
Those cannot be changed on the side of alarmo.
Hence I dont know how to help you with your request.

Could you share a screenshot or something to illustratie the issue?

**Comment by mattexpa** [comment]
![16280025476388518099231600289787](https://user-images.githubusercontent.com/7073294/128037623-dac4deda-51fe-40f2-937b-53c47ce21590.jpg)

Ah I thought it was already translated because on frontend everything is displayed in German.
Sorry for the rookie approach of a Screenshot but ipad is in single app mode preventing Screenshots.
On the bottom right you can see it says lösche not very centered and in German the whole word is löschen - meaning delete. So not very pretty if you get what I mean.

**Comment by nielsfaber** [comment]
That screenshot is from [Alarm Panel Card](https://www.home-assistant.io/lovelace/alarm-panel/).
It is not designed by me, it is part of HA.

My work is the [Alarmo Card](https://github.com/nielsfaber/alarmo-card), which looks quite similar (I used Alarm Panel Card as starting point) but has some extra functions.
I could change things in Alarmo Card only, but you're not using it apparently.

**Comment by mattexpa** [comment]
Wow i'm sorry, didn't even knew you had your own card.
Giving it a try the next days.

Thanks a lot for helping me out, keep up the great work!
