### ISSUE TITLE
No integration entry after installation via HACS

### ISSUE THREAD

**Issue by Arcon389** [nielsfaber/alarmo#256]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
I installed alarmo with HACS and restarted Home Assistant. Next step: Add integration -> is not listed in "add integration".

### Actual behavior
The integration is not listed under configuration -> integrations -> add integration.
No errors in logs.

### Steps to Reproduce
As descripted under "Expected behavior".

Hassio Version: 2021.7.4
Alarmo Version: 1.6.2

**Comment by nielsfaber** [comment]
You probably need to clear your browser cache.
Its a known issue of the integrations page in HA, nothing I can do about it.

**Comment by Arcon389** [comment]
Thats solved it. Thank you very much!
