### ISSUE TITLE
Exception while trying to arm on version 1.2.0

### ISSUE THREAD

**Issue by tomer-w** [nielsfaber/alarmo#26]
Alarm get stuck in arming state. Investigating the log shows the following error:
2020-11-22 20:53:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/alarmo/alarm_control_panel.py", line 459, in async_initialization_timer_finished
await self.async_arm(self.arm_mode)
File "/config/custom_components/alarmo/alarm_control_panel.py", line 408, in async_arm
res = self.sensors.validate_event(event=EVENT_ARM, bypass_open_sensors=bypass_open_sensors)
File "/config/custom_components/alarmo/sensors.py", line 128, in validate_event
open_sensors[entity] = state.state
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by tomer-w** [comment]
seems to happen for sensor entity which was renamed by me earlier.

**Comment by nielsfaber** [comment]
Don’t rename sensor entities.
Alarmo depends on them.

**Comment by tomer-w** [comment]
I just think it should gracefully ignore them / log error and continue to operate while printing the name of the sensor it skips. There is no question I will need to fix it later. It will be hard for someone to investigate it without start changing the source code.

**Comment by nielsfaber** [comment]
> I just think it should gracefully ignore them / log error and continue to operate 

I don't agree on this.
If Alarmo cannot retrieve the state of one of your sensors, the arming will be blocked.
I do agree that the error should be fixed. 
I didn't test such scenario yet.

**Comment by tomer-w** [comment]
Currently it is stuck in arming state forever. I agree that valid solution would be to fail the arming with error (like when sensor is open) and get it back to pending state.

**Comment by nielsfaber** [comment]
I will try to reproduce this scenario and make a fix for it.

**Comment by nielsfaber** [comment]
I just released v1.3.0 which can handle sensor entities that are removed (or renamed) from HA.
As discussed, the failed sensor will still block the arming, i think it is more safe than just excluding the sensor.
Please try it out and if it works for you, close the issue.
