### ISSUE TITLE
Feature Request: Support vacation mode

### ISSUE THREAD

**Issue by ConsoleCriminal** [nielsfaber/alarmo#260]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Home Assistant by now allows away_vacation as an alarm mode. This is quite helpful to trigger additional automations when using it. Also, in alarmo, it allows to configure some things differently.

### Additional info
See https://github.com/home-assistant/architecture/discussions/500 for reasoning.

**Comment by nielsfaber** [comment]
I'm not really convinced that adding this is a useful addition that is worth the extra effort (I would have to change quite a lot of things to add support for this extra mode).

It seems to me that 'vacation' mode and 'away' mode are very closely related, at least when it comes to the sensor settings.

If we are only talking about triggering additional automations during vacation, I think there are better ways to do so (e.g. using flip switches to enable/disable additional actions).

In addition the user has the capability to use the 'custom' arm mode for vacation use-case. The alarmo-card will soon get the support to overwrite the name as displayed on the GUI to something more meaningful than 'custom bypass'.
