### ISSUE TITLE
August contact sensor doesn’t trigger

### ISSUE THREAD

**Issue by gmayfield09** [nielsfaber/alarmo#263]
I have aquara contact sensors that all work great with Alarmo. However, my August lock contact sensor won’t trigger the alarm. Any suggestions?

**Comment by nielsfaber** [comment]
I suppose it is registered as a binary_sensor in Home Assistant?
If so, do you see it switching from off to on when opening the contact?

**Comment by gmayfield09** [comment]
Yea it’s registered as a binary_sensor. Yes, it switches from closed to open when the contacts are opened.

**Comment by nielsfaber** [comment]
Ok, then it has probably something to do with the configuration.
Can you spot any differences between the configurations of the Aqara / august sensors?
If not, could you look in the `.storage` folder (inside the HA config folder) and check the `alarmo.storage` file and post the part involving the sensor?

**Comment by gmayfield09** [comment]
Couldn't find any differences between the aqara/august sensor config.
The August sensor is "front door open" the rest are the aqara sensors. 

"sensors": [
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_0f6e0007_on_off",
                "name": "Bathroom Window",
                "type": "window",
                "modes": [
                    "armed_away",
                    "armed_night"
                ],
                "immediate": true,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_0582f906_on_off",
                "name": "Dining Window",
                "type": "window",
                "modes": [
                    "armed_away",
                    "armed_night"
                ],
                "immediate": true,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_9783f906_on_off",
                "name": "Family Room Side Window",
                "type": "window",
                "modes": [
                    "armed_away",
                    "armed_night"
                ],
                "immediate": true,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_027ef906_on_off",
                "name": "Family Window Left",
                "type": "window",
                "modes": [
                    "armed_away",
                    "armed_night"
                ],
                "immediate": true,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_cf6c0007_on_off",
                "name": "Family Window Right",
                "type": "window",
                "modes": [
                    "armed_away",
                    "armed_night"
                ],
                "immediate": true,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.front_door_open",
                "name": "Front Door Open",
                "type": "door",
                "modes": [
                    "armed_away",
                    "armed_home",
                    "armed_night"
                ],
                "immediate": false,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_e01f7906_on_off",
                "name": "Living Window",
                "type": "window",
                "modes": [
                    "armed_away",
                    "armed_night"
                ],
                "immediate": true,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_3b82f906_on_off",
                "name": "Sliding Door",
                "type": "door",
                "modes": [
                    "armed_away",
                    "armed_home",
                    "armed_night"
                ],
                "immediate": false,
                "always_on": false,
                "arm_on_close": true,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_e021fe06_on_off",
                "name": "Hallway Door",
                "type": "door",
                "modes": [
                    "armed_away",
                    "armed_home",
                    "armed_night"
                ],
                "immediate": false,
                "always_on": false,
                "arm_on_close": true,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            },
            {
                "entity_id": "binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off",
                "name": "Kitchen Window",
                "type": "window",
                "modes": [
                    "armed_away",
                    "armed_night"
                ],
                "immediate": true,
                "always_on": false,
                "arm_on_close": false,
                "allow_open": false,
                "trigger_unavailable": false,
                "auto_bypass": false,
                "area": "1626720844",
                "enabled": true
            }
        ],

**Comment by nielsfaber** [comment]
Configuration looks pretty normal indeed.
So if i understand correctly, you can arm the alarm with binary_sensor.front_door_open being ‘on’, while if any other sensor is ‘on’ this would cause the arming to fail?

Im a bit in the dark here because the code should just process each sensor in the same way, especially if they are configured identically.

I suppose it has nothing to do with the actual brand of the sensor.
You could maybe swap 2 of the entity_ids in this storage file, restart HA, and see if the problem moves to the other entity.
I cannot predict if this will happen actually, just curious.

Anyway, maybe you found a bug here that may affect other users as well, would be great if you could help with getting to the bottom of this!

**Comment by gmayfield09** [comment]
I cannot arm the alarm with binary_sensor.front_door_open 'on' it causes the arming to fail. What's happening is when the system is armed, if the binary_sensor.front_door_open changes from 'off' to 'on' it doesn't actually trigger the alarm. It just stays armed. I tried swapping two entity ids, but for whatever reason after I saved and restarted HA the ids still stayed the same in lovelace.

**Comment by gmayfield09** [comment]
I just realized my mistake looking for a difference in lovelace after the id swap. I did the id swap, armed, then changed the state from 'off' to 'on'. The alarm did trigger on both entities. Switched the ids back and it went back to only triggering on the window and not the door. Also, this problem only arises when armed away. Everything triggers on armed night.

**Comment by nielsfaber** [comment]
> I cannot arm the alarm with binary_sensor.front_door_open 'on' it causes the arming to fail. What's happening is when the system is armed, if the binary_sensor.front_door_open changes from 'off' to 'on' it doesn't actually trigger the alarm. It just stays armed.

From this I understand that Alarmo does check the sensor before arming, but ignores it after arming?

> I did the id swap, armed, then changed the state from 'off' to 'on'. The alarm did trigger on both entities. Switched the ids back and it went back to only triggering on the window and not the door. 

And from this I understand that swapping 2 entities solves the problem?


You might want to enable debug logging for Alarmo.
You can do so by adding to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```
And restarting HA.

The logs should print a lot of extra info, including every time a sensor changes state.
Perhaps this provides more clues on where things are going wrong.

**Comment by gmayfield09** [comment]
Added the debug code- now everything works as it should. Took out the debug code and it continued to work as it should. Not sure what changed, but everything is good now!
