### ISSUE TITLE
failure to arm alarm 

### ISSUE THREAD

**Issue by rysm83** [nielsfaber/alarmo#264]
I was unable to see an open issues for what I am seeing.  
Current version of  Home Assistant 2021.7.4
When trying to arm the alarm in either mode (home or away) Alarmo should change to a failed state and have a message sent to a device with HA app installed that would give the message that the alarm has failed to arm due to (X) sensor open or on. 

 Actual behavior:
 Running the current version of Alamo 1.6.2.  I have all my sensors added into the alarms system for both home and away modes.  If either sensor is open the alarm continues to arm as if all doors and windows are closed.  I know that this did not happen in previous releases.  I also verified that I do have the automation setup with in the Alarmo app with in home assistant.  Tested and do get the sample notification when selecting "Try it" .

**Comment by nielsfaber** [comment]
If you try to arm Alarmo with an open door sensor, I would expect that at the end of the exit delay, the arming fails (goes back to disarmed) and you get this notification if you configured this.
You're saying that if you do this, the alarm can arm without problem?
Also closing + opening this door sensor after the alarm is armed, will not trigger the alarm?

Can you share your sensor configuration perhaps?
Is it the same for all sensors or just one?

**Comment by nielsfaber** [comment]
@rysm83 Could you please follow up on this issue? Otherwise I cannot help you and I will close this.
