### ISSUE TITLE
Support the siren entity which was added in 2021.8

### ISSUE THREAD

**Issue by bogdanr** [nielsfaber/alarmo#268]
I would like to trigger my Aeotec Z-Wave Siren which comes in HA as siren.siren, siren.siren_2, etc.
This option is not available in the entity list for actions. I only see switch and light entities.

**Comment by nielsfaber** [comment]
The siren integration did not exist in HA until a week ago.
It is not supported by Alarmo yet.

**Comment by nielsfaber** [comment]
Should be possible after updating to v1.7.0.
I don't have siren entities in HA so I am unable to test, could you please give feedback if all works OK?
