### ISSUE TITLE
Support the lock entity

### ISSUE THREAD

**Issue by bogdanr** [nielsfaber/alarmo#269]
It would be cool if it was possible to automatically lock the door when the alarm is armed. I think the most straightforward way to integrate this is to support the lock entity.

**Comment by nielsfaber** [comment]
You can do this by creating an action. 
After switching to YAML mode you can choose any entity + service.
E.g.:
```
- service: lock.lock
  entity_id: lock.my_lock
```
Should do the job.

The UI mode does not support selecting a lock, because it is not considered as a 'standard' task (most people won't use this).

**Comment by srodighiero** [comment]
I was not able to do it via YAML (gave me an error), but done it by creating a script that lock the lock, and than recall it inside Alarmo actions. Would be great to have the lock devices directly integrated

**Comment by nielsfaber** [comment]
With release v1.7.3. is now possible to make actions for lock entities without YAML.

**Comment by srodighiero** [comment]
> With release v1.7.3. is now possible to make actions for lock entities without YAML.

Currently, most of the times, is not working anymore, neither if I use the automation to lock the lock recalling a script, nor using directly the lock entity.

**Comment by nielsfaber** [comment]
@srodighiero Please open a new issue if you have problems setting up an action for locks.
Add some technical detail other than "its not working" if you're looking for some help.

I have set it up locally like this (similar job to lock when arming), it works perfectly:
![image](https://user-images.githubusercontent.com/16861605/135152510-b32fad01-b5ee-4da9-9a04-f9055f9e8afe.png)

**Comment by srodighiero** [comment]
> @srodighiero Please open a new issue if you have problems setting up an action for locks. Add some technical detail other than "its not working" if you're looking for some help.
> 
> I have set it up locally like this (similar job to lock when arming), it works perfectly: ![image](https://user-images.githubusercontent.com/16861605/135152510-b32fad01-b5ee-4da9-9a04-f9055f9e8afe.png)

You are absolutely right, I beg your pardon. I will open a new issue with logs and details
