### ISSUE TITLE
Allow different sensors to be used?

### ISSUE THREAD

**Issue by ShayaanF** [nielsfaber/alarmo#27]
I'm trying to add a motion sensor that is attached to a light switch (the Jasco Motion Sensor Switch) to use with my alarmo config... it doesn't show up as a sensor when configuring. Is this a bug or needs to be added as a feature?

**Comment by tteck** [comment]
Make sure the binary sensor has a correct device class

**Comment by nielsfaber** [comment]
As @tteck said, your binary_sensor needs to have a device_class from [this list](https://github.com/nielsfaber/alarmo/blob/main/custom_components/alarmo/frontend/src/data/sensors.ts#L14).
IMO the current list allows already all security-related sensors, but I also experienced that device_classes are not always set correctly by integrations.
I will probably introduce a field for selecting an entity that is not listed.

**Comment by nielsfaber** [comment]
I just released v1.3.0 which adds an option to show all `binary_sensors`.
Please close the issue if you're satisfied with this solution.
