### ISSUE TITLE
Translation to Portuguese Brazil

### ISSUE THREAD

**Issue by lucianoberger** [nielsfaber/alarmo#272]
Hi! I would like to translate it into my native language, PT-br.
How can I do this?

**Comment by nielsfaber** [comment]
Translations are always welcome!
You can do so by going to https://github.com/nielsfaber/alarmo/tree/main/custom_components/alarmo/frontend/localize/languages and taking the `en.json` as starting point and creating a `pt-br.json`.
This file needs then to be added here: https://github.com/nielsfaber/alarmo/blob/main/custom_components/alarmo/frontend/localize/localize.ts

To add it you have to open a pull request.
I think you are automatically directed through this by clicking here:
![image](https://user-images.githubusercontent.com/16861605/129480171-5eb96856-c2b3-4ec5-bdc9-f0fbf3d9454a.png)

If you want to test the translation yourself, its a bit more work.
You would have to make a local copy of the repository and install the dependencies using `npm i`.
Then with `npm start` you can re-compile the code with changes you're making.
