### ISSUE TITLE
Impossible to enable o disable alarm on homekit

### ISSUE THREAD

**Issue by radeon79** [nielsfaber/alarmo#278]
Is impossible to enable or disable alarm on homekit, the card is present on muy iphone but not appear the keypad for a correct operation.
Is possible to add this feature?

**Comment by nielsfaber** [comment]
Please read the docs on how to set up homekit in homeassistant:
https://www.home-assistant.io/integrations/homekit/#code

> code string (optional)
Code to arm / disarm an alarm or lock / unlock a lock. Only applicable for alarm_control_panel or lock entities.
Default: (No code)

Your issue has nothing to do with Alarmo.
