### ISSUE TITLE
Sensor "Allow open" option should not be disabled when "Immediate" option is on

### ISSUE THREAD

**Issue by tomer-w** [nielsfaber/alarmo#28]
Today you can enable the "Allow open" sensor option only if you first disable the "Immediate" option. This should not be the case IMHO.
I have a corridor with motion sensor which is leading me to my entry area. If I walk out fast it could be that I will fail to arm the alarm as the sensor is still active. The way to allow me to ignore it is to set the "Allow open" option (which is I love) but then I have the side effect that I also need to mark it not immediate which is not accurate. I want the alarm to trigger immediately if someone get to the hallway without first disabling the alarm.
So, I think these 2 options should get separated and allow me to set "Allow open" to sensors even if I do want them to trigger the alert immediately if they turn on later.

**Comment by nielsfaber** [comment]
Lucky for you I have no intentions of being a dictator 🙂 
I just thought the combination would be contradictive, but I get your point.
Will revert it in a next release.

**Comment by tomer-w** [comment]
Lucky me :). Thanks. You are doing excellent work with this project. I wonder how you can get it to replace the really broken built in manual alarm.

**Comment by nielsfaber** [comment]
Glad you like it.

> I wonder how you can get it to replace the really broken built in manual alarm.

What do you mean with this?
You mean the BWalarm that’s broken?

**Comment by tomer-w** [comment]
BWalarm is somehow ok. Main problem with that that it forked too many times as the original maintainer left it.
But what I referred as really broken is: https://www.home-assistant.io/integrations/manual/

**Comment by nielsfaber** [comment]
I just released v1.3.0 which should remove this limitation.
