### ISSUE TITLE
Customize Modes

### ISSUE THREAD

**Issue by srodighiero** [nielsfaber/alarmo#281]
Would be great to have the possibility to edit behaviour/names of pre-existing modes, and at the same time maybe create custom ones

**Comment by srodighiero** [comment]
I have just seen now that in future it will be possible to edit names of existing ones

**Comment by elbel86** [comment]
I've been searching for a way to customize alarm modes and stumbled upon this feature request. I can't seem to find any way to rename modes, and think it would be a great feature.
