### ISSUE TITLE
Actionable Notifications not working

### ISSUE THREAD

**Issue by jerodjchastain** [nielsfaber/alarmo#284]

**Comment by nielsfaber** [comment]
@jerodjchastain why did you close this? 
The problem seemed quite serious (though I didnt have the time to look into it yet).

**Comment by jerodjchastain** [comment]
I was trying out Alarmo because I had some time over the long weekend. For now I am going to stick with my current alarm set up i have built. So I would not be able to help trouble shoot this problem and I did not want to waste your time...With my current alarm I have setup I progressive actions for the motions sensors. (meaning it has to see more than one motion sensor or a motion of more than 20 seconds to set the alarm off) which gives me 0 alarm false alarms, with other systems where it only takes one motion to set the alarm off I have had a few false alarms which had me running around my house in the middle of the night with my gun ha ha ha..

**Comment by nielsfaber** [comment]
Ok clear, feel free to use whichever alarm fits best for you 👍 
Note that the feature to consider multiple sensor events before triggering is requested a couple of weeks ago and will be added in a next update (see https://github.com/nielsfaber/alarmo/issues/253).

**Comment by jerodjchastain** [comment]
Alarmo is very cool and well built.  I will definitely be trying again in the future when I have another section of time.
