### ISSUE TITLE
Alarmo Card error - Custom element does not exist after upgrade to HA 2021.08

### ISSUE THREAD

**Issue by faquaresma** [nielsfaber/alarmo#286]
Hi ,

After the upgrade to HA 2021.08 version, the alarmo card does not works.

I have the follow error:

![image](https://user-images.githubusercontent.com/52538650/132723901-3d66696a-057d-4018-a58c-2e5f2010a3bf.png)

I have clean cookies on my browser, but the error remains.

I appreciate your help 

Thanks in advance

FQ

**Comment by nielsfaber** [comment]
Alarmo-card is not part of the alarmo package anymore.
Did you install it separately from hacs or  https://github.com/nielsfaber/alarmo-card ?

**Comment by faquaresma** [comment]
Hi, 

I install from hacs.

What is the alternative ?

Thanks

FQ
