### ISSUE TITLE
Feature request: service to (un-)bypass a sensor while armed

### ISSUE THREAD

**Issue by tader** [nielsfaber/alarmo#289]
Problem: a motion sensor gets triggered by the vacuum robot

Proposed generic solution: if a service is provided to bypass a sensor while the alarm is armed, an automation could be built that bypasses the sensor while the vacuum is running, and remove the bypass afterwards

**Comment by nielsfaber** [comment]
The bypassing functionality is intended for sensors which are active **at the moment of arming** only. 
It is not that easy to modify the behaviour such that it can be changed afterwards and that the user can choose the sensors, I also think it is a bit hacky.

I suggest you make use of the `armed_custom_bypassed` arming mode and make the configuration identical to `armed_away` except for removing the motion sensors which may be triggered by the vacuum.
You can use an automation for switching between `armed_away` <->  `armed_custom_bypassed` at the start and end of the cleanup.
This is how I have it configured in my house as well, works perfectly.

**Comment by tader** [comment]
Thank you for your quick reply! Switching armed modes would require me to somehow remember which mode to switch back to (night/away), and I’m currently using the custom mode as vacation mode. I think I’ll build a template sensor instead that takes in account the vacuum state.
