### ISSUE TITLE
suggerimento custom:numberbox-card

### ISSUE THREAD

**Issue by riddik14** [nielsfaber/alarmo#29]
hi could i suggest this card to set times https://github.com/htmltiger/numberbox-card

hello and great job

if you need, I can help if you start creating the language files in Italian.

![image](https://user-images.githubusercontent.com/37450907/100034519-9f25df80-2dfc-11eb-9a51-d35810766744.png)

**Comment by nielsfaber** [comment]
I cannot use a custom card in Alarmo.
Then all users should install it as well.

But ofcourse i could make something that works similar to it.
The documentation is very limited.
Does the card always show both the slider and the + and -  option?
Or can you switch the mode?
