### ISSUE TITLE
Alert notifications support data field for image attachment

### ISSUE THREAD

**Issue by hewfish** [nielsfaber/alarmo#290]
In Alarmo / Actions / Notifications. Support the Data field so that image snapshots can be sent as a notification. I'm using Signal as a push notification handler which supports a data link for image insertion. When I attempt to add the data field using YAML, it gets chopped up.

This is the typical format that would be used in the message request. However if I switch to YAML and attempt to use just the "service" section then switch back I get data validation issues with the "message" field missing, which its not, its just moved to the data block.

action:
  service: notify.NOTIFIER_NAME
  data:
    message: "Alarm in the living room!"
    data:
      attachments:
        - "/tmp/surveillance_camera.jpg"

This it not really a bug, its just a feature request so that I can send a camera snap on alarm trigger.

Additional Information on the message handling - https://www.home-assistant.io/integrations/signal_messenger/

**Comment by nielsfaber** [comment]
> However if I switch to YAML and attempt to use just the "service" section then switch back I get data validation issues with the "message" field missing, which its not, its just moved to the data block.

Could you share some pictures of this?
Alarmo should be able to handle extra data just fine, in fact this is how [actionable notifications](https://github.com/nielsfaber/alarmo#actionable-notifications) can be set up as well.
Perhaps `data` needs to be replaced by `service_data` ? Don't ask me why 😅
