### ISSUE TITLE
Arming in Panel not working

### ISSUE THREAD

**Issue by seantunley** [nielsfaber/alarmo#291]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Alarmo panel to arm and disarm the alarm

### Actual behavior
When pushing the "Arm" Button, nothing happens. Icon does not change into "Arming" state. Tried to install and reinstall with no luck. No errors in the log files either. This was a brand new installation.

### Steps to Reproduce
Install Alarmo and set the required parameters. Adding panel to Lovelace and it does not arm the Panel

**Comment by nielsfaber** [comment]
This repository is not for problems with the alarm panel card.
I don't know which card you use?
I suggest to install [alarmo-card](https://github.com/nielsfaber/alarmo-card), it should show up a reason why arming wasn't successful.

If you need further help, please share some screenshots of your Alarmo configuration and the arming. I cannot judge what's going wrong without additional information.
