### ISSUE TITLE
'alarmo.trigger' service

### ISSUE THREAD

**Issue by ShadyMCShadesen** [nielsfaber/alarmo#293]
### Checklist
- [✅ ] I checked for similar existing requests (both open and closed) before posting.
- [✅ ] My request is generic, other users may benefit from it too.

### Proposal
I would like to have a 'alarmo.trigger' service to trigger the alarms via automations or scripts.

**Comment by nielsfaber** [comment]
The whole idea of alarmo is that triggering occurs automatically based on sensors.
Why would you want/need to trigger it manually?

**Comment by ShadyMCShadesen** [comment]
In my opinion would this feature allow users to do even more custom stuff with this service available^^

I for exampe have a reed sensor that has a problem that it Switches now and then for a short amount of time (less than a second) while the door is still closed. This triggers the alarmo alarm even when noone opened the door. With the default alarm i was able to trigger the alarm only if the sensor was switched for a choosen amount of time so that this Problem that the sensor has wont fault trigger the alarm.

**Comment by ShadyMCShadesen** [comment]
I have a custom alarm control station in my house using esphome (with Display, keypad, rfid sensor, ...) and this device also triggers the alarm when someone entered the wrong code 3 times in a row. (I know at least one more that has something like this https://github.com/docteurzoidberg/esphome-alarm-keypad )

With alarmo i am currently only able to trigger the alarm via a custom entity that i can turn on or off and add this one as a sensor in alarmo. But it would be so simpler to just trigger a service that does everything for me^^

**Comment by nielsfaber** [comment]
I recommend you to create a (template) binary_sensor per device, as this is easy to manage within Alarmo and better for tracing back the source of triggering or arming failure.
I will see if I can implement some `alarmo.trigger` feature in the near future.

**Comment by teek541** [comment]
So I have another use case for this.  I have an IQ4 Panel and it is monitored by my alarm company.  However, I can't trigger fire alarms from my Z-Wave smoke detectors in the IQ4.  I have them connected to Home Assistant and am having them send a triggered alarm to my IQ4 panel.  I need to sync the 2 panels together so I have that being done through an automation that looks for arm, disarm, etc and mirrors it to Alarmo so I can use either the panel or a HA Tablet/Phone.  However, if I trigger an alarm on the IQ4, I can't sync that status to the Alarmo app w/o the trigger command.
