### ISSUE TITLE
Name triggered sensor without the word "open" 

### ISSUE THREAD

**Issue by pdeswardt** [nielsfaber/alarmo#294]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
Currently the wildcard {{open_sensors}} lists the name of the sensor that triggered an alarm, but it has the words "is open" at the end. Can we please have an extra wildcard with just the name of the sensor that triggered the alarm without the words " is open" appended in the notification. 

### Additional info
Create a new wildcard same as the existing wildcard {{open sensors}}, but without the words "is open" in the resulting notification. Maybe call it {{triggered_sensors}} ?

**Comment by nielsfaber** [comment]
Your patience will be rewarded soon 😉

**Comment by pdeswardt** [comment]
Thank you! Looking forward to it.

**Comment by nielsfaber** [comment]
The added functionality is now released in v1.7.6.
You can choose format option for the open_sensors:

![image](https://user-images.githubusercontent.com/16861605/141520036-de74e6bd-b74e-4a1f-a901-0e5ef8efe37f.png)

**Comment by pdeswardt** [comment]
Awesome! Thank you so much!
