### ISSUE TITLE
Entry delay setting for sensor depending on mode

### ISSUE THREAD

**Issue by adampetrovic** [nielsfaber/alarmo#297]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I have sensors that I would like to have a configurable entry delay depending on the mode they are armed in.

For example, my office sensor when armed in night mode should trigger a 10 second entry delay. When armed in away mode, should immediately trigger the alarm. Currently i'm only able to specify whether the sensor is to be used for entry delay globally, regardless of the armed mode I am in.

**Comment by OtherwisePrickly** [comment]
Hello, could you please share how you figured this out? I have a similar situation where a sensor (for example hallway motion sensor) should not have an entry delay when armed away but should have an entry delay when armed night.

Although each mode has configurable entry delay, the advanced settings for each sensor goes across all modes as far as I can see.

**Comment by coolbombom** [comment]
+1

I would like my window and backyard door to trigger the alarm immediately. but my door and motion sensor at my front door needs a delay of 20 seconds, so i can type in my code in my alarm panel before triggering the alarm.

So @nielsfaber, there is a a need for assigning delay per sensor.

kind regards
c_bb

**Comment by coolbombom** [comment]
hi @nielsfaber

just realized the "Use entry delay" does exactly what i want ... sorry for the noise.

and thank u for the great work

kind regards
c_bb
