### ISSUE TITLE
Handle "unknown" state for sensors initialization during startup

### ISSUE THREAD

**Issue by chemelli74** [nielsfaber/alarmo#298]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]
Avoid firing a notification of failure during startup if sensors are not yet initialized.

I would suggest to trigger only `unavailable` status and discard `unknown`.

### Actual behavior
[What actually happened]

2021-10-13 16:22:57 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.alarmo
2021-10-13 16:23:27 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Not all sensors are initialized yet, starting anyway.
2021-10-13 16:23:27 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot transition from state None to state armed_away, there are open sensors
2021-10-13 16:23:27 ERROR (MainThread) [homeassistant.util.logging] Exception in async_handle_event when dispatching 'alarmo_event': ('failed_to_arm', 'xxxxx', {'open_sensors': {'binary_sensor.finestra_camera_degli_ospiti_vibration': 'unknown', 'binary_sensor.portafinestra_salotto_door': 'unknown', 'binary_sensor.portafinestra_salotto_vibration': 'unknown', 'binary_sensor.portafinestra_sgabuzzino_door': 'unknown', 'binary_sensor.portafinestra_sgabuzzino_vibration': 'unknown', 'binary_sensor.sensore_2_cucina_flood': 'unknown', 'binary_sensor.sensore_1_cucina_gas': 'unknown', 'binary_sensor.sensore_2_salotto_vibration': 'unknown', 'binary_sensor.finestra_camera_degli_ospiti_door': 'unknown'}})

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by chemelli74** [comment]
> This is not a bug but a feature request.

Depends on the point of view ;-)
 
> I understand your point. However unknown state is ambigious, it could be either safe or unsafe. I don't want Alarmo to judge it as safe. Ideally the user should get an option (similar to handling of unavailable state) to tell how to interpret this condition.

Adding an option, like was done for `unavailable`, would be a possibility.
But I think the best approach would be to just wait that boot is completed before evaluating.

> More importantly: why do your sensors start in unknown state? Sensor states should normally be requested at the gateway after restarting HA.

Because during boot up Alarmo may load before Shelly; so this is a temporary situation that auto solves itself in a few secs but is annoying because I have a notification of alarm triggered.


Simone

**Comment by nielsfaber** [comment]
As you can see in the logs you shared, Alarmo gently waits for the sensors to get ready.
After 30 sec this times out, and Alarmo proceeds.
This timeout is necessary as in the meantime the alarm entity will also have `unknown` state, which is not desirable as protection is compromised.

I’m surprised the shelly platform takes more than 30 seconds to initialise the sensors.
Are you sure nothing is set up wrong in your setup which may cause this?

**Comment by chemelli74** [comment]
> I’m surprised the shelly platform takes more than 30 seconds to initialise the sensors. Are you sure nothing is set up wrong in your setup which may cause this?

Nothing wrong here; Alrmo most of the times works fine, but init time is not always the same. Sometimes is a bit slower.

What about using has started status instead of hardcoding 30 secs ?

Simone

**Comment by nielsfaber** [comment]
> What about using has started status instead of hardcoding 30 secs ?

To be honest I don't know when this event fires.
I looked at it at the time, but couldn't find any documentation regarding the conditions involved.
There is also the possibility that this event will wait for the alarmo entity to change from `unknown`, so perhaps it becomes a chicken-and-egg problem.

In my opinion `unavailable` and `unknown` state are more or less the same thing, since the sensor state is non-binary so ambiguous.
Therefor I think its OK if Alarmo treats them the same.
For users who have sensors which take very long to initialize at startup (such as your case), I recommend keep the 'trigger on unavailable' setting unchecked, or avoid rebooting HA while the system is armed.
Would this work for you?

**Comment by chemelli74** [comment]
> For users who have sensors which take very long to initialize at startup (such as your case), I recommend keep the 'trigger on unavailable' setting unchecked, or avoid rebooting HA while the system is armed. Would this work for you?

About the reboot, can be an option even if not really handy. You want to update HA: what should you do ?
Disarm, reboot, rearm ? Not really practical but feasible.

About not using "trigger on unavailable" instead I think it's a big no go.
What if you are away and the door sensor goes unavailable ? You should know immediately that you are not protected isn't it ?

Just my 2 cents,

Simone

**Comment by chemelli74** [comment]
Sorry for the very late reply: with 45s it worked fine. I think a parameter would be really nice ;-)

Thx so much for your support.

Simone
