### ISSUE TITLE
Multiple notification targets

### ISSUE THREAD

**Issue by guystreeter** [nielsfaber/alarmo#3]
I'd like to send notifications to more than one target.

**Comment by tomer-w** [comment]
I think alarmo is incredibly good start with replacing the dated manual alarm. But notifications is one major area to improve here. We should be able to send notifications to multiple targets and we should allow choosing different channel for each notification type as I want the alarm on / off to make small / no noise, but alarm triggered should rock my phone.

**Comment by nielsfaber** [comment]
@tomer-w you mean you want to customize the [service data](https://www.home-assistant.io/integrations/notify/#service)?

I want to create a GUI that allows you to define a notification per state transition (from -> to).
So far the GUI will allow you to define target(s) + title + message. 
For the message there will be some available wildcards, such as {{ open_sensors }} 

Since the `data` part is highly platform dependent I don't want to include it in the GUI.
But perhaps I can add an 'advanced' panel, where you could edit the service call as YAML.
Would this be useful for you?

**Comment by tomer-w** [comment]
I think your effort around getting UX for all the complexity here is admirable and for sure will help novice users, but I also think HA users are quite used to yamls to get the extra power so I dont see any problem with leaving some of the more complex settings as yaml. Yes, your direction is the right way forward.

**Comment by tremebundo** [comment]
> @tomer-w you mean you want to customize the [service data](https://www.home-assistant.io/integrations/notify/#service)?
> 
> I want to create a GUI that allows you to define a notification per state transition (from -> to).
> So far the GUI will allow you to define target(s) + title + message.
> For the message there will be some available wildcards, such as {{ open_sensors }}
> 
> Since the `data` part is highly platform dependent I don't want to include it in the GUI.
> But perhaps I can add an 'advanced' panel, where you could edit the service call as YAML.
> Would this be useful for you?

I would like to send notifications on certain status changes to telegram and tts. So I strongly vote for that aproach.

**Comment by nielsfaber** [comment]
Small preview of the UI I am working on:
![image](https://user-images.githubusercontent.com/16861605/99192671-56bf4f80-2774-11eb-9cec-35d5b54ae721.png)

It is still a work in progress, but I guess it gives much better flexibility compared to the current implementation.
There is a YAML editing-mode included, so custom service_data can be added if needed.

**Comment by tremebundo** [comment]
> Small preview of the UI I am working on:
> ![image](https://user-images.githubusercontent.com/16861605/99192671-56bf4f80-2774-11eb-9cec-35d5b54ae721.png)
> 
> It is still a work in progress, but I guess it gives much better flexibility compared to the current implementation.
> There is a YAML editing-mode included, so custom service_data can be added if needed.

Very good looking.

**Comment by nielsfaber** [comment]
Please try out the new release v1.1.0 and let me know what you think!

**Comment by tremebundo** [comment]
I think the layout is very intuitive.
I still have not checked if I could translate my current automations to this component via the gui. But seems posible with the yaml editor.
This is an example of what I currently have when disarming:
`- id: alarm_disarmed
  alias: Desconexión de la alarma
  trigger:
    platform: state
    entity_id: alarm_control_panel.casa
    to: disarmed
  action:
  - service: script.turn_off
    entity_id: script.light_loop, script.light_flash
  - service: light.turn_off
    entity_id: light.gateway_light_7811dc6c8b26
  - service: notify.juanma
    data:
      message: La alarma se ha desconectado {{now().strftime("%Y%m%d-%H%M%S")}}
  - service: switch.turn_off
    entity_id: switch.vision_zm1601eu5_battery_operated_siren_switch
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.cocina
      volume_level: 0.5
  - service: tts.cloud_say
    entity_id: media_player.cocina
    data:
      message: La alarma ha sido desconectada
      language: es
  - service: light.turn_on
    entity_id: light.gateway_light_7811dc6c8b26
    data:
      brightness: 255
      color_name: green
  - delay: 00:00:10
  - service: light.turn_off
    entity_id: light.gateway_light_7811dc6c8b26`

**Comment by guystreeter** [comment]
I like it.
The "Edit Sensor" card takes about 15 seconds to appear, and about 10 seconds to go away. The "New Notification" card is a little slow as well.

**Comment by tomer-w** [comment]
@nielsfaber , the UI is very intuitive but I dont think it will allow enough customization for my scenario.
What I would do on top of the UX is the ability to add 4 script entities to the different scenarios:
1. Script for siren. Many siren works differently and the user will want to customize it. You can turn off the script by home assiatnt script.turn_off service when it is time to silent the alarm.
2. Script for buzzer. Allow you to configure your buzzer to signal the time in the arming state. Same here. call script.turn_off when not needed anymore.
3. Script for notification. Allow me to sens notification to multiple peoples with different devices, etc.
4. Bonus: Script for errors. For example, when you cant arm as the sensor is still open. Allow me to create special buzzer sequence or TTS to say the alarm failed to arm.

**Comment by nielsfaber** [comment]
@tomer-w  It's OK to use scripts. You can use regular automations in homeassistant for this.
The UI is only intended for providing a simple way of configuring notifications (basic usage).
There will be another UI for triggering devices, but it will probably also be limited to simple ON/OFF actions.
I have no intentions of creating a copy of the extensive automations UI that is already in HA.

If you need some additional attributes to be exposed by the `alarm_control_panel` entity (to be used in your scripts), please open a separate feature request for it.

**Comment by tomer-w** [comment]
@nielsfaber, of course I want to use the built in HA UI to build the scripts and test them. There is no need to do anything like that in Alarmo. I just want the UX to allow choosing those scripts for the different scenarios. just 4 dropdowns in the UX and calling them / stopping them when needed.
I dont think I can easily / at all connect a buzzer to beep when in arming or beep fast when something failed based on what is exposed right now. could be that i'm not expert enough in automation building. Anyway, it will make Alarmo way more extensible if users will be able to easily attach their creativity to your infra.

**Comment by nielsfaber** [comment]
>  I just want the UX to allow choosing those scripts for the different scenarios. just 4 dropdowns in the UX and calling them / stopping them when needed.

I'm not sure what you mean. There is one dropdown for the event (so when to perform the action) and one for the notification target.
There will be no more added.

I think the panel that still is in the making (for switching devices) could be more suitable for your use-case. Normally you would pick e.g. a siren device (`switch`), but I could provide the option to select an arbitrary entity that supports turn_off/turn_on (such as `script`).

> I dont think I can easily / at all connect a buzzer to beep when in arming 

Sure you can. The alarm entity will be in state `arming` during the leave delay, so you can create an automation that loops every X sec while the alarm is in this state.

> or beep fast when something failed based on what is exposed right now. 

If something fails the `changed_by` attribute is set on the alarm entity. It is normally `null`, but would change to a list of failing/blocking sensor entities with their state, in case the alarm failed to arm or is triggered.

So if you create an automation that watches for changes to this attribute, combined with condition that the alarm is `disarmed`, you can also have something triggered when the arming was blocked.

Both use-cases will be also supported by the UI in Alarmo, so the choice is yours.

**Comment by tomer-w** [comment]
ok, i will do deeper testing for this and maybe I can get it to work with some level of automation instead of scripts. It just requires the user to know way more about your implementation then choosing script and focus on what the script do instead of how to get the trigger and conditions right for those basic scenarios used by old regular alarms for ages.
BTW: maybe I dont have the latest version but when I failed to arm the alarm I still get null in the ``changed_by`` attribute both on the ``old_state`` and the ``new_state``.

**Comment by tomer-w** [comment]
@nielsfaber, just installed your latest version. The new notification UI and the upcoming Actions one are exactly what I needed. Thanks. This is already by far the best alarm integration of HA. I would hope you will be able one day to get it into the main product and not leave it as a standalone component.

**Comment by tomer-w** [comment]
@nielsfaber, just installed your latest version. The new notification UI and the upcoming Actions one are exactly what I needed. Thanks. This is already by far the best alarm integration of HA. I would hope you will be able one day to get it into the main product and not leave it as a standalone component.

**Comment by tomer-w** [comment]
There is one issue which is probelmatic though. Although there is a way to add the yaml directly which is great, I cant add there service specific data as it get deleted the moment I save the control or any other configuration save happens. I tried to add something like:
```
data:    
        channel: Important
```
Which is needed to get special alarm on my Android phone but that get lost when save happen. It will be great if it will keep all the manual additions to that section so I can do the device specific customization for the notification.

**Comment by nielsfaber** [comment]
@tomer-w  Updating to v1.2.0 should fix the yaml editor issue. And it adds the actions UI.

**Comment by nielsfaber** [comment]
I'm closing this issue because the original feature request has been added.

**Comment by hhcalder92** [comment]
Was this feature removed in a later releases? i am running v1.9.7 and I only see the ability to add one event type and/or device target per notification. I want to move some exist notifications over to alarmo to leverage the variables( ie `open_sensors`)

![Screenshot 2022-12-28 at 2 16 33 PM](https://user-images.githubusercontent.com/7275599/209872985-29433233-4f09-4f1c-810e-ecfed1f3d41e.png)

**Comment by tomer-w** [comment]
You can still add multiple actions, each with its own setting. In addition, each action can execute script which perform multiple steps. The options are almost limitless.

**Comment by rblaursen** [comment]
I have been playing all night with getting a notification sent to multiple devices without setting up device by device.
I'm not super technical as a programmer, and can't figure out how to do this.
Can some one help, please?
Thank you in advance :-)

**Comment by ukiews** [comment]
@nielsfaber Is there a reason the option to add multiple targets was removed from the UI? Any chance you could bring this back?
