### ISSUE TITLE
time duration and interval sound siren

### ISSUE THREAD

**Issue by riddik14** [nielsfaber/alarmo#30]
hello could you include a setup menu for the siren entity (switch) with the times to set? I ask this because in Italy there are rules that regulate the activation times of the siren.

in fact, to avoid breaking the laws relating to alarms, an intrusion alarm must not sound more than 3 minutes in total, which is the maximum duration allowed.

**Comment by nielsfaber** [comment]
This is already possible:
![image](https://user-images.githubusercontent.com/16861605/100049589-000ee100-2e18-11eb-9bab-7d3076d42971.png)

Just create an action to turn on the siren when alarm is triggered, and one to turn it off when alarm is disarmed.

**Comment by nielsfaber** [comment]
I assume your question is answered.
Please re-open if this is not the case.
