### ISSUE TITLE
Alarm triggers immediately when second sensors is tripped

### ISSUE THREAD

**Issue by Chluz** [nielsfaber/alarmo#307]
### Checklist
- no similar issue listed. I thought this might be a feature, but I cannot find it mentioned anywhere
Observed on v 1.7.4

### Expected behavior
"Pending" state should continue for the whole extent of the trigger delay after one sensor is tripped, regardless of how many other sensors are tripped. 

### Actual behavior
"Pending" state starts when one sensor is tripped. If another sensor is tripped before the end of the trigger delay, the "triggered" state becomes active. 

### Steps to Reproduce
Turn on alarm in any mode with multiple sensors assigned. Trigger a first sensor, and then trigger a second sensor before the trigger delay finishes.

**Comment by xhemp** [comment]
This looks to be the case with me as well,I will be able to test tomorrow and report.
