### ISSUE TITLE
[Feature request] Enable/Disable Users

### ISSUE THREAD

**Issue by Ruud2021** [nielsfaber/alarmo#309]
It would be great if you could enable and disable users. Preferably through an automation.
For example, if the maid comes twice a week, the code should not be able to be used on the other days.

**Comment by nielsfaber** [comment]
This functionality is added, will be part of the next release.
There are new services `alarmo.enable_user` / `alarmo.disable_user`, there will be checkboxes in the 'codes' page as well.

**Comment by nielsfaber** [comment]
The changes are added in the latest release (v1.8.0).
Please update Alarmo locally and check whether it works as you would expect.
If so, you can close the issue. Otherwise, please let me know.
Thanks for the help 👍
