### ISSUE TITLE
HACS deployment copy lot of unneeded stuff to HA custom_components folder

### ISSUE THREAD

**Issue by tomer-w** [nielsfaber/alarmo#31]
HACS installation works but it copies lot of source files into your HA deployment which are not really needed.
Specifically, I see lot of files in the frontend subfolder compared to what you get with manual installation.
Nothing really broken by that, but this is just something which can get cleaned-up eventually.

**Comment by nielsfaber** [comment]
Thanks for noticing, i never took a look at this.
I just released v1.3.0 which should fix it.
From now on, HACS uses the contents of the zip file in the release.
