### ISSUE TITLE
Debounce/sensor delay

### ISSUE THREAD

**Issue by Xebozone** [nielsfaber/alarmo#318]
Some of my sensors appear to be a bit unstable. Perhaps for example a window shakes a bit like if there is wind. This can cause a sensor to go Open Closed Open Closed in quick succession.

If there is either a global or a sensor-specific setting to add a debounce time, then it could help to resolve some false positive triggers.
If the sensor goes from Open back to Closed within this debounce time, it will be ignored. This could go in the advanced settings for each sensor, or under General settings for a global setting (or both, the advanced settings being an override).

This would obviously add a delay, so if it's a global setting, then it should have a warning note near, or set the minimum Entry Time to the globally set debounce time (just in the GUI, so that the users understand that a delay is applied because of debounce).

**Comment by nielsfaber** [comment]
Debounce is already applied in case of applying the 'arm after closing' setting for a door sensor.
But as far as I am aware this is the only use-case where debounce is really relevant.
In which scenario would a sensor go (falsely) from Closed to Open state (and back) while the alarm is armed?

**Comment by Xebozone** [comment]
I have a garage door that when it closes, the arm does a strange locking movement, and the sensors rapidly goes open closed open closed within 1 or 2 seconds, but I suppose if you've considered the use cases, then that's fine. Thanks
