### ISSUE TITLE
Completing language

### ISSUE THREAD

**Issue by Patrick44fr** [nielsfaber/alarmo#319]
Hello,

I use Alarmo, with satisfaction, it's really a good job. the translation is really great now.
I noticed an oversight, but maybe it's not, really.

When receiving an alarm trigger notification by a sensor, the message received is in the chosen language, but the sensor status is always in the system language (English) example: is open.
see the attached photo.
Is it possible to change this
Thank you in advance and good luck
Patrick44fr

sorry for my broken english

![Screenshot_2021-11-11-18-48-58-345_com textra](https://user-images.githubusercontent.com/74200895/141346754-2c1a3efe-e9f3-455b-bc10-4b468cef311c.jpg)

**Comment by nielsfaber** [comment]
I am already working on this!
It is not that easy because the alerts are generated from the backend side, so the json translations are not accessible for me.
However, Home Assistant has built in translations for binary sensors of different device types, so it will be able to find the right word for a door which is open, but also a motion sensor which is activated.
I hope to be able to release this in a few days.

**Comment by nielsfaber** [comment]
It is now released in v1.7.6
You can select it here:

![image](https://user-images.githubusercontent.com/16861605/141519937-1f7230a4-fc57-4345-8649-1808589cbf69.png)

The french option will become automatically visible if your HA account is set to french as well.

Hope it works OK for you 👍

**Comment by Patrick44fr** [comment]
Ok it’s great , it’s work for me for sensors.

It don’t work for state of alarm : arm away, arm night….etc

Thank’s for your quick response

Good afternoon

**Comment by nielsfaber** [comment]
In the latest release (v1.8.0) the `arm_mode` wildcard also has the option to choose local translation.
Please update Alarmo locally and check whether it works as you would expect.
If so, you can close the issue. Otherwise, please let me know.
Thanks for the help 👍

**Comment by Patrick44fr** [comment]
fine, translation for wilcard message, it's good
thank's
