### ISSUE TITLE
skip_delay ignored when service is called in Node Red

### ISSUE THREAD

**Issue by chrispazz** [nielsfaber/alarmo#323]
If I call the service from developer page inside HA the skop_delay parameter is working as expected.
When using it from node red it is ignoring the skop_delay flag.

Here is the flow:

`[{"id":"369b8c78260fdb26","type":"switch","z":"22f66bc511ea4c3a","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"1005","vt":"str"},{"t":"eq","v":"1004","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":370,"y":240,"wires":[["5efdc452202a5998"],["bcc8bbbf106ec10f"]]},{"id":"7bae592aee518bd3","type":"deconz-input","z":"22f66bc511ea4c3a","name":"","topic":"","config_version":1,"server":"95c2ca27c7e6fed4","statustext":"","statustext_type":"auto","search_type":"device","device_list":["sensors/uniqueid/00:15:8d:00:01:55:d2:a3-01-0006"],"device_name":"","query":"{}","outputs":1,"output_rules":[{"type":"state","format":"single","output":"always","onstart":true,"payload":["buttonevent"]}],"x":190,"y":240,"wires":[["369b8c78260fdb26"]]},{"id":"1415cfe141b6d40b","type":"api-call-service","z":"22f66bc511ea4c3a","name":"Cicla In Casa - Fuori Casa","server":"cc289e25.9b734","version":3,"debugenabled":false,"service_domain":"alarmo","service":"arm","entityId":"alarm_control_panel.alarmo","data":"{\t   \"code\":1454,\t   \"mode\":msg.payload,\t   \"skip_delay\":0\t}","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":860,"y":280,"wires":[["954d06099e1b0ad3"]]},{"id":"bcc8bbbf106ec10f","type":"function","z":"22f66bc511ea4c3a","name":"Ciclo modalità","func":"const arming_modes = [ \n    \"home\", \n    \"away\"\n];\n\n/**** dont change *****/\nlet arming_mode = context.get(\"arming_mode\"); \narming_mode = arming_mode == null ? 0 : arming_mode + 1;\nif(arming_mode >= arming_modes.length) {\n    arming_mode = 0;\n}\nmsg.payload = arming_modes[arming_mode];\ncontext.set(\"arming_mode\", arming_mode); \nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":580,"y":260,"wires":[["1415cfe141b6d40b"]]},{"id":"954d06099e1b0ad3","type":"debug","z":"22f66bc511ea4c3a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1100,"y":280,"wires":[]},{"id":"95c2ca27c7e6fed4","type":"deconz-server","name":"Phoscon-GW","config_version":1,"ip":"core-deconz","port":"40850","ws_port":"8081","secure":false,"polling":"15"},{"id":"cc289e25.9b734","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30}]`

**Comment by nielsfaber** [comment]
I am not a node-red user so I cannot help you with that.
Could you try calling the service from HA and see that alarmo behaves as you would expect?

**Comment by chrispazz** [comment]
Problem solved, it was my mistake.

Thank you
