### ISSUE TITLE
Trigger time for environmental sensors in disarmed mode

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#326]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
When Alarmo is disarmed, environmental sensors trigger the alarm with an infinite trigger time.
A trigger time for the disarmed mode would be helpful to avoid infinite alarms.

**Comment by nielsfaber** [comment]
I would say that ideally the environmental alarm is handled completely different than the others.
Not only should the trigger time and delay time be configurable, but also specific automations should be triggered etc.
I do agree with your request, but I have no idea how to implement this right now.

**Comment by Masterz69** [comment]
May be add mode "Disarmed" in General->Modes with only "Trigger time" to be defined and used for environmantal etc. sensors, active in all modes, including in disarmed.

F.e. Xiaomi implement so called "Basic Guard" - for environmental sensors, which active always, independently from Armed& modes.

As well as in Actions  would be nice to have conditions:
* on sensor type
* and add "Disarmed" in "Mode" condition.
