### ISSUE TITLE
Add the option to hide on sidebar

### ISSUE THREAD

**Issue by srodighiero** [nielsfaber/alarmo#328]
This would avoid having the admin panel visible even for non-admin users, for example, and avoiding confusion if another dashboard for users alarm panel/card exists on the sidebar.

Would be great for example to have on integration page the option "open weui", like for Supervisors integrations.

**Comment by nielsfaber** [comment]
Your request is implemented in the latest release (v1.8.0).
Please update Alarmo locally and check whether it works as you intended.
If so, you can close the issue. Otherwise, please let me know.
Thanks for the help 👍

**Comment by srodighiero** [comment]
@nielsfaber thank you for that, really appreciated.

Unfortunately I'm unable to see any option for the feature anywhere after the update, where should it be visible?

**Comment by nielsfaber** [comment]
It’s not an option. The alarmo panel will simply be hidden for non-admin HA users.
I think this is similar to other integrations (like hacs).

**Comment by srodighiero** [comment]
Oh, Ok, understood. Yes, confirmed it's working, not visible for non-admin users
