### ISSUE TITLE
Restore Alarm to its previous state after restart of HA.

### ISSUE THREAD

**Issue by thedom4302** [nielsfaber/alarmo#331]
I am not seeing alarmo restore to its previous state after restart of HA.

### Expected behavior
Alarm was in armed_away state after hass started back up.

### Actual behavior
Alarm was disarmed after unexpected power interruption

### Steps to Reproduce
Arm alarm and waited for state changed to armed_away.
Turned off power from power supply on raspberry pi.
Turned power back on for raspberry pi.
Waited for hass to startup.
Login into web console and check state of alarmo.  It was in disarmed mode.

**Comment by nielsfaber** [comment]
Alarmo does restore its state normally.
Please check the HA logs for a reason why it did not happen for you.
It is likely due to sensors being unavailable.

**Comment by thedom4302** [comment]
Tried again and all good, thanks for checking I have bought you three coffees :)
