### ISSUE TITLE
Wildcard `{{changed_by}}` empty on arming action

### ISSUE THREAD

**Issue by syphernl** [nielsfaber/alarmo#332]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Behavior
- Alarmo is configured to send out a notification:  ```The alarm is set to {{arm_mode}} by {{changed_by}}```
- When arming Alarmo using the Alarmo-Card the message that is sent out reads:   ```The alarm is set to Armed Away by ``` (the value `{{changed_by}}` is not filled in.
- For disarmed I have ```Alarm Turned Off ({{changed_by}})``` which gets properly  replaced:  ```Alarm Turned Off (Frank)```

### Expected behavior
- Alarmo should fill in the `{{changed_by}` with the username who armed it

### Steps to Reproduce
- Set the Notification Action Messages to above values.

**Comment by nielsfaber** [comment]
The `changed_by` property is derived from the code which was used for arming/disarming.
If you configured the alarm to allow arming without any code, Alarmo cannot know who armed it.
Did you set up Alarmo to require a code for arming?
If not, the behaviour is as I would expected, it is not a bug.

**Comment by syphernl** [comment]
Ah, that explains it then! I'll have to enable that then. Thanks.
