### ISSUE TITLE
Wildcard and layout

### ISSUE THREAD

**Issue by KameDomotics** [nielsfaber/alarmo#333]
-Wildcards are not visible with dark themes (for example I use Google Dark Theme)

-With the Home Assistant smartphone application, the cards are cut (see attached images)

![CF7EAA9F-66FC-4188-9C2D-E4F9422F9FE4](https://user-images.githubusercontent.com/47695661/143782374-f18d36e7-5350-417b-8f76-caafd0ff9043.jpeg)
![9373879F-0AC7-4688-9E63-D55302CDD190](https://user-images.githubusercontent.com/47695661/143782379-b149709e-f58b-4782-b7ac-88b0f38434dc.png)

**Comment by nielsfaber** [comment]
Thanks for reporting it. I made some changes which will improve this. They will be in the next release.

**Comment by nielsfaber** [comment]
Version v1.8.1 is released.
It should improve the display with Google Dark Theme.
Could you please test it (check that correct version number is shown in the corner after updating Alarmo)?
If it looks OK after updating, you can close the issue.

**Comment by KameDomotics** [comment]
> Version v1.8.1 is released.
> It should improve the display with Google Dark Theme.
> Could you please test it (check that correct version number is shown in the corner after updating Alarmo)?
> If it looks OK after updating, you can close the issue.


The problem of dark-themed wildcards has been resolved.  Now it works.

The problem with the tab General and Sensors being cut is still present.

**Comment by KameDomotics** [comment]
![4355D86D-7280-4C8F-91EA-7E78B3F1C6F5](https://user-images.githubusercontent.com/47695661/144317792-034ddd4c-42c8-4773-9f0c-dbf467b0977b.png)

**Comment by nielsfaber** [comment]
I don't see this problem on my PC or iPhone, it is probably related to your device or browser.

I tried in chrome with this list of device screen simulators, all look fine (except for the Galaxy Fold which is just too narrow).
![image](https://user-images.githubusercontent.com/16861605/144608808-a73905fd-bb36-4245-8233-85a78ee7e775.png)

I don't know how to help without any way to test it locally.

**Comment by KameDomotics** [comment]
> I don't see this problem on my PC or iPhone, it is probably related to your device or browser.
> 
> I tried in chrome with this list of device screen simulators, all look fine (except for the Galaxy Fold which is just too narrow). ![image](https://user-images.githubusercontent.com/16861605/144608808-a73905fd-bb36-4245-8233-85a78ee7e775.png)
> 
> I don't know how to help without any way to test it locally.

I use Home Assistant app not browser.

I tried with iPhone X, iPhone 8 and iPhone 13 mini.  All devices have the same problem.

I also tried resetting the frontend cache and reinstalling the app.

**Comment by KameDomotics** [comment]
This is another user's screenshot, Android smartphone and Home Assistant APP

![49696381-D63E-45B0-B43D-6EBFC865E811](https://user-images.githubusercontent.com/47695661/144700616-8ad4c6ce-ed9d-4e67-8e5b-1fb44d9cdeda.jpeg)

**Comment by KameDomotics** [comment]
.

**Comment by nielsfaber** [comment]
This should be fixed by updating to `v1.8.2`. 
Please test it and close the issue if it looks OK now, otherwise let me know.

**Comment by KameDomotics** [comment]
> This should be fixed by updating to `v1.8.2`.
> Please test it and close the issue if it looks OK now, otherwise let me know.

Now everything is perfect, great job thanks!
