### ISSUE TITLE
"User is administrator" still shown in UI

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#337]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
After removal of the administrator role, the option "User is administrator" should not be shown in UI anymore.

### Actual behavior
"User is administrator" is still shown in the codes section when editing a user.
Trying to use it produces the error:
"Something went wrong!
Message format incorrect: extra keys not allowed @ data['is_admin']
Response error: 400
Please report the bug."

### Steps to Reproduce
- Edit a user
- Turn option "User is administrator" on
- Save changes

**Comment by nielsfaber** [comment]
Can you check your version number of alarmo in the top right corner of the screen?

**Comment by Eyco1981** [comment]
In UI it shows v1.7.6 (also after cache reset). HACS shows v1.8.0 to be installed.

**Comment by Eyco1981** [comment]
Have reinstalled Alarmo in HACS and it is showing v1.8.0 now.
Also the admin option is away now. Seems to have been an installation issue in HACS.
