### ISSUE TITLE
Filter by area not working for actions

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#338]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
When clicking on an area, only actions assigned to that one should be shown.

### Actual behavior
All actions are shown, whatever area is selected.
Notifications can be filtered as expected.

### Steps to Reproduce
- Create more than one area
- Create at leat one action per area
- Filter actions by area

**Comment by Eyco1981** [comment]
Additional info:
The filter for actions are only executed after a filter for notifications is set too.

**Comment by Eyco1981** [comment]
Additional info:
Selecting a filter for notifications also filters the actions.
The action filter selection seems to be ignored.

**Comment by Eyco1981** [comment]
The filter selectors seem to behave a bit strange.
The actions are filtered, if both filters for actions AND notifications are activated, but actions will be filtered by the area selected for notifications.

**Comment by nielsfaber** [comment]
Thanks for reporting this.
There was indeed a small typo (copy-paste error) which resulted in mixing of the filters for notifications/actions. 
It will be solved in the next release.

**Comment by nielsfaber** [comment]
The issue should be resolved by updating to v1.8.1.
Please check that after updating the correct version number is shown in the top right corner of the alarmo panel.
If the problem is solved for you after updating, please close the issue.

**Comment by Eyco1981** [comment]
Filtering is working, just the highlighting of the selected area is a bit strange.
Initially it shows one area (master) highlighted, even if no filter is set.

**Comment by nielsfaber** [comment]
I didn't pay attention to this earlier, but I see what you mean.
I made a fix for it (once again), I will let you know when it's out.

**Comment by Eyco1981** [comment]
I'm sorry to be such a pain. 😁

**Comment by nielsfaber** [comment]
I am happy with your bug reports!
In my house I only use a portion of Alarmo's features and when making changes I only perform manual tests for verification, so my development process has its flaws.

For me its actually very useful if people help me with testing and share their feedback.
Whether it's bugs or things you like to see changed, both are welcome.
As long as the issues list is not flooding, please keep them coming.
I can always choose not to pick them up, right 🤭
