### ISSUE TITLE
Alarm triggered by a sensor, other sensor doesn't work

### ISSUE THREAD

**Issue by Alessandro1983** [nielsfaber/alarmo#339]
Hi, if the alarm is in armed state and some sensor triggered it, in the alarm panel appear the name of the sensor but if other sensor wil be triggered, nothing happen into the panel and the only way is to disarm te alarm

**Comment by nielsfaber** [comment]
It is intended to be this way, so not a bug.
Alarm can only be triggered once, so the first sensor that causes it, is displayed (and not subsequent events).
