### ISSUE TITLE
"Arm after closing" not working

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#341]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Alarmo switches to state "armed" after closing a (door) sensor with setting "Arm after closing".

### Actual behavior
Alarmo doesn't react to the closing of the door sensor.
Sensor is integrated via Zigbee2MQTT. Opening and closing is detected correctly in Home Assistant.
Opening the sensor in armed state triggers the entry delay as expected.
Behavior seems to have changed since 1.8.0 update, but I'm not 100% sure.

### Steps to Reproduce
- Enable the setting "Arm after closing" for a (door) sensor (my setup has 2 areas and a master)
- Assign the sensor to an area
- Activate Alarmo with exit delay
- Open and close the sensor

**Comment by nielsfaber** [comment]
Hm that is strange, I did not touch any code recently related to this.
I will take a look once I have the time for it, thanks for reporting 👍 
Hope you are not too annoyed with all the bugs you found 😅

**Comment by Eyco1981** [comment]
I'm not annoyed at all. Alarmo is a great integration. Your work is really appreciated!
And every bug we are finding is making it even better later - if it is a bug. ;)

**Comment by Eyco1981** [comment]
I have an idea where the issue might come from. But I have no idea of coding, so please take it with a bit of salt. It's just a theory.
If I understood correctly, you changed the arming behavior in v1.8.0 to solve the security issue (bypassable PIN).
Is it possible that due to those changes on "Arm on closing" the state doesn't change from "arming (exit delay)" to "armed" but from "arming (exit delay)" to "arming (exit delay)"?

**Comment by nielsfaber** [comment]
I checked it out and you are completely right 👍 
I could see that the closing of the door triggered the alarm to be armed again, but with exit delay instead of immediately. 
The effect is that the exit timer would be restarted at 0, quite the opposite of what is desired.
I made a fix for this, I will let you know when it is released.
