### ISSUE TITLE
Unable to add users.

### ISSUE THREAD

**Issue by NickPickles937** [nielsfaber/alarmo#342]
### Alarmo Version

1.7.6 is showing in the top right corner, but according to HACS I have v1.8.1 installed.

### HA Version

2021.11.5

### Bug description

In attempting to create a user I am being presented with an error that states the following:

> Something went wrong!
> Message format incorrect: extra keys not allowed @ data['is_admin']
> 
> Response error: 400
> 
> Please report the bug.

It doesn't matter what code is typed or which options are selected. The name of the user I'm trying to create is "nick" but I've attempted other things to no avail.

### Steps to reproduce

Attempt to add a user.  This is a pretty fresh installation of HA supervised on Debian 11. I haven't been having this issue with anything else.

### Relevant log output

```shell
021-12-02 14:13:45 ERROR (MainThread) [homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['is_admin']
```

**Comment by nielsfaber** [comment]
Please update to v1.8.1 (maybe you need to clear browser cache)

**Comment by NickPickles937** [comment]
So I do actually have v.1.8.1 installed but for some reason when I'm in the Alarmo config it shows v.1.7.6... I've attempted clearing cache and switching computers. Also tried this on my iPhone through the HA app.

**Comment by nielsfaber** [comment]
The only thing I can tell you is that in Google Chrome you can fix this by `ctrl+shift+i` and then go to network tab and select `disable cache`.
I have no influence on the caching behaviour (I believe this is handled by HA internally).

**Comment by NickPickles937** [comment]
Clearing the cache again for the 50th time seems to have worked.  Thanks and sorry for the false bug report!  Thanks a lot for the integration!
