### ISSUE TITLE
SO, i actually dont know it this is a bug - actionable notifications

### ISSUE THREAD

**Issue by Ehlz77** [nielsfaber/alarmo#344]
### Alarmo Version

v 1.8.1

### HA Version

2021.9.7

### Bug description

So i got actionable notifications to work one way. Meaning that when my alarm is triggered, i am able to disarm it directly from the notification which is nice. Trying to utilize the same method when the alarm is disarmed, i want to be able to re-arm it (ARM_NIGHT or ARM_AWAY) I got the two options displayed in my notification, but unlike the ALARMO_DISARM which is working, the ALARMO_ARM_AWAY or ALARNO_ARM_NIGHT does not.

Working:
service: notify.mobile_app_jespers_xs
service_data:
  title: Alarmen udløses om 20 sekunder
  message: 'Årsag: {{open_sensors|lang=da}}'
  data:
    actions:
      - action: ALARMO_DISARM
        title: Deaktiver alarm
        
Not working:
service: notify.mobile_app_jespers_xs
service_data:
  title: Alarmen er deaktiveret
  message: Alarmen er deaktiveret
  data:
    actions:
      - action: ALARMO_ARM_AWAY
        title: Aktiver alarm
      - action: ALARMO_ARM_NIGHT
        title: Aktiver natalarm

Please advice

**Comment by nielsfaber** [comment]
Valid options are:
* ALARMO_FORCE_ARM - repeat previous arming operation, automatically bypass sensors which are still open
* ALARMO_RETRY_ARM - repeat previous arming operation, fails if sensors are open
* ALARMO_DISARM - disarm (is intended to use with ‘alarm triggered’ notification)

Please close your issue if this helps.

**Comment by Ehlz77** [comment]
I see, would be nice if the other options could be included in a future update.

Regards

Jesper Laursen
