### ISSUE TITLE
Message format incorrect: extra keys not allowed @ data['is_admin']

### ISSUE THREAD

**Issue by davcho80** [nielsfaber/alarmo#345]
### Alarmo Version

v1.8.1

### HA Version

2021.11.5

### Bug description

after installing Alarmo unable to create user or admin user error in log
[homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['is_admin']
![alarmo](https://user-images.githubusercontent.com/94725371/144775802-1f9e8530-3a7e-4193-900a-0aa150ba00c8.gif)

**Comment by nielsfaber** [comment]
Duplicate of #342
