### ISSUE TITLE
Add/allow "services" in Actions

### ISSUE THREAD

**Issue by trankillity** [nielsfaber/alarmo#347]
### Checklist
- [✔] I checked for similar existing requests (both open and closed) before posting.
- [✔] My request is generic, other users may benefit from it too.

### Proposal
Allow custom services to be called as part of an action automation. This would expose significantly more functionality to Alarmo/end user without needing to bounce between HA automations, and Alarmo automations. If there was a fear of too much power, and "Advanced Options" toggle could be defaulted to off.

### Additional info
*Example 1*
Action: Alert over TTS.
Service: `tts.cloud_say`
Data: `message: Could not arm due to {open_sensors}`

*Example 2*
Action: Lock exits on arm.
Service: `lock.lock`
Data: `entity_id: lock.front_door`
Service: `cover.close`
Data: `entity_id: cover.garage`

**Comment by nielsfaber** [comment]
I think most of this is already possible by switching to YAML mode. Operating a lock should be possible via UI.
Did you try configuring these actions before writing your request?
I would like to ask for a bit more specific information to continue.

**Comment by Eyco1981** [comment]
If a grafical editor is preferred, you can also create scripts and call those from Alarmo with:
service: script.name
entity_id: script.name

**Comment by trankillity** [comment]
I should have been clearer. I realise that you can achieve this through YAML mode fairly easily, was just hoping to have the same/similar UI to Automations tab. I guess you could consider this "advanced use case" and just require people to use YAML.
