### ISSUE TITLE
[Documentation] Enable and configure Alarmo via YAML

### ISSUE THREAD

**Issue by lrodorigo** [nielsfaber/alarmo#351]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
The README could  provide a small tutorial on how to add and configure Alarmo via Yaml. The UI configuration is really user friendly but for users that want an easy reproducible configuration, versioned on git, configuring things on the UI (it writes files into the .storage folder, which is git-ignored), is not a good thing.

**Comment by nielsfaber** [comment]
It is not possible to configure Alarmo via YAML.
In HA, integrations are either configured via UI or via YAML, but it's not possible in both ways.
I chose the UI way for Alarmo.

**Comment by lrodorigo** [comment]
Ok, sorry for missing this 'structural' requirement.
 I thought that because other integrations like mqtt allows to be configured via YAML and via flows on the integrations panel.

So the only way to backup the configuration is to commit/restore the .storage folder?

**Comment by nielsfaber** [comment]
Yes, `.storage` folder contains all UI-based integration data (including discovered devices via YAML) so it be part of your backups.
