### ISSUE TITLE
Add trigger command for manual triggering the alarm

### ISSUE THREAD

**Issue by tlalos** [nielsfaber/alarmo#352]
Hi,
i thing that adding the trigger command to manually trigger the alarm will help alot.

For example alarmo supports only binary sensors, and i have sonoff sensors that are not binary and are not accepted in alarmo.

So for example i could create an automation when that sonoff sensor state changes to trigger the alarm.
I think it will be most helpful, the ha alarm panel has it too.

Also if you will added make it so that when triggered to go from pending mode first like ha panel does.

**Comment by nielsfaber** [comment]
This feature is on it's way (https://github.com/nielsfaber/alarmo/commit/9b26744fec95ce5be452cc03ef969cde65eb36dd)!

**Comment by louisc** [comment]
Hi, @tlalos just in case you wanted to get this working straight away, I guess you could use template sensors in ha to map these devices ? 

Something like this should work:

`template:
  - binary_sensor:
      name: sonoff_sensor1
      state: >
        {{ is_state('switch.sonoff_sensor1', 'on') }}`
