### ISSUE TITLE
Slow response when calling alarmo.arm/disarm service from home assistant api

### ISSUE THREAD

**Issue by tlalos** [nielsfaber/alarmo#354]
### Alarmo Version

1.8.1

### HA Version

2021.12.1

### Bug description

Hi,
i'm using the home assistant api to arm and disarm alarmo.
For example when i call the api 
http://192.168.100.225:8123/api/services/alarmo/arm
to arm the alarm there is considerable delay to get back the response. 
It works but comparing with the normal alarm, alarmo is delaying about 2 seconds which is a bit slow.

Normal alarm response is les then second.

Another thing that i notice is that also comparing with the normal alarm when using the alarmo panel to arm/disarm there
is the same delay to take the command.

**Comment by nielsfaber** [comment]
What do you consider the 'normal alarm'?
I'm not sure if there is anything I can do to improve the speed, what do you suggest?
