### ISSUE TITLE
Actions ->Edit or create new Action blank

### ISSUE THREAD

**Issue by jfl304b** [nielsfaber/alarmo#355]
### Alarmo Version

v1.8.1

### HA Version

2021.12.1

### Bug description

When trying to edit an existing action or create a new action, I only get a blank screen.  Notifications work fine.  I have reloaded Alarmo, deleted and re-installed it and cleared all caches but nothing worked.  I use Mac Safari, but also tried Chrome as well with the same result

**Comment by nielsfaber** [comment]
Can you check the browser logs for any clue (see https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs)?

**Comment by jfl304b** [comment]
![image](https://user-images.githubusercontent.com/51883647/146219178-14fbf96f-1f32-46c8-9f9f-65a57520bbe8.png)

**Comment by nielsfaber** [comment]
Could you check in your HA entities (under Developer Tools -> States) whether you have some group entities defined with wrong configuration?
I would expect you have groups containing other groups, or containing itself in its group. 

Example of a problem:
![image](https://user-images.githubusercontent.com/16861605/146654779-fe40fadd-3290-475f-9d5a-731e4a9b759c.png)

If you don't see any problem here, maybe you could post a screenshot of the group configurations?

**Comment by jfl304b** [comment]
Here's the screenshot I think you are looking for - nothing obvious to me.

![Screen Shot 2021-12-18 at 3 42 10 PM](https://user-images.githubusercontent.com/51883647/146655096-39a7cfda-155f-4f47-8618-9fa3db5d83fc.png)

Here is the groups.yaml file (saved as a text file so I could attach it)
[groups.txt](https://github.com/nielsfaber/alarmo/files/7739936/groups.txt)

**Comment by jfl304b** [comment]
Sorry - I accidentally closed this

**Comment by nielsfaber** [comment]
Thanks for sharing your config.

This group is pointing to itself, it causes problems:
```
sleep:
#  view: true
  name: Bed State
  all: true
  icon: mdi:bed
  entities:
    - binary_sensor.sleepnumber_sleepnumber_p6_jim_is_in_bed
    - binary_sensor.sleepnumber_sleepnumber_p6_stacy_is_in_bed
    - group.sleep
```

I'm fairly confident that if you remove group.sleep from it and reload the groups, the actions page in alarmo is restored.
Nonetheless I will try to implement a way to detect this case.

**Comment by jfl304b** [comment]
That was the problem - Thank you!  I commented out the - group.sleep line, reloaded and it works!
