### ISSUE TITLE
Actions not executing after notification

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#359]
### Alarmo Version

1.8.1

### HA Version

2021.12

### Bug description

Hi,

Just working through making sure the alarmo based alarm system now works.  Having updated alarmo, I have found the some issues. These things are new. I did have it working on a much older version. First issue:
1. The sirens don't turn on if I have my phone message sent. This message stops execution of the Actions (see error below):
![image](https://user-images.githubusercontent.com/1751192/147043519-2900abcf-e794-40ee-a83f-4f25c8dfacc4.png)
in yaml:
![image](https://user-images.githubusercontent.com/1751192/147043556-ad9eae16-68a1-4b4e-b69e-ed97747b90fa.png)

My phone messages come through fine though.

Please let me know what further info you need.

Thanks,
Stefan

### Steps to reproduce

Cause alarm to trigger.

### Relevant log output

```shell
Got this in the HA log (disabled the notification to phone to verify this was causing it):
Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': (None, 'armed_away', 'triggered') Traceback (most recent call last): File "/config/custom_components/alarmo/automations.py", line 111, in async_alarm_state_changed await self.async_execute_automation(automation_id, alarm_entity) File "/config/custom_components/alarmo/automations.py", line 212, in async_execute_automation await async_call_from_config( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 166, in async_call_from_config await hass.services.async_call(**params, blocking=blocking, context=context) File "/usr/src/homeassistant/homeassistant/core.py", line 1449, in async_call processed_data = handler.schema(service_data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['data']
```

**Comment by nielsfaber** [comment]
> ​voluptuous.error.MultipleInvalid: extra keys not allowed @ data['data']

This error suggest that the action itself (service call) set up with a wrong configuration and cannot be executed.
It seems you have set up the action in YAML mode and it contains a parameter `data`, which was not expected.

Could you post the configuration of this action?
Your bug report suggest it is not the notification but the automation used for switching the siren (the task that was skipped).

**Comment by stefanolson** [comment]
> On my instance, the actions are executed after mobile notification.

Yes, seems to execute the phone notification and stop. No phone notification and the siren action works.

**Comment by stefanolson** [comment]
> Could you post the configuration of this action? Your bug report suggest it is not the notification but the automation used for switching the siren (the task that was skipped).

This is the notification yaml here:
service: notify.mobile_app_stefans_s20_ultra
service_data:
  message: 'The alarm is triggered! Cause: {{open_sensors}}.'
  title: Alarm is triggered

This is the siren yaml (which works when phone notification is off):
- service: switch.turn_on
  entity_id: switch.internal_siren_triggered
  service_data: {}

or something else? Can't see any other yaml.

**Comment by Eyco1981** [comment]
> Yes, seems to execute the phone notification and stop. No phone notification and the siren action works.
I meant, that it works as expected for me and I wasn't able to reproduce the problem.
You should share the configuration in yaml format, as nielsfaber requested.

**Comment by nielsfaber** [comment]
Configuration of both actions look OK to me.

I tried reproducing your scenario, for me there is no problem sending both a notification and turning on a switch when the alarm is triggered.

I think Alarmo handles automations in the order they are created, i.e. if the notification was set up before the task for turning on the siren, they are executed in that order.

The fact that either task seems to be working OK as long as the other is disabled also makes it difficult to pinpoint. This already suggest that nothing is wrong with configuration of either task.

At this point I don't have any clue what causes the problem you are facing.
I don't know how to help. 
Did you try re-creating the tasks, see if the issue remains?
Did you find any other pattern leading to this issue?

**Comment by stefanolson** [comment]
Ok, so I removed the notification and removed all actions. Recreated the notification and now works with no errors. I have no idea what happened. But it appears to be resolved, so I'll close this. For future reference for anyone else, the recommendation would be to delete the notification and try again.
