### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by wdwithmp** [nielsfaber/alarmo#36]
Hi mate, I have tried all the install methods given but "AlarmO" does not show on the left panel once HA is restarted. I had a manual alarm setup in configuration.yaml which I commented prior to installing "AlarmO" 

I am running the latest version of HA
Operating System
Ubuntu 20.04.1 LTS
Docker version
19.03.12

most likely I am doing something wrong, but any help will be great

**Comment by wdwithmp** [comment]
was the same issue as another ticket opened, so closing this

**Comment by nielsfaber** [comment]
Did you add Alarmo in HA Configuration -> Integrations?
This step is often missed (especially by HACS users).
And clearing browser cache will sometimes also do magic.

**Comment by wdwithmp** [comment]
Hi Mate, the 1st part I did, but i needed to clear the cache on my chrome browser, but I also stopped all my automations as per the comment from another ticket that i was going through. I don't think it was my automations as mine was not as advanced as the one in that ticket, so I feel it was the cache 

thanks for the awesome add-on and the replay
