### ISSUE TITLE
Smoke detector not triggering

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#361]
### Alarmo Version

1.8.1

### HA Version

2021.12

### Bug description

This was working very recently. But now when a smoke alarm trips it is no longer triggering the alarm

### Steps to reproduce

Fire smoke at a smoke alarm.  e.g:
![image](https://user-images.githubusercontent.com/1751192/147044297-e06eb83e-a7c2-4a79-8f2a-74ea49a1a965.png)

Check that it is active and home assistant

Note that it is not triggering the alarm.

Let me know if you need any further information.

**Comment by Eyco1981** [comment]
My environmental binary sensors trigger the alarm as expected. Have just checked my instance. Maybe a configuration issue?

**Comment by nielsfaber** [comment]
Can you click on the smoke sensor and check if it is assigned to an area?
If you have this sensor set up before support was added to Alarmo for multiple areas, it might be not assigned to any area, therefore not triggering any alarm.

**Comment by stefanolson** [comment]
Yes, that was it.  But they were only added in the last couple of weeks. The original ones still had an area but the new ones didn't have any area. Is it possible to have some sort of indication in the UI that they won't work without an area?

**Comment by nielsfaber** [comment]
Added some visual aids.

In sensor overview page:

![image](https://user-images.githubusercontent.com/16861605/149558301-872adb48-a801-4818-99ae-e0b9875f3797.png)

And on the sensor configuration page itself:

![image](https://user-images.githubusercontent.com/16861605/149558334-28fe011b-1c44-40d4-b0a7-d5f4dc336834.png)

**Comment by stefanolson** [comment]
Thanks. Looks Great!
