### ISSUE TITLE
Sound support

### ISSUE THREAD

**Issue by edwRoland** [nielsfaber/alarmo#362]
As an FireHD10 user i want to have the possibility to configure sounds for the various alarm states in order to hear the alarm or the arming states.

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Add sound configuration for the various alarm states and play them if the state occur.

**Comment by nielsfaber** [comment]
How do you play sound on your tablet from HA?
Is there some service (for media_player entity or similar) which you can use to play a sound or how does that work?
I don't run HA on a tablet so I have no experience with this.

**Comment by edwRoland** [comment]
That's a good question >.< The FireHD10 has speakers and the HA companion app only describes the possibility with notifications https://companion.home-assistant.io/docs/notifications/notification-sounds. I've tried notifications text, sound, TTF but no luck on the FireHD10. No notifications where shown. Works for my Galaxy S10 tough...

But shouldn't it be possible to add some Javascript Code to play predefined URL wav/mp3/ogg sounds? -> https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_audio_play. Those wav/mp3/ogg files could be stored on the HA installation www folder and later be referenced.

**Comment by snickers2k** [comment]
@nielsfaber i think this is still one of the most important missing features of alarmo. i don't know any alarm-system that is working without audio-feedback.

i think this should working fine using text-to-speech for almost every device like tablets, raspberrys, sonos, hifi-systems etc.
