### ISSUE TITLE
Limit the action to specific arm modes

### ISSUE THREAD

**Issue by calz64** [nielsfaber/alarmo#365]
### Alarmo Version

v.1.8.1

### HA Version

2021.9.7

### Bug description

Hi I would like to report this bug. When limit action mode is selected (es: Night Armed), push notification in case: 'Alarm is disarmed' does not occur. Push notification sends all Alarm is disarmed messages, for example also those set by armed_away

**Comment by nielsfaber** [comment]
This is not a bug. In disarmed state there is no arm mode (the alarm is not armed anymore). 
I could maybe hide the field in case disarmed is selected, to make it more clear.

**Comment by calz64** [comment]
OK thanks. Therefore only one notification is possible in disarmed state.
