### ISSUE TITLE
Trigger time & Actions condition for environmental sensors 

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/alarmo#366]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

As see no way to reopen closed issue - creating new one with reference on existing.

### Proposal

Add mode "Disarmed" (or with another name) in General->Modes with only "Trigger time" to be defined and used for environmental etc. sensors, active in all "Arm modes" (aka "(Always)").

F.e. Xiaomi implement so called "Basic Guard" - for environmental sensors, which active always, independently from Armed% modes.

As well as in Actions: would be nice to have conditions:
* on sensor type (ref. #321, #155)
* and add "Disarmed" choosable in "Mode" condition.

_Originally posted by @Masterz69 in https://github.com/nielsfaber/alarmo/issues/326#issuecomment-1008281514_

**Comment by nielsfaber** [comment]
I'm sorry about the closed requests. I do agree that there is a need being able to create dedicated actions for fire/water leak alarms.
On the other hand, I am wondering whether such sensors really belong in Alarmo, or it's better to treat these with separate automations/blueprints. 
What is the added value for having them inside Alarmo, if their behaviour (triggers+responses)is completely different from the rest?
Just thinking out loud..

**Comment by Masterz69** [comment]
As far I see around: lot of alarm/security solutions include environmental sensors inside.

Fire/smoke sensors/alarms included in home security solutions approx. always. 
My old DSC panel have fire sensors, as well modern revisions allow to add water leak sensors.

Solutions like Xiaomi, Samsung & Hubitat Elevation as well include all threats in Home Security. 

IMHO see no dramatic difference.
Just sensors, which armed always - just missing possibility to react differently.

"added value" is more happy Alarmo users :)

**Comment by nielsfaber** [comment]
I understand your point.
The main issue I see currently is with assigning different delay times.
Alarmo is configured with exit/entry/trigger times per arming mode, so for away/home/night etc., I guess you are aware of that.

In case the system is in `armed away` an environmental sensor can be triggered. 
The question is whether it is appropriate to use:
* the entry times and trigger times corresponding to the away mode, or
* special times which are for environmental alarm.

Ofcourse also an environmental sensor can be triggered while the system is disarmed.
Here I think the best (and only option is:
* special times which are for environmental alarm.

What do you think about this?

**Comment by Masterz69** [comment]
As far I see in known to me implementations for "Armed Always" aka environmental sensors:
Status = always Enabled; Exit & Entry delay non-applicable as always Enabled; Only Trigger Time is applicable.

Just triggered by water leak sensor. As I see - it stay triggered till manual (or by sctipts etc.) disarm.
As for me - it is completely fine. As a bonus - configurable Trigger Time for "Disarmed" mode.

Only missing right now - notifications in "Disarmed" mode.
Tried to create notification & remove all Modes from Condition - all modes appears again.
Despite Mode condition is (optional) - can't create w/out modes sepcified.

Probably just add "Disarmed" in Actions Mode filter.

**Comment by nielsfaber** [comment]
Let's follow-up on this feature in the discussion I made for this: https://github.com/nielsfaber/alarmo/discussions/496
