### ISSUE TITLE
Different Entry Delays for Different Sensors

### ISSUE THREAD

**Issue by Xebozone** [nielsfaber/alarmo#368]
### Proposal
Advanced settings on sensors to set different entry trigger delays

### Additional info
For example on the garage door, I'd like the alarm to set entry delay to 1 minute instead of the default (20 seconds) as the door takes a long time to open.

**Comment by nielsfaber** [comment]
Delays are not set on a sensor, but on the alarm itself.
If you want different delays for your garage door, you could assign it to a dedicated area (with its own timings) or use a [template sensor](https://www.home-assistant.io/integrations/template/#binary_sensor) to delay the opening state.
