### ISSUE TITLE
[Feature Request] - change feature: Trigger alarm only when 2 or more sensors are triggered

### ISSUE THREAD

**Issue by Aldaran** [nielsfaber/alarmo#375]
### Checklist
- [ ] I checked for similar existing requests (both open and closed) before posting. (Found the original topic and even another request. This is a continuation of thema...)
- [x] My request is generic, other users may benefit from it too.

The sensor grouping feature works great, but it also has a severe limitation. When creating a group by selecting several sensors, you cannot create a new group with a part of the same sensors.
<s>You should also pay attention to the fact that when you have a group turned on, you cannot change the choice in another mode (arm_away/arm_night, etc.) to some specific sensors... including the single sensors we need.</s>

For example, after creating a group with opening sensor #1 and motion sensor #1, it is impossible to create a group with motion sensor #1 and motion sensor #2... So you cannot distribute sensors by virtual zones (without creating a new alarm_panel's via addon in Areas menu) and modes (arm_away/ arm_night, etc.).

Thanks for your work.

**Comment by nielsfaber** [comment]
The goal of the sensor grouping is to reduce the risk of false triggers due to a glitch in a (motion) sensor.
I don't see the benefit of having a sensor included in more than one such group, at least not for serving the intended goal.
What are your reasons for wanting this?

**Comment by Aldaran** [comment]
> The goal of the sensor grouping is to reduce the risk of false triggers due to a glitch in a (motion) sensor. I don't see the benefit of having a sensor included in more than one such group, at least not for serving the intended goal. What are your reasons for wanting this?

Ok, I partly agree with you. It can be said that this is a resolved issue, but then I see my problem in that I cannot use a group of sensors or one sensor in another mode (for example, the arm_away mode serves to protect the whole house and my territory, but arm_home should only work to protect my territory and entrance doors), I have to create another alarm_panel because of this (you have it implemented exactly like this through areas (+ master alarm_panel) and 'Edit Sensor' does not actually participate in configuring various modes)...
