### ISSUE TITLE
Superuser being able to override changeby

### ISSUE THREAD

**Issue by alheureux88** [nielsfaber/alarmo#379]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Proposal
Similar to: https://github.com/nielsfaber/alarmo/issues/288

I would like a be able to create a new type of user (superuser?) that allow to override the "changeby" (or a possibly a new field?) to any string when called via the service. 

My main reason for this, is that I already do user management using keymaster (https://github.com/FutureTense/keymaster). Key master user management is pretty advance and it allows me to create, enable, disable, schedule, users. I then use the z-wave lock to disarm alarmo when an user unlock the door.

I use the changeby data to in other automation too (for notifying/emailing/tts).

Issue 288 would be covered by this implementation too, allowing a new "automation" super-user that is able to add more information on what triggered the arm/disarm of the alarm.

**Comment by bugs181** [comment]
In my use-case, I too use Alarmo as if it's coming from "automation". I.e. using NFC tags inside node-red to disarm the alarm. It's STILL a user that is using the device but then we lose meaningful use of the `changed_by` label. Also, I have an external Ring v2 keypad that controls Alarmo from inside node-red. I felt the lack of features and "blueprint" provided by `ImSorryButWho` was a great start but I needed more and wanted to bring all of my devices into Node RED.

**Comment by nielsfaber** [comment]
I don't completely understand the request.
I suppose this feature is related to the `alarmo.arm` and `alarmo.disarm` services?
Currently you can provide a `code` with the service and it will be used to find the corresponding user, which will be set as `changed_by` property.
I understand it's nice to identify that the arming was done by an automation/application rather than user, but for this case I would propose to add a (dedicated) user to alarmo (with its own code) such that it can be identified.
What am I missing?

**Comment by alheureux88** [comment]
Hey nielsfaber, the problem is that I don't really want to know it was triggered via automation, I just don't want all my automation to be filled with user code that need to be kept in sync by adding/removing/changing them.

For example, right now, I have door lock code (user such as a maid) that can only be used on Thursday between 9am and 12am. I want alarmo to get disarmed by her unlocking the door with her code and my automation sending her code to alarmo. Easy enough but that means, I have to keep in sync the door code with user in alaramo user. 

I wish that I could pass in the user id to overwrite changed_by in the case that a super user code (something like a system user maybe) was used.
