### ISSUE TITLE
Change arm modes language.

### ISSUE THREAD

**Issue by wilotas** [nielsfaber/alarmo#381]
Hi,

I have HA in english buy i usually use spanish for my notifications (my parents do not speak english) but i can not change the language for these alarm modes.

Is possible to set it anyway?

Thanks

### Checklist
- [ ] I checked for similar existing requests (both open and closed) before posting.
- [ ] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]

### Additional info
[some example of how the new functionality should look like]

**Comment by nielsfaber** [comment]
The arm mode is translated to the language you have set up in  HA.
You can manually set a different language by modifying the wildcard.
Example: `{{arm_mode|lang=es}}` will give Spanish translation. 
See [here](https://github.com/home-assistant/frontend/tree/dev/translations/backend) for the list of language options in HA.

**Comment by wilotas** [comment]
Thank you @nielsfaber 

I tried that format but the interface behaviour is strange. Once I set it i can not enter to edit message agina. I saw this option in the menu:

![image](https://user-images.githubusercontent.com/513370/153090310-bc2719de-f2de-459b-bb92-8a4ef94cc1e9.png)

I see only "English", how can I add Spanish to this selection?

Regards
