### ISSUE TITLE
Integration not showing in integrations after HACS intallation

### ISSUE THREAD

**Issue by Zkaning** [nielsfaber/alarmo#387]
### Alarmo Version

1.8.3

### HA Version

2022.2

### Bug description

Installed the HACS integration several times and no problem accrued during that step.
All files is in the custom_component/alarmo folder
But the ALARMO do not show up in  Configuration/Integrations/Add integrations...
(yes, I have restarted several times)

![image](https://user-images.githubusercontent.com/59538251/152798021-0237a2db-8df7-45dd-bfea-445756cddb46.png)

### Relevant log output

```shell
Nothing relevant in the logs
```

**Comment by nielsfaber** [comment]
The logs should print:
> We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

If this is not the case, the installation is not OK.
If this is the case and it doesn't show up in integration --> clear your browser cache.

**Comment by Zkaning** [comment]
Thanks,
clearing my browser cache did the trick :)

BR // Fredrik
