### ISSUE TITLE
Error 400: extra keys not allowed @ data['name']

### ISSUE THREAD

**Issue by VBPix84** [nielsfaber/alarmo#391]
### Alarmo Version

v1.8.3

### HA Version

2022.2.1

### Bug description

Hey !

I installed Alarmo with manual installation, without HACS, and It works !

After that i did this : Delete Alarmo, install HACS, reinstall Alarmo via HACS.

Now, i have lot of bugs, I don't know why...

First : When i try to add a sensor extra keys not allowed @ data['name']"
![2022-02-08 18_18_03-Window](https://user-images.githubusercontent.com/59825412/153040467-3c453c71-f9fc-4f61-9822-ad3c603b556c.png)

Second: Echec d'appel du service "alarm_control_panel/alarm_disarm". 'NoneType' object has no attribute 'format'
it happens when i turn off the alarm...

Third : Nothing works when i press "reload" in configuration/alarmo...

Someone have an idea if i broke something and what i can do ?

Tks !

**Comment by VBPix84** [comment]
There is something to remove for Manuel reinstall? I did it but there are always some error :(

**Comment by nielsfaber** [comment]
> Alarmo Version
v1.8.3

Please make sure to run v1.8.4 else I cannot help you.
In case you have installed v1.8.4, but the Alarmo pages still say v1.8.3 (in the top right corner), empty your browser cache.

> First : When i try to add a sensor extra keys not allowed @ data['name']"

I cannot help you with this unless you can  provide steps to reproduce it.

> Second: Echec d'appel du service "alarm_control_panel/alarm_disarm". 'NoneType' object has no attribute 'format'
it happens when i turn off the alarm...

This is a identified bug and a patch has been made, see https://github.com/nielsfaber/alarmo/issues/390

> Third : Nothing works when i press "reload" in configuration/alarmo...

Nothing is supposed to happen, what would you expect it to do?

**Comment by VBPix84** [comment]
Hello !

I completly deleted HACS (i think) and I downloaded Alarmo v1.8.4. I duplicated the folder in my HA custom_component, and there it is :
![2022-02-08 21_49_27-Window](https://user-images.githubusercontent.com/59825412/153073210-dda559da-0cdf-4ded-a251-3bd3476a1d6b.png)

For now, unfortunatly, after a home assistant reboot, I can't see it : 
![2022-02-08 21_47_47-Window](https://user-images.githubusercontent.com/59825412/153073425-8db2fb0e-8ae9-4ff0-b0ab-5cdb80731fe0.png)

I will try to fix it for now...

**Comment by nielsfaber** [comment]
@VBPix84 Empty your browser cache.

**Comment by VBPix84** [comment]
Hello !

I made changes from another computer. There is, for now, one bug : Alarm master doesn't work.

I have 2 aera (Rez-de-chaussée and Etage) and checked for master alarm.

alarm_control_panel.rez_de_chaussee : Works (armed, disarmed, etc).
alarm_control_panel.master : nothing happen when I click on "Arm".

I seen a v1.8.5, i will update and try.

**Comment by nielsfaber** [comment]
@VBPix84 This Github issue is going nowhere, so im closing it.
