### ISSUE TITLE
Error disarming...

### ISSUE THREAD

**Issue by wilotas** [nielsfaber/alarmo#393]
### Alarmo Version

1.8.3

### HA Version

2022.2

### Bug description

Hi, 

I just tried to DISARM my alarm via my Master zone and I retrieve this:

![image](https://user-images.githubusercontent.com/513370/153092272-8fc01dd5-a43b-4809-a5de-2accf59642e4.png)

How can I fix it?

It has been working perfeclty during weeks.

**Comment by nielsfaber** [comment]
Duplicate of #390
