### ISSUE TITLE
Problem adding sensor after update

### ISSUE THREAD

**Issue by kdutton1964** [nielsfaber/alarmo#395]
### Alarmo Version

185

### HA Version

2020.2.5

### Bug description

Cannot move sensor to active from list of sensors.

### Steps to reproduce

I uninstalled and reinstalled after issue in actions not having any drop downs.
When attempting to add sensor to active receive error

### Relevant log output

```shell
Logger: homeassistant.components.http.data_validator
Source: components/http/data_validator.py:57 
Integration: HTTP (documentation, issues) 
First occurred: 10:01:53 PM (10 occurrences) 
Last logged: 10:09:45 PM

Data does not match schema: extra keys not allowed @ data['name']
```

**Comment by nielsfaber** [comment]
Please make sure the Alarmo panel says 'v1.8.5' in the top right corner.
The error you are getting suggest this is not the case.
You need to empty your browser cache if the panel version is not up-to-date.

**Comment by kdutton1964** [comment]
Fixed clearing cache did the trick… Better than ever Thank you!
