### ISSUE TITLE
After failing to arm alarm, send event ALARMO_RETRY_ARM result in unknown alarmo state

### ISSUE THREAD

**Issue by dsantos21** [nielsfaber/alarmo#396]
### Alarmo Version

v1.8.3

### HA Version

2021.2.5

### Bug description

After failing to arm alarm, retry (event ALARMO_RETRY_ARM) results in unknown alarmo state (if there's still pending sensors).

### Steps to reproduce

1. Leave some sensor blocking arm activation;
2. Execute arm alarm (will fail due to open sensor);
3. While keeping an open sensor, send ALARMO_RETRY_ARM;
4. Alarmo will report unknown state to home assistant.

**Comment by nielsfaber** [comment]
Thanks for reporting this. I am seeing the same problem here.
I will investigate and get back to you.

**Comment by dsantos21** [comment]
Thank you for helping all of us and for this great project! Just recently, few days ago, discovered this, before I was trying to do all by myself with "thousands" of Home Assistant automations... :-)

Let me know if I can help.

**Comment by nielsfaber** [comment]
This is fixed by updating to v1.8.6.
