### ISSUE TITLE
User code change notifications

### ISSUE THREAD

**Issue by ervwalter** [nielsfaber/alarmo#397]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I would like a way to subscribe to changes in user (code changes).  I have zwave smart locks on my doors that have keypads to unlock the doors.  I would like to keep the user codes for the smart lock in sync with the user codes in Alarmo as they get changed so that each user has one code that both unlocks the door and disarms the alarm system.  

Currently, I have found no way to get the user codes _out_ of Alarmo via an automation.  

### Additional info
One solution would be an event that is raised by alarmo when a user code is changed.  This would allow an automation to react to that and pass the new code along to the appropriate downstream devices that need to know about the change.

For security reasons, this would probably be disabled by default and would be an option people would have to opt-in to.

**Comment by nielsfaber** [comment]
I am reluctant to have Alarmo send out codes, since I think they should be handled as secret.
Also I believe this request is too specific to add to Alarmo, I expect you will be the only one using this.
Are you changing codes regularly? What is your use-case for the 'syncing' functionality?

**Comment by ervwalter** [comment]
I understand your hesitation, and it's not the end of the world if this isn't something you are ok doing.

My use case is simply to guarantee via automations that the codes for my locks always match the codes to my alarm.  I let my daughter change her own code whenever she wants. Currently, I have an automation for when she changes here door code, I get a notification and then go manually update her alarm code.  It's not super time sensitive since she has only changed her code a twice since I started using alarmo.

I currently store door codes in a helper entity, so not secure at all if someone gets into HA.  But given that if someone gets access to HA, they don't need my codes to unlock doors, they can just unlock them by manipulating the lock entities, and while they can't disarm alarmo without the codes, they can effectively neuter the automations that run when alarms are triggered.  Given that, I already have my HA server locked down fairly well (MFA, etc).

Having the ability to use the alarmo as the source of truth for codes (which are stored much more securely) would let me get rid of those helpers as I would just ephemerally send the new codes to the door locks in the moment that they change and then never store them outside of alarmo.  And I _have_ to send the codes to the locks because the way the smart locks work is that they have their own local copy of the codes that are used when someone tries to unlock (which is helpful since that means they work even if HA connectivity is lost).

I suppose the opposite direction (a service that let me set an alarmo user code) would let me keep them in sync, but would just have different security implications for alarmo and would mean I still have the codes in plain text.

In any case all that is explaination just because you asked.  I can certainly understand if the answer is "no".
