### ISSUE TITLE
Unable to add water leak sensors to Alarmo

### ISSUE THREAD

**Issue by stcbus** [nielsfaber/alarmo#398]
### Alarmo Version

1.8.3

### HA Version

2022.2.5

### Bug description

When I try adding my sensors from the sensors page, I get the below error:

```
Something went wrong!
Message format incorrect: extra keys not allowed @ data['name']

Response error: 400
```

### Relevant log output

```shell
Logger: homeassistant.components.http.data_validator
Source: components/http/data_validator.py:57
Integration: HTTP (documentation, issues)
First occurred: 2:26:08 PM (3 occurrences)
Last logged: 2:26:27 PM
Data does not match schema: extra keys not allowed @ data['name']
```

**Comment by stcbus** [comment]
<img width="1078" alt="Screen Shot 2022-02-11 at 2 29 19 PM" src="https://user-images.githubusercontent.com/3802410/153657059-c806feba-1e5a-42bd-8942-1b3c35776046.png">

**Comment by nielsfaber** [comment]
clearing your browser cache should fix this
