### ISSUE TITLE
Entry delay not working

### ISSUE THREAD

**Issue by tonicb78** [nielsfaber/alarmo#399]
### Alarmo Version

1.8.5

### HA Version

2022.2.6

### Bug description

Hello,

Entry delay seems broken, when any sensor is triggered, alarm is also triggered without waiting the delay.

It is my first time alarmo installation, so could be something I misunderstood.

Very nice integration congrats to devs.

Thanks!

### Steps to reproduce

Config any entry delay.

Arm alarm.

Trigger a sensor.

Check if alarm is directly triggered without respecting the entry delay.

### Relevant log output

```shell
Nothing in the log.
```

**Comment by nielsfaber** [comment]
Entry delay is **not** broken.
This is just user error.

Make sure to turn this on:
<img src="https://user-images.githubusercontent.com/16861605/153720705-98088915-e9a1-4428-8036-3518501274cf.png" width="50%" height="50%">

<img src="https://user-images.githubusercontent.com/16861605/153720736-672119c7-bf74-4c76-9bf0-dac54075c3b1.png" width="50%" height="50%">
