### ISSUE TITLE
 Add option to invert the logic of binary sensor

### ISSUE THREAD

**Issue by TEF2one** [nielsfaber/alarmo#402]
Add option to invert the logic of binary sensor to trigger the alarm.

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Add option to invert the logic of binary sensor to trigger the alarm.

### Additional info
I have a generic contact sensor for my gate which is normally true when closed and would land currently require a dedicated template binary sensor to invert the logic in order to be supported by Alarmo.
having the ability to choose the default state or alarm state of a sensor would help support a wider range of sensors.

**Comment by nielsfaber** [comment]
Alarmo follows the [definitions](https://www.home-assistant.io/integrations/binary_sensor/) from HA for binary sensors.
A sensor is active in the ON state. If your sensor does not follow this, you will need to invert it somewhere else.
