### ISSUE TITLE
error when adding sensor:  extra keys not allowed @ data['name']

### ISSUE THREAD

**Issue by jtonk** [nielsfaber/alarmo#403]
### Alarmo Version

V1.8.5

### HA Version

2022.2.6

### Bug description

error when adding sensors. 
```

Something went wrong!
Message format incorrect: extra keys not allowed @ data['name']

Response error: 400
```
this happens on all types of sensors.

### Steps to reproduce

select a sensor in the Alarm panel sensor section -> add to alarm

error message

Something went wrong!
Message format incorrect: extra keys not allowed @ data['name']

Response error: 400

**Comment by nielsfaber** [comment]
Empty browser cache.
