### ISSUE TITLE
Missing STATE_ALARM_ARMED_HOME for Homekit

### ISSUE THREAD

**Issue by Gloomyeye** [nielsfaber/alarmo#407]
### Alarmo Version

v1.8.5

### HA Version

2022.2.9

### Bug description

Hello,

If I only expose the domain "Alarm Control Panel" within the homekit integration, I got an error log entry (see below). I created an issue in home assistant core for that issue: [#67020](https://github.com/home-assistant/core/issues/67020)

The response of the homekit integration owner for that issue is:
"The custom integration is not setting supported_features correctly at startup.
It is missing STATE_ALARM_ARMED_HOME so HomeKit never adds it to the list of valid values."

Therefore, the custom integration alarmo should set up the supported_features for HomeKit correctly. If I add the alarmo entity to Homekit, all functions are working. However, every home assistant startup shows errors.

### Steps to reproduce

1. Install alarmo integration
2. Activate the domain "Alarm Control Panel" within the homekit integration
3. Restart home assistant

### Relevant log output

```shell
Logger: pyhap.characteristic
Source: /usr/local/lib/python3.9/site-packages/pyhap/characteristic.py:210
First occurred: 05:57:10 (2 occurrences)
Last logged: 05:57:10

SecuritySystemCurrentState: value=0 is an invalid value.
SecuritySystemTargetState: value=0 is an invalid value.
```

**Comment by Gloomyeye** [comment]
@nielsfaber : Something new or may I help you with further information?

**Comment by nielsfaber** [comment]
I don't consider this a bug.
In Alarmo you can change the arm mode settings (including enabling and disabling them) on-the-fly, so the supported_features is a property that may change at any time.
I think changes are required in the Homekit integration to allow for this. 
It seems a bad design assumption that the supported_features property only has to be read once on startup, it will lead to things being out of sync.

**Comment by nielsfaber** [comment]
I did some local testing with Homekit today.
I added some instructions and limitations in the documentation, see: https://github.com/nielsfaber/alarmo#apple-homekit.
For the issue with Homekit and the `supported_features` during startup, I made a small workaround. I will add this change in the next release, it should improve things for you.
Unfortunately, there are quite some limitations which are outside of my control. As said before, I think that the Homekit integration in HA needs to be improved for giving a better user experience.

**Comment by Gloomyeye** [comment]
Thank you very much! I'm happy when the error message will disappear at startup.

**Comment by nielsfaber** [comment]
This function is added to v1.8.7.
Please test it out, you can close the issue if your problems are solved now.

**Comment by Gloomyeye** [comment]
Hi @nielsfaber, thanks for taking care of the issue. However, I must say that the issue is not solved with the v1.8.7. Same error occurs after restart of home assistant.
My testing follows these steps:

1. I restartet the system with activated alarmo entity in homekit -> Error occurs
2. I deactivated the domain "Alarm Control Panel" within the homekit integration and restarted the system -> No error message
3. I added only the domain "Alarm Control Panel" within the homekit integration (no active alarmo entity in homekit) and restarted the system -> Error occurs
4. I added the alarmo entity to homekit and restarted the system -> Still error message

**Error message:**
Logger: pyhap.characteristic
Source: /usr/local/lib/python3.9/site-packages/pyhap/characteristic.py:210
First occurred: 13:34:49 (2 occurrences)
Last logged: 13:34:49

SecuritySystemCurrentState: value=0 is an invalid value.
SecuritySystemTargetState: value=0 is an invalid value.

**Comment by nielsfaber** [comment]
I don’t know how to help any further.
The Alarmo implementation is OK as far as I know.
 In my tests, the available modes in HomeKit match with the Alarmo configuration (but restarting HA is required to sync changes).

**Comment by Gloomyeye** [comment]
Do you have the same errors when you restart HA? Shall I uninstall Alarmo and start fresh to correct the issue?
Other idea is to activate more options, because I don‘t activate mode home my config. But is this needed?

I could raise the log level for alarmo, but this it not the best way, I think.

**Comment by Gloomyeye** [comment]
After activating the home mode in alarmo, the error vanished. So, now I have away, home and night mode activated. It looks like that home mode must be activated for HomeKit.

**Comment by nielsfaber** [comment]
As said, I think the implementation on Alarmo's side is OK.
I am also seeing these errors when disabling the mode `home` in Alarmo:
> 2022-04-02 09:07:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemTargetState: value=0 is an invalid value.
2022-04-02 09:07:22 ERROR (MainThread) [pyhap.characteristic] SecuritySystemCurrentState: value=0 is an invalid value.

They disappear in case it is enabled, so my conclusion is the same as yours.
I think that your issue in Home Assistant core was judged poorly, the problem/limitation is on their side (or even Homekit itself).

**Comment by Gloomyeye** [comment]
Okay, thanks. Looks like that at least this option must be activated. Maybe a hint to the alarmo HomeKit documentation can be added that with the current HA Version this is needed. 

From my side this issue can be closed.
