### ISSUE TITLE
Sensor in multiple groups

### ISSUE THREAD

**Issue by Patrick1610** [nielsfaber/alarmo#408]
### Proposal
I would like the possibility to add a sensor to multiple groups. Some areas or sensors are part of multiple zones. Since some are only active when away, others also when asleep I need to make multiple groups with some of the same sensors in it.

**Comment by Brausmith** [comment]
I've been pondering the same, but with an extra feature included. 

Let's consider two groups that share a common motion sensor. It could be two door sensors, one on either side of the house, and a motion sensor between the doors. 
It would almost always be the door sensors that would be activated before the motion. The door sensors in this example would be the primary sensor in the group.

The primary sensor of a group would be considered the first sensor that has to be activated, before the others in the group that then trigger an alarm.

Having said all that, I'm new to Alarmo, so I might be asking for something that is not widely seen as a good security requirement.
