### ISSUE TITLE
Logbook 

### ISSUE THREAD

**Issue by ecard0** [nielsfaber/alarmo#413]
### Alarmo Version

v1.8.5

### HA Version

2022.3

### Bug description

Logbook does not report the changed by attribute when armed/disarmed from mqtt alarm panel.  The attribute is updated but not published in the logbook

**Comment by nielsfaber** [comment]
The logbook is maintained by HA internally.
I do not know if (and how) it’s possible to influence the data which is shown here.

**Comment by ecard0** [comment]
Interesting, that if I arm my system directly in HA, it shows the all the information :(   But not if I call it from mqtt.
