### ISSUE TITLE
I can't set the delay anywhere

### ISSUE THREAD

**Issue by Melvin6328** [nielsfaber/alarmo#418]
### Alarmo Version

v1.8.6

### HA Version

2022.3.1

### Bug description

I would like to set the delay but if I want to open the menu nothing goes up or anything else as seen in the picture. 
![Screenshot 2022-03-06 223104](https://user-images.githubusercontent.com/64102918/156942981-8afd9bd4-7e05-4df2-8776-8408d9407d54.png)

**Comment by nielsfaber** [comment]
Are you sure you are on version v1.8.6?
Is that shown in the top right corner as well?
The problem you are describing should be solved in the latest update.

**Comment by culiflaqui** [comment]
I have updated the version but it keeps putting v1.8.5. I have uninstalled it, I have downloaded the latest version from the page and it keeps telling me that I have version 1.8.5. Where can I download the new version 1.8.6?
