### ISSUE TITLE
Blueprint Keypad Synch not working anymore

### ISSUE THREAD

**Issue by TLongstride** [nielsfaber/alarmo#421]
### Alarmo Version

v1.8.6

### HA Version

2022.3.3

### Bug description

Hi

The blueprint I used for my keypad doesn't work anymore with recent update.

I post on the forum here : https://community.home-assistant.io/t/zigbee2mqtt-sync-keypad-and-alarm-control-panel-states/345311/30

@nielsfaber have you an idea ?

Thanks 
TLongstride

**Comment by nielsfaber** [comment]
try the alarm_control_panel.alarm_disarm (or alarm_arm_away) manually.
If this works OK I guess the blueprint has an issue.
I didn’t change anything regarding this functionality recently..

**Comment by TLongstride** [comment]
Thanks for your answer !
It doesn't work, nothing appen when I call manually ..

**Comment by nielsfaber** [comment]
Are you using alarmo card? If so, which error message is shown?
Otherwise, what do the logs say?

**Comment by TLongstride** [comment]
Yes y used Alarmo Card from HACS. Nothing in the logs..

The issue seems to be solved :
- I remove alarmo card from HACS Component
- Restart
- Create new card with Alarmo Card (Yes, was again present instead of removed it ..)
- Manual command works great
- Remove cache in webrowser
- Alarmo Card replace by an error message
- Install Alarmo Card From HACS
- Try again manualy command

And it works. I don't have explanation

Thanks for your help !
And thanks for the excellent job you've done with your custom_componement !
