### ISSUE TITLE
New notification - Title does not support {{open_sensors}}

### ISSUE THREAD

**Issue by githubpassera** [nielsfaber/alarmo#428]
### Alarmo Version

v1.8.7

### HA Version

2022.3.6

### Bug description

For Android TTS notification "Message" needs to be set to TTS and "Title" to the spoken text. Title does not support {{open_sensors}} or {{arm_mode}}

### Steps to reproduce

service: notify.mobile_app_galaxy_s22_ultra
service_data:
  message: TTS
  title: 'The alarm has trigger {{open_sensors}}.'

**Comment by nielsfaber** [comment]
This is not a bug, this is how it is designed.
