### ISSUE TITLE
Low battery notification

### ISSUE THREAD

**Issue by Sag06** [nielsfaber/alarmo#43]
Alarmo is working great here. I moved HA alarm related notifications to Alarmo notifications.  I tried them and I think they're working nice. Armed, disarmed, leaving, opened sensor and so on. It seems there's only one kind of notifications I can´t get rid of: "Low battery sensor". I have fire sensors and door sensors that send a specific 433MHz code when low batt reached.  I know I could assign them as "always" but they should trigger alarm as hard as it home were burning, which can be heart dangerous. I would suggest a feature request to another "always" sensor category to assign a low level notifications service as target . In my case it is a telegram group with only a bip sound.

**Comment by nielsfaber** [comment]
Wouldn't it be sufficient to create an automation outside of Alarmo for this?
I also have a low-battery notifier running in AppDaemon, but personally I have no desire to link it to Alarmo.

**Comment by Sag06** [comment]
Yes. It is sufficient. That is the way I have it . It was only a suggestion to improve Alarmo. But automation outside Alarmo is easy and working.  May I know something more about your low-battery notifier? Mine is only a telegram notification for each battery sensor.

**Comment by nielsfaber** [comment]
Whoops I said it wrong.
I had issues that the battery level reported by my sensors was not reliable (jumping up and down between 20-50%), so my notifier script became spam to myself.
So I recently moved to AppDaemon to make a script that keeps checking that a sensor changes state on a regular basis (for motion sensors, every day that we are home, for window/door sensors depending on their location).
The result of this script is that I am able to catch a dead (important) sensor within a day.

**Comment by Sag06** [comment]
I see...
I don't think my motion sensors (433MHz) send low-batt code although motion detected red led keeps on. My fire and door sensors do, but it's just a single 433MHz code when a low voltage is reached. No battery level. So, it's quite easy here with automation outside Alarmo.

**Comment by nielsfaber** [comment]
Conclusion: not in scope for Alarmo currently.
