### ISSUE TITLE
Cannot modify the different modes in the general section of control panel

### ISSUE THREAD

**Issue by dcf1999** [nielsfaber/alarmo#430]
### Alarmo Version

1.8.7

### HA Version

2022.3.7

### Bug description

This is hard to explain. When I try to modify each mode (Armed away, Armed Home, etc..) it won't display each mode to modify. 

On my other instance of home assistant (at a summer home) it works fine. The instance for my house it doesn't. When I go to the general section of the alarm panel and click on the arrows next to the modes, it should drop down with the different options. It doesn't do that. The down arrow just turns to an up arrow. If I click again, it goes back to a down arrow but no drop down shows up. 

I tried removing Alarmo from home assistant and re-install it and still no joy. 

### Steps to reproduce

Clicking different modes.

**Comment by nielsfaber** [comment]
Please check if the Alarmo version v1.8.7 is actually shown correctly in the top right corner.
If not, you need to clear the browser cache to solve the problem.

**Comment by dcf1999** [comment]
ok so when I first had the problem I was remoting into home assistant via NabuCasa. When I got home from vacation, I opened it locally and everything worked. I did not have to clear the browser cache to fix it. It also did display v1.8.7 in the corner.
