### ISSUE TITLE
Ability to add custom alarm modes such as "nap" mode or "guest" mode

### ISSUE THREAD

**Issue by liquidbear99** [nielsfaber/alarmo#432]
Hoping to add a few custom alarm modes such as a "nap" mode or "guest" mode (just like the vacation mode).
Even being to add multiple custom_bypass modes and rename them would be great!

**Comment by nielsfaber** [comment]
Alarmo only provides the modes which are supported by HA.
See [here](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#states).

Obviously the `custom` mode can be used as you desire. In the alarmo-card you could rename it so it appears as a `guest` mode or similar. I'm afraid that's all I can do.
