### ISSUE TITLE
Inputs and dropdowns are not working

### ISSUE THREAD

**Issue by jdtoth** [nielsfaber/alarmo#433]
### Alarmo Version

v1.8.7

### HA Version

core-2021.9.7

### Bug description

None of the text inputs or dropdowns are responding in any of the Alarmo forms (example attached). You cannot focus them and they don't appear to be visible. Tested in both Chrome and Edge.

I don't see anything in HA error logs but I do see a warning in Chrome Inspector:

The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.f08a72d3.js:5264

![example](https://user-images.githubusercontent.com/3156868/160973832-9f55b91c-096a-46c4-91d1-f0312e89f309.jpg)

**Comment by nielsfaber** [comment]
See release notes:
> v1.8.6
**Important**
This release requires HA 2022.3. Things may break for you in case you run an older version.
