### ISSUE TITLE
Cannot Enter Text To Create User

### ISSUE THREAD

**Issue by royaltongue** [nielsfaber/alarmo#439]
### Alarmo Version

v1.8.7

### HA Version

2021.11.4

### Bug description

Cannot create new user, as there are no textboxes for `Name` or `Code`.

I've tried clearing the cache of browser (Edge), using a different browser (Firefox), and using the HA app on my phone, all show the same thing

### Steps to reproduce

* Install Alarmo from HACS
* Enable Alarmo in Integrations
* Try to create new User in Alarmo

**Comment by nielsfaber** [comment]
Is the correct version number displayed in the top right corner of the Alarmo panel?

**Comment by royaltongue** [comment]
Yep, v1.8.7

**Comment by royaltongue** [comment]
Issue resolved after updating Home Assistant to latest version.

FWIW, when going to install from HACS, Alarmo v1.8.7 does not have a warning about minimum HA version like Alarmo v1.8.6 does. 
Can that warning be added all future releases?

**Comment by nielsfaber** [comment]
> FWIW, when going to install from HACS, Alarmo v1.8.7 does not have a warning about minimum HA version like Alarmo v1.8.6 does.
Can that warning be added all future releases?

I indeed added this setting in v1.8.6 such that users of HA < 2022.3 would see v1.8.5 as latest release, users with newer HA version would see v1.8.6.
Unfortunately this setting is not version-dependent in HACS. In other words, anyone in HA < 2022.3 would see that Alarmo (as a whole) is not compatible with their HA version. HACS doesn’t show the latest compatible version instead.

**Comment by royaltongue** [comment]
Ah, hm, well that's a bummer.

Hopefully people can at least find this post if they run into the same problem
