### ISSUE TITLE
Not all MQQT commands work

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#44]
I am trying to set up Mqtt at Alarmo.
I can get the state with several clients and disarm the alarm, but I can not arm_away or arm_home with them.
I have tried with MQTTLens, which is an addon for Chrome and some kind of Mqtt sniffer and lets you to send commands to the subscribed topics. I have also tried with the Android app MQTT Alarm Control Panel and I get the same behaiviour.
It works for disarming but not for the two disarming modes.

**Comment by nielsfaber** [comment]
Can you share which payloads you used, and which you configured in the MQTT configuration?

**Comment by tremebundo** [comment]
<img width="460" alt="alarmo" src="https://user-images.githubusercontent.com/35578150/100543782-79606680-3252-11eb-9c36-0cf0544ac487.PNG">
<img width="893" alt="MQTTLens" src="https://user-images.githubusercontent.com/35578150/100543784-79f8fd00-3252-11eb-83e2-c86b80b271b1.PNG">
In that case, when I publish "disarm" through MQTTLens to "alarmo/command", it disarms (if armed). But it does nothing when I publish "arm_away" or "arm_home"

**Comment by nielsfaber** [comment]
I must say I have the same problem here.
It seems to work only if your alarm doesn't have an arm code enabled (in the 'codes tab) AND the 'require code' setting in MQTT is ON.
Which is a weird combination.

I will have to investigate to find out where this goes wrong.
Please give me a couple of days, i need to find the time to work on a new release.

**Comment by tremebundo** [comment]
Thanks a lot for your interest an quick response.
Take your time.

**Comment by nielsfaber** [comment]
I found the problem and fixed it.
Will try to make a release for it soon.

**Comment by nielsfaber** [comment]
Updating to v1.3.2 should fix this problem.
Please close the issue if the problem is solved after the update.

**Comment by tremebundo** [comment]
Just installed and working beautyfully.
Thanks.
