### ISSUE TITLE
Alarm Triggers sometimes 

### ISSUE THREAD

**Issue by Ajax-online** [nielsfaber/alarmo#441]
### Alarmo Version

 v1.8.7

### HA Version

2022.4.2

### Bug description

Pir sensor pickup motion sometimes after arming but after few arming and disarming it does not trigger. 
- Tried the sensor with lights it pick up all the time also have tried different semsor including Hue and Tuya 
- using Tuya currently 
- Thank you 

### Steps to reproduce

- Tried the sensor with lights it pick up all the time also have tried different semsor including Hue and Tuya 
- using Tuya currently

### Relevant log output

```shell
tHANK
```

**Comment by nielsfaber** [comment]
Is this a problem with Alarmo or a problem with the Tuya sensor?

**Comment by Ajax-online** [comment]
Hello Thank you for your reply. 
Looks like Alarmo Sensors works ok on TUYA app 

Ajay
