### ISSUE TITLE
Multiple zones alarms

### ISSUE THREAD

**Issue by Ryckie** [nielsfaber/alarmo#442]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
It would be good to have the alarm to be able to trigger for multiple sensors in a row instead of only for the first sensor that triggers. If let's say the garage pir triggers the alarm. It may be a faulty detector due to a spider. If then the hallway sensor and living room sensor also picks up and triggers the alarm. We can be sure there is something happening. 

### Additional info
Instead of showing only the first sensor to trigger the alarm, show all additional sensors that trigger after. And have a way of sending this in a notification.

**Comment by nielsfaber** [comment]
This is already implemented via [sensor groups](https://github.com/nielsfaber/alarmo#sensor-groups).
In a sensor group, 2 or more sensors need to be triggered in a row before the alarm is triggered.

You can set this up here:
<img src="https://user-images.githubusercontent.com/16861605/163504937-c3436d4e-b579-4c41-bdb2-258f78c47cc7.png" width="75%" height="75%">

**Comment by Ryckie** [comment]
It says that two or more sensors must be activated in order to trigger an alarm. This is not what I was suggesting. It should trigger the alarm with 1 sensor. But send new alarms for extra sensors triggered when the status is allready at triggered. 
![Screenshot_20220415-053607_Home Assistant](https://user-images.githubusercontent.com/63733138/163514324-26787c43-29c0-44ea-b3ea-922bc3549172.jpg)

**Comment by Ryckie** [comment]
Would be nice if you can re-open my feature request.

**Comment by gkyprios** [comment]
I agree that this would be useful. At the moment I am only notified of the first trigger but not any subsequent triggers until the alarm resets back to Armed. Knowing all triggered devices would be useful and assist with determing whether there has been a false positive, or there is someone moving through the house.

**Comment by Ryckie** [comment]
I'm afraid they closed this and won't look at it anymore. And I don't understand why. Having worked multiple years for a security company, I know how often and easily there are false triggers. And I'm speaking of companies. Who hire professionals to install their alarm system. With home-assistant, this is 99% of the time done by people who have no clue or experience installing alarm sensors. Who points pir sensors at the windows and so on. Especially in the summer with the A/C on etc there are many false alarms due to moving shades etc. It's really a need to have a function to be notified at the first detection, but also for every single detection following after that. Whether the alarm is in an armed or triggered state. It also gives you a better idea of the situation.
