### ISSUE TITLE
Notification upon arming optionally to issue when countdown begins

### ISSUE THREAD

**Issue by esackbauer** [nielsfaber/alarmo#443]
I have a delay of 60 seconds after I set to armed state. My voice assistant is being notified with "Alarm activated" only after the delay is done.
However it would be nice to get some feedback instantly, e.g. "Alarm will be activated soon" or something just when I activate.
Reason is, that else I don't know if the keypress on my keyfob actually has activated the alarm, or I would have to wait for 60 seconds and listen then.
So such a kind of feedback would be great.

**Comment by nielsfaber** [comment]
It is already possible to configure a notification to be sent when the exit or entry delay starts. This should serve your needs.

**Comment by esackbauer** [comment]
Yes I found it now, sorry for the confusion.
