### ISSUE TITLE
Triggered open sensor

### ISSUE THREAD

**Issue by ramonalbertov** [nielsfaber/alarmo#444]
Please add another easy way to determine which "open sensor" triggered the alarm, directly from the Alarmo interface action configuracion or by MQTT message.

**Comment by OscarParzon** [comment]
I also need to decide based on the sensor that fires the event

**Comment by nielsfaber** [comment]
The request is not clear to me.
The following is in place:
* In the alarmo interface you can configure a notification to be sent when alarm triggers, and use the 'open sensors' wildcard to show which sensor(s) caused the trigger.
* In the MQTT interface you can subscribe to the event topic, and you will receive the 'trigger' event with JSON payload including the sensor(s) which caused the trigger.
* In HA there is the alarm_control_panel entity which has the open_sensors attribute containing information of the sensors in case the state is 'triggered'.

What is missing?

**Comment by OscarParzon** [comment]
> 
Yes. Yes!... I always said it: I only know that I don't know anything...

I'm gonna check it.
The intention is to execute a specific script according to the sensor that is open.
Thank you very much for your help.

**Comment by OscarParzon** [comment]
Well!... Yes, Yes, in the "Notifications" option I have the possibility to send the information of which is the open sensor (or which is the sensor that triggered the alarm). In the "Actions" option I have no way of knowing which is the open sensor.
Yes, I can find another way to obtain the information, but it is always adding more lines to the script or doing more laps that waste time (in the execution of the script).
I think it's a good idea to have the option to decide what to do in the same Alarm settings panel.
I try to write a usage idea:

Notification:
Alarm: "triggered"
is armed_home
is "sensor 1" send message 1 and photo 1
is "sensor 2" send message 2 and photo 2
etc...

Action:
Alarm: "triggered"
is armed_away
is "sensor 1" run "script 1"
is "sensor 2" run "script 2"
etc...
in this case each of the scripts looks for the appropriate photo and sends a whole message and photos using Telegram.

For my use case, today I am using the status of the sensors directly from HA, I can't find a quick way to do it using Alarmo. (always thinking "quickly execute the code").

I use, today (without Alarmo):
For when I'm home:
Perimeter alarm:
Message with the photo of the area.
Particular sound in a speaker.

When I am away from home:
Alarm:
Telegram message is sent to a group.
The message includes:
Photo of the area that triggered the alarm (Photo 1 or Important)
Photos of each of the remaining areas (Extra photos).
Link iP to the Live Cameras Panel.
Telegram buttons:
Turn on Siren - Request Photo of x Zone - etc...

I am very sorry that I don't have time to play Alarmo files and give you a better idea.

A hug.
