### ISSUE TITLE
Google home gives error, but alarm does arm

### ISSUE THREAD

**Issue by DarrenSanders123** [nielsfaber/alarmo#448]
### Alarmo Version

V1.8.7

### HA Version

2022.4.7

### Bug description

when saying to google to arm the alarm, it returns sorry something went wrong with "alarm" but in homeassisant it did arm.

same with disarm, the code panel stays, and eventually it says that something went wrong.

(im using the cloud method)

### Steps to reproduce

tell google to disarm XXX alarm

**Comment by nielsfaber** [comment]
Yeah I have the same problem in my house.
Also had this issue before Alarmo existed.
I believe the problem is that Google home doesn’t support an exit delay.
At night I do arm night and it always works OK.
I’m not sure if anything can be improved from alarmo’s side.

**Comment by KSchmeeds** [comment]
I see this as stale, but I'm also having this issue.

I'm not sure how the integration works with Google when commanding it to a state, but maybe this can be resolved by having it expect an arming or armed state instead of just armed.  This might need to be fixed in home assistant upstream though.
