### ISSUE TITLE
second condition in the "actions" tab

### ISSUE THREAD

**Issue by mDieli** [nielsfaber/alarmo#449]
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
The option to use a second condition in the "actions" tab for both "Notifications" and "Actions" besides the alarm event. 

### Only send the notification/run the action when:
    - an specific input_boolean is in the "on" state
    - time or date condition is met
    - etc

**Comment by nielsfaber** [comment]
You can use the standard automations in HA for this.
I don't have plans to make a full duplicate of the automations functionality that HA has.

**Comment by OscarParzon** [comment]
> 

Hello. Thank you for your great work.
Regarding your previous answer. Yes, everything can be done with HA, even an alarm system.
Perhaps many of us are looking for a place to unite all the configuration of our alarm system.
Having more options in Alarmo helps and simplifies.
😀
