### ISSUE TITLE
YAML Editor appears to lose edits?

### ISSUE THREAD

**Issue by davebeckster** [nielsfaber/alarmo#45]
Love your creation, thank you for your efforts.  I'm a user, not developer, so "operator error" is likely, but I am having trouble getting my messaging edits to "stick".  Simply trying to add "type: tts" in YAML editor.  It works (messages make it to ECHO device) but the addition seems to disappears in next edit.  Am I missing something?

**Comment by nielsfaber** [comment]
I'm not sure what you mean.
Could you share some screenshots or something?

**Comment by davebeckster** [comment]
Your release today appeares to have solved the issue.  When adding a
notification action for an alexa.media.echo, I got it to work by using the
YAML editor to add "type: tts". I saved it and it worked, however when I
attempted to edit the action later the type: tts did not show up although
it still worked.  Today, with the new release, the type: tts shows up.
 Could be a newby issue but it was repeatable.  Your  project has allowed
me eliminate several beginner troublesome, difficult to maintain scripts
and automations.  You are appreciated. Appears this one should be closed.

**Comment by nielsfaber** [comment]
I didn't change anything in v1.3.2 regarding actions/notifications.
But if all seems to work now, that's cool.
Anyway, let me know if you have issues again.

**Comment by davebeckster** [comment]
Not yet a request, but perhaps you have a solution that I haven't
recognized.  I have a person with disabilities requiring uncomfortably long
leave/entry times for away mode.  For the potential situation of an
intruder, is there an accessible flag/boolean that i could use at the time
of the event to take actions.  Perhaps turn-on/view cameras or check which
sensor triggered the event (garage door - relax,  bedroom  window - pay
attention).

**Comment by davebeckster** [comment]
Yes, still there.  I'm not proficient enough to assist you in debug.  Try
adding a message to an Amazon Echo media player, get it to work and later
(causal event unknown, perhaps HA restart) and you will find the yaml you
added is no longer there and the message no longer works.
