### ISSUE TITLE
Relay/Switch as a Sensor

### ISSUE THREAD

**Issue by goybar** [nielsfaber/alarmo#450]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
Add a switch/relay to sensor group

### Additional info
Traditional dry contact door/window (NC/NO) sensor connected to a relay.  (example: Zooz Zen17/Zen16)

A NC door/window contact has a state of "on".  When contact is broken Relay goes into an "off" state.

**Comment by nielsfaber** [comment]
In HA, a switch is an _actuator_, which implies that you can set the state to on/off.
This does not apply to a door contact, it should be configured as binary_sensor in HA, meaning you can read the state instead of setting it.
I think the issue is with your configuration, nothing should be changed in Alarmo.

**Comment by goybar** [comment]
I guess it is a relay.  
   
   - 2 Dry Contact or 12-24 V inputs to monitor HVAC systems, magnetic door sensors, or analog leak alarms (use either dry contact or 12-24 V input for R1 and R2 at a time, never apply voltage to the Sw terminals).
It also reports the opposite of my Z-wave door/window contacts.
"On" means Normally Closed state...  When reed sensor is broken (door opening) the relay reports "off"
I'm creating additional automations that will work with Alarmo and this relay.
Thank you for creating Alarmo it is great.  You more elegantly did things I was attempting and failing to do.
Chris    On Sunday, May 1, 2022, 02:20:02 AM EDT, Niels Faber ***@***.***> wrote:  
 
 


In HA, a switch is an actuator, which implies that you can set the state to on/off.
This does not apply to a door contact, it should be configured as binary_sensor in HA, meaning you can read the state instead of setting it.
I think the issue is with your configuration, nothing should be changed in Alarmo.
