### ISSUE TITLE
Mode "vacation" not UI selectable in service "Alarmo: Arm"

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#451]
### Alarmo Version

v1.8.7

### HA Version

2022.4.7

### Bug description

In the script/automation editor the mode "vacation" ist not selectable when using the service "Alarmo: Arm".
By editing YAML it can be used.

### Steps to reproduce

Create an automation, script or use developer tools and select the service "Alarmo: Arm".

**Comment by nielsfaber** [comment]
Yes this issue is known and already fixed a while ago but no release has been made since.
I will try to make a release soon.

**Comment by nielsfaber** [comment]
This should be fixed by updating to v1.9.0.

**Comment by Teh-max** [comment]
Alarmo Version
v1.9.4
HA Version
2022.05.3
Mode "vacation" not UI selectable in service "Alarmo: Arm"

**Comment by Eyco1981** [comment]
![Screenshot_20220625-073827_Home Assistant.jpg](https://user-images.githubusercontent.com/88980079/175760126-f0977781-8ec2-42ae-9c49-0aad8d04cadc.jpg)
I can choose them perfectly fine in 1.9.4 .
Have you tried refreshing the browser cache?
