### ISSUE TITLE
Bug: Adjustments to an existing sensor group results in an error. Adjustments not saved.

### ISSUE THREAD

**Issue by Schmackos** [nielsfaber/alarmo#452]
### Alarmo Version

v1.8.7

### HA Version

2022.4.7

### Bug description

Initial creation of sensor group works. When making adjustments to an existing sensor group the following error is presented.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/13638083/166237852-46409e4f-7790-4711-b0d5-72cd28c9c700.png">

**Comment by nielsfaber** [comment]
Can you provide steps for reproducing the issue?
For me there is no problem modifying a existing group.

Initial group configuration:
<img src="https://user-images.githubusercontent.com/16861605/166405514-08cc96bc-bb55-4f95-9321-8f14e567d9fc.png" width="75%" height="75%">

Coming back later and adding some more:
<img src="https://user-images.githubusercontent.com/16861605/166405551-f5e810c2-f4b1-4f36-8a60-da39b81cac22.png" width="75%" height="75%">

Result:
<img src="https://user-images.githubusercontent.com/16861605/166405588-5b0f0ccc-3b88-4ff6-909b-a74a5331050b.png" width="75%" height="75%">

What am I doing different than you?
