### ISSUE TITLE
State in script not pulling correctly?

### ISSUE THREAD

**Issue by Geniusness** [nielsfaber/alarmo#454]
### Alarmo Version

1.8.7

### HA Version

2022.4.7

### Bug description

I have a script that runs when the alarm is triggered. The script waits 30s, then checks the state condition. If it's still triggered, it will turn on a siren. The purpose is to give us time to disarm the alarm after it has been triggered without sounding the alarm.

When I run the script, the only state returned is armed_away, even when triggered, or armed_home. I have not been able to get a different state.

Executed: May 3, 2022, 6:10:14 PM
Result:
result: false
entity_id/0
Executed: May 3, 2022, 6:10:14 PM
Result:
result: false
state: armed_away
wanted_state: triggered

**Comment by nielsfaber** [comment]
I'm really not sure if something is wrong on Alarmo's side which could cause this.
Is the script configured as an action in Alarmo?
Perhaps the triggering of the script and the state change of the alarm_control_panel entity coincide?

You can enable debug logging for alarmo by adding this to the configuration.yaml of HA and restarting HA:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```
You could use it to see at which point your automation is triggered.
In the `.storage/alarmo.storage` file you could find back the ID's of the automations.

**Comment by Geniusness** [comment]
Thanks, I appreciate the reply! I'll dig in and see if I can track it down. I did have it running as an action in Alarmo. I've upgraded to HA 2022.5.1, so I may try the new If-Then action to see if it works that way.
