### ISSUE TITLE
Could you please help with this to add a Siren group under helper and recognize as a device the tuya siren BW-IS11.

### ISSUE THREAD

**Issue by CharlesGitHib** [nielsfaber/alarmo#458]
### Checklist
- [ ] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]

### Additional info
[some example of how the new functionality should look like]

**Comment by CharlesGitHib** [comment]
Add a Siren group under helper and 
recognize as a device, the tuya siren BW-IS11. Thx.

**Comment by nielsfaber** [comment]
Please use this forum thread instead: https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910
