### ISSUE TITLE
Add event for Environmental (Fire / flood) alarm triggered

### ISSUE THREAD

**Issue by JohanEikelenboom** [nielsfaber/alarmo#460]
It would be nice to have have a extra Event Condition named "Environmental Alarm is triggered" (or something similar)

### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Add an extra option in the Notifications / Actions so you can create different notifications / actions when an environmental alarm (ie fire / flood) is triggered.

### Additional info
When I'm sleeping and the alarm would be triggered (don't hope it will happen), I would like to know if it is a burgalar (so use caution / get the baseball bat / blink lights) or if it's a fire (all lights on / get out as fast as possible).

**Comment by nielsfaber** [comment]
Duplicate of #366
