### ISSUE TITLE
no disarming from MQTT AlarmPanel (Thanksmister) after last update

### ISSUE THREAD

**Issue by carpe07** [nielsfaber/alarmo#465]
### Alarmo Version

v1.9.2

### HA Version

core-2022.5.3

### Bug description

Hi,
I'm using two AlarmPanels (build on a FireTab with MQTT AlarmPanel SW from ThanksMister.
After the last update of Alarmo (1.9.2) I can't diable the alarm from these two panels? Nothing happen after inserting the code.
Switch to alarm after the code is possible!?

Any ideas?
Many thanks!

**Comment by nielsfaber** [comment]
You can update Alarmo to latest version to fix the problem.

**Comment by carpe07** [comment]
after some debugging I found this in der MQTT file (config\custom_components\alarmo\mqtt.py) found

2022-05-10 10:01:13 ERROR (MainThread) [homeassistant.util.logging] Exception in async_message_received when handling msg on 'alarmo/command': '{"command":"DISARM","code":"1234"}'
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 259, in async_message_received
    await entity.async_alarm_disarm(code, skip_code)
TypeError: async_alarm_disarm() takes 1 positional argument but 3 were given

**Comment by carpe07** [comment]
@nielsfaber : which version do you recommend? I gues I'm using the last version 1.9.2?

**Comment by nielsfaber** [comment]
There’s a 1.9.3 as well but I see now that in GitHub it is just marked as tag and not as release. I need to correct this, then it should show up in HACS.

**Comment by nielsfaber** [comment]
The v1.9.3 release should now be visible in HACS as well.

**Comment by carpe07** [comment]
Hi niesfaber,
many thanks for the quick help incl. die update! It is working again! great!
It have been a bad situation not to be able to disarm the active alarm ;-)

**Comment by nielsfaber** [comment]
Sorry about that. I was quite aware of the priority, that's why this fix was released within a day after the 1.9.2 version. Unfortunately not released properly.
Disarming via HA itself was working still so you could use it as alternative, but I can understand it's not desirable.
Anyway, case is closed now 👍

**Comment by carpe07** [comment]
Hi Nielsfaber,
no problem!! I have solved it by using the HA App and direct disarmed the alarm system....
All fine!! Great work from you!
Many thanks!
