### ISSUE TITLE
Custom armed state colors

### ISSUE THREAD

**Issue by waps11** [nielsfaber/alarmo#466]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
I noticed that multiple UI elements (some natif to HA others via HACS) are showing different color for the same armed mode. This is problematic as some turn green to mean armed while others turn blue and this is confusing to end users. To help solve this small mess Alarmo should make available to the UI a specific color per alarm state. Then, themes and UI elements could/should pick it up and adapt around this user choice. This could also benefit colorblind users as a side effect.

### Additional info
Some sensible default should be proposed :
- Triggered : Well everbody knows that red is bad so this one is easy 
- Disarm could be green meaning that some sensors are still active (smoke detectors, leaks, etc...)
- Armed (all flavour) should be some blue to recall protection (I often see red used here but red is a distressfull color and should be avoided in this context)
- Arming/pending should be yellow or orange to recall construction workers
- (completely) Disabled should be some dark grey or whatever global color means disabled in HA

Its obvious but colors should be unique to each state and somewhat limited to prevent ambiguity

Cheers

**Comment by nielsfaber** [comment]
I think this is a very opiniated request, I don't agree with you on all aspects.
For me it is not possible to influence the colors as shown in the HA UI.

The only place where I can influence colors is the alarmo-card.
I don't know if your request is intended for alarmo-card specifically, if so you are posting in the wrong place.
If you're referring to HA generically, you are also posting in the wrong place.

Let's consider alarmo-card for now.

Currently alarmo-card implements the following:
```
        --alarm-color-disarmed: var(--label-badge-green);
        --alarm-color-pending: var(--label-badge-yellow);
        --alarm-color-triggered: var(--label-badge-red);
        --alarm-color-armed: var(--label-badge-red);
```

The actual colors are defined in the the theme installed by the user (obviously, by default green=green etc.).
In case of color-blindness it is very much possible to replace all greens used in HA to another color within the theme.
I think it is also possible to assign a theme to a specific card but I have no experience this.

As far as I know, the colors used in Alarmo-card are aligned with the [HA Alarm Panel card](https://www.home-assistant.io/dashboards/alarm-panel/) and I think they are chosen appropriately.

> Armed (all flavour) should be some blue to recall protection (I often see red used here but red is a distressfull color and should be avoided in this context)

Personally I think red is a good color for the armed state.
Alarmo-card uses the blinking effect to create awareness in the triggered state.

> Its obvious but colors should be unique to each state and somewhat limited to prevent ambiguity

I don't agree on this as the badge in alarmo-card consist of a combination of color and icon. Both together should be unambiguous.
