### ISSUE TITLE
Code valid based on Google Calendar

### ISSUE THREAD

**Issue by DK-MGO** [nielsfaber/alarmo#467]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
I would like to accept a code only if a Google Calendar entry exists. This is to only accept the cleaning lady or neighbor to water the plants on days/times when I have an entry in my Google Calendar.

Perhaps by simply passing the Changed By data to Node Red.

Thank you!

**Comment by nielsfaber** [comment]
You can use the `alarmo.enable_user` and `alarmo.disable_user` services for this.
Ofcourse you will need some automation to enable a user based on the Google Calendar, this has to be done outside of Alarmo.

**Comment by DK-MGO** [comment]
Thank you, works through Node Red ;)
