### ISSUE TITLE
Serious bug with groups and different arm modes

### ISSUE THREAD

**Issue by ASNNetworks** [nielsfaber/alarmo#468]
### Alarmo Version

 v1.9.3

### HA Version

2022.5

### Bug description

So I noticed there is a serious bug when using sensors in a group and when the sensors individually are not part of the same arm mode. I noticed this a few months ago, but couldn't figure out what the issue was untill now. For instance:

I have a Doorway door sensor and a Hall motion sensor. I created a group (let's call it Entry) with a 5 minute timer. I created two arm modes, night and away. 

Night: contains only Doorway door sensor.
Away: contains both sensors. 

When night mode is active and I open the Doorway, the alarm does NOT trigger. Even if the Hall motion sensor was triggered (but it's not used as a sensor for that particular mode). My guess is that Alarmo completely ignores the Hall motion sensor because it's not used as a trigger sensor in that arm mode. And because of that the group Entry never triggers, since a part of the group get's ignored.

This forces the user to use all members of a group for a arm mode, otherwise it will simply not trigger at all. In my case I want only the door sensor to trigger during night mode (and trigger immediately) because I don't want to rely on motion inside my house. The reason I created a group is for the away mode, to prevent a false trigger from the motion sensor in the Hall (which has triggered in the past because of sudden change of heat when nobody was home).

So normally I would just say: use both sensors in the same arm modes, so there wouldn't be an issue. However, as described above, there are times where you need the group and times where only one of the sensors are prefered. In this case however, the active sensor doesn't trigger the alarm, because an other member is not used for the same arm mode.

This creates a second problem. If you decide to disable a sensor that is part of a group, then the entire group will not function. All sensors in that group will not fire the alarm, unless you remove the disabled sensor from the group. If in case you decide to disable a specific sensor, then chances are your entire alarm gets broken and doesn't trigger, unless you revise the group the sensor is part of.

### Steps to reproduce

See above

**Comment by nielsfaber** [comment]
If a sensor is part of a group, it triggers the alarm only when 2 or more sensors in that group become active in the timeframe.
This is done by design.
You shouldn’t set up a group with multiple sensors and then only assign one of them for the arming mode.

**Comment by ASNNetworks** [comment]
> If a sensor is part of a group, it triggers the alarm only when 2 or more sensors in that group become active in the timeframe. This is done by design. You shouldn’t set up a group with multiple sensors and then only assign one of them for the arming mode.

Hi, I understand. But this means it's impossible decide not to use a specific sensor for an arm mode if it's also part of the group. The issue is that even the entire group then doesn't trigger anymore. So if a sensor is part of a group, but not in the arm mode (while another member is) and that other member triggers, then the group doesn't work (even if de excluded member becomes active). So in my example it's impossible to achieve this: 

In my case I want only the door sensor to trigger during night mode (and trigger immediately) because I don't want to rely on motion inside my house. The reason I created a group is for the away mode, to prevent a false trigger from the motion sensor in the Hall (which has triggered in the past because of sudden change of heat when nobody was home).

The way it's designed currently, it blocks the entire group when excluding a member from an arm mode.

**Comment by ASNNetworks** [comment]
I see your point and I understand. I think the only way to achieve this is if groups are set per arm mode. But I'm not sure if this ideal, because then you need to create the same group multiple times if you want the group to function as it does now. The last thing I would want is to solve an one issue, that creates other issues (which in turn can snowball in to other issues/solutions loops).

If I come up with a different approach that doesn't change the way groups currently works for the majority of users, I will get back to you. I do think however that a warning should be included in the Readme somewhere regarding this. I wasn't aware so my alarm didn't trigger (luckily it was no problem since I was the 'culprit' that entered the house by mistake). But in logical sense I would assume that if I use member A and not member B of a group, that member A at least keeps working (unless I got a warning).
