### ISSUE TITLE
Alarmo Features

### ISSUE THREAD

**Issue by brandondb1** [nielsfaber/alarmo#47]
Again, an incredible tool!  Thank you very much!

A suggestion, and maybe this is already in process, but having each action have it's own duration could be good.  I have my alarm set up to run the siren for 5 minutes, but leave the lights on for 20 minutes (if lights and siren go off at the same time, it might not be enough of a deterrent, at least that's my logic).

Thank you very much for these integrations!  They are a huge upgrade to YAML-based config.

Brandon

**Comment by nielsfaber** [comment]
I would recommend to set the trigger time/duration at 20 minutes, and use a script/automation (outside of alarmo) for switching off the siren after 5 minutes.

There is currently no priority for adding timers to the alarmo actions.
I understand that it is nice to have all in one place, but this can be done in HA just fine.
I will close the issue for now (consider it as "won't fix"), feel free to ask me again in a while (if the core functionality is all in place)...
