### ISSUE TITLE
Event "Entry Delay Started" missing from drop-down list when creating a new action

### ISSUE THREAD

**Issue by bjmckay01** [nielsfaber/alarmo#470]
### Alarmo Version

v1.9.3

### HA Version

2022.5.5

### Bug description

When creating a new action, the event "Entry Delay Started" is not available in the drop-down list of events. However, choosing another event (e.g. "Alarm Is Armed") or opening and closing the list and then attempting to choose from the event list again results in the "Entry Delay Started" event being shown in the list as intended. It is only missing on the initial opening of the list.

Also, when the list is initially opened only three options are shown with a scroll bar on the side for viewing the remainder. When opening the list after the first time, the entire list is shown and there is no scroll bar.

### Steps to reproduce

Actions -> New Action -> Click in Events space

**Comment by nielsfaber** [comment]
I'm seeing the same issue here.
So initially only the first 3 items are shown, I can scroll down to see 2 more, last one (entry delay) is missing.
When opening the list a second time, all 6 items are there.

At this point I have no clue what causes it and how to solve it.
It seems to be related to the way the dropdown list element shows its content, which is out of my control.

**Comment by nielsfaber** [comment]
Finally I managed to remove the problem.
The issue should be solved by updating to v1.9.4. 
Please close the issue after confirming the problem is solved in the new update.
Make sure that you don't have an outdated version of the Alarmo GUI in the browser cache, by checking the top right corner in the GUI (it should show the version v1.9.4).

**Comment by bjmckay01** [comment]
Confirmed that 1.9.4 solves the issue. Great work and thanks for the fix.
