### ISSUE TITLE
Send notice via channel

### ISSUE THREAD

**Issue by MrGlad8** [nielsfaber/alarmo#472]
I would love to be able to send the notices through "channel" with this:

  data:
    channel: prio1
    importance: max
    persistent: true
    tag: persistent
    color: red

But when I write these into the yaml it wont save!
Its important for me since prio1 makes my phone have a special sound for that cathegory !

**Comment by nielsfaber** [comment]
I think in Alarmo you need to replace `data` by `service_data` and then it should work.
Please give it a try

**Comment by MrGlad8** [comment]
Ah! Right! thanks for quick reply :) It worked this this:

service: notify.mobile_app_sm_g780f
service_data:
  message: The alarm is set to {{arm_mode}}
  title: Hemlarm Pålarmat!
  data:
    channel: prio1
    importance: max
    persistent: true
    tag: persistent
    color: red

This way I can have a normal notive for normal notices from HA and a persistent nuclear alarm sound when prio 1 launches :)

Thanks!
