### ISSUE TITLE
Add Action for exit delay

### ISSUE THREAD

**Issue by geofffarmer** [nielsfaber/alarmo#473]
Alarmo is fantastic but I feel there is an Action (Event) missing. We have an Action for when we are in a delayed exit and the alarm is arming. (Exit Delay Started)  However, there is no similar Action for when the alarm is Pending.

Whilst it's easy to create a standard HA automation to detect the change of state to 'pending', I feel that this would be nice-to-have as standard. I use this state to cause a message to be played warning the person to deactive the alarm.

**Comment by nielsfaber** [comment]
You can use the last option in the list for it:

<img src="https://user-images.githubusercontent.com/16861605/172003538-8ad50fdc-944a-4abc-a056-314512cc22fd.png" width="75%" height="75%">

It has always been there, but recently there was a bug related to the display of the dropdown list, see here: https://github.com/nielsfaber/alarmo/issues/470. If you use the latest version of alarmo it should show up fine.

**Comment by geofffarmer** [comment]
Thank you
