### ISSUE TITLE
Add support for some alarm keypads (like the Linkind zigbee keypad)

### ISSUE THREAD

**Issue by syvanpera** [nielsfaber/alarmo#476]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
There are some zigbee keypads (the Linkind one at least) that could be made to work with alarmo. The keypads in question expose the `action_transaction` via zigbee2mqtt which could be used to add the support for these.  

### Additional info
This would require additional features for the MQTT support in alarmo. Mainly providing a way to modify the state topic payload to support the correct format used by these keypads:
```
{
    "arm_mode": {
        "mode": "arm_all_zones"
    }
}
```

When they keypad send the alarm state change message, it contains the following information:
```
{
    "action": "arm_all_zones", // This is the example
    "action_code": "123", // The code being entered
    "action_zone": 0, // The zone being armed (always 0)
    "action_transaction": 99 // The transaction number
}
```
This need to be responded to using the same `action_transaction` code as given.
The response is sent to a specific MQTT topic, so a new topic configuration would also be needed.

Additional info is available [here](https://www.zigbee2mqtt.io/devices/ZS130000078.html)

**Comment by syvanpera** [comment]
I can try to make a PR with these changes, if there is any interest in adding this feature. Otherwise I will probably just hack this together using some other method.

**Comment by syvanpera** [comment]
Ah, damn. Just found this: https://community.home-assistant.io/t/zigbee2mqtt-control-alarmo-via-keypad/420016
So I'll close this for now. If there is a way to make this work without any changes to alarmo, all the better

**Comment by nielsfaber** [comment]
I found that keypad support is rather device specific as well as platform specific (zigbee2mqtt, zha, zwave, etc).
Therefore I think it’s best to leave this out of Alarmo and fill the gap using blueprints or similar.
The blueprint you are referring to is one I made myself after buying the linkind keypad. It can probably be ported to other devices/platforms as well, although I don’t own/use these myself so I cannot test these.
Please post in the forum thread if you have suggestions or issues with this blueprint.
