### ISSUE TITLE
MQTT - optional delay parameter when arming

### ISSUE THREAD

**Issue by metronidazole** [nielsfaber/alarmo#479]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
When changing the state via MQTT (e.g. to arm), you are limited to a delay. It should be possible to provide a optional delay in the JSON struct for setting this like it is possible when calling the service.

### Additional info
e.g.
{
  "command": "<my command>",
  "code": "<my pin or password>",
  "delay": "3"
}

**Comment by nielsfaber** [comment]
The delay time for arming is fixed in Alarmo.
This is also the case when arming via a service.
I don't agree with your request.
