### ISSUE TITLE
Alarmo Action / Notification keep putting mode type even if remove

### ISSUE THREAD

**Issue by azuanaa** [nielsfaber/alarmo#480]
### Alarmo Version

v1.9.3

### HA Version

2022.5.5

### Bug description

If we create actions or notifications, the mode which limit the action to specific arm modes is optional. However, if we delete all the modes (away, home) and save the notifications/ actions, then open that notifications/ actions, the modes are not deleted.
<img width="628" alt="Screenshot 2022-05-29 at 8 04 25 PM" src="https://user-images.githubusercontent.com/47180458/170867172-4a409681-1cd9-4cff-b112-d4f69b82fd80.png">
.

### Steps to reproduce

As per bug description

**Comment by nielsfaber** [comment]
I changed this behaviour in v1.9.4.
Please close the issue after confirming the problem is solved for you after updating.

**Comment by azuanaa** [comment]
I have update to v1.9.4, while the is no longer mode to limit action / notification, however, it remove the ability to add the mode. That is the mode is no longer being save, it is the inverse of the old behaviour.

**Comment by nielsfaber** [comment]
I don't understand what you mean.

Starting from:
<img src="https://user-images.githubusercontent.com/16861605/171996285-4b8fd5a4-3e93-4884-b940-3a50aef67139.png" width="75%" height="75%">

I can add modes:
<img src="https://user-images.githubusercontent.com/16861605/171996308-be604bf1-1dc9-4544-bbbd-bfe84df29a02.png" width="75%" height="75%">

And after saving they are still there.

I can also remove one or more afterwards:
<img src="https://user-images.githubusercontent.com/16861605/171996341-ab7875d1-9a17-4af5-ae48-4f8bb8f954aa.png" width="75%" height="75%">

And save them.

What am I missing?

**Comment by azuanaa** [comment]
What happen to me after I add the modes, and save it, and when I open back the notification / action, the mode is gone. Let me try to reboot my HA, and clear my browser cache once more and report back.

**Comment by azuanaa** [comment]
I have reboot my HA host few times, restart the HA core few times. Removing the cache. Creating a new notification / actions. This is what I found out,
1. If I only have 2 modes enable in general page (say Armed Home, Armed Away), I can only save one mode in the notification/ action. If I add 2 modes, it will not save it.
2. If I only have 3 modes enable in general page (say Armed Home, Armed Away, Armed Night), I can only save 3 modes in the notification/ action. If I add 3 modes, it will not save it.

**Comment by nielsfaber** [comment]
The thing is that if you select all modes, its the same as select none of the modes (because there is nothing filtered out).
This was also the reason why previously all modes would show up by default.

The description of the field says:
> Limit the action to specific arm modes

So why would you want to assign all modes? It would not exactly be a limitation.

Anyway, I prefer to keep things intuitive for everyone. What do you see as easiest to understand?

**Comment by azuanaa** [comment]
I see the logic that you are implementing. My understanding while trying to do this, if nothing selected, means that only sensors with (Always) mode is activated. In my case, I have a panic button at home, which if push ( even when the system is not armed ) will trigger the alarm. I'm trying to implement if this is happened, it will activate certain action - which is different from the other modes.

Anyway, thank you for the great program you have created here and I love it. I think I could find way around this, which could serve the same purpose.
