### ISSUE TITLE
Open door/window still activate alarm

### ISSUE THREAD

**Issue by LucaBors** [nielsfaber/alarmo#481]
### Alarmo Version

1.9.3

### HA Version

2022.5.5

### Bug description

Hi, 
even if none of the sensors (doors or windows) are set to "bypass automatically" they are excluded when system arm both on night and away.

![image](https://user-images.githubusercontent.com/73178440/170886038-a2103e93-75d4-40ee-9973-7bccb96c2261.png)
![image](https://user-images.githubusercontent.com/73178440/170886088-269cdf37-60d7-41ac-af77-252c1b701962.png)

**Comment by nielsfaber** [comment]
Are you arming with force option active?
Otherwise the bypassing should not occur.

**Comment by LucaBors** [comment]
hi, thank you for your super fast replay. Where i can check "force option"? Thank you :)

**Comment by LucaBors** [comment]
no bug. only a config error from my side. Thank you :)
