### ISSUE TITLE
ARM NIGHT VACATION

### ISSUE THREAD

**Issue by milandzuris** [nielsfaber/alarmo#482]
### Alarmo Version

1.9.3

### HA Version

2022.5.5

### Bug description

I dont have ARM Night or Vacation, where is problem?.
![image](https://user-images.githubusercontent.com/42905545/170892296-d491ee0d-72aa-4768-b444-5bc93de6c9c3.png)
![image](https://user-images.githubusercontent.com/42905545/170892315-d00c73a4-239e-483f-8f0a-f336ea77a2d0.png)

### Steps to reproduce
Restart HA

### Relevant log output
Clear

**Comment by nielsfaber** [comment]
This is a known issue in HA, see here: https://github.com/home-assistant/frontend/discussions/11287

You can install the alarmo-card to use all modes.
