### ISSUE TITLE
Mqtt state message should be retained

### ISSUE THREAD

**Issue by zbuh** [nielsfaber/alarmo#49]
The state topic should be posted with retain, so that Keypads or other interfaces, can pick it up upon a restart.

**Comment by nielsfaber** [comment]
Agreed. I will try to change this

**Comment by zbuh** [comment]
i've been using it in the last days with success

**Comment by nielsfaber** [comment]
In that case, you could also create a PR with your changes.
I’m a bit busy at the moment. But I think it’s time for a next release soon..

**Comment by nielsfaber** [comment]
Added in v1.4.0
