### ISSUE TITLE
Latest Update (v1.9.4) now automatically disarms system after opening door to leave

### ISSUE THREAD

**Issue by the4jaggz2** [nielsfaber/alarmo#494]
### Alarmo Version

v1.9.4

### HA Version

2022.5.4

### Bug description

After latest Alarmo update, the system now automatically disarms itself after opening door to leave house.  Under "codes" in the Alarmo menu, I have confirmed that both the "use arm code" (which works fine) and the "use disarm code" are checked/activated so I don't see a reason why or how the system would be able to disarm itself automatically.

### Steps to reproduce

1) armed system using defined arm code
2) open front door/trip front door sensor to leave premises

Note: there were no issues experienced in the prior version.

Also, to be sure, I have restarted HA multiple times since upgrading to the new version.

**Comment by nielsfaber** [comment]
Is the sensor allowed to be active during the exit delay?
Else opening the door would cause the arming to fail.

**Comment by the4jaggz2** [comment]
![Screen Shot 2022-06-04 at 1 02 31 PM](https://user-images.githubusercontent.com/52387581/172017697-302460fc-4346-472c-9abd-8a7a37c8a0a3.png)

As per the enclosed, no, I ensured that was not set.

**Comment by nielsfaber** [comment]
You need to set the ‘use exit delay’ setting.
Otherwise the door may not be opened during the exit delay (which is more appropriate for windows).
This should always have been like this.
I didn’t make any (intentional) changes to the behaviour.

**Comment by the4jaggz2** [comment]
That did the trick...thanks so much for your quick responses. It makes perfect sense that it should be selected and based on the fact that the system has been working flawlessly for quite some time, I am guessing I selected that when I first set it up. How it lost that setting after the update is a mystery but I do appreciate you pointing that out and guiding me to the resolution.

**Comment by nielsfaber** [comment]
I’m happy to help. Feel free to open another issue when you see something weird or missing.
