### ISSUE TITLE
Pincode entered through UI reported invalid when entered

### ISSUE THREAD

**Issue by Peerke1** [nielsfaber/alarmo#500]
### Alarmo Version

v1.9.4

### HA Version

2022.6.0

### Bug description

using the alarmo card
created a user with a pincode and set the code format to pincode
set use arm code

when entering the pincode through the card its always marked as invalid. When unsetting the arm code it works fine
tried 1234, 123456

### Steps to reproduce

created a user with a pincode 
set the code format to pincode
set use arm code

arm the alarm entering the pincode using the alarmo card

**Comment by Peerke1** [comment]
logs shows:
2022-06-10 15:54:21 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Service alarmo.arm was called
2022-06-10 15:54:22 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Wrong code provided.

1000% sure I typed 1234 every time when it was 1234 and 123456 when it was 123456

**Comment by Peerke1** [comment]
when changing the pincode to password and enter letters all works fine.
looks like the pincode is treated as a int and not a string (found that somewhere on the HA forum).

I have done all through the UI, how should i make sure the pincode is stored as a string?

**Comment by nielsfaber** [comment]
For me all works fine. I can create a user with code 1234 or 123456, both are accepted in the card.
I cannot reproduce your problem, all suggests you entered a wrong code.

**Comment by Peerke1** [comment]
Hmm, I know it looks like a wrong code. i always tried both...

Is there a way to get/view the saved configuration of the created user?

I can modify the script to print the entered code in the log. That way i can compare the 2.

Stange thing is that when i used a password, it worked as expected.

**Comment by Peerke1** [comment]
well, i deleted the whole configuration, restarted the thing and created it again. Now its working.
Dont know what happend on the way and why the pincode changes didnt work.

thanks for replying and testing.
