### ISSUE TITLE
Weird message in log

### ISSUE THREAD

**Issue by fribse** [nielsfaber/alarmo#501]
### Alarmo Version

1.9.4

### HA Version

2022.6.5

### Bug description

When I restart HA I get this message every time:

```
Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.alarmo.alarm_control_panel
Source: custom_components/alarmo/alarm_control_panel.py:376
Integration: Alarmo (documentation, issues)
First occurred: 07.34.51 (1 occurrences)
Last logged: 07.34.51

Cannot process arm command, alarm is not initialized yet.
```

The alarm is disarmed, so why does it insist that it needs to arm, but the alarm is not yet available?
The Alarmo integration has been installed for a looong time, and I've seen this a couple of times, but haven't really noticed it until I today started moving deprecated configs into integrations and thus rebooted a ton of times.

Looking in MQTT, I've set up the state topic to home/alarm and under that it says 
`alarm = disarmed`

### Steps to reproduce

Not really sure.

**Comment by nielsfaber** [comment]
The warning suggests you try to arm the alarm right on startup of HA. 
Alarmo needs to load the configuration before it can be used.
