### ISSUE TITLE
Codes not restricted to disarm/arm only

### ISSUE THREAD

**Issue by JWynegar** [nielsfaber/alarmo#506]
### Alarmo Version

1.9.4

### HA Version

2022.6.7

### Bug description

When setting codes to only work for disarm or arm only they are still able to be used for both

**Comment by nielsfaber** [comment]
Oooff that sounds like a serious security flaw. Users should be able to rely on their settings.
I will take a look when I have some time available.

**Comment by nielsfaber** [comment]
I made a fix for this problem (https://github.com/nielsfaber/alarmo/commit/d976d0a5213a1d3c9acd0775f2ef8aace710657f) and tested it locally.
The next update will include this fix. 
I will let you know when it is released.

**Comment by nielsfaber** [comment]
Version v1.9.5 is released and should fix this problem.
Please update your alarmo version and test whether the issue is indeed solved.
You can close the issue if so, otherwise please let me know.
