### ISSUE TITLE
Alarm no longer controllable

### ISSUE THREAD

**Issue by Aephir** [nielsfaber/alarmo#510]
### Alarmo Version

v1.9.4

### HA Version

2022.6.7

### Bug description

I can no longer control the Alarmo (has been working for months).

If I try, I get no errors (except if I try, then I get a `arm night`, then I get a `Failed to call service alarm_control_panel/alarm_arm_night. Entity alarm_control_panel.alarmo does not support this service`; I've added the logs about this below, in case it's relevant), but nothing happens. This is regardless of whether I try from the alarm card in, or `services` tab in developer options.

I can see that it worked last night when we were out (automatically armed/disarmed via AppDAamon script). But today, nothing. 

I haven't updated Home Assistant since arriving home. The only thing I can think of that I have changed, is that I added one additional user with a pin code in the alarmo config just now. And when I tried to show how it worked, it didn't. I have also updated and rebooted my system (Ubuntu server with HA in a VM) but I doubt that's relevant?.

Any idea what's going on? I currently have seven users defined in alarmo config, and I haven't changed any other config options since it worked last night.

### Steps to reproduce

1. Have Alarmo set up and working in HassOS running in VM on Ubuntu Server
2. Update/upgrade Ubuntu Server
3. Add one user with a pin code
4. Restart system a few times during this (to update secrets loaded for AppDaemon, that uses pin codes found there to make service calls to arm/disarm alarm)
5. Try arming either via alarm card in frontend, or via a service call in developer tools (or via service call from the AppDaemon script that worked yesterday).
6. If trying `arm night`, it gives an error in the logs, other things do not, they just don't do anything.

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:657
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:33:55 (4 occurrences)
Last logged: 14:35:33

[140224948360192] Entity alarm_control_panel.alarmo does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 657, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.alarmo does not support this service.
```

**Comment by Aephir** [comment]
After having struggled with this for an hour, left it for another 4-5 hours, and trying again, it does react to arming/disarming from UI.

Not that I am any wiser about what happened, but I assume troubleshooting could be difficult for now?

**Comment by nielsfaber** [comment]
The error is generated by HA itself, not Alarmo.
I don't know how it is concluded that the service is not supported.
I assume you have the mode 'night' enabled in the Alarmo configuration panel?

You can also check the supported_features in the entity (in Dev Tools -> States).
E.g. my `alarm_control_panel.alarmo` entity has:
> supported_features: 31

which is composed of 16 + 8 + 4 + 2 + 1.
You can see [here](https://github.com/home-assistant/core/blob/0e1f368b6f020a08530ccb1f0a29b04a27f84ab3/homeassistant/components/alarm_control_panel/const.py#L26-L34) that this means that supported services are:  ARM_HOME, ARM_AWAY, ARM_NIGHT, TRIGGER, ARM_CUSTOM_BYPASS.
