### ISSUE TITLE
Not able to add a user.

### ISSUE THREAD

**Issue by Carlito876** [nielsfaber/alarmo#511]
### Alarmo Version

version v1.9.0

### HA Version

Home Assistant 2021.11.5

### Bug description

After selecting "Code" enable "Use disarm code" >> "New User" the page loads to the option for "Create new user" but there is no field to enter "Name, code, confirm code". 

So I'm basically stuck at this point. 

Please Help!

### Steps to reproduce

Setting Alarmo Panel

**Comment by nielsfaber** [comment]
You need to update HA to use Alarmo.

**Comment by Carlito876** [comment]
What are the steps to update please? 

I don’t have the supervisor option.

**Comment by nielsfaber** [comment]
See https://github.com/nielsfaber/alarmo#updating
