### ISSUE TITLE
not able to Add sensors

### ISSUE THREAD

**Issue by lokaelmo** [nielsfaber/alarmo#512]
### Alarmo Version

v1.6.2

### HA Version

2022.6

### Bug description

When trying to add sensors, an error dialogue appears, saying;
Something went wrong!
Message format incorrect: extra keys not allowed @ data['name']

Response error: 400

Please [report](https://github.com/nielsfaber/alarmo/issues) the bug.

**Comment by nielsfaber** [comment]
Update Alarmo to 1.9.4 please.
Clear your browser cache if the version number shown in the Alarmo panel is outdated.

**Comment by lokaelmo** [comment]
Thanks, it worked
