### ISSUE TITLE
User code enhancements for notifications and actions

### ISSUE THREAD

**Issue by mririgoyen** [nielsfaber/alarmo#521]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
There is currently the ability to add a "Changed By" placeholder in Notifications, but I would like to see more control around this.

Specifically, I don't want to receive notifications every time I or my partner disarms the alarm. But I do when my guest or kids codes are used. I also want a "panic code," which would be a special user/code we would be able to enter under duress that would disarm the alarm like normal, but trigger a very specific workflow of notifications or actions that would alert neighbors, family, or authorities that there is a big problem without alerting someone standing at the keypad.

My proposal is to add a conditional based on the user who entered their code that allows an action or notification to be triggered.

**Comment by snickers2k** [comment]
+1
codes should result in "event: armed/disarmed by person XY". 
this way we can do lots of things, like welcoming that person by name, triggering presence for that person and so on
