### ISSUE TITLE
Warning alarm

### ISSUE THREAD

**Issue by Dinth** [nielsfaber/alarmo#522]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
It would be nice to have a "trigger warning" mode of the alarm, similarly to how car alarms work. For example, if just one of the alarm sensors is triggered, Alarmo could switch on the siren for 3 seconds and only trigger a full alarm if another sensor is tripped. 
### Additional info
Potentially an extra, optional feature would be an option to choose for each sensor if it should set off a warning or go to the full alarm immediately.

**Comment by snickers2k** [comment]
+1
maybe with two options for full alarm
- time based
- two sensor based

also helpful for (accidentally) opening a window while armed
