### ISSUE TITLE
Notification - allow executing services other than notifier

### ISSUE THREAD

**Issue by Dinth** [nielsfaber/alarmo#523]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Right now, the notification settings only allow selecting a notifier service, even when i go to YAML mode and manually change the service to other (for example zwavejs.set_value) im getting an error and cannot save the notification.
It would be nice to be able to use different services as notification - not only performing zwave actions, but it would also be possible to make play a sound on a speaker or use TTS.

**Comment by nielsfaber** [comment]
Could you share your YAML code?
This sounds more like a bug than a feature request.
The notification editor should natively support `notify` and `tts` services (although custom settings have to be done via YAML), others are configurable via YAML mode.
The editor should not block you from creating a custom action.
