### ISSUE TITLE
bind/associate alarmo-device to specific exit-delay-door

### ISSUE THREAD

**Issue by snickers2k** [nielsfaber/alarmo#524]
**Problem**
leaving the frontdoor does not notify about an open backdoor.
resulting in
.- unclosed backdoor
.- disabled arming after exit delay finished, because of open sensor.

**Request**
bind specific alarmo-device to specific exit-delay-door

**Result:** 
frontdoor-keypad allows for frontdoor exit-delay, but shows that the backdoor is not closed. and vice versa.

---

Right now, sad to say, in my opinion, this makes Alarmo almost completely useless for households with more than one door.

**Comment by snickers2k** [comment]
i guess a simple option under device-specific options for a door-sensor would be great.
used for exit delay: Y/N
used for entry delay: Y/N
`associated alarmo device: XY`

**Comment by nielsfaber** [comment]
I'm sorry but your request is not clear to me.
I have no idea what you mean with 'bind specific alarmo-device to specific exit-delay-door'.
I'm not aware what an alarmo device is.
In alarmo, the exit delay is not linked to a certain door, instead it's a setting configured for a certain mode.

If you don't want to have a message of open back door at the end of the exit delay, you have 2 options:

1. Configure the backdoor as not allowed to be open during the exit delay
2. Configure remaining part of the exit delay be skipped upon closing the frontdoor (so arming would fail immediately)

**Comment by snickers2k** [comment]
sorry to not have made it clearer.
lets say i want to exit via frontdoor, i use the display(or ring-keypad in my case) (which i refer to alarmo-device.. so the device which triggered alarmo). 
right now, i have an exit delay for frontdoor and backdoor. because sometime's i leave the house via frontdoor, and sometimes via backdoor. but if i leave the house via frontdoor, i do not get notified about the unlocked backdoor - because it also has an exit delay. 

so i wish alarmo can be notified about where i leave the house, and notify me about the unused door if unlocked. 
so that the exit delay works only for the door next to the device that just has triggered alarmo.

**Comment by nielsfaber** [comment]
I understand what you're trying to achieve.
But it is not easy to obtain this in Alarmo.
The alarm panel/display is external from Alarmo, there is no knowledge of the origin where the arming command came from.
In addition, there is no way to customize sensor settings based on the origin of the command.

As said before, i recommend to set the 'arm on close' setting for your frontdoor and backdoor, such that you will get a notification of an unlocked door before the exit delay has passed.
