### ISSUE TITLE
Disarm notification does not respect modes!

### ISSUE THREAD

**Issue by picotrain77** [nielsfaber/alarmo#526]
### Alarmo Version

v1.9.4

### HA Version

2022.7

### Bug description

Not sure if this is a bug or a feature request, but I have set up notifications to be sent when the alarm is disarmed, however I do not want the notification when alarm is disarmed from armed_night.

I had assumed that the mode options may prevent this by only actioning the notification if the prior state was one of the chosen modes, but my testing suggests that none of the mode options are respected when system disarms!

**Comment by NiC1305** [comment]
Hello,
I am facing the same problem.
When disarming away mode, I want to have some noise in a speaker, but not when disarming from night mode. Unfortunately, by selecting the desired mode, it launches the 2 actions simultaneously instead of one depending on the previous state of arming.

**Comment by nielsfaber** [comment]
This is not working because when reaching the disarmed state, there is no arm mode active (anymore).
I will try to see if I can change the code such that the mode of the previous state is used, but I’m not sure if this is feasible.

**Comment by picotrain77** [comment]
Thanks for the feedback @nielsfaber, I suspected it maybe something along those lines.

I appreciate its not massive issue and can circumvent it by creating my own notification automation in the mean time.

**Comment by nielsfaber** [comment]
I have performed some local testing but sadly I haven't seen the issue you're describing.
For me an action/notification for mode `home` only is triggered when disarming from being armed in mode `home`.
Are there any specific circumstances under which you experience this issue?

**Comment by picotrain77** [comment]
I have a notification setup within alarmo the notifies on state going to disarmed, however I don't want this notification when state goes from armed_night to disarmed.

No matter what mode buttons I select or deselect I always get the notification on disarming no matter what the previous state is / was.

**Comment by NiC1305** [comment]
I have set up an action that runs when the Alarm is disabled in Away mode. I have another action that runs when the Alarm is disabled in Night mode.
When I deactivate the alarm, regardless of the away or night mode, the 2 actions are launched.

**Comment by nielsfaber** [comment]
I saw I actually fixed this a month ago, but it is not released yet..

**Comment by nielsfaber** [comment]
Version v1.9.5 is released and should fix this problem.
Please update your alarmo version and test whether the issue is indeed solved.
You can close the issue if so, otherwise please let me know.

**Comment by picotrain77** [comment]
All working as expected, thank you for all your efforts they are much appreciated by many!
