### ISSUE TITLE
The first "ALARM Disarmed" default notification on iOS cannot be deleted with swipe. Requires clicking it and opening home assistant app before it will go away

### ISSUE THREAD

**Issue by wtstreetglow** [nielsfaber/alarmo#529]
### Alarmo Version

1.9.4

### HA Version

2022.7

### Bug description

I can provide a video of this behavior if necessary.
This has been witnessed multiple times as I am new to HA and have been setting up HA and Alarmo over the last few weeks.

Essentially, upon disarming through the alarm panel, I have configured Alarmo to send a push notification when the alarm is disarmed. 

The message arrives properly, however, it does not allow swiping to remove it.

If I arm the system, and then disarm a second time. I get an arming notification as well as a second disarm notification. ---> The arming notification can be swiped to delete and the second disarm notification can be swiped to delete. The only way I have been able to get the first arming notification to go away is to click it which opens the HA iOS app. This is reproducible if you would like to see a video or screen recording of the issue. 

Thank you for any help you can provide with this!

**Comment by wtstreetglow** [comment]
I just ran an additional test, I took the system to "armed away" and got a notification, it is swipable to the left and gives options such as "clear" and "options". I then Disarmed the alarm, the notification that came with the disarm would not allow swiping to the left to clear it. 

Maybe this is how you intended this to work? (First disarm can't be "acknowledge" or maybe it is a bug. 

Thank you for looking into this and sorry for dropping another message. I just wanted to give you that info as I was testing a little bit more.

**Comment by wtstreetglow** [comment]
This issue has possibly went away for me by deleting the message automation and recreating it within the Alarmo configuration panel. Craziest thing I've ever seen. Maybe this can be closed and if it starts happening again, I will let you know.

**Comment by wtstreetglow** [comment]
Actually, I'm seeing this with other notifications from home assistant so I think this may be an HA issue possibly.

**Comment by nielsfaber** [comment]
The notifications sent by Alarmo rely on the `notify` services of HA.
I cannot influence the behaviour from the side of Alarmo, the configuration is limited to the parameters which HA allows.
Perhaps you could play with the parameters, following the examples on [this](https://companion.home-assistant.io/docs/notifications/notifications-basic/) page.
You could send a 'raw' notification from the Developer Tools -> Services page in HA.
If the problem persists, I think its best to open a bug report in the HA repository (and check if there is already one open for this).
At this point I don't know how to follow up on this report.

**Comment by wtstreetglow** [comment]
Not a problem and I agree with you. Thank your for your response. I will close the issue so it’s not clogging up things
