### ISSUE TITLE
group unavailable -> alarm (rather than single sensor)

### ISSUE THREAD

**Issue by snickers2k** [nielsfaber/alarmo#530]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
if 2 sensors grouped together fails at the same time, that probably means there is a jammer nearby and therefore should trigger the alarm. 

### Additional info
just like there is an option for a single sensor to trigger alarm. but thats kinda risky, i think.

**Comment by nielsfaber** [comment]
What do you mean by sensor failure?
From the side of Alarmo support is currently limited to binary sensors which have On/Off states.
A binary sensor can also become 'unavailable', but this can have many reasons.
Currently the user can configure whether a sensor becoming unavailable should trigger the alarm.

**Comment by snickers2k** [comment]
yeah, exactly that. but i wish there is an option for triggering the alarm only if two sensors become unavailable at the same time.
because, like you said, it can have many reasons for ONE sensor to become unavailable. TWO sensors at the same time **must** be a jammer-device.

**Comment by nielsfaber** [comment]
I believe this functionality is already in place.
If you define a sensor group with multiple sensors, and each sensor is configured to 'trigger when unavailable',  you should see that the alarm is triggered when 2 sensors simultaneously fail.
