### ISSUE TITLE
bypass manually

### ISSUE THREAD

**Issue by snickers2k** [nielsfaber/alarmo#532]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
**accept button on the keypad** 
to bypass open sensors manually by pushing "accept" button (arm in force)

### Additional info
like with Ring-keypad's question "want to bypass sensors?" and the accept button to bypass the sensors manually (rather than automatically). 
This is especially helpful for open windows on second floor, if one's right back.
![keypad 2gen 2](https://user-images.githubusercontent.com/5986024/180672374-e7158be1-bde0-4406-861f-d6e31d51bd96.png)

**Comment by picotrain77** [comment]
You could in theory do this via a HA automation already.

I am guessing you could trigger:

trigger:
  - platform: event
    event_type: alarmo_failed_to_arm
condition:
  - condition: template
    value_template: '{{ trigger.event.data.reason == ''open_sensors'' }}'

Then have a wait for the keypad event, then action the force arm action 'alarmo_force_arm'

**Comment by picotrain77** [comment]
something like this maybe:

`alias: New Automation
description: 'if alarmo triggers failed to arm, set ring keypad alert. If yes button pressed within 10 secs then set forced arm'
mode: single
trigger:
  - platform: event
    event_type: alarmo_failed_to_arm
    event_data:
      reason: open_sensors
condition:
  - condition: template
    value_template: '{{ trigger.event.data.reason == ''open_sensors'' }}'
action:
  - service: zwave_js.set_value
    data:
      command_class: '135'
      endpoint: '0'
      property: '16'
      property_key: '1'
      value: 100
    target:
      entity_id: sensor.keypad_v2_battery_level
  - wait_for_trigger:
      - platform: event
        event_type: zwave_js_notification
        event_data:
          command_class: 111
          device_id: null
          event_type: 2
    continue_on_timeout: false
    timeout: '00:00:10'
  - service: alarmo.arm
    data:
      entity_id: alarm_control_panel.yours
      code: '1234'
      mode: away
      force: true
`

**Comment by nielsfaber** [comment]
@snickers2k As picotrain77 says, there is already an option to arm in force via the `alarmo.arm` service.
For controlling this Alarmo via the Ring keypad, refer to this [blueprint](https://community.home-assistant.io/t/synchronize-ring-alarm-keypad-v2-with-alarmo/349461).
Perhaps the blueprint needs to be extended with the functionality you are looking for, but this is outside of the scope of alarmo. You could propose it to the author of the blueprint instead.
If functionality is missing from the side of Alarmo (e.g. `alarmo.arm_retry` service) this can be discussed here.

**Comment by snickers2k** [comment]
yes, i already do this for the ring-keypads. but i also have two displays i'd like to use with alarmo, which is missing the accept button. so this is more a frontend-request.

**Comment by snickers2k** [comment]
still a valid feature request... and so deeply needed
