### ISSUE TITLE
"Always on" alarms

### ISSUE THREAD

**Issue by Dinth** [nielsfaber/alarmo#534]
### Checklist
- [v] I checked for similar existing requests (both open and closed) before posting.
- [v] My request is generic, other users may benefit from it too.

### Proposal
Recently i have started using Alarmo for a burglar alarm, but also noticed that Alarmo would also be perfect to control environmental alarms, like flooding, gas, smoke, etc. It already has notifications, siren control, most of the things needed to do that - except of one - the ability to set those alarms to be "always on". After setting up a completely new alarm and adding smoke sensors to it, the alarm is by default in "Unknown" state. I need to add the alarm to Lovelace and arm it manually for it to work. If in the future the alarm disarms itself (because of update of HA or Alarmo, software bug, whatever) i may not even notice that the alarm is switched off. 

### Additional info
There should be an option to set the alarm to be "always on". There may be an additional option to manually disable the alarm for a set period of time, but after that it should go back online.

**Comment by nielsfaber** [comment]
Alarmo does support 'always on' mode, but this needs to be defined on sensor level (environmental sensors should have this setting by default). 
When set, the alarm should always go to triggered state when the sensor is activated (also when the alarm is disarmed).
Considering this functionality is already in place, I'm not sure what changes you suggest with your feature request. Could you elaborate?

> After setting up a completely new alarm and adding smoke sensors to it, the alarm is by default in "Unknown" state

This sounds like a bug. Could you report your findings in a separate issue for follow-up?

**Comment by Dinth** [comment]
Thanks for your reply. Ive seen the "always on" option for individual sensors and maybe im trying to do my smoke and gas sensors incorrectly, but i would like to create separate alarms - with separate trigger action and different notifications for environmental things (for example there's no point in triggering the external burglar siren if there's a CO detection in my loft).
>This sounds like a bug. Could you report your findings in a separate issue for follow-up?
Will do. I thought this is a normal behavior because the alarm was never armed or disarmed.

**Comment by nielsfaber** [comment]
There is a discussion topic about this: https://github.com/nielsfaber/alarmo/discussions/496

From the feedback I received I concluded most people are happy with the functionality as it is. By creating different areas, the behaviour for the environmental alarm can be defined independent from the burglar alarm.
