### ISSUE TITLE
New alarms (zones) are in Unknown state immediately after they're created

### ISSUE THREAD

**Issue by Dinth** [nielsfaber/alarmo#535]
### Alarmo Version

1.9.4

### HA Version

2022.7.7

### Bug description

When a new zone (alarm) is being created in Alarm (using "Add" button) its created with Unknown state. According to this https://github.com/nielsfaber/alarmo/issues/534#issuecomment-1198337476 it is not an expected behavior.

### Steps to reproduce

1. Add a new zone using "Add" button.
2. Check it's state using Developer Tools in HA.

**Comment by nielsfaber** [comment]
Fix is on its way: https://github.com/nielsfaber/alarmo/commit/d56b9f7cf1f42a3d8573d0e1cb6b0dec507afba6

**Comment by nielsfaber** [comment]
Version v1.9.5 is released and should fix this problem.
Please update your alarmo version and test whether the issue is indeed solved.
You can close the issue if so, otherwise please let me know.
