### ISSUE TITLE
cannot create new actions

### ISSUE THREAD

**Issue by silmaril464** [nielsfaber/alarmo#537]
### Alarmo Version

v1.9.4

### HA Version

2022.7.7

### Bug description

when I try to create a new action/notification or try to edit an existing action, when saving the configuration, it shows an error:

Something went wrong!
Message format incorrect: extra keys not allowed @ data['actions'][0]['service_data']

Response error: 400

Please [report](https://github.com/nielsfaber/alarmo/issues) the bug.

***this is an example of yaml code:

service: notify.mobile_app_netcom
data:
  message: La alarma está configurada en {{arm_mode|lang=es}}
  title: Alarma Armada
service_data:
  message: La alarma está configurada en {{arm_mode}}
  title: ''

### Steps to reproduce

when I try to create a new action or try to edit an existing action

### Relevant log output

_No response
![Sin título](https://user-images.githubusercontent.com/70072279/181995344-422c0568-d706-42fe-a1a2-e9e91acd2477.png)
_

**Comment by AndyVRD** [comment]
Please restart home assistant. If you installed the update from the HACS integration you will notice a red message to notify you to restart home assistant...

**Comment by silmaril464** [comment]
yes, i did it 2 times, but the error is still there..
I'll try again tomorrow, now I'm back to version 1.9.4

Thank you

**Comment by nielsfaber** [comment]
This is probably a cache issue.
I am guessing you still see v1.9.4 in the top-right corner of the Alarmo panel.
After updating to v1.9.5, please refresh the browser cache.

**Comment by silmaril464** [comment]
OK! you're right! it was a cache problem, the strange thing is that I tried it with 3 different browsers, with one of them I never use it to access home assistant, and I got the same result, that's why I had initially ruled out that it was a cache problem...
thanks a lot!!

Sorry for the bad english, I had to use an automatic translator...
