### ISSUE TITLE
variables are not substituted in notifications

### ISSUE THREAD

**Issue by velzend** [nielsfaber/alarmo#54]
I have the {{ open_sensors }} variable in the notification using telegram as target whenever alarm is triggered.
Using the default message that includes this variable I get the error message below:

```
ERROR (SyncWorker_38) [homeassistant.components.telegram_bot] Error sending message: Can't parse entities: can't find end of the entity starting at byte offset 50. Args: (***********, 'The alarm is triggered! Cause: backdoor_open_close_sensor is on.'), kwargs: {'parse_mode': 'Markdown', 'disable_notification': False, 'disable_web_page_preview': None, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}
```

I also tried to iterate over the variable, this does not raise any error message nor does it show any open sensors.
Referencing to the states individually does work.

```
The alarm is triggered! 

Magneetcontact openslaande deuren: {{ states('binary_sensor.openclose_11') }}
Magneetcontact voordeur: {{ states('binary_sensor.openclose_9') }}
Bewegingsmelder hal: {{ states('binary_sensor.presence_33') }}
....

Open sensors: 
{% for open_sensor in open_sensors  %}
{{ open_sensor.key }}: {{ open_sensor }}
{% endfor %}
```

The arm_mode variable is also not substituted.

Home Assistant version 0.116.2.

**Comment by nielsfaber** [comment]
This:
```
The alarm is triggered! Cause: backdoor_open_close_sensor is on.'
```
Looks like the message text where {{open_sensors}} is processed correctly.

The rest of the problem seems to be related to something else.
This seems to be an error that is telegram-specific:
```
Error sending message: Can't parse entities: can't find end of the entity starting at byte offset 50.
```
I don't know what the error describes. But I'm fairly sure that if you would choose another `notify` service, it would not be thrown.

I'm not sure if I could solve this problem from Alarmo..

**Comment by velzend** [comment]
The issue is related to how the Telegram notify logic parses the input, it tries formatting as markdown.

You may close this issue.
