### ISSUE TITLE
Arm after closing After deactivation of ALL door sensors,

### ISSUE THREAD

**Issue by dborg-nep** [nielsfaber/alarmo#540]
### Proposal
Within the door device type sensor there is a awesome option for 'Arm after closing After deactivation of this sensor, the remaining exit delay will automatically be skipped' I think it would be good if there was a feature that looked at all door sensors being closed then skipping the rest of the exit delay and turning system to armed.

use case: I have two doors and both are opened at time of arming. I start the arming process and close one door, once i proceed to close last door the system will arm and exit delay skipped. I think this would be common.

**Comment by nielsfaber** [comment]
The behaviour could be changed, but I think it would be a step backwards.
I designed the behaviour with the expectation that 'all but one' door would be closed prior to arming, I think this is what most people would do (especially if you have an alarm panel at the entry).
I don't understand why you would arm your alarm before closing doors which are not used for exiting.

The problem with changing as you propose, is that in case a (second) door is unintentionally left open, the user would be informed of this after passing the entire exit delay. 
I don't see a way to implement what you're asking without this side effect.

**Comment by dborg-nep** [comment]
No problems I have two entries at back and front which we can enter/exit our property so was hoping for some logic to manage this. Appreciate response anyway. Awesome product


Dominic Borg
Head of IT, Asia Pacific | NEP Australia
NEP Broadcast Services | Australia
O:+61 2 9690 8125 | M:+61 499 370 408
***@***.***
www.nepgroup.com.au<http://www.nepgroup.com.au>

[cid:nep-logo-fc-grey-rgb-155x82_c3150264-3d19-4874-aa03-adb483ef3756.png]

We bring content to life.

CONFIDENTIALITY NOTICE & DISCLAIMER: This email may contain confidential, proprietary, or privileged information. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by picotrain77** [comment]
"I have two doors and both are opened at time of arming. I start the arming process and close one door, once i proceed to close last door the system will arm and exit delay skipped. I think this would be common"

I have a similar setup, door 1 and 2 are open on arming, i then always close door 1 then finally door 2.

I simply set both door 1 & door 2 to use exit delay (therefore they can both be open when arming is initiated. But i only set door 2 to arm after closing, therefore working exactly as you wanted or am I missing something?

**Comment by dborg-nep** [comment]
Pretty close but with your use case: I simply set both door 1 & door 2 to use exit delay (therefore they can both be open when arming is initiated. But I only set door 2 to arm after closing, therefore working exactly as you wanted or am I missing something?

We sometimes exit through door 1 or sometimes door 2 as my property allows entry/exit from both front and back. Probably not that common &#128522;


Dominic Borg
Head of IT, Asia Pacific | NEP Australia
NEP Broadcast Services | Australia
O:+61 2 9690 8125 | M:+61 499 370 408
***@***.***
www.nepgroup.com.au<http://www.nepgroup.com.au>

[cid:nep-logo-fc-grey-rgb-155x82_c3150264-3d19-4874-aa03-adb483ef3756.png]

We bring content to life.

CONFIDENTIALITY NOTICE & DISCLAIMER: This email may contain confidential, proprietary, or privileged information. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.
