### ISSUE TITLE
Codes Overhaul

### ISSUE THREAD

**Issue by nielsfaber** [nielsfaber/alarmo#544]
### Discussed in https://github.com/nielsfaber/alarmo/discussions/543

<div type='discussions-op-text'>

<sup>Originally posted by **stickbug813** August  3, 2022</sup>
I would like to suggest a few ideas to be integrated into the Alarmo Menu. 

Situation and my thoughts on why I would like this: My dad is a trucker and my mom is a older woman who has trouble feeding our big outside dogs. We hire the neighbors to come over and feed the dogs twice a day. I have an Alarmo code set for an area called "Garage" that the neighbors has access to so they can feed the dogs. We only want this neighbor to have access to the garage between 9:30 am - 11:00 am and 6:40 pm - 8:00 pm

Idea #1: Be able to put each code under the User Management tab to have a confinable 24/7 scheduler. 
     Ex. Mon - Fri | User 1 | 9:30 am - 11:00, 6:40 pm - 8:00 pm
          Fri - Sun | User 1 | 11 am - 3 pm
-----
Idea #2: Allow the API of Alarmo to be able to detect what User/code was used do disarm/arm the system.
     Ex. When my dad comes home and disables the alarm at 3 am, I want it to be able to turn on the kitchen light. But only at 3 am and only for my dads code when entered. 
     
Just a few thought if you ever wanted to do an update to Alarmo. Great addon to HA overall and will still continue to use it if this idea never sees past this thread. 

Good Day!</div>

**Comment by nielsfaber** [comment]
I moved this item since feature requests should be posted under issues.

Regarding idea 1: it is already possible to temporarily disable a user in Alarmo. You can use the `alarmo.enable_user` and `alarmo.disable_user` services for this.
Ofcourse you will need to make an automation (external from Alarmo) to enable/disable the user at the desired times.

Regarding idea 2: you can create an automation (external from Alarmo) that triggers when the alarm is disarmed with condition that the alarm entity has property `changed_by=<your dad>`. 
There is an open feature request regarding the addition of the `changed_by` property as condition for the actions within Alarmo. See https://github.com/nielsfaber/alarmo/issues/521.

**Comment by mririgoyen** [comment]
Bad bot. @nielsfaber I assume you still wish to do this?

**Comment by nielsfaber** [comment]
@mririgoyen I currently have no plans to add time restriction to users. In case you want to do so, you could follow my proposal is in my earlier response.
