### ISSUE TITLE
After Automation attempt Alarmo Entitiy unavailable and cant arm or disarm

### ISSUE THREAD

**Issue by paata01** [nielsfaber/alarmo#545]
### Alarmo Version

1.9.5

### HA Version

2022.7.7

### Bug description

Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 12:20:31 AM (11 occurrences)
Last logged: 9:39:47 AM

Unable to find referenced entities alarm_control_panel.alarmo or it is/they are currently not available

### Steps to reproduce

I tried to run Geofencing automation which was supposed to arm and disarm by geo location of devices, after attempting to do so, I am unable to arm or disarm Alarmo, reinstalling helped but automation again broke, it. here is my automation, seems nothing wrong with it to me:

id: '1659498186916'
alias: 'Geofence: Arm Alarm'
description: ''
trigger:
  - platform: numeric_state
    entity_id: proximity.homealarm
    id: leaving-home
    above: '0.2'
  - platform: numeric_state
    entity_id: proximity.homealarm
    id: approaching-home
    below: '0.2'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: leaving-home
        sequence:
          - service: alarmo.arm
            data:
              entity_id: alarm_control_panel.alarmo
              mode: away
      - conditions:
          - condition: trigger
            id: approaching-home
        sequence:
          - service: alarmo.disarm
            data:
              entity_id: alarm_control_panel.alarmo
              code: 'XXXX'
    default: []
mode: single

**Comment by nielsfaber** [comment]
Please check if `alarm_control_panel.alarmo` exists.
See Developer Tools -> States.

**Comment by paata01** [comment]
> alarm_control_panel.alarmo

thank you for quick reply, yes it exists. [Photo attached](https://i.imgur.com/T9q9owk.png)
But I thats the error I am getting when trying to arm or disarm

**Comment by nielsfaber** [comment]
This is very strange to me.
The error message that you got is generated from HA itself, it is not in the code of Alarmo.
Did you try to manually arm/disarm the alarm via the Developer Tools -> Services tab ? Does it give the same error?

**Comment by paata01** [comment]
> This is very strange to me. The error message that you got is generated from HA itself, it is not in the code of Alarmo. Did you try to manually arm/disarm the alarm via the Developer Tools -> Services tab ? Does it give the same error?

Yes I was able to change state from dev tools. is there anything wrong with this automation causing so much trouble?

id: '1659498186916'
alias: 'Geofence: Arm Alarm'
description: ''
trigger:
  - platform: numeric_state
    entity_id: proximity.homealarm
    id: leaving-home
    above: '0.2'
  - platform: numeric_state
    entity_id: proximity.homealarm
    id: approaching-home
    below: '0.2'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: leaving-home
        sequence:
          - service: alarmo.arm
            data:
              entity_id: alarm_control_panel.alarmo
              mode: away
      - conditions:
          - condition: trigger
            id: approaching-home
        sequence:
          - service: alarmo.disarm
            data:
              entity_id: alarm_control_panel.alarmo
              code: 'XXXX'
    default: []
mode: single
