### ISSUE TITLE
A way to bypass one sensor if another is open

### ISSUE THREAD

**Issue by caraar12345** [nielsfaber/alarmo#548]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
One of my rooms uses a motion detector based on a camera meaning it can be a bit trigger happy from time to time. It's on the first floor so I'm not always concerned about shutting the window before I go out if I want to keep it cool for when I get back. My window has a contact sensor so I can see in HA when it's open.

I'd like for a way to configure Alarmo so that if my window is open, the camera's motion sensor is ignored. Because otherwise, the wind blows the curtains and it sets off the alarm every few minutes 😅 

### Additional info
I believe this might be possible if I set up a second entity which feeds from both sensor values. So, if the contact sensor is open, the secondary sensor should always be in "motion detected" mode, meaning I can force arm Alarmo and force it to bypass that sensor. But it'd be cool to be able to configure it properly without requiring a duplicate sensor!

**Comment by nielsfaber** [comment]
I think the use-case is rather specific, so I don't think Alarmo should be adapted for this.
Instead I propose that you create a template sensor for this and use this entity in Alarmo.
You could write a logic rule such that the template sensor is only triggered in case of motion while the door is open.

**Comment by caraar12345** [comment]
Fair enough - thanks!
