### ISSUE TITLE
Set up failure (work before)

### ISSUE THREAD

**Issue by WHagenauw** [nielsfaber/alarmo#551]
### Alarmo Version

Latest (cannot see it now)

### HA Version

2022.8.2

### Bug description

After installing HA 2022.8 alarmo cannot be set up anymore. It worked before

### Steps to reproduce

Probably after installing HA 2022.8

### Relevant log output

```shell
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/alarmo/store.py:191
Integration: Alarmo (documentation, issues)
First occurred: 8 augustus 2022 om 09:50:07 (1 occurrences)
Last logged: 8 augustus 2022 om 09:50:07

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmo/__init__.py", line 55, in async_setup_entry
    store = await async_get_registry(hass)
  File "/config/custom_components/alarmo/store.py", line 687, in async_get_registry
    return cast(AlarmoStorage, await task)
  File "/config/custom_components/alarmo/store.py", line 682, in _load_reg
    await registry.async_load()
  File "/config/custom_components/alarmo/store.py", line 312, in async_load
    data = await self._store.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 116, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 125, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 170, in _async_load_data
    stored = await self._async_migrate_func(data["version"], data["data"])
  File "/config/custom_components/alarmo/store.py", line 228, in _async_migrate_func
    data["automations"] = [
  File "/config/custom_components/alarmo/store.py", line 230, in <listcomp>
    **parse_automation_entry({
  File "/config/custom_components/alarmo/store.py", line 191, in parse_automation_entry
    output["actions"] = list(map(lambda el: ActionEntry(**el), data["actions"]))
  File "/config/custom_components/alarmo/store.py", line 191, in <lambda>
    output["actions"] = list(map(lambda el: ActionEntry(**el), data["actions"]))
TypeError: ActionEntry.__init__() got an unexpected keyword argument 'service_data'
```

**Comment by nielsfaber** [comment]
Did you check this thread: https://github.com/nielsfaber/alarmo/issues/538
Maybe you’re in the same boat as him, could you check if you’re storage file has a recent version?

**Comment by WHagenauw** [comment]
Probably the same but I cannot check the storage file version. I can only
view files through HA file editor. I tried to delete Alarmo from
configuration and HACS but after installing Alarmo with HACS (reboot) and
than with configuration I get the same error. I don't see a device anymore
under Alarmo. So I can't do anything to solve this problem?

Kind regards,

Wim,


Op di 9 aug. 2022 om 21:51 schreef Niels Faber ***@***.***>:

**Comment by nielsfaber** [comment]
I think its best to install the previous alarmo version v1.9.4 via HACS.
Then you should make a change in your configuration (e.g. change the exit delay), and wait 10 seconds for the storage file to be saved.
After this you should be able to update to v1.9.5 without problems.
I would be surprised if this doesn't work.

**Comment by WHagenauw** [comment]
The problem is that I cannot choose which version from alarmo I wish to
install..... Otherwise I already tried 1.9.4. I do not get any options
during install

Wim Hagenauw

Op wo 10 aug. 2022 18:17 schreef Niels Faber ***@***.***>:

**Comment by rgdif17** [comment]
I've been having the same issue updating to v1.9.5, integration always up to date but havent made any changes to config in awhile and update fails.  Havent tried to make a change yet to see if it fixes it but currently I show V5 minor V1

{
  "version": 5,
  "minor_version": 1,
  "key": "alarmo.storage",
  "data": {
    "config": {
      "code_arm_required": false,
      "code_disarm_required": true,
      "code_format": "number",
      "disarm_after_trigger": true,
      "master": {
        "enabled": true,
        "name": "master"
      },
      "mqtt": {
        "enabled": true,
        "state_topic": "alarmo/state",
        "state_payload": {},
        "command_topic": "alarmo/command",
        "command_payload": {},
        "require_code": true,
        "event_topic": "alarmo/event"
      }

**Comment by rgdif17** [comment]
Dug into it a little deeper and found the issue.  Created a new test notification alert to compare the automations in the storage file and noticed the area is missing.  Editing the file and adding the area to the OG notification allowed me to update to v1.9.5

    "automations": [
      {
        "automation_id": "1620785873",
        "type": "notification",
        "name": "Alarm Triggered Notification",
        "triggers": [
          {
            "event": "triggered",
            "area": null,
            "modes": []
          }
        ],
        "actions": [
          {
            "service": "notify.mobile_app_robs_iphone",
            "entity_id": null,
            "service_data": {
              "message": "The alarm is triggered! Cause: {{open_sensors}}.",
              "title": "Alarm Triggered!"
            }
          }
        ],
        "enabled": true
      },
      {
        "automation_id": "1660251722",
        "type": "notification",
        "name": "TEST ACTION",
        "triggers": [
          {
            "event": "triggered",
            "area": "1620785551",
            "modes": []
          }
        ],
        "actions": [
          {
            "service": "notify.mobile_app_robs_iphone",
            "entity_id": null,
            "service_data": {
              "message": "The alarm is triggered! Cause: {{open_sensors}}."

**Comment by nielsfaber** [comment]
I made a change which should fix this problem: https://github.com/nielsfaber/alarmo/commit/fe206d0fcd10ee5fedcec47afbe651c59bc6fc4b
It is not part of a release yet.
If you want to try it out please manually overwrite the store.py file in the custom_components/alarmo folder.

**Comment by WHagenauw** [comment]
Hello,

 I would like to try it but how do I download this file? I only get the
text part and don't see how to download it

Op di 16 aug. 2022 om 20:34 schreef Niels Faber ***@***.***>:

**Comment by B1G1** [comment]
> I made a change which should fix this problem: [fe206d0](https://github.com/nielsfaber/alarmo/commit/fe206d0fcd10ee5fedcec47afbe651c59bc6fc4b) It is not part of a release yet. If you want to try it out please manually overwrite the store.py file in the custom_components/alarmo folder.

With this change it works.

Thank you

**Comment by awshirley** [comment]
How soon will the fix make it into the release?  I've got the same problem too.

**Comment by WHagenauw** [comment]
I downloaded it and installed it on the location you said. The file is much
bigger. My original file is about 23Kb and this one is 546kb. It is not
working. I restarted HA also but said that the configuration from HA is not
OK,

Op wo 17 aug. 2022 om 17:39 schreef Wim Hagenauw ***@***.***>:

**Comment by nielsfaber** [comment]
This change is added to v1.9.6 release.
I'm closing this issue, assuming this is fixed now.
Let me know if there are still problems.
