### ISSUE TITLE
Possible to have disarmed icon stop flashing after disarming

### ISSUE THREAD

**Issue by confuserated** [nielsfaber/alarmo#553]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]
On all my browsers (Safari/Chrome) the "disarmed" icon stays flashing once the alarm has been disarmed. Is it possible to refresh this icon so that it does not flash (reloading the browser stops it flashing, which is not something it makes sense to do on the wall tablet I control this from).
### Additional info
[some example of how the new functionality should look like]

**Comment by nielsfaber** [comment]
You should use Alarmo-card rather than the HA Alarm Panel card.

**Comment by confuserated** [comment]
Sorry, I didn't even notice I hadn't used the alarmo card as the panel showed "alarmo" inside the card (unsurprising now I think about it). 

I think the alarmo custom card is a bit incognito in comparison (at least on my install) as it does not configure the entity automatically.

My bad, sorry.

**Comment by nielsfaber** [comment]
I don't know how to change the code of the card to automatically detect the best suitable alarm entity.
But I agree it would be preferable (I believe now you start with an error saying that no entity is defined).

Anyway, the flashing of the icon should be solved if you use alarmo-card instead.

**Comment by confuserated** [comment]
Many thanks, it did, works perfectly now.

**Comment by nielsfaber** [comment]
> I think the alarmo custom card is a bit incognito in comparison (at least on my install) as it does not configure the entity automatically. Maybe it could start off assuming the 'master' panel?

Seems I could fix this after all 😊 
https://github.com/nielsfaber/alarmo-card/commit/1838823a1e097a00f9b1fe272447e7c0079148e9

Preview:
<img src="https://user-images.githubusercontent.com/16861605/184523954-7b0d7890-17b4-4982-a8fb-0e1f86814b3c.png" width="75%" height="75%">

It will be added to the next update of alarmo-card.

**Comment by confuserated** [comment]
Oh, fabulous. That’s great 😁
