### ISSUE TITLE
Animation of Icons "Badge" menu

### ISSUE THREAD

**Issue by FabzX11** [nielsfaber/alarmo#561]
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
Hello,

first of all, thank you for the work you have done with Alarmo. 
I have been using it for 2 months and it is great. As time goes by, I'm adding sensors and siren/flash to optimize the surveillance of my house.

On the other hand, I have a question maybe it has already been asked but I have not found anything about it.
Do you think it would be possible to animate the alarm status icons when the icons are placed on the Dashboard in the "badge" menu?
In my case, whether the status is Arming or Disarming, the icon remains red.

Regards,

![image](https://user-images.githubusercontent.com/103033529/187034400-bfeb757a-678d-4236-b998-d7221059b8d1.png)

**Comment by nielsfaber** [comment]
Unfortunately this is handled by HA internally. I cannot influence this from Alarmo.
You could open a feature request for HA instead. I’m sorry to disappoint you.

**Comment by FabzX11** [comment]
Thank you for your answer.
