### ISSUE TITLE
Notification hibernate/deep sleep

### ISSUE THREAD

**Issue by drveni** [nielsfaber/alarmo#575]
im not sure is i need Feature request or its bug. when alarm is triggered. i put notification on my mobile popup (android). and when my mobile is locked and in some state hibernate. notification are not coming until i unlock phone. i'm tired to put priority messages but it doesn't work. said state or statement is not supported. for notifications that turn on the mobile phone from hibernation, I use an automation script that works perfectly. but when I copy that form of priority message, then alarmo throws an error that it is not supported. 

example:

alias: im home
description: ""
trigger:
  - platform: device
    device_id: xxxxxxxxxxxxxxxxxx
    domain: device_tracker
    entity_id: device_tracker.mi_9t
    type: enters
    zone: zone.kuca
condition: []
action:
  - service: notify.mobile_app_pixel_6
    data:
      message: mom
      title: im home
      data:
        ttl: 0
        priority: high
        channel: alarm_stream
mode: single

this priority put notification 

____
 data:
      ttl: 0
      priority: high
      channel: alarm_stream
____

this wakes up the phone from hibernation and plays. on the alarm, I can't force it to wake up my mobile phone and play the alarm or anything, as a priority, like from home assist.

I hope you understand the problem.

if it exists, I can't find it in the documentation... or please, if you can implement it somehow to make the mobile phone send notifications in a state of deep sleep to play for me instant. (as it is already in the scripts from the yalm home assistant itself)

sorry for my bad english

thx

**Comment by nielsfaber** [comment]
You can add extra parameters (like priority) to the action, by switching to the YAML mode.
It is device-specific, so it is rather difficult for me to add this in the GUI editor.
