### ISSUE TITLE
Enable Template code

### ISSUE THREAD

**Issue by LeidenSpain** [nielsfaber/alarmo#577]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [ X] My request is generic, other users may benefit from it too.

### Proposal
Hi,

Right now I have an input_select to select which user the telegram notifications are sent to:
notify.telegram_{{ states('input_select.telegram_user_alarm') }}

I have tried to integrate this possibility in ALARMO, but it does not allow me to save the code, neither in UI nor in yaml

**Comment by nielsfaber** [comment]
I wish I could, but I have no idea how to implement this.

**Comment by LeidenSpain** [comment]
If you don't know that you are the one with knowledge... 🤣🤣🤣

Well, I will continue using scripts to send the messages

**THANKS**
