### ISSUE TITLE
Alarmo always armed after HA restart

### ISSUE THREAD

**Issue by onkytonk** [nielsfaber/alarmo#578]
### Alarmo Version

V1.9.5

### HA Version

2022.9.5

### Bug description

This has been happening for a couple of months now, but I didn’t realise it was until now. 

After HA restarts, for example, after installing an update, Alarmo will be in an armed state, regardless of whether or not it was in an armed state prior to the restart. 

I read on the HA thread something about sensors that take long to be ready causing an issue, but can’t confirm if this is the problem or not. 

I haven’t been able to diagnose it otherwise. 

### Steps to reproduce

Any restart of HA

**Comment by nielsfaber** [comment]
This is not the behaviour as I would expect it.
Alarmo is designed to return back to its former state on restarting.

Could you enable the debug logging for Alarmo and try restarting again?
You can enable the debug logging by adding this to the configuration.yaml (and restarting HA):
```yaml
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```

For me it shows up like this:
> 2022-09-25 13:59:54.278 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_control_panel.alarmo is added to hass
2022-09-25 13:59:54.279 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.alarmo was updated from None to disarmed
2022-09-25 13:59:54.279 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Initial state for alarm_control_panel.alarmo is disarmed

This is equal to the state of the alarm before restarting HA, so I would expect the same to happen for you.

**Comment by onkytonk** [comment]
This is my debug log:

> 2022-09-26 21:43:29.440 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_control_panel.alarmo is added to hass
> 2022-09-26 21:43:29.441 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] Initial state for alarm_control_panel.alarmo is disarmed
> 2022-09-26 21:43:29.441 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.alarmo was updated from None to disarmed
> 2022-09-26 21:43:29.450 DEBUG (MainThread) [custom_components.alarmo.mqtt] Published state 'disarmed' on topic 'home/alarm'
> 2022-09-26 21:43:29.714 DEBUG (MainThread) [custom_components.alarmo.mqtt] Received command arm_home
> 2022-09-26 21:43:29.714 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_arm_home
> 2022-09-26 21:43:29.715 INFO (MainThread) [custom_components.alarmo.alarm_control_panel] Alarm 'Alarmo' is armed (armed_home).
> 2022-09-26 21:43:29.715 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] entity alarm_control_panel.alarmo was updated from disarmed to armed_home
> 2022-09-26 21:43:29.715 DEBUG (MainThread) [custom_components.alarmo.mqtt] Published state 'armed_home' on topic 'home/alarm'
> 2022-09-26 21:43:29.716 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.alarmo is updated from disarmed to armed_home
> 2022-09-26 21:43:29.720 DEBUG (MainThread) [custom_components.alarmo.mqtt] Subscribed to topic home/alarm/set
> 2022-09-26 21:43:29.720 DEBUG (MainThread) [custom_components.alarmo.mqtt] MQTT config was (re)loaded

Looks like somethings coming in from MQTT, but my tablet that controls alarmo via MQTT is completely switched off. 
The easy fix, would be to disable MQTT in Alarmo, but any reason why these MQTT commands are coming through?

**Comment by nielsfaber** [comment]
It looks like you use retained messaging for the command topic in MQTT.
This causes the last command message to be re-sent from the MQTT broker to Alarmo after restarting HA.
This is probably not what you want.
Please change this setting on the device/application where the command is sent from, and make sure to clear the retained data.
