### ISSUE TITLE
Notification slow on Android

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#58]
The alarm notifications aren't coming through on android unless the phone is turned on. I wonder if you could add a couple of extra parameters and when you send the notification. Looks like it needs this:
data:
          ttl: 0
          priority: high
See here for details:
https://github.com/home-assistant/android/issues/594#issuecomment-629323240

Thanks,
Stefan

**Comment by nielsfaber** [comment]
Thanks, I will update the readme with your suggestion.
You can simply update the YAML code of the notification and add the extra lines.
Alarmo just sends the service data as-is, so there is no update needed.
