### ISSUE TITLE
Dont see the Alarmoapp

### ISSUE THREAD

**Issue by Rekkles250** [nielsfaber/alarmo#581]
### Alarmo Version

V1.9.5

### HA Version

Latest 

### Bug description

Hey i cant See the alarmocard Or anything. I always install the HA and alarmo 5 times and i delete the Cache but it dont works i Only the the hacs App.

**Comment by Rekkles250** [comment]
![Uploading CC078900-AEF9-45EE-9C94-8AE42FEDD061.png…]()

**Comment by Rekkles250** [comment]
![632474CB-E348-4319-84AA-FF13EA1537C2](https://user-images.githubusercontent.com/114304335/192111860-b4bb3e5d-a5d1-4013-b968-a7361038934e.jpeg)

**Comment by nielsfaber** [comment]
You need to go to integrations and add Alarmo here to set it up.
For Alarmo card you need to install it separate (it’s in HACS as well).

**Comment by Rekkles250** [comment]
I have installed it do you have anydesk? then you can come to my computer if you have time

**Comment by Rekkles250** [comment]
i have installed alarmo but i dont the the alarmopanel..:(

**Comment by Rekkles250** [comment]
ok i have fix it thanks

**Comment by Rekkles250** [comment]
close
