### ISSUE TITLE
Add support for buzzer sounds in actions

### ISSUE THREAD

**Issue by formatta2003** [nielsfaber/alarmo#582]
hello and thank you ..... congratulations ...
I have some requests !!!

1) the possibility of having the bypass sensor by default ... the security door is always open to exit ... so every time you have to press the 3 dots and select bypas sensor ..... it would be very convenient to put a function that by default all open windows are bypassed by default .... but when the window / door closes the sensor is activated (in traditional burglar alarms it works like this)

2) emit a beep every second when entering the house until the trigger time is reached .... at least it reminds you that the alarm is on ...

3) a beep beep after 30 seconds of exit ... as confirmation that the alarm is armed.

thank you

**Comment by thecheekymonkey** [comment]
im working on creating automations for exit delay and entry delay audible alerts. however something always breaks. ill post when i find out more, i agree that this would be most needed.

exit delay audible beep whilst alarm is arming.

entry delay audible beep whilst alarm is pending.


i can create these automations but its very frustrating, something always breaks....

**Comment by thecheekymonkey** [comment]
> request for

Exit delay audible notification (buzzer) until alarmo armed.
Entry delay audible notification (buzzer) until alarmo disarmed.
Open sensor disarming and buzzer silence.
Ive managed to create these using some scripts and also alarmo's actions but its quite frustrating to create. I have to created 2 scripts

script one is exit delay buzzer. toggles my siren on and off every 200ms until alarmo is armed.
script two is entry delay buzzer, this toggles my siren on and off every 100ms until alarmo is disarmed.

i then use alarmo action to call these when alarmo is set to arming (exit delay script) or pending (entry delay script)
these work great as long as you dont exceed 30 seconds entry delay, going anywhere over this figure results in the sire triggering constantly once entry delay has completed and alarmed should be armed.

open sensor disarm is so that if i set my alarm and say my front door is open and stays open whilst exit delay completes, alarm should count down exit delay and then not arm and siren should not sound. as it is, on completion of exit delay , alarm remains disarmed but siren triggers and i am unable to disable it by entering code or running any script. i have to restart home assistant and restart my alarm interface hardware.

id like to thank you for your integration, its great and is much appreciated.

im just trying to create similar behavior to a real alarm.

audible notifications i think are needed on exit and entry, especially entry so you know the alarm is set. home assistant is brilliant but ive spent days and days trying to get progress on this, but there are a million ways to do the same thing and inevitably something breaks at some point or another. many thanks

>

**Comment by nielsfaber** [comment]
@formatta2003 
Regarding 
> the possibility of having the bypass sensor by default ... the security door is always open to exit ... so every time you have to press the 3 dots and select bypas sensor ..... it would be very convenient to put a function that by default all open windows are bypassed by default .... but when the window / door closes the sensor is activated (in traditional burglar alarms it works like this)

This is very user dependent.
I don't want to make this choice for all users by setting this as default, I rather have the safe/conservative setting as default.
You will have to set this yourself for the doors/windows which should be bypassable.

@formatta2003  @thecheekymonkey 
Which device are you using for making beeps, how can it be controlled (which service) from HA?
It is hard for me to include support for actions which are very depending on the device used.
Some users want the beeps via an Alexa media player, some have a siren-like device which makes beeps when turned on, etc.
I'd like to collect the different scenarios so I can see what I can do..

**Comment by thecheekymonkey** [comment]
hi there thank you, i am using some konnected hardware interfaces and attaching a small piezo buzzer to the siren output.

i do understand that people want to use different hardware and its difficult to implement with many different hardware scenarios and configurations but i do think that audible alarm for exit and entry is important in an alarm system.

so i propose that maybe if it is possible could it not be implemented by class? i.e. have an option to set a tone sound or user selected media out to a class device?  so if you choose siren you could select a siren that you have installed, or media you could do likewise?

set exit or entry delay
check box for output?


i apologise, my understanding of homeassistant is ongoing, and im very grateful for the work you have done and appreciate the responses.

thank you

**Comment by thecheekymonkey** [comment]
@nielsfaber 

hi there thank you, i am using some konnected hardware interfaces and attaching a small piezo buzzer to the siren output.

i do understand that people want to use different hardware and its difficult to implement with many different hardware scenarios and configurations but i do think that audible alarm for exit and entry is important in an alarm system.

so i propose that maybe if it is possible could it not be implemented by class? i.e. have an option to set a tone sound or user selected media out to a class device? so if you choose siren you could select a siren that you have installed, or media you could do likewise?

set exit or entry delay
check box for output?

i apologise, my understanding of homeassistant is ongoing, and im very grateful for the work you have done and appreciate the responses.

thank you

**Comment by nielsfaber** [comment]
@thecheekymonkey Which service / entity are you using to control the buzzer?

**Comment by thecheekymonkey** [comment]
@nielsfaber 

i am using alarm_control_panel.alarmo

so i have created two scripts to create the buzzer sounds under HA , this is basically a repeated toggle for my siren (on/off) with a delay of 200ms for exit delay and 100ms for entry delay.

i then create an alarmo action to run for instance my "EXIT DELAY" script which does this "Repeat an action until Alarmo is armed away is true"

this makes the buzzer beep for however long i have set exit delay for in alarmo until it is armed. this works fine.

i then create an alarmo action to run for instance my "ENTRY DELAY" script which does this " Repeat an action while Confirm Alarmo is pending is true"

this makes the buzzer beep for however long i have set entry delay (bug see notes) for in alarmo whilst alarm is PENDING. when pending complete, i have another alarmo action for when alarmo state is triggered to just turn the siren on constant.

this is all working great so for with a few caveats.

if i set the ENTRY delay for any longer than 30 seconds, for instance say 40 seconds then when arming alarmo after the 30 second exit beep the siren just beeps constant and basically crashes and i have to restart HA and my hardware instances. if i set ENTRY delay back to 30 seconds or below everything works as it should.

hope this helps, i can post configs or screenshots if you like or need and even a video if needed of the behaviours, so please let me know.

thanks again for the great work

**Comment by daloki83** [comment]
Its a old topic, but im also in a similar situation
While status is pending it should play a sound file on my fire tablet. But it doesnt. When i enter the code an press disarm then the sound will be played.

Any ideas?


`alias: 0_Alarm_pending
description: ""
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.alarmo
    from: armed_away
    to: pending
condition: []
action:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.2
    target:
      entity_id: media_player.fire_tablet
  - repeat:
      sequence:
        - service: media_player.play_media
          target:
            entity_id: media_player.fire_tablet
          data:
            media_content_id: media-source://media_source/local/bedside-clock-alarm-95792.mp3
            media_content_type: audio/mpeg
          metadata:
            title: bedside-clock-alarm-95792.mp3
            thumbnail: null
            media_class: music
            children_media_class: null
            navigateIds:
              - {}
              - media_content_type: app
                media_content_id: media-source://media_source
      while:
        - condition: state
          entity_id: alarm_control_panel.alarmo
          state: pending
mode: single
`
