### ISSUE TITLE
Tamper sensors are not detected properly

### ISSUE THREAD

**Issue by segdy** [nielsfaber/alarmo#587]
### Alarmo Version

1.9.5

### HA Version

2022.9.7

### Bug description

It seems that sensors with device class "tamper" are not properly detected in Alarmo. While they can be manually added, user has to untick “XXX items are hidden” where then they show up as type "Unknown". Afterwards all settings have to be manually applied, i.e., the default settings do not apply.

My assumption is that the list for [tamper in Alarmo](https://github.com/nielsfaber/alarmo#sensor-types) does not include the device class "tamper" itself that exists in Home Assistant. Adding "tamper" to this list possibly fixes the issue.

### References

- https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/919
- https://github.com/nielsfaber/alarmo/issues/586
- https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/918

### Steps to reproduce

Take the tamper sensor as exposed by any ZigBee contact sensor (Tuya in my example). It is device class "tamper" in Home Assistant. It shows up as "Unknown" in Alarmo.

**Comment by segdy** [comment]
This is awesome! Very much appreciated. Looking forward to the release & trying it out.

**Comment by nielsfaber** [comment]
This is now added in the v1.9.6 release.
Please try it out yourself, you can close the issue if all is fixed now.

**Comment by segdy** [comment]
Hi Niels, not sure if I did something wrong but I think it doesn't work :-( Just upgraded to v1.9.6, restarted.
Still no Tamper contacts show up (except one):

<img width="530" alt="image" src="https://user-images.githubusercontent.com/7464149/196085942-ae5973ed-aca0-4b0c-bb60-6a3932a29e1a.png">

If I remove "80 items are hidden", all the tamper sensors are still detected as "Unknown":

<img width="617" alt="image" src="https://user-images.githubusercontent.com/7464149/196086054-38ebd5ce-5990-43c9-a97e-db3f21caf50b.png">

However, their settings are correct. Example:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/7464149/196086158-54358a67-5904-431c-9dde-db09e4d4fb0a.png">

**Comment by segdy** [comment]
EDIT: Sorry please dismiss. Alarmo was upgraded but it seems there are issues with the frontend and the app. It still shows 1.9.5 in the app but 1.9.6 with a browser and the Tamper sensors show up there :-) :-) Trying out right now...
