### ISSUE TITLE
Entity Info shows button Arm Home even if disabled

### ISSUE THREAD

**Issue by hesspoint** [nielsfaber/alarmo#589]
### Alarmo Version

v1.9.5

### HA Version

2022.10.2

### Bug description

When I open the alarm entity box "Info" I see 2 buttons "ARM HOME" and "ARM AWAY". See screenshot

![Screen Shot 2022-10-10 at 21 59 40](https://user-images.githubusercontent.com/67288231/194943304-a837a388-5c66-457d-a0f4-1754beb0b4d2.png)

When I click "ARM HOME" I get an error that it failed to call service. ARM AWAY works fine

![Screen Shot 2022-10-10 at 22 00 56](https://user-images.githubusercontent.com/67288231/194943480-7ef739c6-e8ae-4a48-97d2-ac4f59186cf1.png)

I guess it is because I have disabled the Armed Home in the Settings.

I would like to have an "ARM NIGHT" button instead because I use that Alarm all the time. Can I customize somewhere which of the buttons are shown there?

**Comment by nielsfaber** [comment]
This is a bug in HA, not in Alarmo. I cannot influence this.
