### ISSUE TITLE
Feature request - Test button on notification page

### ISSUE THREAD

**Issue by cokeman0** [nielsfaber/alarmo#59]
When creating a new notification, a "test" button, would be nice.

**Comment by bobvmierlo** [comment]
Would love this feature aswell.

**Comment by nielsfaber** [comment]
Since many people seem to like this feature, I will try to add it soon.

**Comment by nielsfaber** [comment]
Will be added in the next release: https://github.com/nielsfaber/alarmo/commit/24e28caef4f654a6a02c3f15be0773ba99cde91a

**Comment by nielsfaber** [comment]
v1.5.2 is released which contains this feature.
Please try it out, and close the issue if your request is fulfilled.

**Comment by bobvmierlo** [comment]
> v1.5.2 is released which contains this feature.
> Please try it out, and close the issue if your request is fulfilled.

Works perfectly for me, thanks again!
