### ISSUE TITLE
Sensor with exit delay is not ignored in the duration

### ISSUE THREAD

**Issue by Puppetmaster91** [nielsfaber/alarmo#590]
### Alarmo Version

1.9.5

### HA Version

2022.10.3

### Bug description

When the front door sensor is open Alarmo require bypass to activate alarm. If you enable "arm after closing" will arm the alarm right away.

The sensor state needs to be ignored so that the door can open and close in the duration of the exit delay and even open before arming the alarm.

### Steps to reproduce

1. Use a sensor that supports Open/close state
2. Open front door (or any sensor with exit delay configured)
3. Type in code and try to arm alarm - **This should result in fail to arm** and requires bypass in order to arm the alarm.

**Comment by nielsfaber** [comment]
I'm a bit confused by your bug description.
What do you mean by
> Sensor with exit delay is not ignored in the duration'.

Which duration are we talking about?
What is meant by ignored?

Please help me through the steps to reproduce the issue.

So I configured my front door sensor to have an exit delay:
<img src="https://user-images.githubusercontent.com/16861605/196020854-70c19c75-4b65-4fdc-9baf-34ae911305e3.png" width="75%" height="75%">

Next I try to arm the alarm (in away mode, my home mode doesn't have exit time) while the door is open.

After the exit time has expired, I get this error:
<img src="https://user-images.githubusercontent.com/16861605/196020742-48a9736e-5d36-485a-9bf0-4c7019556469.png" width="50%" height="50%">

This is what I would expect to happen.
Is this different compared to what you are seeing?

You also state that:
> If you enable "arm after closing" will arm the alarm right away.

This setting will cause the alarm to change from 'arming' to 'armed' state (so skipping the rest of the exit delay) when you close the door.

**Comment by Puppetmaster91** [comment]
Hi Yes

it is different, because i don't get the exit delay if the door is opened and i get the error right away regarding "Could not arm due to the following sensors". 

I have the same settings as described in your reply.

Which duration are we talking about?
- The duration of the exit delay (30sec)
What is meant by ignored?
- Like other alarm systems i would expect to be able to open and close the door as much as i want within the exit delay.

This setting will cause the alarm to change from 'arming' to 'armed' state (so skipping the rest of the exit delay) when you close the door.
- Yea i had to put this setting on in order to arm the alarm when the door was opened, because it refused to start exit delay because the door was opened. Unless i bypassed opened sensors.
