### ISSUE TITLE
After adding entities, action won't save

### ISSUE THREAD

**Issue by rriempie** [nielsfaber/alarmo#591]
### Alarmo Version

1.9.5

### HA Version

2022.10.3

### Bug description

Hi,

The Alarmo integration works great but I recently I have a problem editing some actions. I have one action which turns all lights off when the alarm is armed. I want to add some more lights to the action but when I select a new entity and try to save the action, I get a warning ‘Verplichte sleutel “entity_id” ontbreekt.’ - ‘Required key “entity_id” is missing’.

I get this error also on other fields where I can choose the entity. I just won’t let me save it.
I hope someone can help.

Thanks!

### Steps to reproduce

I get this error also on other fields where I can choose the entity. I just won’t let me save it.

**Comment by nielsfaber** [comment]
I'm having some troubles to understand the issue you are running into.

So I have an action which turns on my office light when the alarm is armed:
<img src="https://user-images.githubusercontent.com/16861605/196020434-7ce1f64c-4f1b-4092-9b2a-a03b50010837.png" width="75%" height="75%">

After saving this action, I return to the action and modify it by adding a second light:
<img src="https://user-images.githubusercontent.com/16861605/196020499-b5114911-3107-4c35-9364-d6a7c5d9cb9d.png" width="75%" height="75%">

If I save these changes there is no error and the changes are stored fine.
If I understand you correctly, for you this results into an error?
Could you help me with the steps to reproduce the issue?

**Comment by rriempie** [comment]
Hi Niels, 

Thanks for investigating. The problem is solved. I think it had something to do with a non-existing entity because I've recreated the action all over again and now it let me save.

Problem solved!
