### ISSUE TITLE
Can't save configuration changes

### ISSUE THREAD

**Issue by otfrancis1** [nielsfaber/alarmo#595]
### Alarmo Version

v1.7.2

### HA Version

2022.10.4

### Bug description

Errors when trying to make some changes in Alarmo.

For example, adding a new sensor

### Relevant log output

```shell
Adding sensor:
Something went wrong!
Message format incorrect: extra keys not allowed @ data['name']

Response error: 400

Saving changes to Action:
Something went wrong!
Message format incorrect: extra keys not allowed @ data['actions'][0]['service_data']

Response error: 400
```

**Comment by otfrancis1** [comment]
screenshot from when I try to add a user:
![image](https://user-images.githubusercontent.com/106662176/196901840-f8fdb86f-a0e8-46b1-ad48-5c99b1b1eac2.png)

**Comment by nielsfaber** [comment]
Update your Alarmo version.

**Comment by otfrancis1** [comment]
Thanks for a quick response

so this is weird, the alarm panel window shows version 1.7.2
![image](https://user-images.githubusercontent.com/106662176/196907606-2c0f211c-8668-4902-9a4d-06c97bfebdda.png)
but I have downloaded the latest version and the manifest file shows 1.9.6
![image](https://user-images.githubusercontent.com/106662176/196907821-3e036e71-6d6f-4931-a372-abf9e1d13644.png)

I have completely removed and reinstalled the plugin but the issue persists

**Comment by nielsfaber** [comment]
If you see a different version in the corner than what is installed, you need to clear the browser cache.

**Comment by otfrancis1** [comment]
That did it, thank you.

what an annoying issue, do I need to always refresh the cache when I update? I'm on Firefox.

**Comment by nielsfaber** [comment]
HA uses caching on the entire frontend.
I am unable to request the clearing of the cache from Alarmo’s side.
So yes, you should always check the version number in the corner after updating.
