### ISSUE TITLE
Trigger alarm from outside Alarmo

### ISSUE THREAD

**Issue by SEKCobra** [nielsfaber/alarmo#596]
Hello! I am using Alarmo with a Ring Alarm Keypad (Gen1) and wanted to implement the Panic Alarm function. I noticed there is currently no way to trigger the alarm from Automations. I think it would be beneficial to allow this. Obviously I could implement the behavior outside of Alarmo, but that means that all the dependent functions would need to be duplicated. (For example: I am running a siren as well as the keypad being set to "Alarm mode". If I can just set alarmo to triggered, this works natively. Otherwise I need to reimplement this all over again for the panic function.)

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Add a command to set Alarmo to "triggered" immediately.

### Additional info
Like the native
`service: alarm_control_panel.alarm_trigger
data:
  code: 1234`

**Comment by nielsfaber** [comment]
You can use the service alarm_control_panel.alarm_trigger.
Is it not working for you?

**Comment by SEKCobra** [comment]
I did try that, it only sets it to pending and uses an unknown (to me) delay, I am assuming it's the entry delay. It does this even when disarmed.

**Comment by nielsfaber** [comment]
Perhaps it's better to change Alarmo and make the `alarm_trigger` service act instantly, instead of with entry delay.
What do you think?

**Comment by SEKCobra** [comment]
Yeah that would work as well. I'd expect a manual trigger to always be
instant and bypass any delay.

**Comment by nielsfaber** [comment]
I made a small change which will cause the service to trigger the alarm instantly (https://github.com/nielsfaber/alarmo/commit/c6c4d8573bdcdf5f2a877d4e1ac5501eb9ccdcd8).
I will let you know when the next version is released which contains this change.
In the meantime you could manually update the file in custom_components folder if you don't want to wait.
