### ISSUE TITLE
Android display issue

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#6]
Opening the alarm panel settings page on the android HA app you can't actually see all the settings when it's in portrait mode - page is too wide.

**Comment by Extreme79** [comment]
Same issue for me. Impossible to correctly view alarmo page inside ha android app

**Comment by nielsfaber** [comment]
This is taken care of.
Will release a new version soon, which is mobile-friendly.

**Comment by nielsfaber** [comment]
Updating to v1.1.0 should fix it.

**Comment by stefanolson** [comment]
Seems much better. Will close this.
