### ISSUE TITLE
Arming delay not activated

### ISSUE THREAD

**Issue by Matz88** [nielsfaber/alarmo#600]
### Alarmo Version

v1.9.6

### HA Version

2022.10.5

### Bug description

In a multi-areas system, not all areas are affected by the arming delay. In my case only one which has one sensor only.
Arming is set to 30s in teh specific mode of use, 
The area affected by the arming delay issue has 3 sensors. Only for one of them, the arming delay is enabled. But also enabling it for all of them, does not solve the issue.
The area not affected by the arming delay issue shows the same behaviour both if the alarm is activated at master or area level.
Any clue?
I can provide more detail/help with additional tests.

**Comment by Matz88** [comment]
Sure:
These are the settings for two of the modes: 

**Away (delayed arming 30s, delayed activation 30s):**
![image](https://user-images.githubusercontent.com/6189282/199407761-17376d9d-e6f7-4374-8bb7-7f55ece4ea21.png)

**And In home (immediate activation and arming):**
![image](https://user-images.githubusercontent.com/6189282/199407845-c73304ed-119f-4095-b0e4-8f7868ad46c7.png)





**Away mode is active in all zones
"In home" mode is not, but is active for "Pian terreno". Specifically for "Pian terreno" that has only one sensor named also "Pian terreno", the delayed arming and activation is enabled:**
![image](https://user-images.githubusercontent.com/6189282/199408134-08807d36-14ee-4a04-bc20-2c05d52c3517.png)

**In the zone "Primo piano" there are several sensors: among those, "corridoio" has both delays enabled:**
![image](https://user-images.githubusercontent.com/6189282/199409327-cc617a6c-e04c-4bef-8523-9aade63f5d6e.png)
**while the other 2 sensors (like here below "camera da letto") of zone "Primo piano" not:**
![image](https://user-images.githubusercontent.com/6189282/199408462-4c7fd0c1-8b76-4e50-85fa-71e96dec19bb.png)

What happens is that the arming is delayed only for the zone "pian terreno", while "Primo piano" is armed immediately also if one sensor has delayed activation.
![image](https://user-images.githubusercontent.com/6189282/199408556-7e17721e-9229-4165-85ae-bc1074307bcf.png)
Is not just an aestetical issue, I have also tried to actually activate the "corridoio" sensor during the arming delay time and the alarm triggers. 
Even if I set all the sensors in the zone "primo piano" to have the arming delay, nothing changes.

Plus another thing is that I have set siren time to 1 minutes, see at the beginning, but the alarm stays on forever.

**Comment by nielsfaber** [comment]
I read your report 3 times and still don't really get the issue.
If I understand you correctly, the issue is that you set up area 'primo piano' with exit delay, but it arms directly?
Are the screenshots you shared corresponding to this area (there is a dropdown list in the 'modes' configuration to select the area)?
You are sharing quite some settings for the sensors, what are you intending to say? The delay setting is applicable to the area. Even if an area contains no sensors which have exit delay enabled, it will still do the countdown when arming.

Have you tried arming the 'primo piano' separately (i.e. not via the alarm master), to see how it behaves?
For me the logbook gives a good insight:
![image](https://user-images.githubusercontent.com/16861605/200185228-d8265d0f-0657-48cd-a295-98128e4c62df.png)
There is 10 seconds between arming and armed state --> this is equal to the exit delay configured for the away mode.

**Comment by Matz88** [comment]
"If I understand you correctly, the issue is that you set up area 'primo piano' with exit delay, but it arms directly?"
   --->> correct

in the middle of the screenshots I have added notes per each one of them, some are relevant to "primo piano" which arms directly and others to "pian terreno" which instead works as intended, with the arming delay

Under each sensor, under "advanced setting, I see the possibility to enable or not the arming delay, is this function actually enabling the arming delay only to a specific sensor? Or is the arming delay always applied to the whole zone? Because in may case looks like this setting has no effect.

About the logs, tryng to arm independently the zones: for the area "pian terreno" I see it clearly going to "activation" and then "armed" as intended, while for "primo piano" it goes straight to "armed"

My observation is that only the zone "pian terreno" with only one sensor with arming delay activated in the advanced setting, has it duly applied. Instead the arming delay does not work in all the other zones which have more sensors in, some with and some without the arming delay activated in thw advanced setting.

**Comment by Matz88** [comment]
Sorry...I got it now...I was trying act on the sensors advanced setting to enable or disabling the arming delay, but actually it has forst to be done in a zone specific way under the "general" tab...me idiot, I understood it wrong, now that is properly set both sides (general and sensor advanced settings) works as expected...niece piece of work your, I would say!
