### ISSUE TITLE
entry delay not applied

### ISSUE THREAD

**Issue by chino-lu** [nielsfaber/alarmo#601]
### Alarmo Version

1.9.6

### HA Version

2022.10.5

### Bug description

even though the entry delay is activated in the advanced settings of the sensors, an activation of the sensor will trigger the alarm immediatly.

### Steps to reproduce

1) set up alarm with a window contact sensor (test with Silvercrest smart window and door sensor (HG06336) and Aqara Door sensor)
2) activate the Use entry delay in advanced settings
3) trigger the alarm by opening the front door.

**Comment by nielsfaber** [comment]
Here's my attempt to reproduce this:

Settings for armed away:
<img src="https://user-images.githubusercontent.com/16861605/199326434-13ac8f88-5285-438a-beb2-10243e051f3d.png" width="75%" height="75%">

Settings for window sensor:
<img src="https://user-images.githubusercontent.com/16861605/199326529-33f82414-defd-426a-acb4-1dc6a2ea1124.png" width="75%" height="75%">

Next I open the window when the system is in armed away:
<img src="https://user-images.githubusercontent.com/16861605/199326950-f50a1abe-81d0-438a-84a5-58bcc6815cd7.png" width="75%" height="75%">

Alarm is 20 seconds in state 'pending' before it becomes triggered, so the entry delay is applied.

Please provide additional information for me to reproduce this issue.

**Comment by chino-lu** [comment]
hm interesting... I checked the log of the alarmo:
<img width="551" alt="grafik" src="https://user-images.githubusercontent.com/43790689/199332284-9888d16d-0848-4838-87f8-d6f5852a1ebd.png">

as visible, it changes to pending, and immediatly to triggered.

but the settings are the following:
<img width="590" alt="grafik" src="https://user-images.githubusercontent.com/43790689/199332391-2c3ceeab-9e27-468d-a275-0c1d2349c991.png">

**Comment by chino-lu** [comment]
for motion detectos, the delay is working as inteded

**Comment by nielsfaber** [comment]
Please check your sensors page, click on the advanced settings to ensure they have the delay enabled.

**Comment by chino-lu** [comment]
this is the case:
<img width="592" alt="grafik" src="https://user-images.githubusercontent.com/43790689/199333548-305a449a-ace2-4449-9184-feba238c36b7.png">

I even tried to change to window and motion, but no change.

**Comment by nielsfaber** [comment]
I see you have 26 sensors linked, are you sure this one is triggering Alarmo?
You could see it either via the Alarmo card, push notification or attributres of the alarm_control_panel entity in the Developer tools tab.

**Comment by chino-lu** [comment]
found the issue... included a group where the sensor is included ... sadly, this group also included the other tested aqara sensor... which is the reason that also for that sensor the delay was not working.

Removing the group fixed the issue

thanks a lot
