### ISSUE TITLE
Trigger Time options

### ISSUE THREAD

**Issue by nhasch** [nielsfaber/alarmo#602]
I would like to set the trigger time to less than 1 minute. I use a custom armed mode to have notifications play if any doors or windows are opened but with the trigger time only going down 1 minute if another door or window open before it rearms I don't get a notification.

**Comment by nielsfaber** [comment]
You can click on the unit (i.e. minutes) next to the slider to change it into seconds.

**Comment by kucau0901** [comment]
i found out minimum in sec, is 10 sec. would be nice if there is option to 0 sec where alarm can be triggered indefinitely and rearm. i use automation to read state of alarm mode.

**Comment by nielsfaber** [comment]
@kucau0901 
> i found out minimum in sec, is 10 sec. would be nice if there is option to 0 sec where alarm can be triggered indefinitely and rearm. i use automation to read state of alarm mode.

This is incorrect. If you drag the slider all the way to the left it will do as you expect:
![image](https://user-images.githubusercontent.com/16861605/201267229-68caa68f-b6c2-4600-8d74-e22e969b602f.png)
