### ISSUE TITLE
Option to only notify the user who caused a notification to happen

### ISSUE THREAD

**Issue by segdy** [nielsfaber/alarmo#604]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal

Alarmo has Notifications that work nicely. I use "Notify" as target to send them to all my devices.

However, there is one catch: When I try to arm and "Notify on failure" executes, the whole family gets the notification. It would be amazing if there is the option to send a notification only to the devices of the user who actually caused this trigger to happen (or alternatively, the last person who did)

**Comment by nielsfaber** [comment]
How would alarmo know which user triggered the alarm?
I don't see any relation between sensors and users.

**Comment by segdy** [comment]
Hi Niels, that’s not what I mean. Of course there is no way to figure out who triggered the alarm.

but there is a way to figure out who TRIED to arm the system and the notification “Failed to arm” should be sent to that user’s devices only. As I wrote, this could be done by either keeping a track of notifications or just storing who last operated Alarmo (ie trying to arm).


I know this is not easy and I was banging my head around how I would solve this in HA directly.


While this is not important, it has become a regular annoyance: Suppose my wife is at work, I am leaving and want to arm the system. I arm and all of the sudden she get the message “Failed to arm because window xy is open” where it would be preferable if only I would get this since I tried to arm the system.


Maybe there is a better way around this but I hope you get the idea.

**Comment by segdy** [comment]
I am aware there is no easy or straight forward solution but I'd still be curious if something like this can be implemented and how.

**Comment by nielsfaber** [comment]
I understand your request and agree this is a good addition.
But I'm also not completely sure at this point how to implement this, so this request might be open for a while.

For my understanding:
* Are you using notifications configured in Alarmo or in HA?
* Are you and your wife using different PIN codes, devices, etc.? How could alarmo tell who (dis)armed?

**Comment by segdy** [comment]
1) I am using the notifications from Alarmo

2) We don’t use pins but we have our own devices. devices are assigned to users (or at least can be), so that provides a link, at least in principle. If there is an issue with it, providing an additional mapping user/device would still be a decent option as well in my opinion

**Comment by nielsfaber** [comment]
The only information that I receive in alarmo is what is sent in the service call (service data).
So I have no way to identify the user through the used device, a PIN code would be the only unique signature as far as I can see.
