### ISSUE TITLE
Distress Code(s)

### ISSUE THREAD

**Issue by MattWeiler** [nielsfaber/alarmo#607]
Either specifying a username/code as a distress code and then allowing actions to be created which target when these distress codes are entered.

### Checklist
-  For now, I've just created a flow in **_NodeRed_** which listens for alarm disarm events and if the username is our distress user, it fires an event of my choosing.
-  Since this is a pretty standard feature of conventional alarm system, I feel that other users would benefit from it too.

### Proposal
Having the ability to add a "_distress code_" would be very helpful.
This could just be a boolean flag on each username/code.
_This would allow each member of a home to have 2 codes, 1 regular code and 1 distress code_

Failing that, if while creating an **_action_** if we could have the ability to select the **_username_** if the **_event_** is that of "**_Alarm is disarmed_**".
This would basically allow us to do what I've done via **_NodeRed_**.

**Comment by nielsfaber** [comment]
Can you please add your request to #248 ?
This is a roadmap feature which I want to pick up soon (especially if there is a lot of interest for it).
