### ISSUE TITLE
Danish langauge

### ISSUE THREAD

**Issue by BDSmmadsen** [nielsfaber/alarmo#609]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I would like to see danish added for langauges.

### Additional info
Can do the translation

**Comment by nielsfaber** [comment]
You could create this translation yourself.
Go to this folder: https://github.com/nielsfaber/alarmo/tree/main/custom_components/alarmo/frontend/localize/languages and download the `en.json` file.
Translate all the lines (right part of each line is translation) and save it into a `da.json` file.
I believe you could upload it (into the same folder of before), by clicking on the right side:
<img src="https://user-images.githubusercontent.com/16861605/202793401-185fed01-1296-45c3-99da-09590f9ee429.png" width="50%" height="50%">
This should open a 'pull request' allowing me to review it and give you permission to make changes to Alarmo.
In the same way you can also make updates in the future.

If you wish to test your translation before uploading, please let me know and I can create a file for you which you can run locally.

Good luck 👍
