### ISSUE TITLE
No configuration panel

### ISSUE THREAD

**Issue by mikyjazz** [nielsfaber/alarmo#61]
HI, I installed alarmo via HACS but there is no configuration panel... I can view the Alarmo integration in the integrations panel but there is no alarmo configuration panel even if I select(click) the entity or the device link...

"4.The Alarmo integration is ready for use. You can find the configuration panel in the menu on the left."
There is nothing...

![alarmo](https://user-images.githubusercontent.com/38558161/102025978-adcc3a80-3d9b-11eb-9e61-eea94b79a97b.jpg)

**Comment by nielsfaber** [comment]
It should show up in the menu:
![image](https://user-images.githubusercontent.com/16861605/102042608-8cd30c00-3dd2-11eb-9658-de524b2bb2ea.png)

If it doesn't see if there is an error printed in the HA log.
If not, maybe try emptying your browser cache.

**Comment by mikyjazz** [comment]
I had the menù hidden but in reality I was looking for it in the integrations tile ... Found ... Very thanks, sorry for the inconvenience.
