### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by robmikulec** [nielsfaber/alarmo#611]
### Alarmo Version

v1.9.6

### HA Version

2022.11.4

### Bug description

After the alarm is triggered, the notification only triggers on the first change of sensor state.  For instance, if I open an exterior door when the alarm is armed (Home or Away) it will trigger the notification.  If I then walk past a motion sensor, there will be no notification.  

### Steps to reproduce

Simply create a notification based on the alarm being triggered.

service: notify.mobile_app_robs_iphone
data:
  message: The alarm was triggered because {{open_sensors}}
  title: Security Alert

**Comment by nielsfaber** [comment]
The alarm is only triggered once, this is not a bug.
