### ISSUE TITLE
Adjust volume in notifications 

### ISSUE THREAD

**Issue by B0ndo2** [nielsfaber/alarmo#616]
I use a media player with TTS in notifications. It would be great to be able to set the volume of the media player in notifications

**Comment by santiniuk** [comment]
Hi. Would like to second this request. Alarmo is fantastic. This tweak would be extremely useful for my usage also.
Thank you for your consideration.

**Comment by kevindesousa** [comment]
It will be great 🙏

**Comment by nielsfaber** [comment]
Do you mean to have alarmo execute the service volume_set (https://www.home-assistant.io/integrations/media_player/#service-media_playervolume_set) ?

I so, personally I would have alarmo afterwards also restore the volume to the previous setting.

**Comment by DamGranger** [comment]
I think this feature is needed. I, today, would'nt be able to hear Alarmo notifications because of the media player previous volume (using tts_edge).
