### ISSUE TITLE
Broken Notifications prevent Actions from executing

### ISSUE THREAD

**Issue by dougmaitelli** [nielsfaber/alarmo#617]
### Alarmo Version

v1.9.4

### HA Version

2022.11

### Bug description

For some reason, the alarmo config in the data store has references to devices that don't exist in my HA, probably deleted a long time ago.
These devices don't show in the alarmo UI when configuring notifications, but no matter how many things I change they stay there in the data store.
When the notifications run, these devices cause exceptions which prevent any actions from running.

IMO, there should be a separate exception handling for notifications and they should not prevent actions from running.
Also, UI should somehow discard these invalid entries.

### Steps to reproduce

I am not really sure how to "cause" the notifications to reference an invalid device.
But I assume:
* Add a device to HA
* Setup notifications for that device
* Remove that device and add another
* Update your notifications to use that new device
* At this point there should be no invalid devices on the UI, but it is still there in the data store
* Now create actions and try to trigger them
* They will fail

### Relevant log output

```shell
2022-10-16 15:24:10.067 ERROR (MainThread) [homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1664863292', 'disarmed', 'armed_home')

Traceback (most recent call last):

File "/config/custom_components/alarmo/automations.py", line 123, in async_alarm_state_changed

await self.async_execute_automation(automation_id, alarm_entity)

File "/config/custom_components/alarmo/automations.py", line 223, in async_execute_automation

await async_call_from_config(

File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 166, in async_call_from_config

await hass.services.async_call(**params, blocking=blocking, context=context)

File "/usr/src/homeassistant/homeassistant/core.py", line 1685, in async_call

raise ServiceNotFound(domain, service) from None

homeassistant.exceptions.ServiceNotFound: Unable to find service notify.mobile_app_douglas_pixel_4_xl
```
```

**Comment by nielsfaber** [comment]
Thanks for informing me of this behavior (I was not aware), sorry for the delay picking this up.

I just made a fix for this in https://github.com/nielsfaber/alarmo/commit/b3171499ff1c89f752983e56c83e0ae06ff3c0a5
I can confirm that with these changes, when any action fails the subsequent actions will still be executed.

The logs will now print an error:
> Execution of action <unique id> failed, reason: Unable to find service notify.<some_missing_service>

Which should raise the attention of the user. 
Ideally the actions panel in Alarmo will mark which action/notification is broken as well, but this not in place yet (I believe HA will also not show this for their automations).

**Comment by nielsfaber** [comment]
This is now released, so please test it yourself and confirm all is fine now 👍

**Comment by dougmaitelli** [comment]
That was fast :)
Updated and everything now works perfectly. Thanks!
