### ISSUE TITLE
Buttons HA not working

### ISSUE THREAD

**Issue by aavosnl** [nielsfaber/alarmo#621]
### Alarmo Version

v1.9.7

### HA Version

2022.12.1

### Bug description

The arm, disarm and other buttons in de alarmo panel not are not working. so arming and disarming true the alarmo panel in HA is not working anymore

**Comment by nielsfaber** [comment]
Try [alarmo-card](https://github.com/nielsfaber/alarmo-card) instead.
It should show you exactly what's going on when arming fails.
Otherwise, check the HA logs for the reason.

**Comment by aavosnl** [comment]
Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:520
Integration: Alarmbedieningspaneel (documentation, issues)
First occurred: 21:26:36 (1 occurrences)
Last logged: 21:26:36

Platform alarmo does not generate unique IDs. ID alarm_control_panel.alarmo is already used by alarm_control_panel.alarmo - ignoring alarm_control_panel.alarmo
is the only thing in my log. 

On the alrmo-card is also everything available the buttons to arm, disarm ....  but when clicking on it the alarm is not going in to the armed mode or the mode that have being used

**Comment by nielsfaber** [comment]
Please share a screen video or something to illustrate the problem.
Without more info i cannot help you.
Here all works OK, also on version 2022.12.

**Comment by aavosnl** [comment]
Logger: homeassistant.helpers.service
Source: helpers/service.py:637
First occurred: 21:37:34 (3 occurrences)
Last logged: 21:37:46

Unable to find referenced entities alarm_control_panel.alarmo or it is/they are currently not available

![alarmo](https://user-images.githubusercontent.com/24371158/206874637-c4ecbfbd-a989-46e4-9a98-f3265f64b682.png)

**Comment by nielsfaber** [comment]
> Unable to find referenced entities alarm_control_panel.alarmo or it is/they are currently not available

This error is quite serious.
Check the developer tools -> States to see if the alarm entity is there. If there's a duplicate you might need to remove it manually (sometimes restarting HA helps as well).

Your screenshot shows that you are not using alarmo-card. I cannot help you with the HA alarm card.

**Comment by tlizakow34** [comment]
I do not have duplicates but have the same issue as above.

**Comment by aavosnl** [comment]
it worked again for some weeks. the last days it is not working anymore with the same issue of this topic
