### ISSUE TITLE
Cannot use sensor state as pin to disarm

### ISSUE THREAD

**Issue by ematt** [nielsfaber/alarmo#622]
### Alarmo Version

v1.9.7

### HA Version

2022.12.1

### Bug description

A sensor state cannot be used as pin to disarm Alarmo

### Steps to reproduce

1. Have Alarmo require pin "4321" to disarm
2. Alarm 
3. Go to developer-tools/service and send

> service: alarmo.disarm
> data:
>   entity_id: alarm_control_panel.alarmo
>   code: sensor.pin_code

Alarm is not disarmed as expected
State of sensor.pin_code is 4321 which is the correct pin code

Sending a the same pin code hardcoded works
> service: alarmo.disarm
> data:
>   entity_id: alarm_control_panel.alarmo
>   code: '4321'

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.alarmo.alarm_control_panel
Source: custom_components/alarmo/alarm_control_panel.py:304
Integration: Alarmo (documentation, issues)
First occurred: 3:39:48 PM (6 occurrences)
Last logged: 3:53:59 PM

Wrong code provided.
```

**Comment by nielsfaber** [comment]
This is not a bug, there is nowhere implied that you are able to enter another entity ID here.
Alarmo (as well as other alarm integrations in HA) interprets the entered text as pin.
If the PIN is exposed in another entity, the security is compromised. I would recommend to do so.

**Comment by ematt** [comment]
Make sense as the pin would be stored in the logbook.

I want to create a physical keypad (similar to http://d1unzhqf5a606m.cloudfront.net/images/large/honeywell-5828-wireless-fixed-english-alarm-keypad.jpeg?1547073527)  to arm and disarm Alarmo. It runs on esphome software. 
Could you tell me if it is possible to arm or disarm Alarmo from esphome?

**Comment by nielsfaber** [comment]
With esphome you can make use of HA services, see [here](https://esphome.io/components/api.html#homeassistant-service-action).  So it should work the same as from the Developer Tools page.

You could also consider to use MQTT for communication instead. The benefit is that by subscribing to the event topic, you will get feedback from Alarmo, e.g. in case a wrong pin was entered, sensors blocking the arming operation, etc.

**Comment by ematt** [comment]
Thank you
