### ISSUE TITLE
Triggering door sensors during exit delay will disarm the alarm

### ISSUE THREAD

**Issue by securebrian** [nielsfaber/alarmo#625]
### Alarmo Version

v1.9.7

### HA Version

2022.12.6

### Bug description

When setting alarmo to "armed away" with an exit delay, the alarm will disarm when a door sensor is triggered while arming. I set the exit delay to 120 seconds. I should be able to walk out the door while it is arming. No matter which door I exit through, the alarm goes from arming to disarmed. If I set the alarm and do not trigger a sensor while arming, the alarm behaves normally.

### Steps to reproduce

Set alarmo to armed away with an exit delay. Then trigger any door sensor during the exit delay and the alarm reverts back to disarmed.

<img width="696" alt="Screen Shot 2022-12-17 at 4 22 17 PM" src="https://user-images.githubusercontent.com/82780897/208268064-376547ec-0e6b-48b5-9077-933ff8973283.png">
<img width="643" alt="Screen Shot 2022-12-17 at 4 23 04 PM" src="https://user-images.githubusercontent.com/82780897/208268065-471ff90c-da52-4865-b881-e8da78b525ad.png">

**Comment by nielsfaber** [comment]
Please click on the front door sensor, ensure this setting is applied/:
![image](https://user-images.githubusercontent.com/16861605/208282839-324e93fd-2306-4c9c-8838-ddf7b73e4cdc.png)

**Comment by securebrian** [comment]
The setting was toggled off. I spent so much time trying to troubleshoot and it was in front of my face the whole time. Thank you so much for your help.

**Comment by nielsfaber** [comment]
No problem, I'm happy to help!
