### ISSUE TITLE
Color for arm and dissarm changed?

### ISSUE THREAD

**Issue by Vabis1010** [nielsfaber/alarmo#627]
### Alarmo Version

1.9.7

### HA Version

2022.12

### Bug description

Before I had a green Color to tell alarmo was disarmd and a red one for arming. Now its charges to Grey for diskrediet and green for armed. Is thuis normal or can ik change this? 
Thks for replay.

**Comment by nielsfaber** [comment]
See https://github.com/home-assistant/frontend/issues/14802
Not caused by Alarmo but by HA itself.

**Comment by Vabis1010** [comment]
Is it positie to change it back?


Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nielsfaber** [comment]
I repeat:  This is not caused by Alarmo but by HA itself. 
You can switch to the alarmo-card if you prefer it: https://github.com/nielsfaber/alarmo-card
