### ISSUE TITLE
Alarmo not reacting on open door

### ISSUE THREAD

**Issue by hlalayan** [nielsfaber/alarmo#629]
### Alarmo Version

v1.9.7

### HA Version

2022.12

### Bug description

Afer armin to armed_away, and triggered by opening door and its return to arming  state, if its repeats 2 or 3 times, after that Alarmon not reacting on door opening.

### Steps to reproduce

in arming mode

### Relevant log output

```shell
no any log
```

**Comment by hlalayan** [comment]
The door sensors is an sonoff ZigBee contact sensors, 

![Screenshot 2022-12-28 180921](https://user-images.githubusercontent.com/50014656/209825062-832b4a5e-6532-441d-87a2-c49800a7ae92.png)
![Screenshot 2022-12-28 181008](https://user-images.githubusercontent.com/50014656/209825123-07dfae73-c23c-4d38-a775-ede0fa046694.png)
![Screenshot 2022-12-28 181520](https://user-images.githubusercontent.com/50014656/209825486-d255bdf2-b4a6-46bb-aa65-4caf55da5e42.png)

**Comment by nielsfaber** [comment]
Click on the sensor in alarmo to see it’s settings (you are now only in the ‘main’ sensor page).

**Comment by hhcalder92** [comment]
I am experiencing the same behavior. The Alarmo alarm is in an armed state with the sensors assigned, but does not change state to triggered when the sensor is opened.

If I use the manual configuration without alarmo, the state does get changed to triggered (ie `alarm_control_panel[0]platform: manual`). Haven't a chance to see what Alarmo does under the hood, but figured this might be helpful. 

Thanks in advance. 


Screenshots below:
![Screenshot 2022-12-28 at 1 26 03 PM](https://user-images.githubusercontent.com/7275599/209868279-00c5881a-d1ec-4a23-946e-21075dec52b7.png)
![Screenshot 2022-12-28 at 1 26 36 PM](https://user-images.githubusercontent.com/7275599/209868319-855bd9b5-d2b6-43f4-acfc-c49d44b9d5db.png)
![Screenshot 2022-12-28 at 1 27 14 PM](https://user-images.githubusercontent.com/7275599/209868375-bf55d59e-f159-4bbe-8f13-1fa43b5916b0.png)
![Screenshot 2022-12-28 at 1 27 41 PM](https://user-images.githubusercontent.com/7275599/209868413-1172c1f3-5573-4cdc-a217-b297a3baf0a3.png)

**Comment by nielsfaber** [comment]
@hhcalder92 you assigned your sensor to a group. When a sensor is grouped, 2 or more sensors in that group need to trigger within the set time interval, before the alarm will trigger.
If you remove your sensor from the group you will see the alarm triggering.

Note that grouping sensors is mostly useful for motion detectors (within the same room). These sometimes show glitches which could result in undesired triggering of the alarm.

**Comment by hhcalder92** [comment]
That did the trick. Thank you for the quick response @nielsfaber !

I see that in the description now, a nifty feature.

**Comment by hlalayan** [comment]
![Screenshot 2022-12-29 120541](https://user-images.githubusercontent.com/50014656/209922121-e73f55dc-3991-42d3-ad25-ecad679367e1.png)
