### ISSUE TITLE
MQTT state not updated

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#63]
I have seen this scenario:
I set a sensor as immediate, I let it open, I try to arm the alarm and it does not go to "arming". So far so good.
But what I have seen too is that the MQTT playload for the state (default alarmo/state) does not change to disarmed after that.
So, any device or app monitoring the state of the alarm does not get updated.

**Comment by nielsfaber** [comment]
There will only be a message sent through the state topic if the state changes.
So, no update on the state topic after sending a command, will mean that the state remains unchanged.

Messages sent through the state topic will become retained in the next update.

**Comment by tremebundo** [comment]
Then, I will wait for the next update.
Thanks a lot for your work.

**Comment by nielsfaber** [comment]
The retain function is in v1.4.0.
I hope this solves your problem.
If not, please re-open this issue.
