### ISSUE TITLE
Display can be kinda buggy on android

### ISSUE THREAD

**Issue by micle546** [nielsfaber/alarmo#631]
### Alarmo Version

1.9.7

### HA Version

2022.12.8

### Bug description

The display can get off center and doesn't scroll correctly  in some instances on android app. Android app ver 2022.11.0-full on Samsung s908u. 

Will post pics tomorrow if needed

### Steps to reproduce

Visit alarm actions, open action, view in yaml mode. Seems to happen with long lines in the yaml editor

**Comment by nielsfaber** [comment]
> Will post pics tomorrow if needed

Please do so.

I don't have any Android device, so I cannot see what you're seeing. An example would be very useful.
