### ISSUE TITLE
Use better icons for "armed away" and "armed vacation"

### ISSUE THREAD

**Issue by nxxxse** [nielsfaber/alarmo#632]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal

"armed away" is currently represented as a car driving away and "armed vacation" as a plane taking off. Both are too specific for my taste. I propose using more generic icons:

* "armed away" something like: https://fontawesome.com/icons/house-person-leave?s=regular&f=classic
* "armed vacation" something like: https://fontawesome.com/icons/island-tropical?s=solid&f=classic

### Additional info

Ok, I admit it, I was mainly triggered by the plane. It is bad for the environment ;-)

**Comment by Tom-ahawk** [comment]
Being able to change icons would be apricated. Now its also a inconsistency between the Alarmo pnel and icons appearing in Lovelace Tile card.

![image](https://user-images.githubusercontent.com/35527507/230430412-388cf4d3-d524-4bbf-9561-84b4761321c8.png)
