### ISSUE TITLE
Event for "Entry delay started" 

### ISSUE THREAD

**Issue by LukasMendez** [nielsfaber/alarmo#633]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I'm looking for a way to capture "entry delay started" events in the default automation builder of HA. 
The reason why state changes of my alarm panel is not enough is because I need a way to access the event data in order to know which sensor that caused the "entry delay started" to trigger. 

### Additional info
Right now this is possible from the Alarmo actions. 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/43059840/209479729-5d175f3c-caf6-4cb3-a20b-6ade723678ef.png">

However I would like something like this: 

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/43059840/209479744-07238080-d311-4a15-b4b9-88084574a8c2.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/43059840/209479757-710d2a85-9ef6-4fc8-84c1-76449f8de1bb.png">

**Comment by nielsfaber** [comment]
You can trigger on ‘state’ of the alarm_control_panel entity becoming arming.
