### ISSUE TITLE
After update to 2022.12 colors have changed

### ISSUE THREAD

**Issue by ferrarid61** [nielsfaber/alarmo#634]
### Alarmo Version

 v1.9.7

### HA Version

2022.12

### Bug description

After update the colors of Alarmi card changed. Now disarmed is gray ( before green) , armed is green(before red). I didn't check yet triggered. Thes are not appropriated colors.

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/alarmo/issues/627
