### ISSUE TITLE
Deleted areas still appear under blank lines as "[object Object]" and prevent displaying real Areas

### ISSUE THREAD

**Issue by kenaddams42** [nielsfaber/alarmo#635]
### Alarmo Version

1.9.7

### HA Version

2022.11.2

### Bug description

I've added some areas and deleted them to discover Alarmo. It turns out I've got 2 or 3 empty lines in the General > Modes > area field, and these extra entries can't be deleted. 

It also seems to prevent creating (or at least displaying) new areas: the dropdown box shows 3 real areas but none appear in the Areas section.

![image](https://user-images.githubusercontent.com/7167034/209586546-d08b7173-69b8-4786-a578-1839b8f74f14.png)

**Comment by vincentization** [comment]
I am still facing this exact issue on Alarmo v1.10.15 and HA2026.1.3. It seems to affect the ability to show active (added) sensors as well, the entire active sensors section is hidden since I assigned some of them to certain areas
