### ISSUE TITLE
Pressing buttons doesn’t do anything 

### ISSUE THREAD

**Issue by GRClark** [nielsfaber/alarmo#636]
### Alarmo Version

v1.9.7

### HA Version

2022.12.8

### Bug description

Every now and then the buttons on panel are unresponsive as well automations aren’t able to change mode.  Tried rebooting with no resolution.  As you can see in screen recording the buttons are being pressed but not doing anything.  Can set state in developer tools but nothing else works. 

https://user-images.githubusercontent.com/5118059/209889670-7a8ba9fe-0a7b-4a3c-b263-152bcff2e8bd.MOV

### Steps to reproduce

Noticed modes weren’t changing via automations, tried manually changing.

**Comment by tlizakow34** [comment]
I am also seeing the same issue and tried changing the entity IDs. It occured when updating Alarmo from 1.9.5 to 1.9.7.

**Comment by kaasszje** [comment]
Had this problem as well, removing the configuration and re-installing alarmo fixed this.

**Comment by coleander** [comment]
I had this issue, removed the integration and every related file and readded again and it started working. But now it randomly happened again. What is going on?

**Comment by coleander** [comment]
Okay just an update. I have figured out that this happens if one of your sensors are in the open state, so make sure none of your sensors are in an open state. I had a sensor being weird and I made sure it went to closed and restarted HA and now it works.

**Comment by nielsfaber** [comment]
@coleander i recommend installing alarmo-card, which will provide you with feedback of the cause in case arming fails.
Otherwise you should see this in the HA log.

**Comment by FauxHobo** [comment]
I've also been having this issue. Just doesn't arm or react to anything. Checking HA logs shows nothing, as if I wasn't even interacting with Alarmo at all.

**Comment by hardwareadictos** [comment]
Same issue here, 1.9.7 fresh installed (hadn't alarmo installed on the past)

**Comment by nielsfaber** [comment]
@FauxHobo @hardwareadictos 

Please enable debug logging for alarmo by adding this to the configuration.yaml (requires restarting HA):
```yaml
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```

This should provide additional lines in the HA log which could hopefully pinpoint to the issue.
Please share the results from the HA log when pressing the arm buttons.

**Comment by hardwareadictos** [comment]
> @FauxHobo @hardwareadictos
> 
> Please enable debug logging for alarmo by adding this to the configuration.yaml (requires restarting HA):
> 
> ```yaml
> logger:
>   default: warning
>   logs:
>     custom_components.alarmo: debug
> ```
> 
> This should provide additional lines in the HA log which could hopefully pinpoint to the issue. Please share the results from the HA log when pressing the arm buttons.

Sorry, just realized that I was using a wrong card for the alarm. With the Alarmo HACs card all works perfectly.

Thanks for the support 👍

**Comment by FauxHobo** [comment]
Thank you, I will. I reinstalled it again. Last time it stopped working after a few hours, this time, so far it's been working a few days. If it breaks again I'll send through the logs.
