### ISSUE TITLE
[Feature request] Suggestion: When opening a notification auto navigate to alarm panel

### ISSUE THREAD

**Issue by SinnoTech** [nielsfaber/alarmo#64]
Hi 

Great work on this intgration!

I dont know if this is possible at all with the companion app, but if the app was left on home page for instance it takes you to that page. Would have been an awesome feature to auto navigate to the Alarm panel page.

**Comment by nielsfaber** [comment]
This is not possible as far as I know.
The functionality is documented here: https://companion.home-assistant.io/docs/notifications/actionable-notifications/
For iOS there is the option `activationMode` which makes the app open after tapping the push message, but i cannot navigate in the app to a certain page.

Anyway, none of this is really in Alarmo, so you can experiment as desired by changing the notification settings in YAML.

**Comment by SinnoTech** [comment]
Thanks for the feedback niels.
