### ISSUE TITLE
browser_mod

### ISSUE THREAD

**Issue by snickers2k** [nielsfaber/alarmo#643]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
add official support for browser_mod

this would allow Alarmo to
- have info about which Area Alarmo was triggered and what the Exit-Delay-Door is. (and check if other doors are closed) #524 
- have the ability the get Alarmo in Fullscreen-Mode. #550 

### Additional info
Alarmo in Fullscreen-Mode is kind of possible already, but if the sensor-notification is showing up before the actual popup - the popup does not show the sensor-notification anymore. That kind of needs a fix. Especially on Smaller 7-10" Screens this would help a lot

**Comment by nielsfaber** [comment]
Do you mean alarmo-card or alarmo?
They are separate things (also have separate GitHub repository).

**Comment by snickers2k** [comment]
it's probably more about the alarmo backend to support browser_mod ? don't know
