### ISSUE TITLE
Alarmo  - Docker Compose

### ISSUE THREAD

**Issue by rseverett** [nielsfaber/alarmo#646]
Thank you for a great product and all the time you have invested in this solution!  Would it be possible to develop a Docker image file for this solution and upload it to Docker Image Library so "container installations" may still use this solution?  Will you also include a Docker Compose file [with your tweaks] if the solution has contingent requirements like a database, vol, etc?  

### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
[Docker-Compose file that works to install Alarmo]

**Comment by rseverett** [comment]
I assume no one is monitoring these comments.  understood.

**Comment by nielsfaber** [comment]
> I assume no one is monitoring these comments. understood.

Not true.
But since alarmo is a plug-in / custom component for HA I cannot provide a separate docker image for it.
Users can install HA as docker container and then install alarmo into it.
