### ISSUE TITLE
[Feature request] Ability to choose colour of lights and flashing

### ISSUE THREAD

**Issue by SinnoTech** [nielsfaber/alarmo#65]
Hi!

Again, great work done on this!

I have another possible suggestion, it would be brilliant if under actions, i could selct a light and instead of switching on and off, it actually flashes the light in lets say RED.

![image](https://user-images.githubusercontent.com/74432416/102205048-f0d8fb80-3eca-11eb-9d25-ee1fd1c7eff9.png)

**Comment by sharkyP** [comment]
i agree, i'm trying to set this via YAML however it wont let me that way either

**Comment by SinnoTech** [comment]
Hej sharky

Best I could get is to flash the light at 100% brightness. But i would actually like to have it flashing the full amount of time but i dont think thats a Alarmo thing but rather a light limitation on what HA can send to the light?

`name: Flashing Light
modes:
  - armed_away
triggers:
  - state: triggered
actions:
  - service: light.turn_on
    service_data:
      entity_id: light.lamp_ikea_02
      brightness: 255
      flash: long`

**Comment by sharkyP** [comment]
> Hej sharky
> 
> Best I could get is to flash the light at 100% brightness. But i would actually like to have it flashing the full amount of time but i dont think thats a Alarmo thing but rather a light limitation on what HA can send to the light?
> 
> ```
> name: Flashing Light
> modes:
>   - armed_away
> triggers:
>   - state: triggered
> actions:
>   - service: light.turn_on
>     service_data:
>       entity_id: light.lamp_ikea_02
>       brightness: 255
>       flash: long
> ```

I've actually got this working however you need to abandon the use of the actions part of the alarmo UI and jump into automations, you can then write your own in YAML with alot more flexibility
Here is what I have working so far..as you can see the light and notification can run in the same automation script

`### Disarm Light ###
- id: '1608167599575'
  alias: Alarmo - Disarm Light
  description: ''
  trigger:
  - platform: device
    device_id: a904412b44e27fb94c9e3da5d09d42e5
    domain: alarm_control_panel
    entity_id: alarm_control_panel.alarmo
    type: disarmed
  condition: []
  action:
  # push notification
  - service: notify.mobile_app_device_id
    data:
      title: "Security System Disarmed"
      message: "{{user}} disabled alarm system"
  # flash indicator light green
  - service: light.turn_on
    data:
      entity_id: light.lamp
      rgb_color:
      - 0
      - 255
      - 0
  - delay: 00:00:02
  - service: light.turn_off
    entity_id: light.lamp
  mode: single`
