### ISSUE TITLE
Ability to Duplicate Notifications

### ISSUE THREAD

**Issue by mattmansm** [nielsfaber/alarmo#650]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I've setup a number of notifications to send to myself, but in order to setup the same notifications for my wife, I need to re-create each one by hand. It would be great if there was an option to duplicate each notification and then I'd only need to adjust the target for each one. All of the notification wording and other settings would be copied.

### Additional info
Similar functionality to the Home Assistant Automations 'duplicate' function.

**Comment by nielsfaber** [comment]
I'm sorry, I did not have any time to work on this project recently. I will see if this can be added.
