### ISSUE TITLE
Allow tables to be sorted by clicking on the column heading

### ISSUE THREAD

**Issue by mattmansm** [nielsfaber/alarmo#651]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
It would be great if each of the data tables could be sorted by clicking on the respective column heading. For example, you cannot sort the list of users on the codes page, nor can you sort the table of actions by the name column.

### Additional info
Functionality to match the Home Assistant automations, scenes and scripts tables would be great. These can all be sorted by clicking on the header of each column.

**Comment by nielsfaber** [comment]
I'm sorry, I did not have any time to work on this project recently. I will see if this can be added.
