### ISSUE TITLE
Critical Notifications

### ISSUE THREAD

**Issue by Glennesink** [nielsfaber/alarmo#654]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Make channel and critical a option.

### Additional info
Add parameters from this articel to the actions of Alarmo >>
https://companion.home-assistant.io/docs/notifications/critical-notifications/

**Comment by SaltyBart** [comment]
That will be great 👍

**Comment by nagydavid** [comment]
@Glennesink @nielsfaber Hi All, has this feature implemented?
