### ISSUE TITLE
Exit delay not bypassing sensors

### ISSUE THREAD

**Issue by raphus** [nielsfaber/alarmo#658]
### Alarmo Version

v1.9.7 

### HA Version

2023.1.7

### Bug description

When trying to arm, the exit delay starts, but as soon as I open the door, it stops and disables (does not arm, "bypass required"). Only way i can arm then walk out is to:
1. open the door
2. override the 'open door' sensor
3. walk out and close the door. 

am I missing something? shouldn't the exit delay bypass any sensors for the 'exit delay' period?
![image](https://user-images.githubusercontent.com/5577312/216171516-7c4ddc17-4436-4f68-b2d1-0f062a327d95.png)

### Steps to reproduce

1. Ensure all sensors are cleared
2. Type in alarm code, then ARM AWAY
3. Delay starts "exit delay"
4. Open door; soon as the door opens, keypad says "bypass required" & arming is canceled.

**Comment by nielsfaber** [comment]
Yes, you’re missing something.
In the sensors page you can click on a sensor to change its settings.
There’s a setting ‘use exit delay’ which needs to be turned on for a sensor that is allowed to be active during the exit delay.

**Comment by raphus** [comment]
ah thank you so much. the door sensor was set to "tamper', not 'door', and those options were not there. 

much appreciate it!
