### ISSUE TITLE
During Exit Delay, opening window/door gives warning and aborts arming

### ISSUE THREAD

**Issue by segdy** [nielsfaber/alarmo#659]
### Alarmo Version

v1.9.7

### HA Version

2023.1.4

### Bug description

A conventional alarm system (the ones I am aware of) do neither trigger alarms nor warnings during the arming period ("Exit Delay").

This makes sense: The "Arming Away" can be engaged from the inside (at this point making sure all windows/doors are closed etc). From then on, one would have 1 minute to leave the house. Of course, leaving the house entails opening the front door. This action should be _ignored_ during the arming period.

However, in Alarmo, opening the front door during the arming period results in "Failed to arm" to trigger (I have configured with a notification) and aborts arming.

This means the system can effectively only be armed when already out side of the house.

The desired outcome would be to make "Failed to arm" only trigger at the beginning or the end or both of the Exit Delay.

In order to not break people's setup who expect something else, would it be an option to add this to the settings?
Something like:

```
Trigger 'Failed to Arm'
(o) At any time during Exit Delay (default)
( ) Only at the beginning of Exit Delay (when user initiates system arming)
( ) Only at the end of Exit Delay (when system arms)
( ) Both at the beginning of end of Exit Delay
```

If not configurable, the 2nd option would make most sense because this is when a person engages the alarm and is prepared to get feedback when something is wrong. At the end of Exit Delay might be useful for some but causes issue if someone left the house already and decided to leave a window open on the way out.

**Comment by nielsfaber** [comment]
in the sensors tab, click on the sensor and review its settings.
There is already a ‘use exit delay’ setting.

**Comment by segdy** [comment]
Indeed! Apologize for cluttering this issue list.
There is even "Arm after closing" and "Bypass automatically", both of which are pretty useful too.
Thanks for creating such a powerful framework!

**Comment by pbhm** [comment]
I think the 1st option would be ideal (speaking on my behalf ;-)) to have it as options, if possible.
Thank you indeed for all your work and effort creating Alarmo!
