### ISSUE TITLE
The attributes arm_mode, changed_by and bypassed_sensors are not replaced in notifications.

### ISSUE THREAD

**Issue by jbolanosg** [nielsfaber/alarmo#66]
When i use the attributes "arm_mode", "changed_by" and "bypassed_sensors" in notifications, they are not replaced in the message with your current values.

**Comment by nielsfaber** [comment]
do you place them between brackets as the example shows?
can you share your configuration?

**Comment by jbolanosg** [comment]
> 
> 
> do you place them between brackets as the example shows? Yes
> can you share your configuration? For example.. This is one of the my notifications:
![imagen](https://user-images.githubusercontent.com/22716962/102276822-5f32b380-3ef5-11eb-98e6-04224e8000cd.png)

**Comment by jbolanosg** [comment]
As I know something about python I was reviewing the ALARMO source code and I think that the current code only supports the replacement of the open_sensors attribute .... you could check this in the next line of the alarm code:
https://github.com/nielsfaber/alarmo/blob/8161699c116d55a9e6d952a74b2ee1471a38e303/custom_components/alarmo/automations.py#L115

**Comment by nielsfaber** [comment]
Ah yes you’re right!
I misread your issue, thought you had troubles with open_sensors as well.
For the others I could create support.
You’re the first one to ask for such function 🙂

**Comment by zbuh** [comment]
I was going to also request this. It makes sense.

**Comment by nielsfaber** [comment]
I added the support for these attributes in v1.4.1.
Note that `changed_by` and `bypassed_sensors` are not always defined.
The wildcards will be replaced with `""` (nothing) if there is no value for them.

It would be better if you could define different notification message depending on the circumstances, like:
> Alarm is armed.

In normal situation, vs:
> Alarm is armed with bypassed sensors {{bypassed_sensors}}.

If there are bypassed sensors.

However I don't see a easy way to support this currently.
Ideally I would make it available to all users, meaning that the UI should allow you to construct messages with optional parts.
This is a roadmap feature (currently not considered as a priority).

**Comment by jbolanosg** [comment]
Thank you...i test it coming soon.

**Comment by zbuh** [comment]
What are the available place holders now?

**Comment by nielsfaber** [comment]
The ones in this table: https://github.com/nielsfaber/alarmo#attributes

**Comment by nielsfaber** [comment]
@jbolanosg can this issue be closed?

**Comment by jbolanosg** [comment]
if this issue can be closed
