### ISSUE TITLE
Error with MQTT command

### ISSUE THREAD

**Issue by rp1783** [nielsfaber/alarmo#660]
### Alarmo Version

1.9.7

### HA Version

2023.2

### Bug description

When sending a any publish command, I'm receiving this error:

`2023-02-08 21:15:31.179 ERROR (MainThread) [homeassistant.util.logging] Exception in async_message_received when handling msg on 'alarmo/command': 'arm_home'
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 258, in async_message_received
    if command == command_payloads[const.COMMAND_DISARM]:
KeyError: 'disarm'`

**Comment by nielsfaber** [comment]
I can confirm this bug. 
I noticed the problem occurs in case the command payloads are left empty in the configuration.
As a workaround, please make sure to define the payloads (under page 'General' click the button 'MQTT configuration'):
!<img src="https://user-images.githubusercontent.com/16861605/226114099-3e644891-164d-498e-ae76-234899ac1c80.png" width="75%" height="75%">
I working on a fix for this issue in the next release of Alarmo.
Thanks for reporting 👍

**Comment by nielsfaber** [comment]
This is fixed in release v1.9.8.

**Comment by array81** [comment]
I use the last version but I have the same problem
