### ISSUE TITLE
localize ru

### ISSUE THREAD

**Issue by angelicaruta** [nielsfaber/alarmo#662]
### Proposal
[Hello. I have translated into Russian, where can I send the file?]

**Comment by nielsfaber** [comment]
Improvements can be submitted via pull request.
You can do this by creating a fork (local copy) of this  repository and making changes to it.
The PR is used for uploading your changes to this repository.

there is already a PR open for Russian translation: https://github.com/nielsfaber/alarmo/pull/657
Please add your contributions there.
I can only allow 1 version of Russian translation.

**Comment by angelicaruta** [comment]
Не получается прикрепить файл в формате json. Можно отправить в текстовом формате?

**Comment by angelicaruta** [comment]
I can't attach a file in json format. Can I send it in text format?
