### ISSUE TITLE
Problem with sensors

### ISSUE THREAD

**Issue by angelicaruta** [nielsfaber/alarmo#663]
### Checklist
- [* ] I checked for similar existing requests (both open and closed) before posting.
- [* ] My request is generic, other users may benefit from it too.

### Proposal
[Thanks to Neliss for the good work. I noticed one problem if the alarm is triggered by one sensor (for example, a window sensor), and then during the operation of the trigger, open another sensor (for example, a door), it is not visible in any way and if you leave this sensor open before arming after triggering, then this sensor is excluded from protection and then "close" it or "open" it is not visible. I made for myself a simple automation in which, according to the messages, I can see the order of opening sensors. But I don't understand much and did what I could. I would like it to work in Alarm, and not by third-party automation.]

### Additional info
[- id: Alarmo - sensors are triggered
  alias: Alarmo - sensors are triggered
  trigger:
  - platform: state
    entity_id: 
    - binary_sensor.0x00158d00031c6823_contact
    - binary_sensor.0x00158d00031e670e_contact
    - binary_sensor.0x00158d00031c6d31_contact
    to: 'on'     

  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alarmo
      state: triggered
    - condition: state
      entity_id: alarm_control_panel.alarmo
      state: armed_away
      
  action:
  - service: notify.telegram_id_1
    data:
      message: '{{ trigger.to_state.attributes.friendly_name }} - open']

**Comment by nielsfaber** [comment]
Alarmo will only respond to the **first** sensor that triggers the alarm.
It is already possible to set up a notification message with the name of this sensor.

If additional sensors are activated while the alarm is already triggered, Alarmo will not respond.
If I understand you correctly, you would like to have a message sent also in this case?

**Comment by angelicaruta** [comment]
Yes. Then the sensors can track the path of the criminal

**Comment by iAutom8** [comment]
I thought the same thing but figured I could quickly look at my other sensors, see what else was triggered, and map out a timeline.  However, that is a little work.  A trace of some sort would be a nice feature.  While the alarm is triggered, all sensors in the alarm mode would be logged as part of that trigger.  Similar to how traces work in Home Assistant automations.

For me, it is not a high-priority item but a nice-to-have.

Thank you
