### ISSUE TITLE
Notifications/actions on the master area do not work.

### ISSUE THREAD

**Issue by ichilton** [nielsfaber/alarmo#669]
### Alarmo Version

v1.9.7

### HA Version

2023.2.5

### Bug description

Notification and actions on the 'master' area do not work - so need to add notifications/actions for each area.

**Comment by nielsfaber** [comment]
I set up this notification:

![image](https://user-images.githubusercontent.com/16861605/226119286-bea91877-fa70-4d8c-a478-90b2f8d8c6e5.png)

Next I arm the master.
Notification is sent:

![image](https://user-images.githubusercontent.com/16861605/226119328-f002a3fe-31cd-4bba-bc66-a06900ab99b6.png)

In summary, I don't agree that
> Notification and actions on the 'master' area do not work 

Please provide details if you have some specific issue.

**Comment by ichilton** [comment]
That's strange - they don't seem to work for me.

Will re-test and get back to you!
