### ISSUE TITLE
YAML code in Actions (f.e. triggered alarm) does not work properly

### ISSUE THREAD

**Issue by HayaminiNL** [nielsfaber/alarmo#675]
### Alarmo Version

v1.9.7

### HA Version

2023.3.1

### Bug description

Within the 'triggered' action a task can be defined.

When this task is altered to YAML code and custom code is inserted, it can be tested and works great.
When the 'action' is saved, reopened, it defaults to 'entity' and cannot be tested.

Next when the alarm gets triggered, the YAML code is not executed and so no Siren is 'enabled' with high volume.
It only works when the task is set up with an entity/device and not with YAML code.

### Steps to reproduce

Create an action, set it to trigger on alarm.

Change ACTION to Yaml and include the yaml to call a service with some extra input to get the Zwave Siren activated with the correct settings.

Save the action, open de the newly created action and it shows an empty entity field and does not fall back to the custom Yaml code.

**Comment by nielsfaber** [comment]
I did some test with the following action:
![image](https://user-images.githubusercontent.com/16861605/226120614-efe86b64-a1e9-4e8d-a172-c1af072184b7.png)

If I save it and edit it again, the code is still there.

Can you share your action configuration (YAML code) so I could try the same as you do?

**Comment by HayaminiNL** [comment]
Hi Niels,

When I open the action it first displays:
![image](https://user-images.githubusercontent.com/107961050/226144495-28ec315f-ef19-4fc7-a54d-8455ac354dec.png)

Next when I switch it to YAML code i do see my service-call:
![image](https://user-images.githubusercontent.com/107961050/226144512-c872cbb7-517f-46dd-9d57-84b9aa5df80e.png)

This service call works perfectly when being called from the 'Developer Tools' -> 'Services' tab.
It changes the volume, the duration time and next switches the alarm on.

The script that is called via this service call is:
![image](https://user-images.githubusercontent.com/107961050/226144621-c6a1ded2-ec91-480f-a107-f03dabc79ad1.png)


Thanks in advance.

**Comment by nielsfaber** [comment]
I'm still having trouble reproducing the issue.
I set up an action like this:
<img src="https://user-images.githubusercontent.com/16861605/226154594-6d493f08-19a9-4cfa-ac26-a7971005cb32.png" width="75%" height="75%">
And configured the action to run when the alarm is armed.

I configured the script like this:
```yaml
sequence:
  - service: notify.persistent_notification
    data:
      title: Notification title
      message: >-
        Script was triggered with entity '{{ entity }}' and duration '{{ duration }}'
alias: Send notification
mode: single
```

When arming the alarm, the notification is triggered with the correct parameters:
<img src="https://user-images.githubusercontent.com/16861605/226154881-431b4a34-b40d-477a-a240-fd8b0e702575.png" width="75%" height="75%">

Perhaps you could try clicking the 'try it' button to see if the action is performed?
If that works, maybe the action is not triggered correctly.
For completeness, these are the conditions I configured for the action: 
<img src="https://user-images.githubusercontent.com/16861605/226155209-0614d271-3cb6-45ba-9088-5706217bf58d.png" width="75%" height="75%">
Could you troubleshoot if this is maybe the problem?

**Comment by HayaminiNL** [comment]
Good morning Niels,

When 'try it' is used, it works flawlessly, just like it can be executed from the DEV-tools->Services part of HASS.
When I replace the with the action to just turn on the siren, without YAML call to the script, it does make a lot of noice in the garage when the PIR or door-contacts are triggered in any armed mode.

This is the standard entity call with standard action:
![image](https://user-images.githubusercontent.com/107961050/226166181-2ab85be3-ad92-4a33-893f-05d71edac163.png)

**Comment by nielsfaber** [comment]
> When 'try it' is used, it works flawlessly, just like it can be executed from the DEV-tools->Services part of HASS.

The 'try it' button is intended exactly for the purpose of testing whether the configuration is OK.
Alarmo will (should) execute the action in the same way as when clicking that button.
If it works OK when clicking the test button, this suggests that the action is configured correctly.

Could you check whether the script is executed when it should?
You can see this under Settings -> Automations and Scenes -> Scripts

![image](https://user-images.githubusercontent.com/16861605/226172940-df4245e9-dd60-4864-b117-044cd2c304ed.png)

There should be the the time displayed when the script was last executed.
If you click the dots you can check the traces and see the parameters which were sent by alarmo:
![image](https://user-images.githubusercontent.com/16861605/226173073-726d5a27-b9b5-4cac-b5eb-c7e9a12449fa.png)

In my testing, all looks as it should.
At this point I have no clue what is happing on your side.
Did you also try to delete the action and create it again?

**Comment by HayaminiNL** [comment]
I have checked it too over and over and still nothing happens at the Siren object.

I have done a test by activating the PIRs once more and I get the following feedback from the 'Automations & Scenes' script debug:
![image](https://user-images.githubusercontent.com/107961050/226187396-02657a72-631d-42ce-8b53-f676099a3291.png)

The device itself shows this:
![image](https://user-images.githubusercontent.com/107961050/226187436-c302a152-0b3a-4337-a85d-d4284adcf203.png)


But when I trigger is manually by 'Try it' I get the following:
![image](https://user-images.githubusercontent.com/107961050/226187642-e0dec974-b91b-4304-b4ba-76dc42767534.png)

![image](https://user-images.githubusercontent.com/107961050/226187616-9cc73ea9-3af3-41b3-9bd0-8dec7ffef0d3.png)

**Comment by HayaminiNL** [comment]
Good evening Niels, have you looked at it?
I went through the code but have not found anything useful that links to a valuable error during the 'trigger'.

**Comment by nielsfaber** [comment]
I don't really know how to help at this point.
In both the screenshots you shared, you can find in the variables section:
```yaml
entity: switch.sirene_garage
duration: 3
```
So I would expect the script to run OK.

I think it's good to check if this data is also present when the alarm is triggered and the automation is executed from HA.
As said in https://github.com/nielsfaber/alarmo/issues/675#issuecomment-1475108656, in my testing this worked properly.
You could try to perform this test on your own configuration as well.
