### ISSUE TITLE
Modify modes name

### ISSUE THREAD

**Issue by magomao** [nielsfaber/alarmo#680]
### Proposal
I’m looking to add or modify a mode name like “BRB mode” (be right back) so the house don’t turn off the ac or other options for a short time exit.

### Additional info
Option to add or edit the name of the modes

**Comment by nielsfaber** [comment]
The mode names are defined by HA, see here: https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#supported-features

I cannot change these from the side of Alarmo.
Note that in [alarmo-card](https://github.com/nielsfaber/alarmo-card) you can override the state names by your own values, but 'under the hood' they are fixed.
