### ISSUE TITLE
Permissible time period for alarm deactivation

### ISSUE THREAD

**Issue by jmicjmic** [nielsfaber/alarmo#681]
### Checklist
-  My request is generic, other users may benefit from it too.

### Proposal
Add the possibility to allow disarming only during a certain time for a certain person/pincode.
This can be very handy for a maid, for example.

**Comment by nielsfaber** [comment]
You can create an automation and execute the enable_user / disable_user services for alarmo to accomplish this.
I don’t think anything needs to be added..
