### ISSUE TITLE
Tamper always active / Engineering mode

### ISSUE THREAD

**Issue by sickboy2468** [nielsfaber/alarmo#685]
Most alarm systems constantly monitor the tamper zones / sensors regardless of the arm state, that way if someone tampers with devices it alerts the system & users, eithe by notification or alarm. This means that in order to perform maintainence such as changing batteries the ssytem needs to be put into an engineering mode. 

Could this be implemented in Alarmo to mirror the functionality of most alarms.

I know this could be implemented in HA by simply having any of the tamper sensors activating the Siren but it would be better to keep everything contained in alarmo.

**Comment by ColColonCleaner** [comment]
This would be nice to have.
