### ISSUE TITLE
Add support to send alarm events to Alarm Company over standarized alarm protocols.

### ISSUE THREAD

**Issue by ruant** [nielsfaber/alarmo#686]
### Proposal
Are there plans for adding support to send alarm events to "third party" alarm centrals?
Like adding support for SIA DC-09, or Contact ID?

I would LOVE to get rid of my duplicate sensor setup since the alarm system needs access to it's own set of sensors, and my lighting etc. can't easily get fast enough access to these over the slow cloud. (Especially for motion this doesn't work).

So being able to skip the entire dedicated alarm system and have Alarmo set up in HA and configure it so it sends events to the Alarm company/central over the already standardized protocols that exists for the alarm sector would be awesome.

I know Alarmo aims for a more run your-own alarm, but the added safety of a 3rd party acting on events when I'm not within cell coverage is important to me (and I can't be the only one?)

### Additional info
Perhaps there is a need for a way to include/exclude what sensors should be sent to the external system too? If not all sensors should be acted upon. Like I have some water sensors that isn't really important that the alarm company gets notified about, but it's nice to get notified by Alarmo/HA when they're triggered so I can empty the container it monitors.

**Comment by dpbarinov** [comment]
Hi. I need ability to send alarm events to "third party" alarm centrals too.
Please add this feature!!!

**Comment by dpbarinov** [comment]
Hi. Are you planning to add this feature?

**Comment by nielsfaber** [comment]
@dpbarinov 
> Hi. Are you planning to add this feature?

No. I have no idea about such protocols and I don't think this platform is reliable enough to automatically send reports to an security company.
I would assume such companies require a certified alarm system, rather than some DIY solution with Home Assistant running on a Raspberry Pi.

**Comment by ruant** [comment]
I've been doing a bit more research around it.

And I see that HA has a SIA addon that we maybe can pick some code from.
This HA integration is listen only, to get sensor data into HA. But it contains a lot of the "codes" and what each code means etc.
So in my mind it would be a great starting point since it most likely contains a lot of logic that could be used.
https://www.home-assistant.io/integrations/sia/
https://github.com/home-assistant/core/tree/dev/homeassistant/components/sia
Home Assistant Core is Apache License 2.0, so shouldn't be an issue to snip out some code from here. But not sure what license alarmo is under, can't find any info about it in this repo? @nielsfaber 


SIA is as I understand it the "newest" protocol, so I guess it would be fine to just implement this, and drop ContactID (older protocol).

**Comment by ruant** [comment]
> No. I have no idea about such protocols and I don't think this platform is reliable enough to automatically send reports to an security company. I would assume such companies require a certified alarm system, rather than some DIY solution with Home Assistant running on a Raspberry Pi.

Good point. I have little to no knowledge about alarm system certifications.
I just know I can set up where my current alarm system should send event through my alarm panel (IP, subscription id, etc. etc.)

Not sure if the SIA protocol has any identifying info about what system it is (brand, model etc.)
I'll keep reading up on the protocol.

**Comment by dpbarinov** [comment]
> @dpbarinov
> 
> > Hi. Are you planning to add this feature?
> 
> No. I have no idea about such protocols and I don't think this platform is reliable enough to automatically send reports to an security company. I would assume such companies require a certified alarm system, rather than some DIY solution with Home Assistant running on a Raspberry Pi.

Security on the HA is a completely reliable solution, in addition, the raspberry can be upgraded (adding a GSM modem and backup power) to meet the requirements of security companies

**Comment by nielsfaber** [comment]
@dpbarinov 
> Security on the HA is a completely reliable solution, in addition, the raspberry can be upgraded (adding a GSM modem and backup power) to meet the requirements of security companies

Since any user can interconnect any kind of hardware and software (including this integration), the reliability of the system is very much arguable.

@ruant 
> And I see that HA has a SIA addon that we maybe can pick some code from.

If an addon already exist, why not use that instead? I guess it would be easier (and more generic) to focus on some 'glue layer' to have Alarmo interact with that.

**Comment by ruant** [comment]
> @ruant
> 
> > And I see that HA has a SIA addon that we maybe can pick some code from.
> 
> If an addon already exist, why not use that instead? I guess it would be easier (and more generic) to focus on some 'glue layer' to have Alarmo interact with that.

The integration I mentioned is LISTEN/READONLY.
For example my existing alarm system, I can configure to send the SIA events to the SIA HA integration.
In other words, the SIA HA integration is the same as the alarm company. Just receiving the events.

So basically it's the exact opposite of what I want.
I want to be able to send the SIA events, so the alarm company receives events when alarms are triggered in alarmo.

**Comment by ruant** [comment]
WIP PR: https://github.com/nielsfaber/alarmo/pull/1270

Started doing some work on this.
Currently WIP and not really tested at all.
