### ISSUE TITLE
not arming after update

### ISSUE THREAD

**Issue by aavosnl** [nielsfaber/alarmo#691]
### Alarmo Version

v1.9.8

### HA Version

2023.04.0

### Bug description

After the update tot the latest version of alarmo again the system is not working.  Pushing on armed mode is not doing anything.  ALso with the other options 

### Steps to reproduce

reinstall alarmo 

### Relevant log output

```shell
Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:554
Integration: Alarmbedieningspaneel (documentation, issues)
First occurred: 16:35:25 (1 occurrences)
Last logged: 16:35:25

Platform alarmo does not generate unique IDs. ID alarm_control_panel.alarmo is already used by alarm_control_panel.alarmo - ignoring alarm_control_panel.alarmo
```

**Comment by aavosnl** [comment]
Logger: homeassistant.helpers.service
Source: helpers/service.py:757
First occurred: 16:39:37 (16 occurrences)
Last logged: 16:44:31

Unable to find referenced entities alarm_control_panel.alarmo or it is/they are currently not available

**Comment by rpanachi** [comment]
Same problem here with the latest version:
```
2023-04-08 23:09:39.945 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.alarmo
2023-04-08 23:09:39.966 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new alarm_control_panel.alarmo entity: alarm_control_panel.alarmo_2
2023-04-08 23:09:39.968 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Platform alarmo does not generate unique IDs. ID alarm_control_panel.alarmo is already used by alarm_control_panel.alarmo_2 - ignoring alarm_control_panel.alarmo
2023-04-08 23:14:21.604 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities alarm_control_panel.alarmo_2 or it is/they are currently not available
```

**Comment by GiaMisu** [comment]
Same problem:

Logger: homeassistant.helpers.service
Source: helpers/service.py:757
First occurred: 17:50:01 (17 occurrences)
Last logged: 19:07:10

Unable to find referenced entities alarm_control_panel.alarmo or it is/they are currently not available

**Comment by Lazzapao** [comment]
Same issue !

Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:554
Integration: Alarm control panel (documentation, issues)
First occurred: 10:49:45 AM (4 occurrences)
Last logged: 10:49:45 AM

Platform alarmo does not generate unique IDs. ID alarm_control_panel.primopiano is already used by alarm_control_panel.primopiano - ignoring alarm_control_panel.primopiano
Platform alarmo does not generate unique IDs. ID alarm_control_panel.piano_terra is already used by alarm_control_panel.piano_terra - ignoring alarm_control_panel.piano_terra
Platform alarmo does not generate unique IDs. ID alarm_control_panel.garage is already used by alarm_control_panel.garage - ignoring alarm_control_panel.garage
Platform alarmo does not generate unique IDs. ID alarm_control_panel.master is already used by alarm_control_panel.master - ignoring alarm_control_panel.master

Home Assistant 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest

**Comment by Lazzapao** [comment]
I solved the issue reebooting the system completely! (not Restart HA)

**Comment by GiaMisu** [comment]
> I solved the issue reebooting the system completely! (not Restart HA)

it doesn't work restarting the system or home assistant, alarmo works only for a few minutes but then the identity is not found by home assistant making alarmo unusable. No need to uninstall and reinstall alarmo, the problem occurs after a few minutes again.

**Comment by nielsfaber** [comment]
@GiaMisu please check the developer tools -> states page and find the alarm_control_panel entity/entities corresponding to alarmo.
Perhaps they were renamed with an appended _2 since HA detected them as duplicates.
In that case you should use this entity instead for arming/disarming (also configure this in alarmo-card).
I don’t know what causes this issue though, I have never experienced this myself. If anyone has found a pattern on how to reproduce this I would be happy to hear.

**Comment by Alvarito2201** [comment]
Same problem here, i unistalled alarmo and start from scratch and that only fix the problem for 1 day, now is back, somebody found something ??

**Comment by actabi** [comment]
I have the same problem, I have follow the instruction of @rpanachi but after 1 or 2 days the problem returns  : upgrade HA, reboot server and install Alarmoupgrade HA, reboot server and install Alarmo

**Comment by nielsfaber** [comment]
@Alvarito2201 @actabi did you find any pattern when this occurs? I would like to solve this issue but I haven’t been able to reproduce it so far..

**Comment by Alvarito2201** [comment]
Hello i think i dont understand your question, for info im having the same message error that actabi, please let me know who can i help you or wich information can i provide to you
