### ISSUE TITLE
Apple Homekit notifications

### ISSUE THREAD

**Issue by norbertjoni** [nielsfaber/alarmo#693]
It would be nice to get notifications through the HomeKit app like : 
The alarm is triggered! {{open_sensors|lang=en}}

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

**Comment by norbertjoni** [comment]
I found this on Reddit maybe it help:

[Reddit post about sensor and alarm ](https://www.reddit.com/r/homeassistant/comments/9j3pcy/pro_tip_for_homekit_component_turn_on/e6odd7l/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1&context=3)

**Comment by codyc1515** [comment]
HomeKit does not allow free form notifications but you can configure general mobile app notifications for iOS through the Alarmo web UI.

**Comment by nielsfaber** [comment]
As far as I know this is not possible in HA, therefore also not possible via alarmo.

**Comment by norbertjoni** [comment]
That's true that basic notification is not possible by home kit. However, we can pass binary sensors through HomeKit Bridge and we can make some automation with it. 

Example movement detected or the door opened. 
So all we need is a sensor for the “shield” and when it's opened is means the alarm is boomed.

Links what I found ( sorry about youtube)

https://youtu.be/YOQPJ9ZTPl0

https://support.apple.com/en-au/HT208939

**Comment by nielsfaber** [comment]
If this is what you want, why don’t you create a template binary sensor in HA with template is_state("alarm_control_panel.alarmo", "triggered")?
If you add such sensor to HomeKit you could get a notification when the sensor is activated (which is when the alarm is triggered).
I don’t see any need of adapting alarmo for this usage.

**Comment by norbertjoni** [comment]
Yes, this is the best that I can do. When I opened the fr I believe there is a better way because some home kit supported alarms have a notification feature. Thank you anyway 2023. máj. 3. dátummal, 9:30 időpontban Niels Faber ***@***.***> írta:﻿
If this is what you want, why don’t you create a template binary sensor in HA with template is_state("alarm_control_panel.alarmo", "triggered")?
If you add such sensor to HomeKit you could get a notification when the sensor is activated (which is when the alarm is triggered).
I don’t see any need of adapting alarmo for this usage.
