### ISSUE TITLE
Pre-arming status

### ISSUE THREAD

**Issue by niraviry** [nielsfaber/alarmo#694]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Proposal
At this point when one runs an automation that arms the Alarmo automatically (geo-fencing) the alarm might not start due to open sensor. This is what happens to me from time to time.
There is the automatic bypass feature but that is not enough.
A good thing would be a changing color of each of the arming buttons (Night, Home Away etc.) of one or more sensor(s) is open before arming. 
Many users has some kind of tablet next to the main door. When leaving the house one will be able see immediately if all openings that are mandatory are closed by the color of the frame of the above buttons (or similar approach) thus not having to return back to the house and close the relevant opening (door , window etc.).
### Additional info
I think the idea is very simple. I would also try get use info using NFC tag as a trigger for notification when leaving the house or if the mobile phone's actively paired with the car's BT. This will issue a push notification before leaving that park drive.

**Comment by KSchmeeds** [comment]
I also agree that a way to see a ready/not ready status would be helpful, as most hardwired alarm systems will display faulted/open sensors on their keypad without needing to attempt to arm it.

**Comment by niraviry** [comment]
Hi. I see no progress. I have made my own solution using blinking icons and custom button card.
It works OK but it takes space. A built in indication will be smoother.

**Comment by nielsfaber** [comment]
I agree with this request but:
* This requires a fundamental change that Alarmo should keep track of the states of all sensors at all times. Currently sensors are only watched when needed (i.e. if system is armed)
* This requires communication between alarmo and alarmo-card to keep track of 'ready for arming' status per arm mode
* I am not sure about the visual indication which should be used in the card. Colorizing the arming buttons seems a tricky solution (the result is subject to the theme which is used)
* Users can set an 'automatically bypass if open` setting on a window. It would be hard to judge whether the alarm should be marked as ready for arming if a window with such setting is open.

**Comment by niraviry** [comment]
Hi Everyone.

Eventually I did it by myself with a large card, flashing in red when a
relevant sensor is open.
This is done using custom:button-card and horizontal stuck card.
I will add an immediate view change to the Alarmo card when the main door
opens and change the number of beeps appearing when the door has opened,
Normal one is 2 beeps. When a sensor is open I will change to 3 beeps.

‫בתאריך שבת, 24 ביוני 2023 ב-16:21 מאת ‪Niels Faber‬‏ <‪
***@***.***‬‏>:‬

**Comment by hughhalf** [comment]
I've just started using Alarmo, thank you for great work @nielsfaber and all that have contributed!

I came across this issue when looking to see if Alarmo exposed a way of seeing if a particular Area was open or closed. I'd like to be able to have an indication of the state of an Area so can tell at a glance if (for example) my outdoor shed has doors locked etc. 

Based on what Niels has said I understand it will mean an architectural change to Alarmo to regularly/continually monitor the state of sensors.  Perhaps this would be a stepping stone to a subsequent change/feature that adds this indication to the card as well ?  By having it exposed as a state (if that's the right term) it can be used outside the Alarmo card is my thinking.

**Comment by nielsfaber** [comment]
@hughhalf
Thank you very much for your donation!  
I agree this feature could be rolled out in a stepwise approach.
First I could add to the `alarm_control_panel` entities some property `ready_to_arm_modes` (or similar) listing the modes in which the alarm could be armed without resulting in errors.
The property would be continuously recalculated as sensor states change (hopefully motion sensors don't have to be monitored).
This would allow users to create their own automations / GUI to indicate the readiness status of the alarm.
Next I will see how to give this a place in the card. I was thinking of adding red/green indicator dot to the arm mode buttons (if possible).

**Comment by hughhalf** [comment]
Thanks for the reply @nielsfaber that all sounds very reasonable!

I don't if this would work with the internal architecture of the code, but if it were simpler perhaps each alarm_control_panel entity could have a property (called state ?) which is either "ready" or "not ready". The former would mean it's clear or ready to arm, the latter would mean a door is open, motion sensor tripped etc. and so the zone isn't yet ready to arm.

I'm curious - what is the concern with monitoring motion sensors, just that they are likely to constantly change state more than a door switch ?

I'm happy to help with testing if that's useful - I've not got a build environment set up but daresay I can work it out - life settles down a bit at the end of the month!

Thanks again!

**Comment by nielsfaber** [comment]
I am currently working on the implementation of the feature.

For the backend implementation I added a property `ready_to_arm_modes` which will lists the arm modes which are ready:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/75dc30c5-1198-4194-8ac9-ffb6aa421035)

For the computation of the ready-to-arm-modes, alarmo will now continuously monitor all sensor states (also when alarm is disarmed) and update the list. Motion sensors will not be monitored, since I think this would introduce too much computational load (due to the many triggers when people are moving in the house).

On the alarmo card side, I added red/green dot indicator:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/ef388ad9-9e4e-482b-8020-bd5817277e14)
I thought this would be less distracting (and more fitting the color theme) than colorizing the whole button. But I'm not sure whether it is intuitive. There will be an option to hide the indicators (for those who don't like it).

@niraviry @hughhalf Do you have any thoughts regarding these changes, ideas for implement?

**Comment by ddanielww** [comment]
When will this feature be released please ?

**Comment by hughhalf** [comment]
Hey @nielsfaber I'm so sorry, I missed this notification :(  

All sounds like great progress - I do have one comment/suggestion for improvement...

Please please please make the choice to monitor Motion detectors an option, even if off by default. My rationale is as folllows.  Firstly, I think Motion detectors are an important part of a system for many people, not everyone will use door sensors (I have both) - so the ability to check both are ready will be important I think.  Secondly, not everyone will be running HA in a computationally constrained environment so the overhead doesn't matter - I run mine in a VM with a couple of cores and lots of RAM available for example.

Thanks again for taking this work on :)

**Comment by nielsfaber** [comment]
The feature is now released in v1.9.11 (note that changes to the alarmo-card need to be released still).
@niraviry Could you update to the new version and confirm the changes satisfy the request? If so the request can be closed.

@hughhalf I am not a fan of involving motion detectors in determining the ready status.
As mentioned it would involve a lot of code execution when people are walking through their homes.
Secondly, I expect users to assign an appropriate exit delay to their system, such that motion detectors have already cleared before the system becomes armed. In other cases the 'allow initially open' setting should be applied on such sensors.
I don't feel for adding a setting for this. I want to keep alarmo simple as possible, I don't see a good place for such setting and I think it would create confusion to users.

**Comment by ddanielww** [comment]
Will this stop the alarm from re arming if one of the sensors is still active ? It used to just bypass them?

Is there an alert to say the auto re-arm has failed and the sensors that caused it ?

**Comment by hughhalf** [comment]
Thanks for the thoughtful reply @nielsfaber - I see where you're coming from and will happily give it a try as is, without the motion sensor option.  Thanks again!

**Comment by ddanielww** [comment]
I’d rather it not bypass sensors that I am not aware are still open. I would like a notification telling me why it’s failed to re-arm and the sensors affected.

**Comment by ddanielww** [comment]
If you then want to re-arm the alarm and bypass these sensors you are then aware of what is going on

**Comment by ddanielww** [comment]
Actually I think this is already possible, so I’m happy with the solution (providing it passes my testing).

**Comment by ddanielww** [comment]
@ByteConFusion  you can set your sensors to automatic bypass if it’s a window sensor and you leave these open sometimes.

**Comment by ddanielww** [comment]
Or you can use Allow open initially
