### ISSUE TITLE
Actionable Notifications to set an armed status

### ISSUE THREAD

**Issue by herb0072** [nielsfaber/alarmo#697]
### Checklist
- [ X ] I checked for similar existing requests (both open and closed) before posting.
- [ X ] My request is generic, other users may benefit from it too.

### Proposal
As an Alarmo user, I would like to be able to use Actionable Notifications to set an armed status.

### Additional info
It appears the only actionable notification options are:
- ALARMO_RETRY_ARM
- ALARMO_FORCE _ARM
- ALARMO_DISARM

I think it would be really useful to be able to set armed away from a notification if no one was home. It's nice to be able to retry arming if it fails, but why not set it to start as well.

**Comment by nielsfaber** [comment]
I don't really picture how this would work.
Alarmo sends you an actionable notification only after a failed arming attempt.
So when clicking a button in this notification it becomes automatically a retry, right?
In which scenario would you like to have the arm buttons show up?

**Comment by herb0072** [comment]
I set up a notification to trigger when I leave the house, I may or may not want to have the system arm automatically, so the notification says "Do you want to arm?". The action I would like to set is ARM_AWAY, but it hasn't failed to trigger a retry of course.

**Comment by herb0072** [comment]
Would love to keep this open unless there's a decision to close.

**Comment by srrsparky** [comment]
I also wanted to have an "immediately arm away" actionable notification when the house is empty. I've made the required changes locally, but haven't used github enough to be confident with a pull request. I haven't done much HA programming either, so hopefully this is ok.

**const.py**
Line 149ish - added **EVENT_ACTION_FORCE_AWAY = "ALARMO_FORCE_AWAY"**

```
PUSH_EVENT = "mobile_app_notification_action"
EVENT_ACTION_FORCE_ARM = "ALARMO_FORCE_ARM"
EVENT_ACTION_FORCE_AWAY = "ALARMO_FORCE_AWAY"
EVENT_ACTION_RETRY_ARM = "ALARMO_RETRY_ARM"
EVENT_ACTION_DISARM = "ALARMO_DISARM"
```

**__init__.py**
Line 300ish added:
- const.EVENT_ACTION_FORCE_AWAY,
- if action == const.EVENT_ACTION_FORCE_AWAY:
	_LOGGER.info("Received request for retry arming away")
	await alarm_entity.async_handle_arm_request("armed_away", skip_code=True, bypass_open_sensors=True, skip_delay=True)

```
if action not in [
	const.EVENT_ACTION_FORCE_ARM,
	const.EVENT_ACTION_FORCE_AWAY,
	const.EVENT_ACTION_RETRY_ARM,
	const.EVENT_ACTION_DISARM
]:
	return

if self.hass.data[const.DOMAIN]["master"]:
	alarm_entity = self.hass.data[const.DOMAIN]["master"]
elif len(self.hass.data[const.DOMAIN]["areas"]) == 1:
	alarm_entity = list(self.hass.data[const.DOMAIN]["areas"].values())[0]
else:
	_LOGGER.info("Cannot process the push action, since there are multiple areas.")
	return

# Force arm away
if action == const.EVENT_ACTION_FORCE_AWAY:
	_LOGGER.info("Received request for retry arming away")
	await alarm_entity.async_handle_arm_request("armed_away", skip_code=True, bypass_open_sensors=True, skip_delay=True)

arm_mode = alarm_entity._arm_mode
```

**Comment by nielsfaber** [comment]
Your request was added in v1.9.10 of alarmo.
The commands `ALARMO_ARM_AWAY`, `ALARMO_ARM_HOME`, `ALARMO_ARM_NIGHT`, `ALARMO_ARM_VACATION`, `ALARMO_ARM_CUSTOM_BYPASS` were added.
The effect should be the same as regular arming (via card or service). So, if there is an exit delay configured, it will be applied.

@herb0072 Please update and check if it fits your need.
If so, you can close the issue.
Otherwise, please let me know.

**Comment by herb0072** [comment]
This works great, thanks!
