### ISSUE TITLE
Alarmo intergratie can not open it

### ISSUE THREAD

**Issue by Homeassistjoenka** [nielsfaber/alarmo#698]
### Alarmo Version

V1.9.8

### HA Version

2023.4.2

### Bug description

The intergratie its working but we can not open it than is he always loaded 
![B6EFD76D-24F2-4DDA-8BDA-D996EF61D92E](https://user-images.githubusercontent.com/113582714/231077389-20d2610c-1dc3-411d-97df-5b8762317085.png)

### Steps to reproduce

We re install alarmo but its not working

**Comment by nielsfaber** [comment]
Duplicate of #688
