### ISSUE TITLE
Additional verification for expulsion machines

### ISSUE THREAD

**Issue by carlos837** [nielsfaber/alarmo#699]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
I want to implement a fog machine to my home, but I only want Alarmo to activate it if its really sure that there is someone inside.

### Additional info
I also recomend everyone getting a fog machine for that, if the theft cant see he cant rob, he has to run away

**Comment by nielsfaber** [comment]
I don't understand what you are requesting. Please elaborate.
