### ISSUE TITLE
Select sensors for home/away

### ISSUE THREAD

**Issue by kroese** [nielsfaber/alarmo#701]
Currently my Alarmo shows 18 sensors active for Away mode, and 7 sensors active for Home mode.

I want to make a different selection of active sensors for the Home modus, but when I click on "7 sensors" it takes me to the general sensors page, and not a specific one for Home modus.

So is it not possible to customize which sensors to use for Home modus?

**Comment by nielsfaber** [comment]
> I want to make a different selection of active sensors for the Home modus, but when I click on "7 sensors" it takes me to the general sensors page, and not a specific one for Home modus.

This shouldn't be the case. Can you share some details?


![image](https://user-images.githubusercontent.com/16861605/233255710-ddbd4762-44f6-439c-bd9f-a0750321a6ea.png)
If I click on the '1 sensor active' for armed night for example, I do get a filtered view:
![image](https://user-images.githubusercontent.com/16861605/233255774-d4362f15-3d48-468f-9fdf-e687d3773eae.png)

**Comment by nielsfaber** [comment]
It seems you misunderstand the interface.
When the view is filtered, there will be only some items removed from the list. 
When clicking the cross next to the filter, you remove the filter, so you will see the full list again. 
What would you expect to happen in this case instead?

The toggle switches next to the sensors are for eliminating them from the alarm completely.
A disabled sensor is ignored in Alarmo, regardless of the modes.

If you want to configure which sensor is active in which mode, click on a row in the list and change its settings.
