### ISSUE TITLE
Open sensors: only one is detected during arm

### ISSUE THREAD

**Issue by Extreme79** [nielsfaber/alarmo#702]
### Alarmo Version

v1.9.8

### HA Version

2023.4.4

### Bug description

I noticed that the open_sensors attribute contain only one of a list of opened sensor.
As a side effect the alarmo card show only this sensor, and no others:
![image](https://user-images.githubusercontent.com/33934444/232239169-8af40f49-143a-415a-8c65-7279dbcbea23.png)

Here is my alarm panel attributes with open_sensors with only one item (but there are many more opened sensor now), in a disarmed state
`{'code_format': 'number', 'changed_by': 'Simone', 'code_arm_required': True, 'arm_mode': None, 'open_sensors': {'binary_sensor.persiana_matrimoniale': 'open'}, 'bypassed_sensors': None, 'delay': None, 'icon': 'mdi:shield-home', 'friendly_name': 'Piano Terra', 'supported_features': <AlarmControlPanelEntityFeature.TRIGGER|ARM_AWAY|ARM_HOME: 11>}`
And here in armed state:
`{'code_format': 'number', 'changed_by': 'Simone', 'code_arm_required': True, 'arm_mode': 'armed_home', 'open_sensors': None, 'bypassed_sensors': ['binary_sensor.persiana_asia', 'binary_sensor.persiana_matrimoniale', 'binary_sensor.persiana_salotto', 'binary_sensor.porta_cucina'], 'delay': None, 'icon': 'mdi:shield-home', 'friendly_name': 'Piano Terra', 'supported_features': <AlarmControlPanelEntityFeature.TRIGGER|ARM_AWAY|ARM_HOME: 11>}`

The bypassed sensors after the forced arm is correct and reflect the real bypassed sensors.

### Steps to reproduce

Open many sensors included in the panel and try to arm the alarm.

**Comment by nielsfaber** [comment]
If I try to arm with multiple sensors active, they are all listed:
![image](https://user-images.githubusercontent.com/16861605/232563015-4e3792b5-433a-4c67-9de9-d662b88444cc.png)

So this seems more a configuration issue to me.
Please check all sensors, see if their setting is correct.
Most important setting to look for is this one:
![image](https://user-images.githubusercontent.com/16861605/232563451-add2af10-fd45-44e8-9bc0-246dd48f3a24.png)

If this is set for a sensor, it does not show up as blocking when arming (only at the end of the exit delay).

**Comment by Extreme79** [comment]
I understood.
It's not what you said, but near: it's the automatic exclusion. 
If sensor is marked for automatic exclusion the card do not list it. 
This make sense, because the card actually display what avoid the arm, but at the same time could cause a misunderstanding without a notification about the bypassed sensors.

What about displaying also the auto-excluded sensors, maybe in a different color or with a tag "excluded" or something else? 
(I don't know if could be a good idea)

Anyway, not a bug, my fault
