### ISSUE TITLE
Dutch translated notifications no longer works.

### ISSUE THREAD

**Issue by CyborgNL** [nielsfaber/alarmo#703]
### Alarmo Version

v1.9.8

### HA Version

2023.4.4

### Bug description

After the last update of Home Assistant, the Dutch translation of the Alarmo notifications no longer works. 

{{arm_mode|lang=nl}}

Text will be in English

### Steps to reproduce

Het alarm is ingeschakeld op {{arm_mode|lang=nl}}

![Alarmo](https://user-images.githubusercontent.com/61829624/232300231-5a4bd87d-aaa6-4450-9f44-631c366da349.jpeg)

**Comment by nielsfaber** [comment]
This should be fixed in v1.9.9.
@CyborgNL Can you update alarmo to this version and confirm its working again? You can close the issue if this is the case.

**Comment by CyborgNL** [comment]
Thanks for the update. It works again in v1.9.9.
