### ISSUE TITLE
Platform alarmo does not generate unique IDs.

### ISSUE THREAD

**Issue by actabi** [nielsfaber/alarmo#704]
### Alarmo Version

1.9.8

### HA Version

2023.4.4

### Bug description

I tried to completely uninstall it, restart HA, but I still get this error that prevents me from using it. Do you have any idea? Thank you for your help.

2023-04-16 23:13:13.306 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Platform alarmo does not generate unique IDs. ID alarm_control_panel.alarmo is already used by alarm_control_panel.alarmo - ignoring alarm_control_panel.alarmo

### Steps to reproduce

I can reproduce it simply by installing it from "devices and services". Once installed, if I click on Alarmo in the left panel, I only see 'loading...' and when I look in the logs, this is what I find.

**Comment by rickDo70** [comment]
Same issue. Also no Errors in log, but display stays with "loading" only in Chrome (Windows 10, 64 bit). 
No Problems in iOS App, with Safari and Edge (chromium). 
No errors shown in Chrome developer tool.

**Comment by Alvarito2201** [comment]
Same issue here

**Comment by snoopfab** [comment]
i have the same problem. 
Does not work in chrome, edge or firefox.
Works however from the android app.
Tried to clear the browser cache in chrome with no success

**Comment by nielsfaber** [comment]
Let's keep this open until the issue is found and fixed
