### ISSUE TITLE
Missing mode names as text form in the Alarmo "Modes" section

### ISSUE THREAD

**Issue by Grandma-Betty** [nielsfaber/alarmo#705]
### Alarmo Version

v1.9.8

### HA Version

2023.4.5 (HAOS 10.0)

### Bug description

On the "Modes" section in the Alarmo UI the names of all modes are not appearing as a text:

![Unbenannt](https://user-images.githubusercontent.com/48346793/233103596-c4af4c3f-b04c-4531-9ff7-4ca12a5dcf96.PNG)

I tried with Edge browser and Firefox, also with clearing the cache. Also on the HA Android app the issue is the same.

Not sure if Alarmo is dependent on mushroom somehow as there was also an update of mushroom recently and I'm not quite sure if the issue came with the mushroom update or with the latest Alarmo update. But maybe the issue is also HA dependent, I cannot really tell.

### Steps to reproduce

I guess installing everything to the latest version should show the issue.

**Comment by nielsfaber** [comment]
This should be fixed in v1.9.9.
Could you update alarmo to this version and confirm it's fixed for you as well? You can close the issue if this is the case.
