### ISSUE TITLE
Failed to arm state for home assistant scripts

### ISSUE THREAD

**Issue by KSchmeeds** [nielsfaber/alarmo#706]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
There are currently states that home assistant can use for arming, pending, triggered, etc.  but there is not one for arming failed.  This makes running custom scripts more difficult when a failed to arm condition occurs.

### Additional info
Add an available state of failed that will be the state of alarmo for a few seconds before changing to a disarmed state.

**Comment by EnricoBettella** [comment]
Any news on this? I'd like to create an autmation when alarmo fails to arm, and I'd like it to have a state or attribute to use as trigger.
At the moment what I can do to achieve this is creating an action inside Alarmo and running a script.

**Comment by kitty99hub** [comment]
Hi,
same question here.
I would also use the "failed to arm" state in HA automations....
Please, add this state to integration.
Many thanks
