### ISSUE TITLE
Feature Request - Disarm Panic PIN

### ISSUE THREAD

**Issue by mikebol** [nielsfaber/alarmo#71]
It would be a nice addition to provide a "Disarm Panic PIN" for Alarmo.  If a user disarms with the panic code, additional automations could be triggered to perform further notifications\actions like enabling recording on ALL cameras. 

Mike

**Comment by nielsfaber** [comment]
What you could do is create a user called "panic" and give it a dedicated pin.
The `alarm_control_panel.alarmo` entity will have attribute `changed_by: panic` if this pin is entered for disarming.
So you could use automations (outside of Alarmo), that triggers on disarmed state with condition `changed_by = panic`

In some time I might create functionality for defining a panic mode with its own responses.
Your suggestion would be a nice idea for this.
But currently my priorities are elsewhere.
So in the meantime, the above should help you.

**Comment by mikebol** [comment]
That's a good work around, a "Panic" user.  I'll look into that further.  Thank you, sir.

**Comment by nielsfaber** [comment]
I will close for now, hoping that you found a workaround using the panic user.
We can discuss this again at a later point.
