### ISSUE TITLE
No message when changing code and current is wrong

### ISSUE THREAD

**Issue by nsleigh** [nielsfaber/alarmo#712]
### Alarmo Version

v1.9.9

### HA Version

2023.4.6

### Bug description

If I try to change a code but get the current code wrong there is no message to say the code was wrong, so you are unaware that the code hasn't been changed.

### Steps to reproduce

Create a user with a code, edit user and enter the wrong code in the "Current code" box and a new code in the Code and Confirm code boxes.

**Comment by koolsb** [comment]
This issue still exists
