### ISSUE TITLE
Apple Homekit Disarming integration

### ISSUE THREAD

**Issue by ralvarez83** [nielsfaber/alarmo#716]
I would like disarming my alarm from Home app in my iPhone. Now the HASS Bridge integration to Apple HomeKit show the Alarm as a Security element but when I select disarming it will never end.

I will write a similar Feature in HASS Bridge because I maybe you must collaborate.

**Comment by ralvarez83** [comment]
I add a issue in HASS Bridge: https://github.com/home-assistant/core/issues/92511

**Comment by ralvarez83** [comment]
Ok, thanks @bdraco. 

I have code disarming configured, maybe this information is important

**Comment by nielsfaber** [comment]
Alarmo already has support for HomeKit. Multiple people are using this without problems. From the side of alarmo there is nothing different in disarming via normal procedure (e.g. dashboard card) or via HomeKit.
Make sure you have the code configured correctly in the HomeKit configuration and check for errors/warnings in the HA logs when trying to disarm.
If the state of the alarm is different in HA compared to HomeKit, this is an issue outside of control of alarmo.

**Comment by ralvarez83** [comment]
Hi @nielsfaber,

The state of the alarm are the same in HA and HomeKit. I exported the "alarm_control_panel" entity with HASS Bridge configuration wizard. In HA panel the code work right and I can disarming the alarm with the code without problem. But when I try to disarming from HomeKit with my iPhone the code panel not appear and I can't insert it (next picture shows disarming function but it never change because Alarmo need the code and I can't insert).

![Screenshot 2023-05-05 at 09 16 03](https://user-images.githubusercontent.com/11288778/236397774-c014f4cd-d433-4c9d-b53a-3580c97eb8eb.png)

Next picture shows the HomeKit state "Away" that the same in HA because I have not change it. And alarm arming the alarm works fine.
![Screenshot 2023-05-05 at 09 18 10](https://user-images.githubusercontent.com/11288778/236398087-7d31a359-a4b3-49c5-ad63-35936dbb530a.png)

Could you send me some documentation where I can review where is my mistake, please?

**Comment by nielsfaber** [comment]
See here for example: https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910/1033?u=neliss
