### ISSUE TITLE
 Alarmo not showing up in HA Integration Add

### ISSUE THREAD

**Issue by rejenet24** [nielsfaber/alarmo#717]
### Alarmo Version

0

### HA Version

2023.4.6

### Bug description

I have a new install of HA running the most recent version. When searching for Alarmo in the "+ Add Integration" I'm unable to find it.

<img width="243" alt="Screenshot 2023-05-04 093117" src="https://user-images.githubusercontent.com/4596851/236239445-c6ed13b8-8096-4521-a47b-a4c91384f6fc.png">

### Steps to reproduce

After looking at other old issues reported, I tried clearing the cache, using multiple browsers, as well as multiple computers (one Windows and one macOS)

**Comment by nielsfaber** [comment]
Please check the HA logs for error messages

**Comment by rejenet24** [comment]
Niels, thanks for the response!

Is there something particular to look for? When I go to add integration nothing hits the error or full logs that seems specific to it, all of the errors I'm getting seem to be around either bluetooth not starting and the media player trying to access devices on my network, nothing seemingly related to it pulling the integration list.

**Comment by nielsfaber** [comment]
There should be at least a warning message occurring when you are restarting HA saying ‘you are using a custom integration alarmo which is not tested…’

If this message indeed shows up, the integration is properly installed.
If it still doesn’t show in the list of integrations to be added, it is for sure an issue with browser cache.

**Comment by rejenet24** [comment]
Niels,

I'm not even getting to the point where I can install it, its now showing up in the "add" screen at all.

RJ

**Comment by nielsfaber** [comment]
If the files are copied correctly, there should be at least a warning message occurring when you are restarting HA saying ‘you are using a custom integration alarmo which is not tested…’

If this message indeed shows up, the integration is properly installed.
If it still doesn’t show in the list of integrations to be added, it is for sure an issue with browser cache.

I am not going to repeat this statement.

**Comment by eyalspier** [comment]
I have the same  issue - I follow the installation instructions **without copying files manually** and cannot add Alarmo from the existing integrations. Does this not work via docker and do I have to copy the files manually?
Kind  regards

**Comment by nielsfaber** [comment]
@eyalspier You **should** place the files of alarmo in the custom_components folder (or let HACS do this).  This is what installs alarmo in HA. After doing so you should restart HA to get the message in the log as mentioned in https://github.com/nielsfaber/alarmo/issues/717#issuecomment-1537295618. The only remaining step is to add the integration in the devices & services page in settings. If it doesn't show here, refresh the cache.

Docker is not related to this. Your HA user folder is not inside the docker image.

**Comment by eyalspier** [comment]
Fantastic, thanks so much for your help - it all works now!
