### ISSUE TITLE
how best to have motioneye motion detection trigger alarm?

### ISSUE THREAD

**Issue by claud9999** [nielsfaber/alarmo#721]
So I am curious what folks think is the best way to trigger an alarm when MotionEye detects motion on a security camera. 

My solution is to create an MQTT binary_sensor in HASS and have MotionEye use mosquitto_pub to send the command to turn the binary_sensor on; then trigger Alarmo on the binary_sensor.

The MotionEye integration can automagically configure MotionEye to send events to the HASS event bus, but no way to trigger an alarm without going through an automation to change the state of a sensor...?

**Comment by nielsfaber** [comment]
This is not the right place to ask for support.
I suggest to use the HA forum instead.
