### ISSUE TITLE
alarmo_failed_to_arm does not pass user id

### ISSUE THREAD

**Issue by CudaSpawn** [nielsfaber/alarmo#723]
### Alarmo Version

v1.9.9

### HA Version

2003.5.2

### Bug description

event type alarmo_failed_to_arm will always pass a null for user_id, even with a code required for arming.

### Steps to reproduce

1. have code required for arming
2. set user with pincode
3. force a alarmo_failed_to_arm
4. listen to events/send notify message with {{changed_by}}

### Relevant log output

```shell
event_type: alarmo_failed_to_arm
data:
  command: arm_home
  context_id: null
  area_id: "1683563424"
  reason: open_sensors
  sensors:
    - binary_sensor.workshop_alarm_workshop_front_door_left
origin: LOCAL
time_fired: "2023-05-12T16:50:36.559050+00:00"
context:
  id: 01H08DY6CF2QKXPD010K7GCXAK
  parent_id: null
  user_id: null
```

**Comment by nielsfaber** [comment]
I don't understand your bug report. Could you please elaborate?

> event type alarmo_failed_to_arm will always pass a null for user_id, even with a code required for arming.

Are you referring to this part:
```
context:
  id: 01H08DY6CF2QKXPD010K7GCXAK
  parent_id: null
  user_id: null
```

This data is added to the event by HA itself, it's out of the control of alarmo.
I wouldn't look for anything relevant here.

As per documentation, the `failed_to_arm` event will come with a `reason` and if the `reason` is `open_sensors` a list of sensors. Is this not what are you were expecting?
