### ISSUE TITLE
Alarmo frontend fail to build

### ISSUE THREAD

**Issue by oded996** [nielsfaber/alarmo#725]
### Alarmo Version

v1.9.9

### HA Version

2023.5.2

### Bug description

Not able to build from head due to incompatible library versions and lint errors.

The fix is not very difficult, need to update a few dependency versions and couple of small changes in the code to fix the lint issues

### Steps to reproduce

- Clone Alarmo repository
-  cd .\custom_components\alarmo\frontend\
- npm install --save-dev  
- npm run build

**Comment by oded996** [comment]
npm install -save-dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: alarmo@1.0.0
npm ERR! Found: rollup@1.32.1
npm ERR! node_modules/rollup
npm ERR!   rollup@"^1.32.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@"^2.22.0" from @rollup/plugin-commonjs@15.1.0
npm ERR! node_modules/@rollup/plugin-commonjs
npm ERR!   @rollup/plugin-commonjs@"^15.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR!

**Comment by mnneely** [comment]
I believe I’m having the same error, although I’m using HA Supervisor. I have Alarmo 1.9.9, HA 2023.5.3, Supervisor 2023.04.1 and HA OS 10.1. Alarmo Front
