### ISSUE TITLE
Sensor name missing from dashboard panel when "could not arm due to the following sensors"

### ISSUE THREAD

**Issue by iculookn** [nielsfaber/alarmo#726]
### Alarmo Version

1.9.9

### HA Version

2023.5.2

### Bug description

I have had alarmo setup and working, but I tried to turn on the alarm today from the dashboard panel and I got an error. 
"could not arm due to the following sensors". Normally this will show which sensor is open, but this time it does not show anything?
![alarm](https://github.com/nielsfaber/alarmo/assets/8793442/c65ea2b9-fa48-4872-a062-a7d7ce521371)
Normally

### Steps to reproduce

"Arm Away" button on Alarm Panel

### Relevant log output

```shell
Nothing in the logs
```

**Comment by nielsfaber** [comment]
Please check in Developer Tools -> states for the related alarm_control_panel entity and see what is listed under its properties.
I would expect an `open_sensors` property with one or more sensor entity IDs under it.

Perhaps you have configured Alarmo with a sensor that was later deleted from HA?

**Comment by iculookn** [comment]
yep, I had renamed a Zigbee sensor under Zigbee2mqtt. removed it from Alarmo and re-added and all good.

Thanks

**Comment by r3wt** [comment]
after latest home assistant update, i can no longer arm away from my ring keypads. as soon as i open the door, it transitions to the "sensors require bypass" and then i can't push the check button to bypass. it just does nothing. seems like it could be related.
