### ISSUE TITLE
Sensor configuration mode 'flakey'

### ISSUE THREAD

**Issue by LukeDefeo** [nielsfaber/alarmo#728]
## background 

I am using some xioami motion sensors which are lets say are 99% reliable but occasionally they will indicate prescence due to unknown factors, for lights this means a hallway light might turn on for a minute, not the end of the world but for the alarm this would cause a false alarm and has freaked me out a few times. As a result I can't really use alarmo 

### Proposal
I'm not too sure of the best way to represent this feature request in Alarmo so but here is what I came up with

I would propose a sensor config called flakey, it would take 2 (or n) firings of any grouped flakey sensor within some time range x to change the alarm state to triggered. In my experience I've never had 2 misfires of the sensors.

Since the flakiness is extremely rare this should allow me to use these motion sensors with confidence 

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

**Comment by nielsfaber** [comment]
This is already in place by means of creating a [sensor group](https://github.com/nielsfaber/alarmo#sensor-groups).
You can set this up in the sensor configuration page:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/0cedc0c1-77b4-4e2e-bba6-12e1675837cc)

**Comment by LukeDefeo** [comment]
My apologies I don't know how I missed this.

Thanks for making such a comprehensive and well thought out bit of software
