### ISSUE TITLE
Activation Delay does not work (partly)

### ISSUE THREAD

**Issue by glockmane** [nielsfaber/alarmo#732]
### Alarmo Version

v1.9.9

### HA Version

2023.5.3

### Bug description

I have a Activation Delay set to 60 seconds. But when arming and then opening the door arming process cancels! If I don't open the door it arms correctly after the 60 second period.

### Steps to reproduce

Just add a few sensors to the profile, set activation delay, arm and open the door..

**Comment by nielsfaber** [comment]
Please share a screenshot of the settings of this door sensor.

**Comment by glockmane** [comment]
My fault, didn't know these advnced sensor settings.. Sorry..
