### ISSUE TITLE
Ability to trigger sensors on any change

### ISSUE THREAD

**Issue by ColColonCleaner** [nielsfaber/alarmo#734]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I have a bunch of Shelly relays/switches around the house and garage. Those devices expose the state of the physical switches wired to them.

If the alarm panel is armed I would like to trigger the alarm if the state on these inputs changes, either on or off. If someone toggled the switch either on or off. I can see them in the list of sensors in alarmo, but they can be in any state when the arming happens. Want to trigger if that state changes after arming.

### Additional info
An additional toggle in the advanced section that would disregard the state of the sensor during arming but keep track of it, and trigger the alarm if that state changes.

**Comment by nielsfaber** [comment]
Alarmo only supports binary sensors.

You need to create a template binary sensor that activates in case such button (or multiple buttons) change.
A template binary sensor can be configured with the delay_off / auto_off parameters to reset to off after some time.

I don’t think changes are needed in alarmo for this.

**Comment by ColColonCleaner** [comment]
These are binary sensors, and I see them in the list of options for alarmo, was just looking for a trigger on any state change.

Thanks for the workaround though, I'll use that method for now!
