### ISSUE TITLE
arm_mode in HA language (available in automations)

### ISSUE THREAD

**Issue by Extreme79** [nielsfaber/alarmo#736]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Actually arm_mode it's in english and only translated in another language using alarmo built-in notificaiton.
In built-in notification I can use {{arm_mode|lang=it}} (or choose a language from the drop down, but If I write my own notification routines by automations, I have to read with {{state_attr('alarm_control_panel.piano_terra','arm_mode')}} that is in english.
Clould be good to add an attribute 'arm_mode_locale' translated in the HA interface language (if supported by alarm, else fallback in english too), so we can read {{state_attr('alarm_control_panel.piano_terra','arm_mode_locale')}}
This let us to avoid scripting/templates in automations to translate it in another language.

### Additional info
-

**Comment by Extreme79** [comment]
No stale, only "wait for a reply" 👍

**Comment by nielsfaber** [comment]
The locale setting is not accessible by the backend of Alarmo (where the automations are handled), it can only perform translation for a known language.

**Comment by Extreme79** [comment]
What I meant is to have the translated arm_mode also available in automation. Because customized complex automation/notification can only be done with automations/scripting.
Sure, I can simply create a translation inside the automation but obviously could be better to have available in automations like in your Alarmo notifications👍
