### ISSUE TITLE
Allow sensors settings to vary between alarm modes

### ISSUE THREAD

**Issue by francesc0s** [nielsfaber/alarmo#737]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
Allow the settings for each sensor to vary from one alarm mode to another.

### Additional info
Currently, if sensor A has has the Bypass automatically setting ticked yes, then this would apply to all alarm modes enabled for that sensor. However, it would be nice if you could have different settings configurations for each alarm mode.

Real world example: if my windows are open and Alarm Home is set, then bypass automatically. If windows are open and Alarm Away is set, do not bypass automatically.

**Comment by Brausmith** [comment]
Was this actually implemented?
I am looking for the exact example as shown in the original post.

**Comment by Brausmith** [comment]
Fantastic. Thank you.
