### ISSUE TITLE
Delay time flexibility

### ISSUE THREAD

**Issue by benjani85** [nielsfaber/alarmo#740]
My alarm system is configured to sound the siren after 45 seconds however the Alarmo interface only accommodates increments of 10 seconds.

Is there the possibility of allowing for 5 second increments in a future version?

**Comment by nielsfaber** [comment]
This change is added in v1.9.10 of alarmo.
Please update and check if the issue if resolved for you.
If so, you can close the issue.
Otherwise, please let me know.

**Comment by benjani85** [comment]
Just updated but still don't have the option of selecting 5 second increments.

**Comment by benjani85** [comment]
Not sure if I was being too heavy handed with the slider or coming back to it a day later many any difference but I can set the 5 second incremental now.

Thank you very much for implementing this :)
