### ISSUE TITLE
Enable Alarmo integration and configure it wihout using the UI

### ISSUE THREAD

**Issue by ddeguglielmo** [nielsfaber/alarmo#741]
Hello,
first, thank you so much for your work. The alarmo integration is simply amazing!

I would like to ask you if there are ways to enable the alarmo integration, and configure it, without using the UI, e.g. by adding entries to the configuration.yaml file.

I am assuming that the alarmo package has been installed in the custom_components/ folder. Then, I would like to configure home assistant in such a way that if it finds the custom_components/alarmo folder, it starts up alarmo with a pre-configured setting.

I reached in achieving something like that by adding an entry like the following one in the .storage/core.config_entries file:

{
  "version": 1,
  "minor_version": 1,
  "key": "core.config_entries",
  "data": {
    "entries": [
      {
        "entry_id": "28eb233267c07b12aaa4d021e6b29dd4",
        "version": "1.0.0",
        "domain": "alarmo",
        "title": "Alarmo",
        "data": {},
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "7d157df4ab24",
        "disabled_by": null
      }
    ]
  }
}

and by having the file .storage/alarmo.storage with the following content (I want to enable the away, home and night modes):

{
  "version": 6,
  "minor_version": 1,
  "key": "alarmo.storage",
  "data": {
    "config": {
      "code_arm_required": false,
      "code_disarm_required": false,
      "code_format": "number",
      "disarm_after_trigger": false,
      "master": {
        "enabled": true,
        "name": "master"
      },
      "mqtt": {
        "enabled": false,
        "state_topic": "alarmo/state",
        "state_payload": {},
        "command_topic": "alarmo/command",
        "command_payload": {},
        "require_code": true,
        "event_topic": "alarmo/event"
      }
    },
    "areas": [
      {
        "area_id": "1685025590",
        "name": "Alarmo",
        "modes": {
          "armed_away": {
            "enabled": true,
            "exit_time": 60,
            "entry_time": 60,
            "trigger_time": 1800
          },
          "armed_home": {
            "enabled": true,
            "exit_time": 0,
            "entry_time": 0,
            "trigger_time": 1800
          },
          "armed_night": {
            "enabled": true,
            "exit_time": 0,
            "entry_time": 0,
            "trigger_time": 0
          }
        }
      }
    ],
    "sensors": [
    ],
    "users": [],
    "automations": [],
    "sensor_groups": []
  }
}

I just want to ask if there are better ways that do not require to change files in the .storage folder.

Thank you so much for your help.

**Comment by cnaslain** [comment]
+1
I try to configure HA as much as possible using CasC.
having an example of configuration using yaml files would be great.

**Comment by nielsfaber** [comment]
This is not possible due to limitations of HA.
An integration is either UI or yaml managed, not both.
