### ISSUE TITLE
Add time of day to Alarmo card

### ISSUE THREAD

**Issue by niraviry** [nielsfaber/alarmo#743]
### Checklist
- [V] I checked for similar existing requests (both open and closed) before posting.
- [V] My request is generic, other users may benefit from it too.

### Proposal
Usually the alarm card is the default card when used in tablets inside the house. Adding the time of day in a size that is seen even to users that wear reading glasses will be great.

### Additional info
A dedicated time of day card is possible but takes space and prevents the Alarmo card from being a clean card in the dashboard.

**Comment by nielsfaber** [comment]
You will have to make your own card for that. I don't see it fitting with this card.
