### ISSUE TITLE
Volume settings 

### ISSUE THREAD

**Issue by Leettp** [nielsfaber/alarmo#745]
Would be nice with a possibility to increase volume of announcements from Google aswell as a more native way to insert an alarm sound for Sonos. In Ui for us nooby HA people.

**Comment by snickers2k** [comment]
is a duplicate of so many requests .. :D 

@nielsfaber is still not sure how to manage it. but i guess is super easy.

-1 #752 
-2 #362
"Browser_mod" or "LANnauncer" to play from Tablets. Sonos etc. is already populated as media-player.

**Comment by nielsfaber** [comment]
How do you set the volume on your Sonos device outside of alarmo (which service)?
What limitation did you find in Alarmo?

**Comment by Leettp** [comment]
> How do you set the volume on your Sonos device outside of alarmo (which service)?
> What limitation did you find in Alarmo?

Hi Niels

So I tried to change the volume from the actions tap, by going into the yaml mode and add service: media_player.volume_set but it’s not saving the parameter. 

The dream feature for me in alarmo would be the ability to change volume in the actions UI tab. 

If it make sense?

**Comment by iroQuai** [comment]
I struggle with this too! since a lot of times the alerts played on my google home speakers are not loud enough, the tts function is practicly unusable!

**Comment by Leettp** [comment]
Would still be so nice to have

**Comment by iroQuai** [comment]
I still hope this feature request will get some love :)

**Comment by iroQuai** [comment]
Completed? Woah I have to check that out..
