### ISSUE TITLE
One time passcodes and users with time only access

### ISSUE THREAD

**Issue by hastime** [nielsfaber/alarmo#746]
### Proposal
Hi,

I am wondering if it would be possible to add one time passcodes, these could then be used by someone to disarm and then arm the system again once and then be deleted. Along the same lines I was wondering if it would be possible to have access codes that only work between set hours on set days. This functionality is similar to most smart locks and would be useful to mimic on the smart alarm.

Thanks for developing such a useful integration! 

Thanks,

**Comment by nielsfaber** [comment]
There are services `alarmo.enable_user` and `alarmo.disable_user` which can be used for this.
You could create a simple automation (outside of Alarmo) to disable the user after it was armed.
The `alarm_control_panel.alarmo` entity should have a `changed_by` property which should show which user has last armed/disarmed the alarm.
So connecting it together, your automation should look like this:
* Triggers when the alarm is being armed (state changed to armed_*)
* Condition is that the `changed_by` property matches a certain user
* Action is that the `alarmo.disable_user` service is performed with that user as parameter.

**Comment by hastime** [comment]
> There are services `alarmo.enable_user` and `alarmo.disable_user` which can be used for this. You could create a simple automation (outside of Alarmo) to disable the user after it was armed. The `alarm_control_panel.alarmo` entity should have a `changed_by` property which should show which user has last armed/disarmed the alarm. So connecting it together, your automation should look like this:
> 
> * Triggers when the alarm is being armed (state changed to armed_*)
> * Condition is that the `changed_by` property matches a certain user
> * Action is that the `alarmo.disable_user` service is performed with that user as parameter.

This is a great idea, I cannot believe I missed this. Thanks! I am going to set this up now. I guess using a time/date or day of the week condition, you could also set up time based users as well as one time codes! Thanks again!
