### ISSUE TITLE
Breaking Change in latest HomeAssistant Update

### ISSUE THREAD

**Issue by CarlesLlobet** [nielsfaber/alarmo#751]
### Alarmo Version

1.9.9

### HA Version

2023.7.0

### Bug description

The most recent update (14 hours ago), includes a [commit](https://github.com/home-assistant/core/commit/12129e9d21db5a808478b0795ed3ac5a023a9124) from 3 days ago where they've removed the SERVICE_CALL_LIMIT variable from core.py.

This only affects to `latest` versions of some repositories such as `homeassistant/raspberrypi4-64-homeassistant`.

This makes Alarmo unable to initialize properly, and therefore breaks all functionality:
![image](https://github.com/nielsfaber/alarmo/assets/6575422/242bfbcc-0912-48ea-89a8-9df972648c8b)

### Steps to reproduce

Update to latest version of home assistant:
`docker-compose pull && docker-compose up -d`

See the notification when home assistant inits that couldn't load Alarmo:
![image](https://github.com/nielsfaber/alarmo/assets/6575422/327b92a9-9e22-4a38-8249-0da479acb912)

### Relevant log output

```shell
The following integrations and platforms could not be set up:

alarmo (Show logs)
Please check your config and logs.

----

Home Assistant Core
Setup failed for custom integration alarmo: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
21:17:02 – (ERROR) setup.py


--- 

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 21:17:02 (1 occurrences)
Last logged: 21:17:02

Setup failed for custom integration alarmo: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
```

**Comment by nielsfaber** [comment]
Thanks for informing me, I will try to make a fix for this in the upcoming days

**Comment by jsnyde30** [comment]
I'm not sure if this was updated or not, but I removed my old alarmo instance and re-installed it using HACS (then rebooted HASS) and after the reboot, Alarmo is working again.  Hope this helps!

**Comment by nielsfaber** [comment]
@jsnyde30 the issue will only occur when the user has configured an action or notification in Alarmo. A re-install will not work. I am aiming at releasing the changes later this week, before the july release.

**Comment by nielsfaber** [comment]
This change is now released in v1.9.10 of alarmo.
Please update and check if the issue if resolved for you.
If so, you can close the issue.
Otherwise, please let me know.

**Comment by MattWeiler** [comment]
Thank you, the latest build fixed it 😁

**Comment by CarlesLlobet** [comment]
+1

Confirming fix, I was waiting for the stable tag of HA to be released. 
Updated to stable and everything fine with latest release (1.9.10) 👍
