### ISSUE TITLE
Feature Request - Changed By AppUser wildcard for notification messages

### ISSUE THREAD

**Issue by thlucas1** [nielsfaber/alarmo#754]
### Proposal
Would like to have a "Changed_By_AppUser" wildcard for Actions.Notification.Task messages.  This would insert the name of the currently logged on user into the message.

### Additional info
In the case of notifying a user when the alarm is disarmed ... it appears that Alarmo resolves the "Changed By" wildcard value (based upon the PIN code that was entered) to a user name defined for the PIN code in Alarmo User Management UI.  I have a family of 4 that share the same PIN code.  I have all 4 of our names defined with the same PIN code in the Alarmo User Management UI.  We all get notifications of when the alarm was disarmed, using the "Changed By" wildcard placeholder.  No matter who disarms the alarm, the "Changed By" wildcard always displays the same name in any notification messages that are sent.  However, the *Logbook* entry does indicate the correct user name that disarmed the alarm as part of the event log.

I would propose a new "Changed By AppUser" wildcard value to insert the user name of the person that is logged into Home Assistant.  If the logon cannot be determined (or is not set if coming from an automation task by the system) then fall back to the "Changed By" PIN code behavior.  Otherwise, use the same user name value that the Logbook entry is using.

****Logbook Screenshot****
![image](https://github.com/nielsfaber/alarmo/assets/38439576/84127a7b-a81e-4335-923d-a8d48205b2e2)

****Notification Log****
![image](https://github.com/nielsfaber/alarmo/assets/38439576/7438cca9-9900-4363-89f6-2fbcf5270ef8)

**Comment by nielsfaber** [comment]
Alarmo has no data available of which HA account or which device was used for (dis)arming.
This is exactly why Alarmo has its own user administration.
I believe changes are required within HA before your request could be implemented.

**Comment by nielsfaber** [comment]
Thanks for the appreciation, feedback is always welcome.
I wish I could implement your request, but my previous investigations resulted in a dead end.
I will ask around (again) in the developer forums to check if provisions can be made to share the user data.
