### ISSUE TITLE
Verified alarm possibility

### ISSUE THREAD

**Issue by robinbohnen** [nielsfaber/alarmo#759]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Only trigger alarmed state if 2 sensors are triggered, this way false positives will happen a lot less (now flies are triggering my movement sensors).

### Additional info
Trigger an alarm with more than 1 triggered sensor. For example one door and one movement sensor are trigger shortly after eachother. Or 2 movement sensors in (for example) 1 minute.

**Comment by nielsfaber** [comment]
Did you try setting up a [sensor group](https://github.com/nielsfaber/alarmo#sensor-groups)?

**Comment by robinbohnen** [comment]
🤦‍♂️ oh wow; totally not seen that one. I think this is the exact solution to my question. Thanks!
