### ISSUE TITLE
Audible Entry and Exit Delay Request

### ISSUE THREAD

**Issue by GitYaSome** [nielsfaber/alarmo#761]
Hi there, I have a Home Assistant Blue and I'm using Alarmo through HACS to use it as a replacement for my old hardwired alarm system.  I arm and disarm from my tablets and phones with the HA App and from 3 permanently wall-mounted android tablets running Fully Kiosk browser.  A huge item I am missing from my old system is the entry and exit delay sounds.

### Proposal
I would love to see an audible Entry and Exit delay option. 
A simple beep once a second with the last 5 seconds beeping twice a second would be a start.
If you wanted to take it further you could add an option to play an audio file.

Thank you!

**Comment by GitYaSome** [comment]
What I'm looking for is for the wall mounted tablet that is running alarmo to use it's internal speaker as a beeper or sound player to beep or play a sound on entry or exit.

**Comment by GitYaSome** [comment]
@ nielsfaber Is there any way to do this on a wall mounted Samsung tablet, or would you consider making it a feature?

**Comment by GitYaSome** [comment]
@nielsfaber Is there any way to do this on a wall mounted Samsung tablet, or would you consider making it a feature?

**Comment by nielsfaber** [comment]
@GitYaSome I don't own a Samsung tablet and I don't want to add anything device-specific to Alarmo, so I'm not sure about this request.

Can you make HA play a sound on your tablet outside of Alarmo? Which service would you use for that and with which settings?
If this can be done, I could look into adding support in the actions tab.
If not, Alarmo is limited to what's possible in HA so I don't see a way forward.

**Comment by GitYaSome** [comment]
I run everything in a browser on the tablet and I thought the browser could
be made to play a .mid or .wav file, etc...  I was hoping that there could
be something in Alarmo that would allow you to select if you wanted delay
sounds and possibly a dropdown list of sounds.  If not a simple beep a
second would be great.
That would not be Samsung specific.
