### ISSUE TITLE
Create "Silent Open" functionality that suppresses triggered sensors

### ISSUE THREAD

**Issue by steveredden** [nielsfaber/alarmo#765]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Introduce a "quiet" or "silent" open feature, where while [some other sensor/button/logic is determined], suppress any triggered sensors from putting alarm in `pending` state.

### Additional info
I would expose a separate button (or multiple) whose state would reset after 10 seconds, but during those ten seconds any "doors" opened would not trigger the alarm to progress to `pending` state

Reference:  [Nest Detect Quiet Open](https://support.google.com/googlenest/answer/9225587?sjid=1009148164451515975-NA&co=GENIE.Platform%3DiOS&oco=0)

**Comment by steveredden** [comment]
Alternatively, Is there an API I can hit to toggle the enabled switch on the `sensors` page?

![image](https://github.com/nielsfaber/alarmo/assets/35814432/c76ce866-90f9-4c17-8d62-73f4212af1fb)

**Comment by steveredden** [comment]
seems like i found the api

uri:  `http://<yourURL>/api/alarmo/sensors`
method: `POST`
body: `{"entity_id":"<id>","enabled":<bool>}`
auth:  headers.authorization == `bearer <jwt>`

**Comment by steveredden** [comment]
...would love a builtin service to disable entity...

**Comment by steveredden** [comment]
for anyone that wants to use my Node-RED workaround:

![image](https://github.com/nielsfaber/alarmo/assets/35814432/8b4a6bf2-f25d-4475-bd39-dc5a17e4ca51)

```java
[
    {
        "id": "42334f4ff0d95ebf",
        "type": "hb-event",
        "z": "b1d79aa1436b7f71",
        "g": "f7fa5c40331f4eb8",
        "name": "Silence Chime",
        "Homebridge": "homebridge",
        "Manufacturer": "Homebridge",
        "Service": "Switch",
        "device": "homebridge0E:25:93:11:3A:8FHomebridgeSilence Chime00000049",
        "conf": "44f75c4e150eb005",
        "sendInitialState": false,
        "x": 750,
        "y": 2980,
        "wires":
        [
            [
                "a08b7cdf9abb5a8e"
            ]
        ]
    },
    {
        "id": "a08b7cdf9abb5a8e",
        "type": "function",
        "z": "b1d79aa1436b7f71",
        "g": "f7fa5c40331f4eb8",
        "name": "Create body for enabling/disabling sensors",
        "func": "const newState = (msg.payload.On == 0);   //if silenced, state will be false (disable sensors)\n\nvar msgArray = [];\n\nconst sensors = [\n    \"binary_sensor.examplesensor1_contact\",\n    \"binary_sensor.examplesensor2_contact\",\n    \"binary_sensor.examplesensor3_contact\"\n];\n\nfor (const entityID of sensors) {\n    msgArray.push({\n        \"payload\": {\n            \"entity_id\": entityID,\n            \"enabled\": newState\n        }\n    });\n}\n\nreturn [msgArray];",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1010,
        "y": 2980,
        "wires":
        [
            [
                "3d859f8e045744c5"
            ]
        ]
    },
    {
        "id": "3d859f8e045744c5",
        "type": "http request",
        "z": "b1d79aa1436b7f71",
        "g": "f7fa5c40331f4eb8",
        "name": "POST to /api/alarmo/sensors",
        "method": "POST",
        "ret": "txt",
        "paytoqs": "ignore",
        "url": "http://<myURL>:8123/api/alarmo/sensors",
        "tls": "",
        "persist": false,
        "proxy": "",
        "insecureHTTPParser": false,
        "authType": "",
        "senderr": false,
        "headers":
        [
            {
                "keyType": "other",
                "keyValue": "authorization",
                "valueType": "other",
                "valueValue": "Bearer <myLongLivedHASSToken>"
            },
            {
                "keyType": "other",
                "keyValue": "Content-Type",
                "valueType": "other",
                "valueValue": "application/json"
            }
        ],
        "x": 1320,
        "y": 2980,
        "wires":
        [
            []
        ]
    },
    {
        "id": "44f75c4e150eb005",
        "type": "hb-conf",
        "username": "932-29-317",
        "macAddress": ""
    }
]
```

**Comment by ToastyMallows** [comment]
I feel bad bumping a closed/stale issue, but I was looking for this functionality as well.  I'm trying to switch off of the Nest Secure system before its end-of-life in April 2024, and this is one feature that Alarmo doesn't have yet.

**Comment by steveredden** [comment]
That was my use case as well. i'm pretty happy with my dummy switch that disables all alarmo sensors (then re-enables after 10sec).

https://github.com/nielsfaber/alarmo/issues/765#issuecomment-1636880181

**Comment by ToastyMallows** [comment]
@steveredden did you get that button working entirely within Home Assistant?  I've never created an automation that makes REST API calls, I'm looking into it now to see if I can get it working.  Any additional info you have about your setup would be super helpful 😄

**Comment by steveredden** [comment]
I use node red to do it.  but it looks like you could do it with this integration:

https://www.home-assistant.io/integrations/rest_command/

**Comment by nielsfaber** [comment]
Sorry for ignoring this request until now.
> ...would love a builtin service to disable sensor entity...
One for "ALL" and one that specifies an entity_id

This could be added. However, it forms a bit of a security leak.
Theoretically anyone with HA access could execute this service which would compromise the security, even if the alarm is armed.
Therefore, it would be more conservative to have the service require a valid pincode (as for arming the alarm) to be provided.
What is your view on this?

> I would expose a separate button (or multiple) whose state would reset after 10 seconds, but during those ten seconds any "doors" opened would not trigger the alarm to progress to pending state

To help fulfilling the request, the service could get an extra 'time' parameter, which would revert the disabling operation after the entered time.

**Comment by ToastyMallows** [comment]
I agree requiring a PIN would be good.

In the Nest Secure implementation, you can't enable "Quiet Open" from the app, you have to hit a physical button on the sensor.  It's useful for when you want to exit the house but keep the house in its current armed state, usually "Home and Guarding" in Nest or "Armed Home" in Alarmo.

My current use-case for this is to just hit a button on the Nest Secure door/window sensor while I'm leaving the house so that I can go out to the garage while someone else is still home.  Ideally each sensor you want to Quiet Open with would have its own button for disabling that sensor only and the re-enabling it after the time period is done.

This is just me though, someone else may have a use-case for disabling all of the sensors.  I guess the more configurable the better!

**Comment by ToastyMallows** [comment]
> require a valid pincode (as for arming the alarm) to be provided

Assuming you just mean that the service in Alarmo would need the pin.  I wouldn't want to type in the PIN each time I hit this button, because they're in separate rooms.

**Comment by ToastyMallows** [comment]
I've implemented this completely in Home Assistant!

I was trying to make a Blueprint for this but I couldn't figure out how to add a RESTful Command to a Blueprint to share it.  Not sure if that's possible.

# Quiet Open for Alarmo sensors

## What To Purchase

- Any button you can mount next to your door sensor (like your current Nest Secure setup)
  - I bought these Zigbee Smart Switches:
    - https://www.amazon.com/dp/B07D19YXND
  - Not sure if they make sensors with buttons, that'd be ideal if it existed!

## Create Long-lived Token

1. User > Scroll down to "Long-lived access tokens"
1. Create a new token with a descriptive name
1. Copy the token to a notepad to use next

## `secrets.yaml`

Create a Bearer token authentication header secret to use in your RESTful Command.

```yaml
quiet_open_auth_header: "Bearer <long-lived token>"
```

## `configuration.yaml`

Create a start and end RESTful Command to disable and reenable the door sensor.

- `<yourURL>` - The URL for your Hassio setup
- `<id>` - The entity Id in question (the door sensor)
- `!secret quiet_open_auth_header` - The Bearer token auth header we created previously

Duplicate the start and end commands for each button you need to create.  Probably a better way to do this by passing around some data between the automation and the RESTful Command using templates, but this should be fine unless you have tons of buttons to create.

```yaml
rest_command:
  door_quiet_open_start:
    url: http://<yourURL>/api/alarmo/sensors
    method: POST
    headers:
      authorization: !secret quiet_open_auth_header
    payload: '{"entity_id":"<id>","enabled":false}'
  door_quiet_open_end:
    url: http://<yourURL>/api/alarmo/sensors
    method: POST
    headers:
      authorization: !secret quiet_open_auth_header
    payload: '{"entity_id":"<id>","enabled":true}'
```

> ⚠ **IMPORTANT!** ⚠
>
> After creating these RESTful Commands in YAML, you **MUST** restart Home Assistant, or else the commands won't show up in the Automation GUI.

## Create the Automation

Settings > Automation & scenes > + Create Automation

### Triggers

Your new door switch button pressed

![image](https://github.com/nielsfaber/alarmo/assets/4356159/9fd5e6a5-3ce4-46b1-a312-daaa01f9f184)

### Conditions

Alarmo is armed home

![image](https://github.com/nielsfaber/alarmo/assets/4356159/216d82b7-906a-4768-a8c9-778a426bb641)

### Actions

Call 'Start' RESTful Command, delay X seconds (I picked 10), call 'End' RESTful Command

![image](https://github.com/nielsfaber/alarmo/assets/4356159/5167f9df-613f-4416-a544-66feec225dda)

Save the new Automation.

And that's it!  Make sure to test this out by setting Alarmo to armed home and press your button.  When you open the door, Alarmo should stay armed.  After 10 seconds, if you open the door again, the entry delay should start (or the alarm is triggered, depending on what you have configured).

**Comment by ljb2of3** [comment]
Unfortunately, this doesn't seem to be working for me. I'm using the API to disable and enable sensors in alarmo, and I can see the enabled toggle switch state change in the UI in real time, but the alarm behavior only seems to be respecting the initial state when the alarm was armed.

If the sensor was disabled when the alarm was armed, the sensor is ignored, even if it is enabled via the API while the alarm is armed. If the sensor was enabled when the alarm was armed, then the alarm is triggered by the sensor despite being disabled by the API while the alarm was armed.

I'd love to make this work. I'm moving away from Nest Guard (thanks google) and I very much like the quiet open feature so I want to replicate this functionality.
