### ISSUE TITLE
Group doesn’t work

### ISSUE THREAD

**Issue by wolfs1989** [nielsfaber/alarmo#768]
### Alarmo Version

v1.9.10

### HA Version

2023.7.2

### Bug description

Group doesn’t work.
When I regroup some device in the same room, each device trigger alarm

### Steps to reproduce

Group some device in same room
Arm alarm

**Comment by nielsfaber** [comment]
Groups work fine for me (and many others).
Please describe the issue more clearly (e.g. share screenshots of your configuration) if you expect any help on this.
This is not a valid bug report.

**Comment by wolfs1989** [comment]
I have 2 groups
One with 4 devices, another with 3 devices.
When my presence detector detects some people, it trigger alarm (even if my other detector (in the same group) don't detect anything).

https://ibb.co/6P1K336 
(one group)

https://ibb.co/d5QyFHP
(another group)

https://ibb.co/YWL7p0F

Maybe my configuration isn't good but I don't understand why one device in group "veranda" trigger alarm 
I understand : if all devices in the same group detect some presence, that's trigger alarm

I expect to be clear ... (I'm French..)

**Comment by nielsfaber** [comment]
Can you show a screenshot of the ‘sensors’ tab as well?
I am suspecting you didn’t configure all sensors in the group(s) to be active in the mode in which you arm (e.g. away mode).
In this case the group will not work fine.

**Comment by wolfs1989** [comment]
yes for the screenshot : 

https://ibb.co/1rKt3Fy

All of my sensor are in the mode away

**Comment by wolfs1989** [comment]
for the group, I have in the same group the same type of sensor (move sensor, for detection, with 1 camera and 1 presence sensor)

**Comment by wolfs1989** [comment]
Do you have any ideas ?

**Comment by nielsfaber** [comment]
At this point I have no idea what causes problems for you.
As a last resort,  could you copy the contents of the `alarmo.storage` file which is located in your HA configuration directory in subfolder `.storage`? This folder may be hidden depending on your OS, but it does exist.
I am only interested in the section regarding the sensors, feel free to remove the rest.
