### ISSUE TITLE
Group times changed to seconds

### ISSUE THREAD

**Issue by OptimusGREEN** [nielsfaber/alarmo#769]
### Checklist
- [ y] I checked for similar existing requests (both open and closed) before posting.
- [y ] My request is generic, other users may benefit from it too.

### Proposal
Have the time in the group settings set to seconds instead of minutes. This allows a more definitive positive of motion. 
I've had false positives on sensors within a minute of each other before, I currently manually set up a sensor thats on when 2 other sensors trigger within 10 seconds and this has served me well. It would be nice to delete these extra sensors and rely on groups within alarmo.

### Additional info
Only just fornd Alarmo today and its awesome. well done!

**Comment by OptimusGREEN** [comment]
Go away stale bot, I still want this.

**Comment by nielsfaber** [comment]
Note that you can click on the 'x mins' text to toggle the units to seconds.
But I will shuffle some things around to allow for a finer resolution.

**Comment by nielsfaber** [comment]
I made some changes (https://github.com/nielsfaber/alarmo/commit/eaf82cf9408835b623ad0d941abb1b5659c091f3), I will let you know when a new version is released.

**Comment by nielsfaber** [comment]
v1.9.11 is released. It allows setting delay in 10 second resolution.
Could you update to the new version and verify whether it solves your needs?
If so, the request can be closed.
