### ISSUE TITLE
Alarm not triggered

### ISSUE THREAD

**Issue by cnmarch6** [nielsfaber/alarmo#77]
- My door sensor is set up as immediate but it didn't triggered the alarm.
- Then I kept the door open/on --> I still could arm the system 
> Immediate
......
Note: an immediate sensor must be off before you can enable the alarm. It is not allowed to be on while you are leaving the house.
> 

- I disable "Arm night", "Arm home" but it still showed 2 mode "Arm home" "Arm away" on the panel after restart HA. Is that the minimum mode I must have?

**Comment by cnmarch6** [comment]
https://user-images.githubusercontent.com/46871524/102848981-3e74db80-446a-11eb-97c3-0d9e06586c8a.mov

**Comment by nielsfaber** [comment]
Please revise this setting:
![image](https://user-images.githubusercontent.com/16861605/102894310-2fd6f600-4463-11eb-870f-339f2b110353.png)

The red label with cross is meant to emphasize that it is not enabled.

> I disable "Arm night", "Arm home" but it still showed 2 mode "Arm home" "Arm away" on the panel after restart HA. Is that the minimum mode I must have?

You mean the Lovelace Alarm panel card?
You have to define which buttons you want to see (it's not synced with the configuration).
See here: https://www.home-assistant.io/lovelace/alarm-panel/#states

**Comment by cnmarch6** [comment]
I deleted from hacs and installed manually then it worked
