### ISSUE TITLE
When arm show directly open sensors in screen

### ISSUE THREAD

**Issue by poudenes** [nielsfaber/alarmo#770]
Hi ALl,

I love this integration. It's so advanced and lots of great options!!!
Maybe it is there already, but when I arm the house for away and the time is over I see the message "Could not arm....."
Then im already left the house. 

Would it be possible at the moment you press ARM AWAY the message will shown already? Then you see direct after pressing the button the message and you can close the door/window and arm again.

Greets,
Peter

**Comment by nielsfaber** [comment]
You can configure if a sensor is allowed to be active during the exit delay.
If a sensor is configured as not allowed, the arming will fail (and message will be shown) before the countdown.
I would suggest to only use exit delay on door sensors which you use for leaving the house, all other sensors should not have delay.
I don't think a new feature is needed to satisfy your request.

**Comment by poudenes** [comment]
This are the settings for all of my door sensors except front door. But when I arm no message will show. Arm is active after 30 seconds.
<img width="602" alt="Screenshot 2023-09-04 at 09 59 58" src="https://github.com/nielsfaber/alarmo/assets/4399532/b9cfbc95-f629-4195-a2b0-a19304c57206">
