### ISSUE TITLE
Alarm don't activate

### ISSUE THREAD

**Issue by orebla85** [nielsfaber/alarmo#773]
### Alarmo Version

v1.9.10

### HA Version

2023.6.3

### Bug description

The buttons are inactive. When I try to activate via HomeKit it waiting without success. Manually activates but then does not arm when motion is detected. I haven't made any updates of any kind. It worked yesterday, not today. 

### Steps to reproduce

The buttons are inactive, they don't work.

### Relevant log output

```shell
nothing in any log.
```

**Comment by diversit** [comment]
Perhaps because a sensor was in a state not allowing the alarm to be armed?

I had a similar issue. See #771.

**Comment by nielsfaber** [comment]
> The buttons are inactive, they don't work.

Which buttons? Alarmo doesn't have such buttons.
Please show a screen video of the problem. Without more info I am unable to help and this issue will be closed.

**Comment by orebla85** [comment]
> Perhaps because a sensor was in a state not allowing the alarm to be armed?
> 
> I had a similar issue. See #771.

Yes it is the problem, one of my sensor is became unavailable and Alarmo don’t work.
I disable the sensor and now it’s works.
Thanks!!

![65292342-2332-448A-BB0B-96DA17A3021A](https://github.com/nielsfaber/alarmo/assets/97201917/984601ae-73cd-438b-a149-93e2b15c8fa3)
