### ISSUE TITLE
Entry Delay not working

### ISSUE THREAD

**Issue by gmum4d** [nielsfaber/alarmo#774]
### Alarmo Version

V1.9.10

### HA Version

2023.7.3

### Bug description

Entry Delay is not working. I have the entry delay set to 90 seconds but the alarm triggers immediately.  I have tried different time settings but no change. (The exit delay seems to work OK)

### Steps to reproduce

HA on RPi4 and Konnected Alarm Pro alarm panel

**Comment by nielsfaber** [comment]
This doesn't look like a valid bug report to me.
Check your sensor settings (by clicking on a sensor in the 'sensors' tab).
You can configure per sensor whether it should trigger immediately or after delay, only motion sensors will trigger with delay by default.

**Comment by gmum4d** [comment]
Hi. You are correct. I had already configured all the sensors and switches that needed to include an entry delay, but I didn’t realise that one of my motion sensors in a different room was just about picking the slightest bit of movement through a tiny gap in a doorway and triggering the alarm. Thanks for the responseGaryOn 24 Jul 2023, at 19:59, Niels Faber ***@***.***> wrote:﻿
This doesn't look like a valid bug report to me.
Check your sensor settings (by clicking on a sensor in the 'sensors' tab).
You can configure per sensor whether it should trigger immediately or after delay, only motion sensors will trigger with delay by default.
