### ISSUE TITLE
Different alert for environment / fire alarms

### ISSUE THREAD

**Issue by beyondunreal79** [nielsfaber/alarmo#775]
Would it be possible to set a different alert notification for fire alarms? Or maybe a way to separate burglary alerts from environmental (high priority) alarms?

**Comment by Skysurfer-14** [comment]
I was asking me, how to alert my environment sensors, like smoke and water sensors. At the moment it's only possible to include this sensors to the other sensors with the result, that an alarm of a smoke sensor at disarmed state not leads to an alarm. So I support this feature request.

**Comment by Ryckie** [comment]
I would also like this feature!
As of now when my smoke alarm triggers, I must use the same notification channel as a normal alarm because alarmo doesn't make a difference.

I would like thisfeature:
-  Triggered by: Environmental Alarm is triggered (For notifications and actions, so we can trigger different scripts to sound the fire alarms and not the intruder alarms.

**Comment by nielsfaber** [comment]
If a fire alarm and burglar alarm should behave differently, I think it's best to keep them apart.
This is possible by creating a separate area in Alarmo and adding all environmental sensors here.
Next you can create different actions for the different areas (burglar alarm area and environmental alarm area).
Note that area does not necessarily have to be a physical space in your house. 

A related question (that has also been discussed before): do environmental sensors really belong within Alarmo?
Are the different states and disarm/arm operations needed for an envionmental alarm?
If the desired behaviour is to play a sound or send a notification when (or while) the smoke sensor is activated, wouldn't this fit better in a simple automation (outside of Alarmo)?

**Comment by Ryckie** [comment]
Thank you for your explanation. Doing this and creating some additional scripts / automations for my ring keypad has solved it for me.
What is the trigger time for environmental alarms?
