### ISSUE TITLE
Can't arm away (SOLVED)

### ISSUE THREAD

**Issue by ansris** [nielsfaber/alarmo#779]
### Alarmo Version

1.9.10

### HA Version

2023.7.2

### Bug description

when I try to arm-away (60sec pre-activation time is set), alarmo goes automatically to disarm as soon as i open the door (there is a sensor on my door)... I think that in pre-activation time, no sensor should trigger the alarm... 
please let me know how I can solve this 

thanks in advance 

### Steps to reproduce

arm away with the main door closed
in the 60sec pre-activation time, open the door to exit home
alarmo goes to disarm

**Comment by XxCabbyoO** [comment]
Do you have unrecognized entitys? Just disable them and test again:

-> https://github.com/nielsfaber/alarmo/issues/773#issuecomment-1648482097

**Comment by XxCabbyoO** [comment]
> thanks for the answer... please can you tell me how to check unrecognized entitys? I think i have no one of them but if you can tell me where to ckeck just to be sure. thanks in advance

Alarmo - Sensors

See the screenshot at the linked comment: https://github.com/nielsfaber/alarmo/issues/773#issuecomment-1648482097

**Comment by ansris** [comment]
ok thanks for the screenshot, I confirm that there are no unrecognized sensor entitys in my alarmo installation

**Comment by alfem** [comment]
I confirm @ansris (thanks!) issue.

(After many days trying to debug why my alarm does not arm when I activate a physical button at home, but it does when I arm it using the lovelace interface from work).

Obviously (now), the front door sensor deactivates the arming process as soon as I go out.

**Comment by nielsfaber** [comment]
Click on the front door sensor in the list to access its settings. Ensure it has ‘use exit delay’ enabled. This doesn’t look like a bug to me, just a configuration issue.

**Comment by ansris** [comment]
Great! This seems to solve the problem!
Thank you so much!
I consider it a bug because if a sensor is set as front door that gives access to the home, I suppose it's automatically configured to use the activation delay.
Anyway now that I know this option I configured it properly.
Tomorrow I will make more tests, thank you so much!

**Comment by alfem** [comment]
Yes! That was hidden in advanced options. Thank you very much for your help @nielsfaber

**Comment by nielsfaber** [comment]
> I consider it a bug because if a sensor is set as front door that gives access to the home, I suppose it's automatically configured to use the activation delay.

I agree. I thought this was the case but I just double checked it and saw it is only applied on the entry delay.
I just fixed it, to avoid the same problem for others.
I'm glad this issue is fixed now.

**Comment by ansris** [comment]
thank you so much

**Comment by KidA001** [comment]
> Click on the front door sensor in the list to access its settings. Ensure it has ‘use exit delay’ enabled. This doesn’t look like a bug to me, just a configuration issue.

This was the exact issue for me. I had no idea these settings were here. Thanks so much!
