### ISSUE TITLE
Remain the triggered state option 

### ISSUE THREAD

**Issue by Ryckie** [nielsfaber/alarmo#782]
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
Add an option to keep the alarmo state to triggered after an alarm, until actually disarming it.

### Additional info
I use a Ring Keypad v2 and when the alarm is triggered, it makes sound for the time set in alarmo. But after that it goes back to a normal armed state. No nottification on the panel that there has been an alarm after ariving home hours later then the alarm was triggered. Keeping the triggered state may help some people like me to keep the alarm led's in a red state.

**Comment by Ryckie** [comment]
bump

**Comment by nielsfaber** [comment]
In alarmo you can set the trigger time to zero, it becomes infinite:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/5686e29e-854a-495f-b91e-efa37ed8d6d9)

The alarm would stay in the triggered state until you disarm it yourself.

**Comment by Ryckie** [comment]
> In alarmo you can set the trigger time to zero, it becomes infinite: ![image](https://user-images.githubusercontent.com/16861605/269716421-5686e29e-854a-495f-b91e-efa37ed8d6d9.png)
> 
> The alarm would stay in the triggered state until you disarm it yourself.

Hi, I understand this can be done per arm mode. But for the environmental sensors I put in another alarm group. I have all modes disabled. Bc it doesn't make sense to have any enabled for an always on sensor group. And even then, under what mode would an always on sensor fall?
