### ISSUE TITLE
Disarm with tag while in pending state (entry delay)

### ISSUE THREAD

**Issue by hugomickael** [nielsfaber/alarmo#783]
### Alarmo Version

1.9.10

### HA Version

2023.8.2

### Bug description

I have an automation created to change state to Disarmed when I scan a tag and the alarm is armed. It Works great. But when a sensor is triggered (alarm armed) and Alarmo is in the entry delay (pending state), the tag doesn't work to disable the alarm, I need to wait until it is in triggered state. How can I do it to disable before siren is triggered?

Here is my code on automation conditions:

`condition: or
conditions:
  - condition: device
    device_id: 4a5195648146643a5b8a981a630f908d
    domain: alarm_control_panel
    entity_id: 4cac6d729e9e0a5dbbf574e0c92f1c3c
    type: is_armed_home
  - condition: device
    device_id: 4a5195648146643a5b8a981a630f908d
    domain: alarm_control_panel
    entity_id: 4cac6d729e9e0a5dbbf574e0c92f1c3c
    type: is_armed_away
  - condition: device
    device_id: 4a5195648146643a5b8a981a630f908d
    domain: alarm_control_panel
    entity_id: 4cac6d729e9e0a5dbbf574e0c92f1c3c
    type: is_armed_night
  - condition: device
    device_id: 4a5195648146643a5b8a981a630f908d
    domain: alarm_control_panel
    entity_id: 4cac6d729e9e0a5dbbf574e0c92f1c3c
    type: is_armed_vacation
  - condition: device
    device_id: 4a5195648146643a5b8a981a630f908d
    domain: alarm_control_panel
    entity_id: 4cac6d729e9e0a5dbbf574e0c92f1c3c
    type: is_triggered`

### Steps to reproduce

Create an automation, where the trigger is "When a tag is scanned", Conditions are the above, and actions are "Call a service Alarm Control Panel: Disarm".

**Comment by nielsfaber** [comment]
Can you clarify why you post a bug report for this?
Is something wrong on the side of alarmo?

For automation triggers/conditions I suggest to use the state with entity ID, not a device. There are examples in the documentation.
