### ISSUE TITLE
Temperature / heat / fire alarm

### ISSUE THREAD

**Issue by YvoTuk** [nielsfaber/alarmo#789]
I noticed in the sensor type list that heat sensors would be recognized, but in my install they're not.
That is, if a heat sensor is a temperature sensor (which I'd expect?)

I would like to use alarmo mainly as a fire alarm, but that doesn't really seems to be an option.

A fire alarm would be consisting of smoke detectors and temperature sensors.
If a temperature rapidly increases (% in time) it would raise an alarm / if a smoke detector triggers it would raise an alarm.

I can see the smoke detector functionality, but can something be implemented with temperature sensors?

**Comment by nielsfaber** [comment]
Alarmo only supports binary sensors (i.e. on/off sensors).
Temperature sensors are not supported.
You could define a [template binary sensor](https://www.home-assistant.io/integrations/template/#binary_sensor) to convert the temperature reading to a on/off value, and use that for alarmo.

**Comment by josh208** [comment]
> Alarmo only supports binary sensors (i.e. on/off sensors). Temperature sensors are not supported. You could define a [template binary sensor](https://www.home-assistant.io/integrations/template/#binary_sensor) to convert the temperature reading to a on/off value, and use that for alarmo.

Just to add to this, you can also create a sensor group based on min or max of a group of sensors, then create a threshold sensor based on that group sensor. In this way, you can avoid having to add a bunch of separate threshold sensors. I did this to provide Freeze Warning for a cabin that is not regularly occupied.
