### ISSUE TITLE
Switching "Mode" in Alarmo: Doesn't Update/Refresh Page

### ISSUE THREAD

**Issue by teek541** [nielsfaber/alarmo#791]
### Alarmo Version

1.9.10

### HA Version

2023.8.4

### Bug description

I opened the alarmo app, under modes, I selected a different area (shop) and it doesn't update to the sensors in that area or allow me to edit things such as entry delay, or enable/disable arming modes for that area.  It's still stuck on the first area when the page loads.

There are no errors in the log.

### Steps to reproduce

Select a different area from the drop down list.

### Relevant log output

```shell
None
```

**Comment by nielsfaber** [comment]
You mean this view?

https://github.com/nielsfaber/alarmo/assets/16861605/a63600f8-5a8d-48eb-8bf7-3ca6ef1eb2e1

For me it works as I would expect. How does this look like for you?

**Comment by teek541** [comment]
I don't have a video screen capture, sorry.
![image](https://github.com/nielsfaber/alarmo/assets/45326308/04559044-7bed-4536-83d8-44e2a58517a7)
That is my "home" alarm.  When I click the "Shop" option from the drop down, it doesn't change.

![image](https://github.com/nielsfaber/alarmo/assets/45326308/a11ef818-3c87-4583-8b2b-5426bbbe82e5)
The Shop alarm only has 1 sensor in it.

**Comment by kidhasmoxy** [comment]
I just noticed this exact issue when using the iOS Home assistant app. Also appears my environmental sensors didn't trigger my alarm.

**Comment by teek541** [comment]
It's been resolved now I think in the latest version.
