### ISSUE TITLE
{{changed_by}} is not always addressing the right user

### ISSUE THREAD

**Issue by citgot** [nielsfaber/alarmo#794]
### Alarmo Version

V1.9.10

### HA Version

2023.8.4

### Bug description

I’m using Alarmo both with the HA app on iPhone and with a zigbee keypad. When I arm the alarm sometimes the wrong user is shown in the notification. Not every time but more often than not. It is also a random wrong user, not the same every time. 

 I have four users in Alarmo with different PIN codes and the problem is the same for all users. The problem is also the same using the app or the zigbee keypad. The {{changed_by}} wildcard is somehow not addressing the right user (the user with the used PIN code). 

I’ve tried to delete users and add them again with new PIN codes but the problem persist. 

### Steps to reproduce

Setup notification with {{changed_by}} wildcard. 

Arm the alarm with HA app on iPhone or zigbee keypad.

**Comment by Tobbe82** [comment]
Close enough to my problem, as I wanna catch the user (state) reported by Yale that I use to control the alarm. 
When unlocking with code on the Yale unit I suppose the notification in alarmo picks the state before Yale has a chance to change it. Maybe the possibility to add a delay for like 0,5-3 seconds could help? So that the state may change before the notification picks it.

**Comment by nielsfaber** [comment]
I am unable to reproduce this issue.
I created 3 users with different pin code, and configure the alarm to require a code for arming.
Next I configured a notification using the `changed_by` wildcard.
For me, the wildcard is always showing the user corresponding to the entered code.
Do you have any further suggestions which could help me reproduce the issue?

**Comment by Tobbe82** [comment]
Citgot uses a zigbee keypad and I uses a Yale lock to arm/disarm. So basically the alarmo works. But what’s needed is like a delay for a second or two before the notice goes out so that the state from the external units is able to be updated and received in alarmo.

**Comment by nielsfaber** [comment]
@Tobbe82 the changed_by property is updated simultaneously with the state. I don’t see a reason for adding a delay somewhere.
Delaying the responsiveness of alarmo for all users is not a good idea anyway.
What is the bug here on the side of alarmo exactly? It is not clear for me.

**Comment by citgot** [comment]
On my end the problem seems to have gone away. Now it never shows the wrong user. I don’t know why it was showing the wrong user from the start but it sorted itself out after a week or so (with several reboots inbetween). You can close this issue

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

Den 11 okt. 2023 kl 21:13, Niels Faber ***@***.***(mailto:Den 11 okt. 2023 kl 21:13, Niels Faber <<a href=)> skrev:
