### ISSUE TITLE
Change pin code / password without UI

### ISSUE THREAD

**Issue by PaulSka** [nielsfaber/alarmo#795]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal

Hi,
It's possible to add feature for changing password / code for user without UI ( with service, mqtt,...)

### Additional info
Some exemples :
* On arming, generate new code and notify user
* Change code each week / month with specific pattern
* With calendar, read code value and enable user with this

Thanks !

**Comment by kohlerryan** [comment]
+1

**Comment by rtrox** [comment]
The reverse would be great too -- an event fired when a code is added -- usecase: when adding a code to alarmo, duplicate that code onto keypad based door locks.

**Comment by nielsfaber** [comment]
@PaulSka Your request seems to introduce security problems. If the pincode can be set via a service call, it would be very easy to set the code to e.g. ‘0000’ and override the alarm.

@rtrox alarmo cannot send the configured code via an event, since the code is encrypted (and cannot be decrypted).

**Comment by PaulSka** [comment]
@nielsfaber It's possible to secure this call with api key generated on alarmo ( required for 'secure' service call ) ?
It's possible to disable alarm with service call too no ?
