### ISSUE TITLE
Possibility to exclude persons

### ISSUE THREAD

**Issue by saschabrockel** [nielsfaber/alarmo#798]
I cannot use this because I cannot exclude persons who shouldn't be considered as persons being home.
I'm living in my apartment but my parents have access to HA too and are included and even though they are in their own apartments the alarm will never arm because they will be at home in HA.

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Add a possibility to exclude person entities that shouldn't be used for arming.

**Comment by nielsfaber** [comment]
Alarmo does not make use of person entities.
The arming/disarming is done via a pin code instead.
I don't understand your request.

**Comment by saschabrockel** [comment]
Lol sorry the German translation seems a bit weird then. I misunderstood that and still wonder why Alarmo is not working for me. I stays on inactive and I cannot change it
