### ISSUE TITLE
Allow "Use disarm code" to be set at the HA user level

### ISSUE THREAD

**Issue by francesc0s** [nielsfaber/alarmo#799]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Allow the configuration option for "Use disarm code - Require a code for disarming the alarm" to be set at the home assistant user level. 

### Additional info
This would allow a user with minimal security requirements (e.g. a wall-mounted tablet) to require a code to disarm the alarm, while another user with stricter security requirements (e.g. a complex login/pass with 2FA on a phone/PC with fingerprint sign-in) could disarm without using a code.

**Comment by nielsfaber** [comment]
I completely agree this would be a great improvement.
Unfortunately it is not possible to detect from which device alarmo is armed/disarmed nor by which user.
The pincode that is used for the operation is currently the only way to distinguish the user.
This is not really a limitation of alarmo, it is a limitation of the services in HA.

**Comment by francesc0s** [comment]
Thanks for the quick reply and background details. I'm surprised HA has this limitation. Could you expand a bit more on the limitation and how HA would ideally pass along information regarding which user is accessing the frontend of a custom integration? I might submit a feature request on the core-HA github repo, but it would help to have a better understanding of what's needed.

**Comment by nielsfaber** [comment]
> Could you expand a bit more on the limitation and how HA would ideally pass along information regarding which user is accessing the frontend of a custom integration? 

The alarm can be armed via a service call, for example this:
```yaml
service: alarm_control_panel.alarm_arm_away
data:
  code: 1234
target:
  entity_id: alarm_control_panel.alarmo
```
Pressing a button in the UI (like with the alarm panel card) will trigger a similar service to be executed.

On the integration side, the counterpart of this service call is implemented, the function that should perform the arming:
```python
    async def async_alarm_arm_away(self, code: str | None = None) -> None:
        """Send arm away command."""
        # implementation goes here
```
[assistant/core/blob/2722e5ddaaf583adda9dce55197145b54097d08d/homeassistant/components/alarm_control_panel/__init__.py#L175-L177)](https://github.com/home-assistant/core/blob/2722e5ddaaf583adda9dce55197145b54097d08d/homeassistant/components/alarm_control_panel/__init__.py#L175-L177)

The parameters that are passed to the integration (alarmo in this case) are limited to the service data that is sent along. In this case only the 'code' is a data parameter that can be used within the function.
There is no details sent along, like contextual information of how the service was called. Hence it is not possible to determine whether:
* The service was executed from a dashboard card or via the Developer Tools / Services panel
* The service was executed by User A or User B being logged in into HA
* The service was executed from a browser or a mobile phone

Having such information would be very useful for alarmo. This would satisfy your request, but also notification messages could be targeted to a specific device.

**Comment by francesc0s** [comment]
Thank you so much for breaking this down so clearly. That was incredibly easy to understand even as an intermediate user/developer.

I noticed that the Logbook in HA reflects the user that called a service:

![image](https://github.com/nielsfaber/alarmo/assets/115735094/80bd0e09-3d6b-44cf-9317-923e5f5aeb71)

Just to make sure I understand this correctly, HA does retain details regarding which user made the service call, but when HA sends the code to alarmo it does not pass a parameter though with the user details?

One other thing I've been thinking about is how browser_mod is able to track which user and device is accessing the frontend. Are you familiar with that integration? I imagine the way browser_mod is ingesting that data is significantly different than the way alarmo receives a service call, but figured it was worth mentioning.

**Comment by nielsfaber** [comment]
I am aware that the HA logbook displays more information than what is available to alarmo. However I have no idea whether the extra information can be retrieved in any way. This doesn’t seem to be documented anywhere.

I have used browser_mod in the past but I remember it just generates some (random) ID per device, and adds entities for it to HA. I don’t think the device type (like someone’s phone running the HA app) is known (as can be selected via the notify services).
I would like to keep alarmo independent of other custom integrations, so using browser_mod as a means to detect the device does not seem the way forward for me.

Did you create a feature request in HA core related to this topic?

**Comment by francesc0s** [comment]
Unfortunately, HA-core does not have feature requests open on their github. As an alternative, they direct you to [community.home-assistant.io/c/feature-requests](https://community.home-assistant.io/c/feature-requests/13) where you can open a forum topic. It's primarily used for custom_component requests, and given that none of the available tags are related to the backend, it doesn't appear to be very useful for this type of request.

With that, and along with the reality that I wouldn't be able to articulate the request adequately, I decided not to open it. I apologize, but it seems like I would be a castaway placing a message in a bottle and throwing it into the ocean. 

I sincerely appreciate your time here and am sorry for falling short on my promise.
