### ISSUE TITLE
Reloading the integration deletes the storage file with settings

### ISSUE THREAD

**Issue by bobvmierlo** [nielsfaber/alarmo#80]
When you reload the integration from the 'Integrations' page the alarmo.storage files gets deleted from the .storage folder.
Thus deleting all the configuration done in Alarmo.
Why not write the config to a YAML file in the custom_component/alarmo root folder?

**Comment by Tibor070** [comment]
HI, great integration, but when I reload the integration, all my settings are gone and I have to redo all the setting again. Is this a know bug, or is this normal behavior when reloading?

**Comment by nielsfaber** [comment]
What would you expect to happen by clicking this reload button?
I cannot influence the behaviour as far as I know.
I will try to hide this button.

**Comment by Tibor070** [comment]
May be reloading the integration without losing all the data! But never mind, now I know it, I won't use it! Keep up the good work! 👍🏻

**Comment by cnmarch6** [comment]
Is there a way to copy this .file?

**Comment by nielsfaber** [comment]
This is fixed by https://github.com/nielsfaber/alarmo/commit/00e159078195f3d520b35c95063c87fc39bf62cf (will be released in v1.6.1).
Reloading will only reset the entities, not longer remove the configuration.
