### ISSUE TITLE
After iOS17 update, all arm modes are visible in HomeKit 

### ISSUE THREAD

**Issue by stormshaker** [nielsfaber/alarmo#801]
### Alarmo Version

v1.9.10

### HA Version

2023.9.2

### Bug description

Since the update to iOS17 (from the public beta onward), home assistant is publishing all alarm modes to HomeKit (arm away, arm home, arm night and off) even though I only have arm away and off configured in Alarmo.

### Steps to reproduce

Use the Home app in iOS17. Alarm control panel published via HomeKit bridge. This was working as expected in ios16.

**Comment by nielsfaber** [comment]
This bug should be addressed to HA, not alarmo.
