### ISSUE TITLE
Notification activated but not send 

### ISSUE THREAD

**Issue by meepmeep** [nielsfaber/alarmo#802]
### Alarmo Version

v1.9.10

### HA Version

2023.9.1

### Bug description

I tried to set up a simple notification, "when alarm is triggered", 

I use this message with names & states of 

```
The alarm is triggered! Cause: {{open_sensors}}.
L'alarme est en etat : {{arm_mode}}
```
The dry run works perfectly : 

![image](https://github.com/nielsfaber/alarmo/assets/584651/ce6f943f-f53e-4d08-a1e6-95cd88585138)
 but when the alarm is really armed, it doesn't trigger and I got the log below.

### Steps to reproduce

Set the notification to (in yaml) : 

```
service: notify.monitoring_status
data:
  message: |-
    The alarm is triggered! Cause: {{open_sensors}}.
    L'alarme est en etat : {{arm_mode}}
  title: Alerte !


```

### Relevant log output

```shell
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:655
Integration: Telegram bot (documentation, issues)
First occurred: September 28, 2023 at 12:19:17 PM (3 occurrences)
Last logged: September 28, 2023 at 8:14:05 PM
Error sending message: Can't parse entities: can't find end of the entity starting at byte offset 47. Args: (-760638195, "Alerte !\nThe alarm is triggered! Cause: capteur_porte Door is open.\nL'alarme est en etat : Armed away"), kwargs: {'parse_mode': 'Markdown', 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}
```

**Comment by nielsfaber** [comment]
See https://github.com/nielsfaber/alarmo/issues/54. The issue is related to telegram.

**Comment by OptimusGREEN** [comment]
The notification seems to be sent after the action which if an issue if the action involves a loop. Are you using a loop in your action?

**Comment by meepmeep** [comment]
I'm not.
It's clearly link to #54 (parsing error for telegram)

**Comment by jsapede** [comment]
got the same problem here with telegram, event without "states" in the message
can someone explain what it is related to ?

**Comment by hardwareadictos** [comment]
Did someone managed to get a solution?
