### ISSUE TITLE
Arming the alarm gives error 'does not support this service'

### ISSUE THREAD

**Issue by actabi** [nielsfaber/alarmo#805]
### Alarmo Version

v1.9.10

### HA Version

2023.10.0

### Bug description

After installing Alarmo and setting up the detectors to monitor, I am unable to use Alarmo as intended. Every time I try to activate Alarmo, I receive an error stating: "Entity alarm_control_panel.alarmo does not support this service." Despite troubleshooting attempts, the issue persists.

### Steps to reproduce

Go to HACS (Home Assistant Community Store) within Home Assistant.
Install the Alarmo integration.
Restart Home Assistant.

Configuring the detectors with Alarmo:
Open the Alarmo user interface.
Set up multiple detectors to monitor.
Save the configuration.

Activating Alarmo:
Try to activate Alarmo through the user interface.
Observe the error: "Entity alarm_control_panel.alarmo does not support this service.

### Relevant log output

```shell
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:53:47 (1 occurrences)
Last logged: 21:53:47

[281472506759232] Entity alarm_control_panel.alarmo does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 857, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity alarm_control_panel.alarmo does not support this service.
```

**Comment by nielsfaber** [comment]
Could you check in the Developer Tools -> States page, whether the 'alarm_control_panel.alarmo' exists? And perhaps, could you share a screenshot of all the properties showing here?

Furthermore, what do you mean by 'Try to activate Alarmo through the user interface'?
There are multiple ways to do so. Which card are you using? Which button are you clicking?

Could you try arming alarmo via the Developer tools -> Services page as well? You should be able to arm via the alarm_control_panel.alarm_arm_away or alarmo.arm services. Does the service still fail this way?
