### ISSUE TITLE
Configuration page stuck on 'loading...'

### ISSUE THREAD

**Issue by ssorgatem** [nielsfaber/alarmo#807]
### Alarmo Version

1.9.10

### HA Version

2023.10.1

### Bug description

The interface remainsas "loading..."

A different user on reddit has the same issue: https://www.reddit.com/r/homeassistant/comments/1749rpa/alarmo_interface_not_loading/

### Steps to reproduce

Go to the Alarmo panel

**Comment by nielsfaber** [comment]
I cannot reproduce this issue.
Does this occur all the time or only on some specific device, right after restarting HA, etc. ?
It's pretty hard for me to help on the issue until I'm able to catch it myself, so if you have some pointers, that would be great.

**Comment by ddanielww** [comment]
This happens on PC and mobile for me.

Easiest way to reproduce is just to click from the dashboard back into alarmo several times.

it will eventually bug out and get stuck on loading.

**Comment by ssorgatem** [comment]
This happened to me in all devices (PC, phones, tablet) at the same time.
And then, the next day, it didn't happen anymore, without doing anything about it.

Funnily enough, I can no longer reproduce it, but I did upgrade HA in the meantime.

**Comment by nielsfaber** [comment]
I haven't been able to reproduce this issue still. Tried on multiple devices but I never see the 'loading..' message for more than 2 seconds.

**Comment by LukeDefeo** [comment]
Im also facing this, issue tried updating to the latest version of alarmo. Here are my logs, hope this helps




 
```
2023-11-06 22:57:32.058 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-06 23:09:26.212 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Platform alarmo does not generate unique IDs. ID alarm_control_panel.alarmo is already used by alarm_control_panel.alarmo - ignoring alarm_control_panel.alarmo
2023-11-06 23:09:26.257 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in async_watch_sensor_states when dispatching 'alarmo_state_updated': ('1667820847', None, 'disarmed')
File "/config/custom_components/alarmo/sensors.py", line 199, in async_watch_sensor_states
File "/config/custom_components/alarmo/sensors.py", line 436, in update_ready_to_arm_status
alarm_entity.ready_to_arm_modes = arm_modes
File "/config/custom_components/alarmo/alarm_control_panel.py", line 271, in ready_to_arm_modes
async_dispatcher_send(self.hass, "alarmo_state_updated", self.area_id, None, None)
```

**Comment by EvanMTickets** [comment]
Same, I am stuck on this issue too

**Comment by EvanMTickets** [comment]
> larmo_state_updated", s

How did you access those logs? I am not seeing any logs.

**Comment by sabricakmak** [comment]
I tried to reach config page of alarmo from laptop pc and it was opened without any problem. But loading stick problem is same on apple phone application.

**Comment by fribse** [comment]
I saw this as well on both firefox and Chrome on my pc, but I did a 'ctrl+F5' on it, and now it shows the page, so it could be some sort of old cache?

**Comment by nielsfaber** [comment]
I added a small improvement which _may_ fix this (may, because I cannot reproduce it still) in the v1.9.14.
Please update to the new version (note that in the alarmo panel you should see v1.9.14 written in the top right corner after updating, else you have the older version in cache).
If you still experience this issue with this version, please let me know.

**Comment by baloo2** [comment]
I upgraded my docker container to 2024.1.6 today and Alarmo is stuck on LOADING in MacOS Safari. On iOS app it works OK.

**Comment by nielsfaber** [comment]
@baloo2 Could you wipe your browser cache to make sure the new version is used by the browser?

**Comment by alex3305** [comment]
Still an issue for me.
