### ISSUE TITLE
Allow "Disarm after trigger" to be settable by mode

### ISSUE THREAD

**Issue by harryfine** [nielsfaber/alarmo#808]
### Checklist
- [YES ] I checked for similar existing requests (both open and closed) before posting.
- [YES ] My request is generic, other users may benefit from it too.

### Proposal
I use Alarmo HOME mode to trigger a script to simply alert people with a gentle chime who may be outside or on the terrace that someone has arrived home.  I want it perpetually armed once set.  If I set it to "Disarm after trigger", then I only get my automation (script) the first time the door is opened.  So I want to disable "Disarm after trigger". 

I use Alarmo AWAY mode to trigger a script to alert via phone, siren and trigger video if someone opens the door when I am away.  So it's a security system, rather than a notification.  If I have set it to disable "Disarm after trigger", then the siren keeps going.  I would prefer the siren to go off, so I want to enable "Disarm after trigger".  

### Additional info
The setting for Disarm after trigger should be setable for each of the modes.

**Comment by nielsfaber** [comment]
I would like to keep alarmo simple as possible, so I am reluctant to add more settings.

> If I have set it to disable "Disarm after trigger", then the siren keeps going. I would prefer the siren to go off, so I want to enable "Disarm after trigger".

The time for which the siren keeps ringing is defined by the trigger time.
Whether the alarm afterwards reverts to the disarmed state or armed state is unrelated.

For your usage disabling the 'disarm after trigger' setting should fit your needs.
