### ISSUE TITLE
Alarmo should ask a code for switching between armed modes, but not from "disarmed" state.

### ISSUE THREAD

**Issue by mrgrlscz** [nielsfaber/alarmo#809]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting. -> OK
- [x] My request is generic, other users may benefit from it too. -> OK

### Proposal (edited for understanding ) 
Hey, alarmo (without "use arm code" option) let us switching from i.e. armed_away  to armed_home... without any code. And this is a big security problem as, in my case, armed_home mode do NOT watch for a lot of sensors.
There is an option to ("use arm code") but... there's no need for a code from" disarmed mode" to any armed mode.... only from an armed mode to another on.
(i'm using "armed_away","armed_home","armed_night","disarmed")

**Comment by nielsfaber** [comment]
>  Alarmo have to ask a code for switching between armed modes, but not from "disarmed" state.

Alarmo requires a code for any arm action if you enabled the 'use arm code' setting. 
There is no difference between arming from the disarmed state or from another mode.
Your request describes the current behaviour.

>  alarmo let us switching from i.e. armed_away to armed_home... without any code.

I don't think this is possible with the current behaviour (unless you have the 'use arm code' setting disabled).

**Comment by mrgrlscz** [comment]
Yes, there's no difference at the moment but....maybe it should?

If I turn on "use arm code" option, you just can't arm from services.
I am using an android tile to arm_away. And a momentary switch in my garage for arming_home.
I can understand this is not possible, I was just wondering.

**Comment by nielsfaber** [comment]
Sorry, I don’t understand your request.
Your initial request (and the title) seems to be opposite of what you are mentioning now.
Please clearly state what is desired.

**Comment by mrgrlscz** [comment]
No worries, my english level is... Barely medium.
Here's my logic:
  - disarmed to any armed mode = do NOT need a code
  - any armed mode to another on OR disarmed = obviously NEED a code

BUT, my apologies, I just realized that I can insert a code in a service settings. This way I can do what I want.
HOWEVER in the future, if I change security code, I'll have to modify manually EVERY service call to match the new code?

**Comment by mrgrlscz** [comment]
I still think it could be a good idea. But everything is OK for me this way.
Thank you, really, for Alarmo. I know a lot of people are saving a lot of time thanks to you.
