### ISSUE TITLE
 Add option to always use code when use the "alarm_custom_bypass" function.

### ISSUE THREAD

**Issue by HolmbomDK** [nielsfaber/alarmo#814]
Add option to always use code when use the "alarm_custom_bypass" function.

And alarm custom bypass should always have a code arm and disarm, since you technical can make the alarm system like a swish cheese - full of big holes :-)

**Comment by nielsfaber** [comment]
I don’t really understand your point.
Why is this request specific to “custom bypass”?
When transitioning from armed away to armed home, the same issue could occur right?

I am considering to add an extra option “require code when changing between arm modes”. I don’t see any benefit of making it specific for the “custom bypass” mode.

**Comment by HolmbomDK** [comment]
Sorry for not answering before i have been out with covid for the laste 3 weeks.

I have seen the “require code when changing between arm modes” have come and I am a "happy camper"

In my original "request" before i sendt it, i had 3 requests but 2 was already covered by others, so they were removed.

1.  “require code when changing between arm modes”  Solved.
2.  "assault alarm" one code not a used code by any users to signal destress - a forced entry against your will, with you pressent - running a "silent alarm" to alert others that you are in distress. 
3. specific code to “custom bypass”


1. When transitioning from armed away to armed home, the same issue could occur right? Yes but has been taken care off  "require code when changing between arm modes” Now it works both ways, up and down the security ladder, personally I would only like it if you went down the security ladder, like from a higher to a lower security level, but now it's both ways and not a problem for me, but an option would be nice.

2. Seems to say it all, and needs no further explanation

3. Request specific to “custom bypass”?

You are running a multiuser system. You have no option to set the alarm mode - away. night etc. by user or user groups - it is all or nothing.

Example : User is setting the alarm and it does not work cause there is a open sensor. 
So a conscious man will go and close the open sensor, then set the alarm. Where as an lazy employ or teen son/daughter, just want to get out of there, does not give a damn that a sensor is open, and take the easy way - custom bypass. If it is in the perimeter then we have a hole in the system - the system is technical sound but the user is the problem. 

So a super-user level or a super-user-code  on “custom bypass” - or use HA owner or Admin - to take care of this problem.
“Custom bypass” should be the highest level on the security ladder, because it is security with deliberate gaps. and when creating gaps in security, it must be a very deliberate and premeditated action, and not the easy solution.

:-)

**Comment by HolmbomDK** [comment]
sorry - I just realized - custom bypass - is a way to set up your own "total fucked system" and not a hole in the system.

So by setting require code when changing between arm modes this solves the problem
