### ISSUE TITLE
Don’t consider sensor changes from unavailable to on

### ISSUE THREAD

**Issue by candrea77** [nielsfaber/alarmo#815]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [ X] My request is generic, other users may benefit from it too.

### Proposal
For any kind of sensor, add another Advance settings : don't trigger alarm when status change from "Unavailable" to "On"
On the opposite, would be also sufficient to add, for motion sensors only : "Bypass automatically Exclude this sensor from the alarm if it is **_`ON`_** while arming."

### Additional info
Currently , the new zwave feature in V12 that restart the controller when it is freezed, cause all zwave device to flip between their current status to unavailable and then back to their status again.
https://github.com/zwave-js/node-zwave-js/issues/6402
In case a zwave device is an alarm sensor, and you have choosen to alarm system either if sensor is active, when a zwave hang occur, sensor change it's status from ON --> to UNAVAILABLE.
When zstick is recovered , sensor change it status back to ON again, triggering the alarm.

**Comment by nielsfaber** [comment]
What’s up with the capital title text? Please don’t do that.

Regarding the request: why should alarmo ignore the sensor state becoming “on” after being “unavailable”?
If the sensor reports state “on”, there is motion detected. I don’t see why this should be ignored.

**Comment by candrea77** [comment]
@nielsfaber : Hi there,
I would like to apologies for the inconvenience with capital text on the subject line.
I didn't want to appear rude (simple I tought that subject need to be in capital text)

Have a nice day

**Comment by candrea77** [comment]
> Regarding the request: why should alarmo ignore the sensor state becoming “on” after being “unavailable”?
> If the sensor reports state “on”, there is motion detected. I don’t see why this should be ignored.
Motion sensor haven't the settings  "Bypass automatically Exclude this sensor from the alarm if it is ON while arming."
So, if you arm the system and the sensor is on, it woldn't be ignored. Also the system will be armed without triggering the alarm.

In case of any problem with the sensor subsystem, if it become unavailable and then turn back available, the changes between "Unavailable" and then "On" trigger the alarm.

My proposal is to : 
- Solution A :  Don't track changes from unavailable to on
- Solution B : Add the seetings "Bypass automatically Exclude this sensor from the alarm if it is ON while arming" also for Motion Sensor (actually this is available for door and windows sensor)

I know that this is a workaround for a problem not related to "alarmo" (motion sensor that remain on is a lack of communication between sensor and hassos) but it could help to prevent false positive.
