### ISSUE TITLE
Don't re-arm after alarm trigger if opening sensor even if initially armed with open sensors

### ISSUE THREAD

**Issue by robertoprubio** [nielsfaber/alarmo#816]
### Alarmo Version

1.9.1

### HA Version

2023.10.5

### Bug description

When arm the alarm we have the option to bypass open sensors. 
When the alarm is triggered it auto re-arm after the timeout but in this new version (1.9.1) you have introduced a change that the alarm doesn't re-armed if opened sensors.
Please, change to automatically re-arm if open sensors if initially armed bypassing open sensors or add a setting to user change this.
Thanks

### Steps to reproduce

-

### Relevant log output

```shell
-
```

**Comment by nielsfaber** [comment]
I made release v1.9.12. In this version the previously bypassed sensors will be maintained when re-arming after triggering.
Hope this solves the issue for you.

**Comment by robertoprubio** [comment]
Thanks for the quick reply and also for the good work
