### ISSUE TITLE
Can't set desiered trigger time

### ISSUE THREAD

**Issue by froloffw7** [nielsfaber/alarmo#817]
### Alarmo Version

1.9.11

### HA Version

2023.8.4

### Bug description

After update from 1.9.10 to 1.9.11 there some problem to set mode trigger time with UI.
- all modes, which had 1 minute trigger time with version 1.9.10,  with version 1.9.11 trigger time can be set between 5-60 seconds;
- **Home Mode** which had 5 minutes trigger time with version 1.9.10,  with version 1.9.11 trigger time can be set between 5-60 minutes.

Any value can be set manually in file .storage/alarmo.storage 

### Steps to reproduce

Go to Alarmo->General->Modes and try to change Trigger Time

**Comment by nielsfaber** [comment]
The change has been made on purpose.
You can click on the text next to the slider to switch between setting the time in seconds vs minutes.
Am I missing something?

**Comment by froloffw7** [comment]
Yes, switching between seconds and minutes works fine. The idea is great, but probably some help tooltip will not be superfluous.

Just a question before closing this issue.
After update, the alarm now activated also with the sensors do not included in the mode sensor list.  For example in home mode it triggers alarm from the entrance door sensor also, which is not in this mode list.  Should I try to clear Alarmo configuration and setup everything again?

**Comment by codyc1515** [comment]
> After update, the alarm now activated also with the sensors do not included in the mode sensor list. For example in home mode it triggers alarm from the entrance door sensor also, which is not in this mode list. Should I try to clear Alarmo configuration and setup everything again?

#818

**Comment by nielsfaber** [comment]
I released v1.9.12 which brings back the previous trigger time setting, hope it solves the issue for you.
