### ISSUE TITLE
Alarm triggering via sensor associated with other mode

### ISSUE THREAD

**Issue by tdickman** [nielsfaber/alarmo#818]
### Alarmo Version

v1.9.11

### HA Version

2023.10.5

### Bug description

After the latest version upgrade to Alarmo, I am getting invalid alarm triggers. Specifically, the alarm is getting triggered via sensors that are setup to trigger in other modes.

This same config worked fine with the previous version.

### Steps to reproduce

1. Configure a sensor for away and night.
2. Arm the alarm in home mode
3. Trigger the sensor from 1
4. Alarm is triggered despite it not being associate with home mode

**Comment by nielsfaber** [comment]
Noted, thanks for reporting.
I will look into this as soon as I can.

**Comment by santiniuk** [comment]
Just to advise I was looking to post same issue found after upgrade.
Thanks

**Comment by smarthomefamilyverrips** [comment]
Same issue here when set to "armed night" which only is associated with 2 sensors it triggers the alarm by 5 other sensors that are only associated with "armed away"

**Comment by nielsfaber** [comment]
I released v1.9.12 which should patch the issue. My apologies for the mistake.

**Comment by santiniuk** [comment]
Fantastic support. Thanks for the quick fix.

**Comment by smarthomefamilyverrips** [comment]
Thanks for the swift response 👍🏻

**Comment by Drewskieza** [comment]
I have updated to 1.9.12 but it seems to send a notification each time a door is opened/closed "Alarm state changed to disarmed".
Have not tried it with the alarm active.
Not sure if this is the same issue we had earlier.

**Comment by smarthomefamilyverrips** [comment]
At me the integration fails to start if I update to 1.9.12

Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 15:02:11 (3 occurrences)
Last logged: 15:02:17

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/__init__.py", line 56, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 682, in async_get_registry
    return cast(AlarmoStorage, await task)
                               ^^^^^^^^^^
TypeError: custom_components.alarmo.store.Config() got multiple values for keyword argument 'code_mode_change_required'

**Comment by smarthomefamilyverrips** [comment]
@nielsfaber it also not loads anymore now when I rollback to 1.19.10 😐

**Comment by virtusas** [comment]
> I have updated to 1.9.12 but it seems to send there is a status update for alarmo each time a door is opened or closed. Not sure if this is the same issue we had earlier.
> 
>
I have similar issue. My automation on Alarm disarm sends notification on alexa speaker that alarm was disarmed. Now any contact sensor on every event update, open or close issues message to alexa that alarm is disarmed, whilst alarm is already at disarmed state.

**Comment by nielsfaber** [comment]
@smarthomefamilyverrips @Drewskieza @virtusas @mleiber Please limit the discussion here to the initial issue that was reported. Feel free to open another bug report if you encounter any.

**Comment by tdickman** [comment]
Thanks for the swift bugfix @nielsfaber. Since the original bug is fixed for me (and a few other users), I'm going to go ahead and close this issue.
