### ISSUE TITLE
Cannot set notification custom icon

### ISSUE THREAD

**Issue by PilaScat** [nielsfaber/alarmo#820]
### Alarmo Version

v1.9.12

### HA Version

2023.10

### Bug description

This is what I want:
![image](https://github.com/nielsfaber/alarmo/assets/12989749/2726079b-f342-4de7-8cc7-c0d1afbf9f6b)
This is what I get:
![image](https://github.com/nielsfaber/alarmo/assets/12989749/946edd92-ac5c-4b40-a525-d6dedc5f2306)

### Steps to reproduce

set icon via yaml

**Comment by nielsfaber** [comment]
This has nothing to do with alarmo.
Read the docs: https://companion.home-assistant.io/docs/notifications/notifications-basic#notification-icon

**Comment by PilaScat** [comment]
yes instead, I'm trying to customize the alarm notification but it doesn't work, I tried to do it manually and it works
