### ISSUE TITLE
Contact sensor event change triggers Alexa notification

### ISSUE THREAD

**Issue by virtusas** [nielsfaber/alarmo#825]
### Alarmo Version

1.9.12

### HA Version

2023.10.5

### Bug description

Whilst alarm is in disarmed tate, opening any contact sensor linked to Alarmo, causes notification being sent to Alexa that alarm has been disarmed. Usually notification is being sent only once whilst disarming alarm. Now it itriggers on any event change on contact sensor. Alarmo operates normally in Armed state. 

### Steps to reproduce

Alarmo in disarmed state. 
Any contact sensor linked to Alarmo is being activated. 
Notification is being sent to Alexa.

**Comment by Drewskieza** [comment]
I have a similar issue.

This is the automation being triggered

alias: Alarm - Send notification for activation
description: ""
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarmo
action:
  - service: notify.mobile_app_xxxxxxxxx
    data:
      title: Alarm state changed to
      message: "{{ trigger.to_state.state}}"
mode: single

**Comment by Steve-gnome** [comment]
this also triggers node red disarm events

**Comment by virtusas** [comment]
Thank you for update @nielsfaber . I have sorted mine also. It was exactly the issue as described above. But it was like that since day one setting up Alarmo and there was no issue. So something has been updated in Alarmo updates that issue arised only now and started causing troubles for people. I believe this is exactly the place for people to talk about issues, especially that are linked to same integration, if no one will ask questions then there will be bunch of people scratching their heads on what is wrong. Not everyone is at advanced level of coding, or understanding full aspects of automations. There must be tons of people who are just reading and not commenting and trying to figure out things. Please @nielsfaber don't take it so personally or offencivelly this matter. No one is posting here anything with bad intentions on their mind. Thank you for understanding.

**Comment by rt400** [comment]
I have the same issue. After downgrade to 1.9.10v the issue is gone.
So i think that is not automation problem.
Something in the code make any sensor change to change alarm state.

**Comment by virtusas** [comment]
I have just changed this attribute field from blank to Arm Mode and my issue was gone of false triggering. 

![Uploading IMG_0097.jpeg…]()

**Comment by Drewskieza** [comment]
I populated the "to" field on the trigger with "Any state (ignoring attribute changes)" as suggested by nielsfaber and this resolved the issue.
Home Assistant is evovling so sometimes we have to adjust our setups.

alias: Alarm - Send notification for activation
description: ""
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.alarmo
    **to: null**
action:
  - service: notify.mobile_xxxxxxxxx
    data:
      title: Alarm state changed to
      message: "{{ trigger.to_state.state}}"
mode: single

**Comment by virtusas** [comment]
> I populated the "to" field on the trigger with "Any state (ignoring attribute changes)" as suggested by nielsfaber and this resolved the issue. Home Assistant is evovling so sometimes we have to adjust our setups.
> 
> alias: Alarm - Send notification for activation description: "" trigger:
> 
> * platform: state
>   entity_id:
>   
>   * alarm_control_panel.alarmo
>     **to: null**
>     action:
> * service: notify.mobile_xxxxxxxxx
>   data:
>   title: Alarm state changed to
>   message: "{{ trigger.to_state.state}}"
>   mode: single

My one automation has few different outcomes, depending on Alarmo state, to avoid multiple other automations being created. There fore not assigning attribute was the cause of automation failing perform as intended.

**Comment by Beer17HWAM** [comment]
Can anyone translate this to node-red? I use the "trigger state node" now.
Thanks.

**Comment by Beer17HWAM** [comment]
How can I set "To" to null in the "trigger state" node within node-red? I can't find it. Sorry. Who can help me?

**Comment by Sinfonia97** [comment]
I've been able to get it to work for the most part.  Configure your trigger state as follows and it should get rid of the double trigger. 
![2023-11-25 14_39_28-Node-RED – Home Assistant](https://github.com/nielsfaber/alarmo/assets/75184065/19934531-ab66-4955-af50-cccaf6bf8575)
Hope this works for you.  Right now I am dealing with the fact that Alarmo is only allowing me to include sensors in the Alarmo zone for triggering the alarm when I have all sensors configured for both home and away modes.

**Comment by Beer17HWAM** [comment]
> I've been able to get it to work for the most part.  Configure your trigger state as follows and it should get rid of the double trigger. 
> ![2023-11-25 14_39_28-Node-RED – Home Assistant](https://github.com/nielsfaber/alarmo/assets/75184065/19934531-ab66-4955-af50-cccaf6bf8575)
> Hope this works for you.  Right now I am dealing with the fact that Alarmo is only allowing me to include sensors in the Alarmo zone for triggering the alarm when I have all sensors configured for both home and away modes.

Thanks. It's working.
