### ISSUE TITLE
Sensors trigger the alarm, not respecting Alarm mode

### ISSUE THREAD

**Issue by francescotili** [nielsfaber/alarmo#826]
### Alarmo Version

v1.9.11

### HA Version

2023.10.5

### Bug description

Since the last update, the sensors linked to Alarmo trigger the alarm, even if they should not, based on the specific Alarm mode they should be enable in the sensor settings.

Example: I have window sensor that trigger the alarm only on **Away** mode. They are now triggering the alarm also in **Night** or **Home** mode, for which they are disabled in the settings. I have not touched any settings since months, I have only updated the last 2-3 days.

### Steps to reproduce

Disable some alarm mode for a specific sensor (i.E. Home mode), in the sensor settings. Then set the Alarm to the same mode (i.E. Home) and try to trigger the sensor. The Alarm will be triggered.

**Comment by nielsfaber** [comment]
You are not on the last version.
The .11 release contained an error which was fixed in the .12 release.

**Comment by francescotili** [comment]
> You are not on the last version

Sorry, HACS doesn't show me any update. It also show the last version as 1.9.11, how can I manually update?

**Comment by francescotili** [comment]
Nevermind, opening the Alarmo page in HACS now has triggered the update notification.

Thank you!
