### ISSUE TITLE
Update to 1.4.1 and all datas are gone

### ISSUE THREAD

**Issue by cnmarch6** [nielsfaber/alarmo#83]
I followed the instruction to update Alarmo

`Manual: Download the latest release as a zip file and extract it into the custom_components folder in your HA installation, overwriting the previous installation.`

and all settings are gone 👎

**Comment by nielsfaber** [comment]
That is very strange.
All settings are kept in .storage/alarmo.storage, so they shouldn't be affected by updating.
From which version where you updating?
Is anything displayed in the logs?

**Comment by cnmarch6** [comment]
Hi nielsfaber, 

i update from 1.4.0
One I replaced the Alarmo folder and reset HA. All codes, users, sensors and settings are gone. It is like when I first installed this :(

**Comment by nielsfaber** [comment]
Can you check the `.storage/alarmo.storage` file?
It is only deleted when you uninstall the integration from HA (by Configuration -> Integrations), so your data could be still there.

**Comment by cnmarch6** [comment]
sorry where would it be?

this is all i have:
![Uploading Screen Shot 2021-01-03 at 11.44.32 pm.png…]()

**Comment by cnmarch6** [comment]
![Screen Shot 2021-01-03 at 11 44 32 pm](https://user-images.githubusercontent.com/46871524/103478896-ecdf3000-4e1d-11eb-8f62-bac4af1dd3fb.png)

**Comment by nielsfaber** [comment]
The .storage folder is on top level (so not in custom_components)

**Comment by cnmarch6** [comment]
![Screen Shot 2021-01-03 at 11 49 43 pm](https://user-images.githubusercontent.com/46871524/103478976-5e1ee300-4e1e-11eb-861a-44361a730525.png)
 
I don't think i have it then :-|

**Comment by cnmarch6** [comment]
![Screen Shot 2021-01-03 at 11 52 49 pm](https://user-images.githubusercontent.com/46871524/103479048-d5ed0d80-4e1e-11eb-86fc-3fee70682a29.png)
here it is

**Comment by nielsfaber** [comment]
This is indeed where the file should be.
It is not affected by replacing the alarmo directory in the custom_components.
The file will only be deleted by going to Configuration -> Integrations and clicking delete for Alarmo (or reload).
For every change you make in the configuration, the file will be saved (with 10 seconds delay).
I have no idea how the file disappeared for you.
I guess it has nothing to do with the update of the component.
Is there anything printed in the logs that could give some help?

**Comment by cnmarch6** [comment]
I just deleted all at once and reinstall Alarmo from HACS. 

version is still 1.4.0 and there is no `alarmo.storage `file. Do I have to create this file?

**Comment by nielsfaber** [comment]
The alarmo.storage file is created/updated 10 seconds after you make a change to the configuration.
If it doesn't, then we have a bug to investigate (but i haven't heard of anyone else with these problems).

**Comment by cnmarch6** [comment]
Thanks a lot for your time. I have just tried and saw this file.

**Comment by nielsfaber** [comment]
No problem.
Sorry about your data loss.
Hope it’s a one time incident.
Take care to backup that storage file so you won’t lose the data again.

**Comment by TRDSClub** [comment]
I had the same issue after updating from 1.3... Alarmo died on me as well. Any luck sorting this one out?
