### ISSUE TITLE
Cannot set exit delay time always reverts back

### ISSUE THREAD

**Issue by toogooda** [nielsfaber/alarmo#837]
### Alarmo Version

1.9.13

### HA Version

2023.11.1

### Bug description

You can change settings but they do not save for Exit Delay, Entry Delay and Trigger Time.
Sliders work but there is no save button and when you come back to page they are all back at 0.
Note: this was for Armed Night.

### Steps to reproduce

![image](https://github.com/nielsfaber/alarmo/assets/9059644/286dd2c8-8ec9-419c-bcc9-fedbea408dd9)
Set a value, navigate away then back.

### Relevant log output

```shell
No errors
```

**Comment by toogooda** [comment]
Tried upgrading to 1.9.13 still does not save changes

**Comment by ramorimdias** [comment]
Second this, getting the same bug here

**Comment by nielsfaber** [comment]
Please check the version number in the top right corner in the alarmo pages.
Ensure it states v1.9.13 before reporting a bug.

**Comment by dhman45** [comment]
Same here too updated to v1.9.13 and can't save changes to the Exit delay, Entry delay and Trigger time. There is on save Button to push. How to fix?

**Comment by toogooda** [comment]
> Please check the version number in the top right corner in the alarmo pages. Ensure it states v1.9.13 before reporting a bug.

As per my comment above I did upgrade and issue still exists

**Comment by ramorimdias** [comment]
The issue is solved this morning. Same version than yesterday, v1.9.13. I'm not sure what hapenned.

**Comment by dhman45** [comment]
I finely got it to work by  closing chrome browser and clearing cache. Thanks for to help
