### ISSUE TITLE
Feature request - Ability to manage remote alarmo

### ISSUE THREAD

**Issue by arnishow** [nielsfaber/alarmo#84]
The ability to manage remote alarmo (using remote_homeassistant) in one place would be nice.

**Comment by nielsfaber** [comment]
I'm not sure what this implies, I don't use remote_homeassistant personally.
In what way should things be adapted for making it compatible?
Do you have experience with remotely accessing a component with frontend, such as HACS?

**Comment by nielsfaber** [comment]
@arnishow can you elaborate on your request?
Otherwise I will close this.
