### ISSUE TITLE
Cover entities are missing in actions

### ISSUE THREAD

**Issue by bifbaf** [nielsfaber/alarmo#842]
Hi,
I would really like to open all my shutters/covers when a alarm happen. All my covers have entities like 
cover.bedroom
but for some reason I can't finde them when I want to create a new action? I only see switches.

I don't know if this should possible or not or maybe it is not implemented yet

**Comment by williknow** [comment]
I would like to have this, as well. I will use an external HA automation in the meantime. Thank you very much

**Comment by mcondren** [comment]
I have the ring glass break sensors and they go through batteries like they are going out of style if they are always listening.  I would like to make an event to change the microphone status on the zwave node to turn the mic on when the alarm arms.  Unfortunately, I am having the same problem with binary sensors being missing from the Action list.  I see lights and switches, but binary sensors are missing.
