### ISSUE TITLE
Disarmed trigger when alarmo was already disarmed 

### ISSUE THREAD

**Issue by Beer17HWAM** [nielsfaber/alarmo#844]
### Alarmo Version

1.9.13

### HA Version

2023.10.5

### Bug description

Why is alarmo triggering disarmed if a door sensor is opening while the alarm was already disarmed?
Version 1.9.10 wasn't doing that. 

### Steps to reproduce

Open sensor with alarm disarmed.

**Comment by Beer17HWAM** [comment]
The armed and disarmed events are also triggered twice. When you arm and disarm alarmo. Why is that?

**Comment by Beer17HWAM** [comment]
Also "Exit Delay" event is triggered more than once since the latest updates. Why is this all changed? Why triggering all unnecessary events?

**Comment by Beer17HWAM** [comment]
I did some research and I found out that the double events one were available in Node-Red with the "Trigger State Node". 
The normal "Event State Node" isn't doing that. For me it's strange because with older Alarmo versions this wasn't the case.
So I guess you can check this and maybe you know why this changed.

**Comment by Sinfonia97** [comment]
I can confirm that I am also getting the double trigger.  I use the "Trigger State Node" in my alarm configuration and it gets triggered twice every time I arm home, disarm, or is pending arm away.

**Comment by Beer17HWAM** [comment]
> I can confirm that I am also getting the double trigger as well as it triggering a state change when opening or closing a door or window sensor.  I use the "Trigger State Node" in my alarm configuration and it gets triggered twice every time I arm home, disarm, pending, and arming away.

Luckily I am not the only one who is responding! Niels... Please answer us.

**Comment by nielsfaber** [comment]
This is not a bug, just wrong configuration. See #825.
