### ISSUE TITLE
Can no longer arm alarmo in home mode

### ISSUE THREAD

**Issue by seancmalloy** [nielsfaber/alarmo#847]
### Alarmo Version

 v1.9.13

### HA Version

2023.11.3

### Bug description

Not sure what happened but i can no longer arm alarmo in home mode. It is enabled but arm home button does nothing

![Screenshot (54)](https://github.com/nielsfaber/alarmo/assets/23019226/e56a7786-3d07-43fd-9589-9e7a1ef7176e)

### Steps to reproduce

i removed alarmo from ha and re installed / configured it. same issue.

states:
  - arm_home
  - arm_away
type: alarm-panel
name: Alarm
entity: alarm_control_panel.alarmo

### Relevant log output

```shell
no logs created in ha system log
dont see any alarmo logs (or any way to able this)
```

**Comment by ciec68** [comment]
same but "home works"......"away" not work
alarmo v1.9.13
Core 2023.11.3
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2

**Comment by seancmalloy** [comment]
Very strange. Today my arm home button IS working. Do you know know to enable logs for alarmo?

**Comment by nielsfaber** [comment]
I recommend to install alarmo-card.
It will give feedback why arming did not work.
There is probably no bug to report here, I assume issue is related to your own configuration.

**Comment by seancmalloy** [comment]
Awesome. Did not it was option, been using alarm-panel. Works great, thanks.

**Comment by ciec68** [comment]
sensor provided by "ezviz" deprecated did not trigger the alarm. Resolved
