### ISSUE TITLE
Change URL for notifications to Alarmo Card

### ISSUE THREAD

**Issue by daelsc** [nielsfaber/alarmo#853]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
Allow the notification URL field to be editable.

### Additional info
N/A

**Comment by nielsfaber** [comment]
I have no idea what you are requesting.
Can you please clarify?

Note that alarmo-card is a separate project with a separate github, so you might be posting in the wrong place.

**Comment by daelsc** [comment]
Sorry, I was not clear!  When alarmo is triggered, it is configured to send a push notification to my phone.  When I press on that notification in iOS it loads the default dashboard of home assistant.  It is preferable to have it load directly to a specified URL that links to a dashboard that shows my alarmo status/cameras so I can figure out what is going on.
