### ISSUE TITLE
Alarmo Support Xiaomi speakers And Add zh-Hant

### ISSUE THREAD

**Issue by wymanhns** [nielsfaber/alarmo#854]
``

### Checklist
- [ ] Support Xiaomi speakers.
- [ ] Add zh-Hant.

### Proposal
[Support Xiaomi speaker]
`service: xiaomi_miot.intelligent_speaker`

[Add zh-Hant]
[zh-Hant.json](https://github.com/nielsfaber/alarmo/files/13624410/zh-Hant.json)

### Additional info
[Support Xiaomi speaker]
`service: xiaomi_miot.intelligent_speaker`
`data:`
`  entity_id: media_player.xiaomi_XXXX_play_control`
`  text: The alarm is set to `

**Comment by nielsfaber** [comment]
I added your translation file, it will be part of the upcoming release.
Thank you for your efforts.

As for the xiaomi speaker, I don't own one so I don't really know how to add support for it.
Alarmo has support for [TTS](https://www.home-assistant.io/integrations/tts/) services, this should work with your media player entity as well.
Why is there a service `xiaomi_miot.intelligent_speaker` instead? To me it seems that this service is wrongly designed. I suggest  to add a feature request for adding a TTS service in the Xiaomi Mio integration.
