### ISSUE TITLE
Mode for manually triggered

### ISSUE THREAD

**Issue by dexn** [nielsfaber/alarmo#859]
Google Assistant can set the state to "triggered" while it is disarmed.

I use this as an emergency medical alert in case my fall sensor doesn't trigger. I have this setup as an automation currently. It would be nice to use Alarmo for this instead to help keep the automations list cleaner and more organised.

**Comment by nielsfaber** [comment]
You can use the service  `alarm_control_panel.alarm_trigger` to manually trigger the alarm.

**Comment by dexn** [comment]
I think you're misunderstanding me.

In the mode drop down box for conditions, have a Disarmed option. Then we can set notifications and actions for those events.

![Screenshot_20231228_083304_Home Assistant](https://github.com/nielsfaber/alarmo/assets/2460478/5ed3580a-b805-4120-9887-1bd56b660d57)

**Comment by nielsfaber** [comment]
> In the mode drop down box for conditions, have a Disarmed option. 

Disarmed is not an arm mode. It does not belong in this list.

> Then we can set notifications and actions for those events.

There is an event 'Alarm is disarmed' for this.
