### ISSUE TITLE
mqtt does not work

### ISSUE THREAD

**Issue by not-chees** [nielsfaber/alarmo#861]
### Alarmo Version

1.9.13

### HA Version

2023.12.3

### Bug description

When I tried to arm my alarm using mqtt it didnt work. I don’t know if this is something that I am doing wrong or if it is a bug.

This is the code I use:

```
{
  "command": "arm_home",
  "code": "123456" //not my actual code
}
```

I made sure that I use json.

### Steps to reproduce

I just tried to do this with 2 different publishers. But there aren’t any steps to do this.

**Comment by nielsfaber** [comment]
Here's an example:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/162a2719-264a-42cb-a89c-e700a431bfdf)

Works with this alarmo configuration:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/760c5f38-eb89-4607-84a5-58b8e6871452)

![image](https://github.com/nielsfaber/alarmo/assets/16861605/3bc7b136-c964-47e2-9e51-2369080c796d)

I left all payload fields empty (default setting).

**Comment by AJax2012** [comment]
I'm actually having the same issue and I'm using the configuration posted above. @not-chees - were you able to get this working? I'm about to the point where I want to try reinstalling Alarmo..

**Comment by f18m** [comment]
Hi,
I'm having the same problem. I don't have any code defined and I'm sending on the default "alarmo/command" the message

```
{"command": "ARM_HOME", "code": "none"}
```

and the alarm is not armed. Actually I found NOTHING in the logs. It would be nice if Alarmo could print something like "ignoring command received on MQTT for reason XYZ" to help debugging :)

I'll keep investigating and I'll try to restart HA

**Comment by f18m** [comment]
> Hi, I'm having the same problem. I don't have any code defined and I'm sending on the default "alarmo/command" the message

I resolved the problem and now Alarmo is working fine with MQTT!!
Turns out it was a bug on my client application: it's written in Python and using aiomqtt/asyncio. However one task was blocking completely the event loop and this was (sneakily) breaking MQTT communications. 
I fixed that bug and now I see Alarmo getting armed/disarmed correctly!
