### ISSUE TITLE
DISARMED Output in alarmo/event MQTT

### ISSUE THREAD

**Issue by ervede** [nielsfaber/alarmo#862]
Currently, the `alarmo/event` does not include a "DISARMED" output. 
I would like to request the addition of a "DISARMED" output for better integration with external systems.

### Checklist
- [ X ] I checked for similar existing requests (both open and closed) before posting.
- [ X ] My request is generic, other users may benefit from it too.

### Proposal
The proposed change involves extending the `alarmo/event` payload to include a "DISARMED" status when the alarm system is disarmed. 

### Additional info
For example:

```json
{
  "event": "DISARMED",
  "timestamp": "2023-12-28T12:34:56",
  "additional_data": "[USER]"
}

**Comment by nielsfaber** [comment]
> The proposed change involves extending the alarmo/event payload to include a "DISARMED" status when the alarm system is disarmed.

The disarmed status update is already visible in the state topic.
The only reason I see for adding this to the event topic is to send out contextual info.
Your request seems to hint at this but you don't make it very clear that is what you're looking for.

>   "timestamp": "2023-12-28T12:34:56",
  "additional_data": "[USER]"

Sending such contextual information could be considered. 
However, for sake of consistency this would have to be added to the other events as well.
I think the field `additional_data` should be renamed to `user` in this case, with the name of the user as payload.

What are your thoughts about this? 
Note that all the data which is currently sent via the event topic is listed [here](https://github.com/nielsfaber/alarmo?tab=readme-ov-file#event-topic).

**Comment by ervede** [comment]
> > The proposed change involves extending the alarmo/event payload to include a "DISARMED" status when the alarm system is disarmed.
> 
> The disarmed status update is already visible in the state topic. The only reason I see for adding this to the event topic is to send out contextual info. Your request seems to hint at this but you don't make it very clear that is what you're looking for.

In response to your concerns about clarity, I want to emphasize that the primary motivation behind this proposal is to enhance the user experience for Node-Red users. The idea is that by including the "DISARMED" status directly in the event payload, Node-Red users could streamline their integration process, as they would only need to listen to the alarmo/event payload.

> 
> > "timestamp": "2023-12-28T12:34:56",
> > "additional_data": "[USER]"
> 
> Sending such contextual information could be considered. However, for sake of consistency this would have to be added to the other events as well. I think the field `additional_data` should be renamed to `user` in this case, with the name of the user as payload.
> 
> What are your thoughts about this? Note that all the data which is currently sent via the event topic is listed [here](https://github.com/nielsfaber/alarmo?tab=readme-ov-file#event-topic).

In the spirit of consistency, I'd like to propose an alternative naming convention that aligns with your suggestion. Instead of using user, we could consider using changed_by as the field name.
