### ISSUE TITLE
[Feature Request] Support for Duress Code

### ISSUE THREAD

**Issue by arielwulkan** [nielsfaber/alarmo#863]
A Duress Code would be a must feature for real safety functionality. Is there a way to implement it as it is, or are there any plans on adding this feature any time soon?

**Comment by PowerBat80** [comment]
This would be a nice feature to have. 
Perhaps an extra Attribute "DuressCodeInUse" is set when the Duresscode is used to arm/disarm, that can be used in Automations Event, perhaps in the Mode section (DuressCode is used to arm/disarm Area xx)?
This is a special code that not should be sent to the one that operate the alarm.
It is not nice if the hostile person can see the message in the victims phone..

Perhaps if we need this type of protection, we should have a more sofisticaded alarm connected to an professional alarm company?

BR
