### ISSUE TITLE
Group of sensor - access the group's state

### ISSUE THREAD

**Issue by Trevianos** [nielsfaber/alarmo#865]
### Accessing Group State
- I propose the ability to access the state of a group of sensors. If both sensors detect movement within a specified time period, the group state would be set as 'Detected'; otherwise, it would be 'Clear'. This feature would enable to utilize the group state in automations and display it in Lovelace cards. Essentially, I aim to combine two PIRs to minimize false triggers and use the group as a 'virtual' PIR. Is this feasible? Perhaps integrating Alarmo groups into standard HA groups could facilitate this functionality (if that is even possible). While I can create a grouped virtual PIR in HA and use it in Alarmo as a single PIR, a direct integration could benefit everyone.

In any case, thanks for your work, I really love Alarmo!

**Comment by PowerBat80** [comment]
Hi, is this not the feature "Group" in "Edit Settings"?
![Alarmo_DeviceEditSettings](https://github.com/nielsfaber/alarmo/assets/155341362/0a44ebeb-a8a2-4ad1-b3f9-04aaddc93bb8)
Regards

**Comment by Trevianos** [comment]
Hi Niels, you can create and manage the group in alarmo, as your screen
print shows, but how can I access the state of the GROUP in automations
outside Alarmo, or display the group state in Lovelace? I didn't find a way
yet. Lets say, I have 2 PIRs in a group_garage and I would basically want
to access the Alarmo group_garage state. For example, only if both PIRs are
ON, the group_garage state is ON, else OFF.

Cheers,
Lukas

čt 11. 1. 2024 v 23:44 odesílatel PowerBat80 ***@***.***>
napsal:
