### ISSUE TITLE
Alarmo card - display list of currently triggered sensors

### ISSUE THREAD

**Issue by Trevianos** [nielsfaber/alarmo#867]
### Alarmo card - display list of currently triggered sensors
- Visualizing the last 'n' (variable) triggered sensors (or groups of sensors) or their corresponding freetexts (see the other feature request) in the Alarmo card would be beneficial. For instance, in a house with a garden, if a silent alarm triggers at night beause the gate was opened, knowing the currently detected location and direction could assist in an appropriate response (e.g. person moving from gate to house, now is in garage etc., or when siren is switched on - leaving). Presently (if I am not mistaken), the Alarmo card displays only the first triggered sensor (or group of).

**Comment by Trevianos** [comment]
bump...

**Comment by erkr** [comment]
+1
