### ISSUE TITLE
Add support for device automations

### ISSUE THREAD

**Issue by cnmarch6** [nielsfaber/alarmo#87]
Good arvo, 

I use "automation" to play a siren media when `Alarmo is triggered `

I wanted to play a sound when Alarmo is at `pending` stage to remind me to disarm the alarm. However, the trigger is only have: `Alarmo disarmed` `Alarmo triggered` `arming` and `Alarmo armed away`

I tried edit in YAML but of course it returns: Trigger: `unknown trigger`

Since we already have `arming` as a trigger, is there a way to add one more `pending` to it please?
![Screen Shot 2021-01-05 at 12 54 39 pm](https://user-images.githubusercontent.com/46871524/103598073-d1774080-4f55-11eb-856a-99d9f2e00e6e.png)

![Screen Shot 2021-01-05 at 1 00 23 pm](https://user-images.githubusercontent.com/46871524/103598134-fb306780-4f55-11eb-85e9-434a6e62b048.png)

**Comment by nielsfaber** [comment]
Honestly I don't know how the device triggers work in HA.
The options you see seem to be auto-generated, I didn't create this list.
I'm working on a feature now to support multiple areas with their own independent alarms.
This is how the page now looks for me:
![image](https://user-images.githubusercontent.com/16861605/103617967-6adf2c00-4f2f-11eb-979b-91134a739e5d.png)

The documentation in HA is very poor, as a result I don't know how to make this panel useful.
I could investigate, but it would take some time before i can get to that.

I propose instead to use  the entity as trigger:
![image](https://user-images.githubusercontent.com/16861605/103617884-4b480380-4f2f-11eb-96de-0feae74612b3.png)

For a full overview of all states, see here: https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#states
Note that Alarmo does not implement the `disarming` state.

**Comment by cnmarch6** [comment]
It works using entity as trigger thank you. 

Multiple area looks great, amazing work thanks man.
