### ISSUE TITLE
FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead

### ISSUE THREAD

**Issue by luke7101** [nielsfaber/alarmo#870]
### Alarmo Version

v1.9.13

### HA Version

v2024.1.0

### Bug description

Got this message during startup since v2024.1.0

```FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead```

### Steps to reproduce

Update to v2024 HA version.

**Comment by golles** [comment]
Duplicate #864
PR #869

**Comment by prodoff** [comment]
Bonjour

J'ai recu aussi ce message

`Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:205
Integration: Centrale d’alarme (documentation, issues)
First occurred: 18:50:12 (2 occurrences)
Last logged: 18:50:12

FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues`

**Comment by codyc1515** [comment]
Will there be a new release for this?
