### ISSUE TITLE
Missing permanent activated sabotage alarm function

### ISSUE THREAD

**Issue by pvangorp** [nielsfaber/alarmo#872]
Missing permanent activated sabotage alarm function, so when a sabotage is triggered, the alarm should be triggered. Even when it's not activated. I created a separate area called Sabotage. But I can't make it permanent on!

**Comment by PowerBat80** [comment]
I think if you change the device type to "Environmental" you will get it "Always on"?
![Alarmo_DeviceType](https://github.com/nielsfaber/alarmo/assets/155341362/0ad41396-9f48-46d7-b946-41fc4ec4e6f6)
Regards
