### ISSUE TITLE
access with 30-second delay only on some sensors

### ISSUE THREAD

**Issue by javifly** [nielsfaber/alarmo#874]
this application is super good, very complete. I only see a lack that any professional alarm includes.

It is the option of a delay of 30 seconds in sounding since it is activated only in some sensors.

That is, this application has the option to put a delay of 30 seconds or 1 minute to give you time to open the door of the house and disable the alarm without sounding. But this delay is applied to all sensors, while it should really only apply to those that cover the area of the front door, those that are in windows, other rooms etc... should go off instantly without leaving that waiting time.

Do you understand me?

**Comment by PowerBat80** [comment]
Hi
I think this is handled by advanced setting on the device tht you want to aply this delay to. Normally the delay is not activated on the sensors, or am I wrong?
![Alarmo_advanced](https://github.com/nielsfaber/alarmo/assets/155341362/c8b1ab6a-7aea-44da-8fdb-e50b3b11e943)

**Comment by javifly** [comment]
all solved, it can be closed.
