### ISSUE TITLE
FORMAT_NUMBER deprecation in HA Core 2025.1

### ISSUE THREAD

**Issue by pvh0** [nielsfaber/alarmo#878]
### Alarmo Version

Current

### HA Version

2024.1

### Bug description

FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues

### Steps to reproduce

FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues

**Comment by PowerBat80** [comment]
All ready merged https://github.com/nielsfaber/alarmo/pull/869#issue-2064744751
[Merge pull request](https://github.com/nielsfaber/alarmo/commit/bd5d64941e23cfd54879c383ee684b3829afe318) https://github.com/nielsfaber/alarmo/pull/869 [from TheZoker/fix-deprecation](https://github.com/nielsfaber/alarmo/commit/bd5d64941e23cfd54879c383ee684b3829afe318)

**Comment by nielsfaber** [comment]
Fixed in v1.9.14 release.
