### ISSUE TITLE
Hide keypad until action selected

### ISSUE THREAD

**Issue by STDEin** [nielsfaber/alarmo#881]
The option to hide the keypad until an action is selected (arm, disarm etc), giving a minimized or abbreviated panel.

### Checklist
- [ ] I didn't see any other requests (open or closed) that fit this
- [ ] While a aesthetic option, it helps in fitting the card in certain dashboard layouts

### Proposal
An option to show the keypad after selecting an action that would require it, such that the card maintains it's smaller size regardless of state / keypad options until it's needed. Additionally, publishing state info when the keypad is shown to allow for conditional cards to reflow or hide elements to fit in the interface correctly.

### Additional info
Currently I'm using conditional cards to hide cards (weather) when Alarmo is armed, so that all cards fit on my wall panel without scrolling. By eliminating the static keypad I could deliver a more consistent experience and only adjust the layout when the keypad is actually requested.
A 'cancel' button would need to be added to the panel when the keypad is shown to revert back to the abbreviated view.
Eliminating the code requirement entirely isn't reasonable in my application, since the dashboard is displayed on an always-on wall panel.
I've attached an image showing how Alarmo and my wall panel dashboard currently looks, and how I propose it could look with the proposed changes..
![Alarmo-mods](https://github.com/nielsfaber/alarmo/assets/1834598/cdc83db0-c308-46de-8647-d3009c48f2f8)

**Comment by JoeHogan** [comment]
I agree with this ask! I would also add that the "Clear" button should be an "Enter" button, and "Clear" can be moved to the left of the 0 and renamed Cancel - the Disarm and Cancel buttons at the top can be hidden when keypad is visible. That said, i may just build my own UI component to meet my own needs.

**Comment by joohann** [comment]
I would love to have it too! Btw am I the only one that types in the code too fast and it's misses a digit what results in I can't disarm?
