### ISSUE TITLE
Alarmo fails on HA startup.

### ISSUE THREAD

**Issue by awshirley** [nielsfaber/alarmo#882]
### Alarmo Version

1.9.14

### HA Version

2024.1.5

### Bug description

Alarmo fails on on Home Assistant startup

### Steps to reproduce

Start or restart Home Assistant and review logs

### Relevant log output

```shell
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:04:34 PM (1 occurrences)
Last logged: 10:04:34 PM

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/__init__.py", line 56, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 691, in async_get_registry
    return cast(AlarmoStorage, await task)
                               ^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 686, in _load_reg
    await registry.async_load()
  File "/config/custom_components/alarmo/store.py", line 315, in async_load
    data = await self._store.async_load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 133, in async_load
    return await self._load_task
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 142, in _async_load
    return await self._async_load_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 243, in _async_load_data
    stored = await self._async_migrate_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 293, in _async_migrate_func
    for sensorGroup in data["sensor_groups"]
                       ~~~~^^^^^^^^^^^^^^^^^
KeyError: 'sensor_groups'
```

**Comment by nielsfaber** [comment]
Could it be that you did not make any change to the alarmo settings in over 3 years?
The error suggest that your settings file is missing a property that was added a long, long time ago.

**Comment by ZinTheDog** [comment]
I've been running into the same problem the last few days.  I just updated to 2024.1.6 and the issue persists.

**Comment by nielsfaber** [comment]
@ZinTheDog
Can you look up the `alarmo.storage` file in subfolder `.storage` (might be a hidden folder) in the HA configuration directory?
I would to see the version that is listed here, and if any section `sensor_groups` is present here. Could you share this information?

**Comment by ZinTheDog** [comment]
Version 6, Minor Version 2. "sensor_groups": [] is present at the end of the file.

**Comment by nielsfaber** [comment]
@ZinTheDog 
I'm surprised you are running into this error since it suggest that the `sensor_groups` is missing from that file. An ampty list should not give such error. If I update my local file to match yours, the issue does not show up.

Do you mind sharing your complete storage file?
Any information that you consider as private can be replaced by "x" or similar (its just about the file structure).

**Comment by ZinTheDog** [comment]
@nielsfaber 
My apologies, I think I may have jumped to conclusions based on timing of my issue and OP's and should probably take a step back.  The Alarmo integration is starting in my system, but the alarm_control_panel.alarmo entity is showing as unavailable and won't allow me to enable it.  Debug logging is turned on, but it's not reporting any errors that I have been able to find.

**Comment by nielsfaber** [comment]
@ZinTheDog 
This indeed seems unrelated to the bug reported here.
You might want to check the developer tools > states page and look for the alarm entity.
There is another unresolved issue causing HA to create a new entity (under a different name) for alarmo.

**Comment by ZinTheDog** [comment]
@nielsfaber, My sincere apologies again for the wild goose hunt.  There were no additional entities, just the original that was perpetually stuck in disabled/unavailable.  I ultimately ended up deleting the device & entity and recreating my Alamo configuration.  Still not sure what caused it, but it was easy enough to recreate new.  Thank you for your quick action!

**Comment by flubba** [comment]
Alarmo failed to start up with the same error message for me as well. The issue was that "sensor_groups" was missing in the configuration. I reverted back to version 1.9.13, made changes to the configuration, and then switched back to the main branch. That fixed the problem.

**Comment by bcutter** [comment]
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/alarmo/panel.py:33
Integration: Alarmo (documentation, issues)
First occurred: 23:44:23 (1 occurrences)
Last logged: 23:44:23

Error setting up entry Alarmanlage for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmo/__init__.py", line 84, in async_setup_entry
    await async_register_panel(hass)
  File "/config/custom_components/alarmo/panel.py", line 33, in async_register_panel
    await panel_custom.async_register_panel(
TypeError: async_register_panel() got an unexpected keyword argument 'config_panel_domain'
```

After restarting HA after roughly a month, likely Alarmo integration has been updated meanwhile from HACS. How to fix this?

**Comment by nielsfaber** [comment]
@bcutter your issue is not related to the topic discussed here. I think your issue is caused by an incompatible HA version. The error is related to a property that was added to HA about half a year ago.

**Comment by bcutter** [comment]
> @bcutter your issue is not related to the topic discussed here. I think your issue is caused by an incompatible HA version. The error is related to a property that was added to HA about half a year ago.

I created a seperate issue, sorry for mixing things here.

**Comment by robwiklu** [comment]
I renamed alarmo.storage and reverted to Alarmo verson 1.9.13. Now Alarmo works for me again. I haven't tested upgraded to .14 again after that - I just need it to work at the moment.

**Comment by MihaiP17** [comment]
For me it was sufficient to add in alarmo.storage (file is found in \config\.storage) a new entry for sensor groups. The json file should look similar to this.

![image](https://github.com/nielsfaber/alarmo/assets/25912255/38515f4f-fa76-4d20-b55e-49d3e0c07822)

After a restart, everything started to work again as normal. This on last version (1.9.14) of alarmo.
