### ISSUE TITLE
Door sensor causing alarmo to report disabled state every time there is door interaction

### ISSUE THREAD

**Issue by RaptorPR443** [nielsfaber/alarmo#887]
### Alarmo Version

V1.9.10

### HA Version

2024.1.5

### Bug description

i am using Nodered for automations, z2m with aqara door sensors. Everytime any door sensor open/close causes alarmo to report disabled state every time resulting in triggering the disabled automation in every door open/close.

### Steps to reproduce

updating to 1.9.11 to 1.9.14 gives this bug. in 1.9.10 everything works perfect and alarmo states change only when interacting with the alarm.

**Comment by nielsfaber** [comment]
This sounds like an issue with your automation.
Perhaps it is triggered every time one of the properties (instead of the state) of the alarm entity is updated?

**Comment by Beer17HWAM** [comment]
![Screenshot from 2024-01-29 15-38-12](https://github.com/nielsfaber/alarmo/assets/97590748/74da539e-c75e-4f88-be94-74dea4d26980)
Try this extra condition in your state node.
