### ISSUE TITLE
Add illumination and seismic Intensity entities to the list of sensors.

### ISSUE THREAD

**Issue by Aacgh** [nielsfaber/alarmo#888]
Some sensors like Fibaro Motion or Aeotec Multi-sensors have the entities for illumination and seismic intensity.
-->

### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
I think it would be beneficial to have these type entities available as sensors in Alarmo.

### Additional info
Maybe set up the same as a door or motion sensor.

**Comment by nielsfaber** [comment]
Any binary_sensor can be added.
But I don’t see specific types defined for seismic / illumination sensors: https://www.home-assistant.io/integrations/binary_sensor/
This list is used for the support within alarmo .

**Comment by Aacgh** [comment]
I should have known that about binary, it is plain as day. I apologize for jumping the gun. I'll think before I leap next time.
Thank you all for the good work and your patience with me.
