### ISSUE TITLE
Trigger time <1min

### ISSUE THREAD

**Issue by raderack3948** [nielsfaber/alarmo#894]
Hi,
is it possible to set a trigger time below 1 min? For example 10 seconds?
I'd like to use the Home Function of Alarmo for a Bell on a specific movement - but the 1 minutes trigger time prevents it from ringing under 1 minute.

Thanks!

**Comment by rkaczorek** [comment]
Up

**Comment by nielsfaber** [comment]
This is already possible: 
![image](https://github.com/nielsfaber/alarmo/assets/16861605/74a05bcc-6cfb-4f35-8a2e-3561f58228d7)

Click on '10 mins' and the unit will change into seconds:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/cbf36645-d02b-4f55-afee-943e262a242d)

Now you can set the time to a few seconds:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/18d85261-b085-4adb-9b07-be3880eff023)

**Comment by margit73** [comment]
Hi @nielsfaber , 
would it be possible to change the Trigger time granularity to 1, 2, 3 seconds ?
