### ISSUE TITLE
Intelligent motion-detection outdoor

### ISSUE THREAD

**Issue by tackin** [nielsfaber/alarmo#898]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]
I have multiple outdoormotion-sensors. I would like to trigger if persons are running around the house.

### Additional info
[some example of how the new functionality should look like]
We have had multiple events of burglary in the neighbourhood. A recognition pattern was always that some people walked around the house not touching anything. Sometimes for more than an hour they walk around. If they are sure nobody and nothing reacts, they started to break in.

If a cat or squirrel runs past one of the sensors I don't want to get an alarm but if different sensors are triggered and/or one sensor multiple times in a timeframe, it might be because one or more persons are walking around the house.

**Comment by nielsfaber** [comment]
In alarmo you can make a sensor group for this. It works exactly as you describe, see the documentation for more info.

**Comment by tackin** [comment]
Nice! Now I finally understood how to get sensors into this grouping-mode.
But one thing could be added I guess. At the moment all group-sensors must be triggert to get alarm.
"Alarm when minmal x from y (=total groupmembers) are triggert" would be great. If the scumbag misses to pass only one out of ten sensors when walking around, he will never trigger the alarm.

... or did I get that wrong as well?   ;-)

**Comment by nielsfaber** [comment]
In a sensor group 2 sensors must be triggered within the set time frame, not all.

**Comment by tackin** [comment]
2 sensors is a problem in my case. I needed to bring it up to at least 3.
I simply just modified "event_count" default=3 in custom_components\alarmo\store.py for my needs. But would you mind to just make the integer editable as well in the frontend?
