### ISSUE TITLE
2024.3.0b0 ERROR on startup

### ISSUE THREAD

**Issue by enkama** [nielsfaber/alarmo#899]
### Alarmo Version

 v1.9.14

### HA Version

2024.3.0b0

### Bug description

Error on startup when using newest Home-Assistant Beta version.

### Steps to reproduce

Use newest Home-Assistant Beta

### Relevant log output

```shell
[homeassistant.util.logging] Exception in async_alarm_state_changed when dispatching 'alarmo_state_updated': ('1691315103', None, 'disarmed')
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 61, in async_alarm_state_changed
    if not self._config[ATTR_MQTT][const.ATTR_ENABLED] or not new_state:
           ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bharvey88** [comment]
+1 this is happening with my setup on 2024.3.0b0 as well. Suggested to open an issue per devs and adding onto this one instead.

**Comment by bharvey88** [comment]
per bdraco: That integration subscribes to the events before it sets self._config and its faster now so it get the callback soon enough that the data isn't there yet

**Comment by nielsfaber** [comment]
Thanks for letting me know. I looked into this and made a fix for it: https://github.com/nielsfaber/alarmo/commit/7a7c06cd4b6b906e42baa0455854c037d3ef9baa
I will make a release somewhere in the upcoming days (before the next HA version is out).

**Comment by nielsfaber** [comment]
This should be fixed in the latest version.
