### ISSUE TITLE
Kind of sensors permanently armed

### ISSUE THREAD

**Issue by Sag06** [nielsfaber/alarmo#9]
Beside armed away, night, etc. IMHO there should be a permanent armed state for all time alarm sensors like smoke, gas, water leak, etc that should trigger always, no matter if away, night, home, etc are armed or not.

**Comment by nielsfaber** [comment]
This is in place in v1.1.0.

The response is still open for discussion.
Currently they will/should trigger the alarm immediately, so you will have the siren switched on immediately.
I'm not sure if this is desirable (since I expect the triggers are mostly false).

**Comment by stefanolson** [comment]
If it's a smoke sensor you always want siren on if the sensor finds anything, I would have thought.  So seems the correct behaviour.

**Comment by Sag06** [comment]
> If it's a smoke sensor you always want siren on if the sensor finds anything, I would have thought. So seems the correct behaviour.

Agreed

**Comment by nielsfaber** [comment]
Can this issue be closed? 
Or is there a need for additional functionality?

**Comment by stefanolson** [comment]
Yes, I think there is a need for a permanently armed sensor that doesn't trigger the alarm,  But just notifies. For example, a power overload/overheating on a Shelley switch.

**Comment by nielsfaber** [comment]
Such behavior is out of scope for Alarmo.
You can use a standard HA automation for this.

**Comment by nielsfaber** [comment]
I'm closing this issue as the original request seems to be resolved.
