### ISSUE TITLE
Request - Trigger duration before triggering alarm - can eliminate quite a lot of false positives

### ISSUE THREAD

**Issue by lcbester** [nielsfaber/alarmo#908]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
With many motion sensors eg PIR, beams, etc causing false alarms (not Alarmo's fault), it would be good to be able to specify that a certain sensor has to be in active/triggered state for a certain duration before triggering the alarm.  As an example, a gust of wind can cause a PIR to be active for a part of a second, and then go inactive again.  However, if there was an actual criminal around, the active state would last longer than for instance 500 ms.  For the same token, a falling leave can break a laser beam for a few split seconds, but a person climbing over a wall would disrupt that same beam for a longer period of time.

### Additional info
An option to select whether the active state leads to an immediate trigger, or where you can specify [editabe field] (in milliseconds) how long the sensor has to be in an active state before it triggers the alarm.

**Comment by shred86** [comment]
This is something I've been dealing with as well as one of our rooms will sometimes have the PIR sensor trigger based on some light coming through the windows. Even with our blinds closed, there's just a couple areas where light will come through at certain sun angles and cause the alarm to trigger.

I'm not sure if all PIR sensors work the same but mine are hardwired PIR sensors that I have integrated with Konnected. The trigger events age out very quickly (~1 second) if there's no motion, so I think something like the OP mentioned would resolve this.

The other solution is probably creating a helper binary sensor in Home Assistant and setting up an automation or script that only triggers that helper binary sensor when the PIR sensor has been active for a specified length of time, but it would be nice to have this as a built-in feature of Alarmo (which is awesome btw).

**Comment by nielsfaber** [comment]
In my opinion, the sensor should provide internal filtering of glitches to eliminate false positives.
I don't think this should be part of alarmo.
In my own experience, PIR sensors remain triggered for some time (30sec or 1 minute) after motion has been observed. A filter in alarmo is not going to help distinguish here.
A door sensor should not have glitches, we can only expect contact bounce on opening/closing but no false positives.
> For the same token, a falling leave can break a laser beam for a few split seconds, but a person climbing over a wall would disrupt that same beam for a longer period of time.

Are you protecting your house with outdoor laser beams? This sounds more like a scene from Mission Impossible. Please share a link to such product, i'm interested.

For special cases, I think the solution provided by @shred86 should fits your need.

**Comment by lcbester** [comment]
Hi Niels.  The sensors are homebuilt. Photos below....

Just a D1 mini running Tasmota connected to the beams.  Feeding the info to Alarmo.

South Africa unfortunately have very violent crime stats.  A burglar would have no issues murdering the home owner too.

So, I protect the perimeter with the beams, the area between the perimeter and house with smart human sensing cameras and internally (in the house) with PIRs and door & window sensors.  A total of 46 sensors, which your system is handling flawlessly. Well done.

The only false alarms at present were the beams, but I found a workaround on Tasmota to delay x seconds before sending a signal to Alarmo.  If the sensor clear before the set delay, I send command to cancel sending the trigger.   Due to the computing power of the D1 the results seem to vary a bit though. A 1 second delay actually translate to between 1.5 and 2.5 seconds.

At least there is now a massive reduction in false alarms.

Have a fantastic day.

![IMG_0787](https://github.com/nielsfaber/alarmo/assets/135130525/5777ad81-25f4-4b59-b669-25c972d563e4)
![IMG_0786](https://github.com/nielsfaber/alarmo/assets/135130525/d6378e19-69bd-408b-99d1-5d57b97fc6c2)

**Comment by shred86** [comment]
> In my opinion, the sensor should provide internal filtering of glitches to eliminate false positives. I don't think this should be part of alarmo. In my own experience, PIR sensors remain triggered for some time (30sec or 1 minute) after motion has been observed. A filter in alarmo is not going to help distinguish here. A door sensor should not have glitches, we can only expect contact bounce on opening/closing but no false positives.
> 
> > For the same token, a falling leave can break a laser beam for a few split seconds, but a person climbing over a wall would disrupt that same beam for a longer period of time.
> 
> Are you protecting your house with outdoor laser beams? This sounds more like a scene from Mission Impossible. Please share a link to such product, i'm interested.
> 
> For special cases, I think the solution provided by @shred86 should fits your need.

Personally, I think it would be great to have the ability to set a motion duration before triggering the alarm in Alarmo under advanced settings of motion sensors. Alarmo makes it very easy to setup a robust alarm system using the front end and not having to mess with config files, which I think having this would just continue to add to that. Battery powered motion sensors usually refresh after 30-60s, but hardwired ones will refresh after about a second making this feature very useful for eliminating false positives.

Either way, appreciate all the work on Alarmo. It far exceeds any alarm system I've ever had in the past.

**Comment by lcbester** [comment]
I agree Shred86.

We can set similar behaviour on the device (very complicated and not 100% reliable in results).  Or we can set it on Home Assistant as per your previous post (Still a bit complicated for a novice user, and with the risk of messing something else up in HA. Also more reliable in results).

Having the option in Alarmo would be ideal from an ease of use and functionality perspective.  However, my level of skill does not even give me an inkling of how complicated this would be for Niels to add.
