### ISSUE TITLE
Integration with existing alarm

### ISSUE THREAD

**Issue by andzie82** [nielsfaber/alarmo#91]
Would be nice to have the option to forward arm states to a action for example if alarmo arms the action is to arm the main house alarm that’s connected to HA using this https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/envisalink.markdown. 

So to shorten it off it would me nice to be able to trigger the Mail alarm also. 
#feature request

**Comment by thanksmister** [comment]
Can't you do this with an automation?

**Comment by nielsfaber** [comment]
This seems quite feasible.
Alarmo already will get the option for creating separate entities for each area, there will be a ‘master’ entity on top to link them.

**Comment by andzie82** [comment]
Yes it would be possible through a automation but since Alarmo is so user friendly it would be nice to have actions on arm/disarm as well in the Alarmo GUI.

**Comment by thanksmister** [comment]
You will be knee deep in features :D

**Comment by nielsfaber** [comment]
Handled on a first come, first serve basis 😉
