### ISSUE TITLE
Audible beep or sound during change state (disarm,arm)

### ISSUE THREAD

**Issue by hellyhans** [nielsfaber/alarmo#910]
Hey people.

I've been struggling to see if I can find a way to make Alarmo trigger and audio sound or something on a tablet so to hear an audible beep for a delay to disarm. Just like a regular alarm keypad.

I'm running a Konnected alarm setup and I can't for the life of me figure it out. 
I don't want to send a notif. to a phone or device or audio clip to a smart speaker. I think this is a feature that should be directly implemented in alarmo and not some misc. trigger that calls the media player etc in HA. 
i just want alarmo to sound a beep during the arming/disarming delay on said device.

Unless you guys have a suggestion it would be awesome. I've checked a ton of docs and my next step would be to setup my tablet in Kiosk mode, because maybe that would give me an option to play maybe an mp3 locally on a trigger.

**Comment by mogultekin** [comment]
Hello,

I have made three scripts after watching the Smart Home Australia's https://www.youtube.com/watch?v=ga3Hojc33Pk&t=425 video. One for flashing LED strips in the living room , playing siren as loud as possible from living room Sonos speaker, one for stoping the siren, turning off the LED stripe and last one for arming and disarming sound (car alarm set sound like beep beep).

![image](https://github.com/nielsfaber/alarmo/assets/81960545/d8e8b994-c06a-4921-8c16-d27cc90c343e)

 In that video repeat until is advised but in my environment is_state did not work. So I made 3 seconds delay and repeat siren again.

The disarm action is not working. I visited this this repo for known issues and saw your issue.

I have recently bought SONOS Bookshelf speaker integrated with HA which makes audible notifications fun. Like:
-Refrigerator door left open
-Hourly time announcements 
-Cell phone batteries low
-Main door opened
-Prayer times
..etc..

**Comment by f18m** [comment]
Not sure if it helps but I'm using Alexa media_player component (https://github.com/alandtse/alexa_media_player) to turn my Alexas into speakers that I can drive from HomeAssistant.
This makes it easy to get a 'voice' notification when the alarm is activated. Here's the YAML snippet I put in my Alarmo -> Actions -> Notifications panel:

```
service: notify.alexa_media
data:
  message: Attenzione. L'allarme è impostato in modalità {{arm_mode}}.
  title: Titolo
  data:
    type: tts
  target: media_player.echo_dot_del_salotto, media_player.echo_pop_cameretta_arancione
```
