### ISSUE TITLE
Alarm is triggered when set to disarmed 

### ISSUE THREAD

**Issue by sterling90x** [nielsfaber/alarmo#911]
### Alarmo Version

1.9.15

### HA Version

2024.3.3

### Bug description

When alarm keypad is set to disarm and the sensor changes to unsafe/triggered the alarm will go off. Using a ring keypad 

### Steps to reproduce

Setting the alarm to armed, triggering the alarm, and disarming it. 

Triggering the contact sensor (opening a door) 

the alarm will go off in disarm

**Comment by skaggerik** [comment]
Did you check "device type", and "always on"? Unsafe/triggered sounds like an environmental sensor.

**Comment by sterling90x** [comment]
This is a ring contact sensor brought in via zwave. Using zwave js. 

What information from this sensor do you want me to provide?

I'm not sure where to locate "always on"

Is this something within the device settings or within Alarmo?

**Comment by skaggerik** [comment]
Go to: Alarmo - Sensors
Select the sensor
Field: device type. Should be set to door. But sounds like it's set to environmental.

**Comment by sterling90x** [comment]
Ahh! Look at that! Thank you. I've never edit a sensor before, did not know this option. Was available. 

No bug. 

Thank you.

**Comment by skaggerik** [comment]
It's not a bug, it's a feature. 😉

**Comment by sterling90x** [comment]
I do have a question about using the ring contact sensor button within alarm or an automation to activate the alarm bypass until the door is shut again. 

Where is the right place to ask this question. - I know I asked it here lol
