### ISSUE TITLE
Deprecated call

### ISSUE THREAD

**Issue by EPinci** [nielsfaber/alarmo#918]
### Alarmo Version

v1.9.15

### HA Version

2024.4.0

### Bug description

Reporting bug as indicated in HA log:

`2024-04-04 00:11:53.407 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alarmo' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/alarmo/mqtt.py, line 49: self.hass.async_add_job(self._async_subscribe_topics()), please create a bug report at https://github.com/nielsfaber/alarmo/issues`

### Steps to reproduce

Appears at HA startup time

**Comment by nielsfaber** [comment]
This should be fixed in the v1.10.0 release of alarmo. Please update and check if the error disappears.

**Comment by EPinci** [comment]
Indeed, all good! Thank you!
