### ISSUE TITLE
Moisture sensor not triggering alarm

### ISSUE THREAD

**Issue by LarsStegman** [nielsfaber/alarmo#919]
### Alarmo Version

v1.9.15

### HA Version

2024.3.3

### Bug description

I have some IKEA Badring sensors connected through Zigbee2 MQTT to home assistant. If I manually trigger the alarm by shorting the contacts the sensor shows as "wet" in the user interface, but alarmo does not trigger the alarm. 

### Steps to reproduce

Short contacts of the moisture sensor
See the status of sensor in user interface change
Alarmo does not sound the alarm

**Comment by LarsStegman** [comment]
I think it is because of this line: https://github.com/nielsfaber/alarmo/blob/42f49c82adef8c47bc399827a1fb721360a6def3/custom_components/alarmo/sensors.py#L93

Would a moisture sensor not have STATE_ON, instead of open?

**Comment by skaggerik** [comment]
Moisture detectors work for me. Did you check that the sensor is set to "environmental" and "always on"?

**Comment by LarsStegman** [comment]
It does work now. I suspect it didn't work because the sensor states went from unknown to wet. I rebooted home assistant in the mean time, which caused the initial sensor state to be dry instead of unknown.
