### ISSUE TITLE
Alarm Control Panel entity does not use state icons

### ISSUE THREAD

**Issue by codemunkie15** [nielsfaber/alarmo#922]
### Alarmo Version

v1.9.15

### HA Version

2024.4.1

### Bug description

The Alarmo alarm_control_panel entity does not change icons depending on the alarm state (armed/disarmed). I have a Ring Alarm that uses Ring MQTT integration and that alarm_control_panel entity shows different icons depending on the alarm state which makes it perfect for using in a mushroom chips card.

Would it be possible to add this please?

**Alarmo example:**
![image](https://github.com/nielsfaber/alarmo/assets/13065317/93cbb024-8386-4f64-b979-92a94b1bd44a)

**Ring MQTT example:**
![image](https://github.com/nielsfaber/alarmo/assets/13065317/2a8ec282-1ee6-46ae-86b5-46e2f4190736)

### Steps to reproduce

Change state of alarm and check alarm_control_panel entity icon does not change.

**Comment by nielsfaber** [comment]
This should be fixed in the v1.10.0 release of alarmo. Please update and check if its ok for you now.

**Comment by codemunkie15** [comment]
Looks prefect now. Thanks for the speedy resolution!
