### ISSUE TITLE
Entry delay in seconds

### ISSUE THREAD

**Issue by gvillo** [nielsfaber/alarmo#925]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Entry delay is measured in minutes and I have no way to set 15 seconds (to match it with exit delay at all), I can only set 0.5 min, and it's a lot of time for me. I would be ideal to have the same unit in both delays (we could add a selector between minutes and seconds).

**Comment by brokenlegacynz** [comment]
You can, it took me a moment to work out that you just need to click on the 0.5 min and the time will change to seconds.

**Comment by gvillo** [comment]
nice, it works perfectly, it might be good to add some sort of tooltip on the "Entry Delay" label explaining that, so you can know it, I didn't see that behavior coming at all 😅

**Comment by gvillo** [comment]
@brokenlegacynz thank you so much, closing this out.
