### ISSUE TITLE
Add a service to force arm the alarm.

### ISSUE THREAD

**Issue by zd3sf** [nielsfaber/alarmo#926]
Add a service that can be called from HA to make alarmo force arm... similar to actionable notification that can force arm. The benefit is that we can make HA force arm after a timeout period. 

### Checklist
- [ ] I checked for similar existing requests (both open and closed) before posting.
- [ ] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]

### Additional info
[some example of how the new functionality should look like]

**Comment by nielsfaber** [comment]
This already exists, you can use the `alarmo.arm` service and include `force: true` in the data.
