### ISSUE TITLE
Notification TTS Speak error

### ISSUE THREAD

**Issue by Nuroduas** [nielsfaber/alarmo#927]
### Alarmo Version

v1.10.0

### HA Version

2024.4.3

### Bug description

Using the UI for Alarmo in HA I am trying to create a Notification to announce when the alarm is armed/disarmed.  When selecting tts.speak then selecting the entity I get the following YAML

data:
  message: The alarm is set to {{arm_mode}}
  entity_id: media_player.office_home
service: tts.speak

When clicking Try It or Save I get an error "required key not provided @ data['media_player_entity_id']"

### Steps to reproduce

I was able to find a syntax that is working using the developer tools.  It looks like the UI needs an option with TTS Speak to specify the media_player_entity_id after selecting the tss.google_en_com entity

data:
  message: The alarm is set to {{arm_mode}}
  entity_id: tts.google_en_com
  media_player_entity_id: media_player.office_home
service: tts.speak

**Comment by shettich** [comment]
Same issue here.  Also, media_player_entity_id is a list, so ideally you should accept several devices

**Comment by TheRealFalseReality** [comment]
Same error here, want to use tts.speak service but will not work due to the same bug mentioned

**Comment by nielsfaber** [comment]
I added a field for setting the media_player entity when tts.speak service is selected.
I will update you when the new version is released.

**Comment by nielsfaber** [comment]
@Nuroduas The extra field for setting media_player_entity is now included in release v1.10.2, please update to the latest version and test if it works OK for you now.
You can close the issue if so, otherwise please let me know.
