### ISSUE TITLE
Support for cameras 

### ISSUE THREAD

**Issue by marcokreeft87** [nielsfaber/alarmo#928]
I would love for Alarmo to have support for cameras so the push notification can include a snapshot of the room where the alert came from.

**Comment by skaggerik** [comment]
I have a setup where Alarmo sends a text message to my monitoring service when triggered. Also, when triggered, a script starts, taking two snapshots with two seconds in between them, and e-mails these to the monitoring service email-alarm receiver. Which allows for photo verification. I have another script starting when an entry delay is started, and when triggered, these pictures are included in the email.

**Comment by marcokreeft87** [comment]
Not ideal but that would work I guess

**Comment by maatx** [comment]
I use telegram to receive images from the cameras. Just edit the relevant action in YAML and insert the snapshots relating to the trigger.
![Screenshot 2024-04-25 alle 09 07 39](https://github.com/nielsfaber/alarmo/assets/4578794/16e72076-fdf8-4a9a-b911-280fc116acd1)

**Comment by lucasdellasantina** [comment]
could include a gif in the notification
