### ISSUE TITLE
Smartlock - ready to arm

### ISSUE THREAD

**Issue by pietro4711** [nielsfaber/alarmo#929]
I have a smart door lock.
This is configured as a sensor with the "Arm after closing" option.
In other words, as soon as I arm the alarm system, the door lock closes and if this is successful, the system is activated.
However, the "ready to arm" status depends on whether all sensors are closed  - but this is not necessarily the case with the smart lock.
I would therefore like the "ready to arm" status to be OK, even if the door has not yet been locked at this point.
I could activate "Bypass automatically" for the sensor, but then Alarmo switches to armed, even if the door lock was not closed successfully after "arming".

**Comment by nielsfaber** [comment]
Based on your configuration, the alarm can only be armed succesfully if your smart lock is closed.
If you don't close it during the exit delay, the arming would fail, hence 'ready to arm' status will indicate false while the lock is unlocked.
The alarm will not make assumption that you will close it on time, this information is unknown.
So I don't see a way to fulfill your request.

**Comment by pietro4711** [comment]
Thanks for your feedback!
I'll try to make my problem clearer again:
Normally I would set "use exit delay" for the door lock.
This allows me to arm the alarm system and the "arming" status automatically triggers the closing command to the door lock.
If the door lock still does not report locked after the "exit delay", the arming fails.
This is actually the perfect behavior I would like to see.
The only problem is that "ready to arm" is not displayed before arming.
Or in other words, those sensors for which "use exit delay" is set should not be taken into account in the "ready to arm" status.

**Comment by nielsfaber** [comment]
>  those sensors for which "use exit delay" is set should not be taken into account in the "ready to arm" status.

I disagree on this.
As I said before, as long as such sensor is open, the arming will fail. Therefore the system is not ready to arm. The system becomes ready to arm only when you closed the lock.

**Comment by pietro4711** [comment]
Ok understood, this means that users with a motorlock that is integrated in Homeassistant should always trigger an action first to lock the door, then wait until the motorlock reports the successful locking (takes about 10 seconds) and then switch on the alarm separately.
Too bad, I was hoping that this could be done in one step.
