### ISSUE TITLE
MQTT (dis)arm code never processed -- it is pulled from MQTT but never used!

### ISSUE THREAD

**Issue by derekatkins** [nielsfaber/alarmo#93]
Hi,
Trying to use MQTT Alarm Panel with Alarmo and it's not working.
Unless I am missing something, looking at the python, you never actually use the "code" sent in the MQTT.
Looking at alarm_control_panel.py:async_message_received():
```
...
                if "code" in payload:
                    code = payload["code"]
...
            payload_config = self._config[ATTR_MQTT][ATTR_COMMAND_PAYLOAD]
            skip_code = not self._config[ATTR_MQTT][ATTR_REQUIRE_CODE]
...
            if command == command_payloads[COMMAND_DISARM]:
                await self.async_alarm_disarm(code, skip_code)
```
In other words, the "code" is pulled out of the MQTT payload but it is never actually used or processed!

**Comment by derekatkins** [comment]
Okay, I misread the code -- it IS passing it in.. But it's still not working according to one user..

**Comment by ggoodell2** [comment]
sending passcode does nothing. but not sending passcode works fine...

**Comment by derekatkins** [comment]
I think the issue is that the panel app sends code as an int and not a str.  If that works, then maybe the alarmo mqtt docs might need a small clarification?  (IMHO a str is the right thing)

**Comment by nielsfaber** [comment]
Hello,

The reported issue here is a bit fuzzy to me.
Please define your problem in a clear way (expectation vs reality).
Instead of trying to interpretative the code, please tell me what you are trying and how things are configured.
You can read about the format of the payload [here](https://github.com/nielsfaber/alarmo#mqtt).
Note that there is a "require code" setting for MQTT, having it disabled could lead to the behaviour you are seeing.
IMO we can keep the discussion between me and end-user, no offense @derekatkins.

**Comment by derekatkins** [comment]
None taken.  We're discussing this on @thanksmister 's discord right now.  I'll let @ggoodell2 continue the discussion, but honestly we aren't sure if the bug is in the app or configuration.

I'll step aside now.

**Comment by ggoodell2** [comment]
turning off any requirement for passcode on alarmo allows me to disarm the alarm from @derekatkins app. what we are trying to do is to get it to where his app sends a passcode to alarmo and alarmo verifies it as valid and disarms. but i get an unexpected payload error.

**Comment by ggoodell2** [comment]
we enter {"command": "DISARM", "code": "****"} into mqtt with a topic of home/alarm/set and mqtt returns 2021-01-13 06:54:24 WARNING (MainThread) [homeassistant.components.manual_mqtt.alarm_control_panel] Received unexpected payload: {"command": "DISARM", "code": "****"}

*=private pin code

**Comment by ggoodell2** [comment]
just noticed this 

2021-01-13 06:54:24 WARNING (MainThread) [homeassistant.components.manual_mqtt.alarm_control_panel] Received unexpected payload: {"command": "DISARM", "code": "****"}
2021-01-13 06:56:33 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Wrong code provided.
2021-01-13 06:57:11 WARNING (MainThread) [homeassistant.components.manual_mqtt.alarm_control_panel] Received unexpected payload: {"command":"DISARM","code":"****"}
2021-01-13 06:57:53 WARNING (MainThread) [homeassistant.components.manual_mqtt.alarm_control_panel] Received unexpected payload: {"command":"DISARM","code":"****"}

**Comment by ggoodell2** [comment]
@nielsfaber can this be reopened?

**Comment by nielsfaber** [comment]
It looks like 3 out of your 4 attempts have the wrong payload format, the 4th has wrong code.
The warnings tell you exactly that.

you could try to publish a test command from command line (in a linux enviroment) like this:
```
mosquitto_pub -t 'alarmo/command' -m '{"command": "disarm", "code": "1234"}'
```

For me the result in the logs is:
```
2021-01-13 16:01:01 DEBUG (MainThread) [custom_components.alarmo.alarm_control_panel] alarm_disarm
2021-01-13 16:01:01 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state disarmed from state disarmed.
```
(note that i have debug logging enabled and the alarm was already disarmed)

Please check your config, these fields should be set up correctly:
![image](https://user-images.githubusercontent.com/16861605/104469662-0a985c00-55b9-11eb-9e3a-c5c9fd8a5904.png)

**Comment by ggoodell2** [comment]
yes they are the same

**Comment by ggoodell2** [comment]
using the alarm widget on hadashboard/appdaemon everything works as intended...

**Comment by derekatkins** [comment]
For the record, the "wrong payload format" messages appear to be coming from `manual_mqtt` and not `alarmo`.
The only alarmo error I see in the logs is "Wrong code provided".

**Comment by nielsfaber** [comment]
Seems like a false report and a waste of time for all of us..
Please be careful next time @ggoodell2 , hope you can continue now.

**Comment by thanksmister** [comment]
It is not case sensitive right?  {"command": "disarm", "code": "1234"}'  should be {"command": "DISARM", "code": "1234"}', payloads are uppercase.

**Comment by nielsfaber** [comment]
@thanksmister
I think the issue is solved in the meantime as the errors were coming from `manual_mqtt`.
The only error from Alarmo is "Wrong code provided." which seems pretty clear to me.
Seems like @ggoodell2 has mixed up things in his config, that's out of our hands..
