### ISSUE TITLE
Include area in notifications

### ISSUE THREAD

**Issue by skaggerik** [nielsfaber/alarmo#930]
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
Device area in notifications would be useful. 

### Additional info
Example notification: Alarmo is triggered. Window in bedroom is open.

**Comment by nielsfaber** [comment]
Not everyone (including myself) uses areas in HA so it would be difficult to make a generic implementation for this.
 Wouldn't it be better to rename the entity to 'bedroom window sensor' such that you can identify it by its name?

**Comment by jmerifjKriwe** [comment]
+1

**Comment by lu-mueller** [comment]
+1
