### ISSUE TITLE
'alarmo' calls `async_track_state_change` instead of `async_track_state_change_event` 

### ISSUE THREAD

**Issue by tomlut** [nielsfaber/alarmo#931]
### Alarmo Version

v1.10.0

### HA Version

2024.5.b0

### Bug description

Beta testing 2024.5.b0 produces this error:

Detected that custom integration 'alarmo' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/alarmo/sensors.py, line 175: self._state_listener = async_track_state_change(, please report it to the author of the 'alarmo' custom integration

### Steps to reproduce

Install HA core 2024.5.b0

**Comment by gvillo** [comment]
It's happening on latest release too (2024.5.1)

**Comment by gvillo** [comment]
Actually I think this is causing an issue that alarm cannot be armed, the workaround that I found is to restart HA and it works again. This is the only thing that I see on logs.

**Comment by zollak** [comment]
This might help to fix it:
https://developers.home-assistant.io/blog/2024/04/13/deprecate_async_track_state_change/

**Comment by Omnipius** [comment]
This may be causing instability due to using the incorrect async call. Thread safety errors can lead to crashes in 2024.5.0 and higher:
https://community.home-assistant.io/t/2024-5-tracking-down-instability-issues-caused-by-integrations/724441

I know for my part, all attempts to update to 2024.5.2 fail and result in a rollback.

**Comment by nielsfaber** [comment]
@tomlut Thanks for reporting this, I will take care of this change in the next update.

@Omnipius Could you please explain what incorrect call, safety errors and ccrashes you are referring to?
As far as I am aware, the **warning** reported here is about a deprecated function which will no longer work **in a year from now**.
If you experience issues with Alarmo when updating HA to 2024.5, I don't think this is related to the deprecated function call. Please create a bug report if you think something is wrong in Alarmo.

**Comment by tomlut** [comment]
For me there is no instability. Just the error logged at start up.

**Comment by nielsfaber** [comment]
This is issue is resolved with the new v1.10.1 release.
