### ISSUE TITLE
Actions doesn't work when triggered by "master"

### ISSUE THREAD

**Issue by burbon-pl** [nielsfaber/alarmo#938]
### Alarmo Version

v1.10.1

### HA Version

2024.5.2

### Bug description

Action works when attached to alarm trigger in any particular area, but stops working when attached to master "area" alarm trigger.

### Steps to reproduce

-Add two areas
-add PIR sensor to one of them
-set action to do whatever action you want (triggering wifi relay in my case) when alarm triggered by "master" area.

**Comment by nielsfaber** [comment]
I don't agree with this bug, for me (and many others) it works fine.

Here's my configuration:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/b9a46edf-e517-4091-8101-a2d263383654)

From the debug log I can see that the automation is indeed exectued when the alarm is triggered:
> 2024-06-02 08:44:21.312 DEBUG (MainThread) [custom_components.alarmo.automations] state of alarm_control_panel.master is updated from armed_home to triggered
2024-06-02 08:44:21.312 DEBUG (MainThread) [custom_components.alarmo.automations] Executing automation 1717309887

**Comment by burbon-pl** [comment]
"It woks for me" doesn't prove anything.
My configuration looks exactly the same (apart of that "script" in Task of course - i have "relay on" function there).
If I set area to "master", when PIR detects movement the alarm zone where the PIR belongs triggers, the master also - but the relay doesn't fire up. If I change area from "master" to one of the subzones - relay reacts properly.
I've just made another test: with area set to "master", but the event set to "Alarm no longer triggered", the relay works after alarm ends and alarm arms back (ca. 1 minute from alarm triggering).

**Comment by burbon-pl** [comment]
It also works with "Alarm is armed", "Alarm is disarmed" and "Failed to arm" events. Just the most important "Alarm is triggered" doesn't work.

**Comment by nielsfaber** [comment]
With the information you provided I was unable to reproduce the issue. So I don’t really know how to help you. Perhaps you can make a screen video demonstrating what you do and how the system responds?

**Comment by nielsfaber** [comment]
I just created this action to duplicate yours:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/562e3f7a-042d-496f-8e9b-707c24126caf)

Next, with the siren off, I arm the master alarm.
![image](https://github.com/nielsfaber/alarmo/assets/16861605/94ac8a22-8dd1-4503-bb21-bc0caf59ba40)

Next I trigger a sensor linked to an area, such that the master alarm is triggered. The siren was turned on:
![image](https://github.com/nielsfaber/alarmo/assets/16861605/3e70ff6e-de74-4496-817f-2584edba3550)

Same as previous, it works OK for me.
I don't see any issue, so I don't know how to help you.

**Comment by burbon-pl** [comment]
![Zrzut ekranu z 2024-06-06 21-10-50](https://github.com/nielsfaber/alarmo/assets/158087437/61fd679d-8dce-49fb-823c-393c91955f59)
Here the log from two subsequent tests:
-first - the alarm fails to arm because of one sensor missing. Event set to "failed to arm", area "master". Relay fires up.
-second - the alarm is triggered by one of the sensors. Event set to "alarm is triggered", area "master". Action doesn't work.
