### ISSUE TITLE
force arming when already armed (another mode) is not working

### ISSUE THREAD

**Issue by mrgrlscz** [nielsfaber/alarmo#943]
### Alarmo Version

v1.10.1

### HA Version

2024.5

### Bug description

When alarmo is `disarmed`, if I want to arm in `armed_away ` when i live my home but some sensors are not OK, i receive an alarmo notification from wich i can force arming, by ignoring those sensors. That is OK, BUT:
If alarmo is in `armed_home` mode, if y try to `arm_away` when living, i receive the same notification but forcing do NOT work.

### Steps to reproduce

try to force arming from one mode (not `disarmed`) to another by ignoring open sensors

**Comment by nielsfaber** [comment]
Thanks for reporting the issue, I made a fix for this (https://github.com/nielsfaber/alarmo/commit/04f7754488f4aa972d0a0ae9f3bdc0187c548c66).
I will let you know once the change is released, so you could test if it works OK now.

**Comment by nielsfaber** [comment]
The fix is now included in release v1.10.2, please update to the latest version and test if it works OK for you now.
You can close the issue if so, otherwise please let me know.

**Comment by mrgrlscz** [comment]
It works like a charm!!
Thank you so much.
