### ISSUE TITLE
Unable to add scripts on Actions

### ISSUE THREAD

**Issue by raedkit** [nielsfaber/alarmo#945]
### Alarmo Version

v1.10.1

### HA Version

2024.5.3

### Bug description

On this version of Alarmo I'm unable to add any script on actions for when alarmo is triggered. I have always an error : required key 'service' is missing even if it really exists the YAML

### Steps to reproduce

1. go to Actions tab
2. Create a new action 
3. Add as a trigger : alarm is triggered 
4. As an action select a script
5. Click on run button for the script
6. Add a description of the action on the field below
7. Click on save button
8. An error message appears on the service run button with required (even if it's already clicked) 
9. When switching to yaml it appears : required key 'service' is missing eventhough it appears on the yaml

**Comment by nielsfaber** [comment]
I took a look into this. My finding was that this issue only occurs in case you have a script that is later renamed. As a result the entity_id of the script could be different to the service that is related, Alarmo is unable to find it back.
I made some changes to improve this (https://github.com/nielsfaber/alarmo/commit/b454170b560e34bf4f126891dc41d0dadc743f89), I will let you know when this is released.

**Comment by DJaeger** [comment]
As I have the same issue, I researched this and it seems to bee a core issue:
https://github.com/home-assistant/core/issues/115334

The change you've made in https://github.com/nielsfaber/alarmo/commit/b454170b560e34bf4f126891dc41d0dadc743f89 is a breaking change, as it changes the behaviour of how the scripts are started, if more than one is defined:
https://www.home-assistant.io/integrations/script/#waiting-for-script-to-complete

**Comment by nielsfaber** [comment]
@DJaeger Thanks for your comment, I'm glad that you pointed out this is a core issue (which hopefully will get some attention soon).
> The change you've made in https://github.com/nielsfaber/alarmo/commit/b454170b560e34bf4f126891dc41d0dadc743f89 is a breaking change, as it changes the behaviour of how the scripts are started, if more than one is defined:

I don't quite follow your point here.
For a script having entity `script.my_new_entity_name` and related service `script.my_original_entity_name`, before the change Alarmo would create yaml config for the service call as such:
```yaml
service: script.my_new_entity_name
entity_id: script.my_new_entity_name
data: {}
```

and after the change:
```yaml
service: script.my_original_entity_name
entity_id: script.my_original_entity_name
data: {}
```

Effectively, Alarmo no longer looks at the entity list to find scripts (and their IDs) but takes them from the service list.
Technically both are wrong, in the old code the wrong service would be called, in the new code the wrong entity_id will be passed. But I couldn't find a way to find the matching entity_id for a given service. It seems that passing the entity_id when calling a script is optional and doesn't have any effect.

**Comment by DJaeger** [comment]
@nielsfaber Your're right, I overlooked an exclamation mark and misunderstood it, sorry.
The entity_id seems to be required only when using e.g. `script.turn_on`

**Comment by raedkit** [comment]
> @raedkit The fix is now included in release v1.10.2, please update to the latest version and test if it works OK for you now. You can close the issue if so, otherwise please let me know.

Thank you for the fix. I will test it this weekend and will let you know.

**Comment by infinitenewworld** [comment]
This is still happening for me on 1.10.7

**Comment by matmoeh** [comment]
> This is still happening for me on 1.10.7

I am still having problems too. I found a workarout: Only scripts with the name "script" in it will be listed.
created "test" (script.test) -> not listed
Edited the name in script editor (edit script and use the function rename) to "test script" -> listed
the entity-id will be still the same -> script.test. It is only changing the friendly_name

**Comment by johnyee916** [comment]
I have the same/similar issue while using a switch. With the UI, it says that Action is required but after I switch to YAML, it says Required key 'service' is missing.

![2024-12-28 17_45_57-Alarmo – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/546b760c-3a96-429a-bfcd-d3fd29983a15)
![2024-12-28 17_46_11-Alarmo – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/79ac5758-b679-4585-a64c-d73c8b031af2)

**Comment by johnyee916** [comment]
> This is still happening for me on 1.10.7

Same for me but I'm using a switch entity.
![2024-12-28 17_46_11-Alarmo – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/879ef2f3-6688-4463-8b3f-4ed70262b1df)
![2024-12-28 17_45_57-Alarmo – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/88b00e0d-15ec-424d-af0f-107400006ca5)

**Comment by mjleonides** [comment]
> > This is still happening for me on 1.10.7
> 
> I am still having problems too. I found a workarout: Only scripts with the name "script" in it will be listed. created "test" (script.test) -> not listed Edited the name in script editor (edit script and use the function rename) to "test script" -> listed the entity-id will be still the same -> script.test. It is only changing the friendly_name

This worked for two scripts that I tried, but failed with a third. Renaming script to "Script: Script Name" from the scripts page (renaming from inside the script editor itself did not work) allowed a couple more scripts to show up in the Alarmo actions panel. The workaround that worked the best was using the YAML editor to call the "script.turn_on" service.
```
-  service: script.turn_on
   entity_id: script.script_name
````
This found the script for me regardless of it showing up in the Alarmo actions dropdown.
