### ISSUE TITLE
Use labels for sensor selection

### ISSUE THREAD

**Issue by dannytrigo** [nielsfaber/alarmo#946]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
With the recent addition of labels to Home Assistant it would be great to generically select all sensors with a particular label to be used for certain arming modes. For example, use all sensors labelled "alarm_away" for the away mode alarm.

With that, I could manage sensors, for example adding a new door sensor, and just label it appropriately and it would be used by Alarmo automatically instead of having to maintain the Alarmo configuration separately

### Additional info
[some example of how the new functionality should look like]

**Comment by jftanner** [comment]
I'd still like to see this.

**Comment by jftanner** [comment]
I'd still like to see this.
