### ISSUE TITLE
Disarming Alarm without the code returns success (but doesn't disarm the system)

### ISSUE THREAD

**Issue by Mattheinrichs** [nielsfaber/alarmo#947]
### Alarmo Version

v1.10.1

### HA Version

2024.5.4

### Bug description

Disarming Alarm without the code returns success (but doesn't disarm the system).
I have an existing automation that disables the alarm in the morning when I get up. I put on a PIN code yesterday and the automation still runs successfully - but the alarm was still running this morning. I checked the logs (no Disarm event) and the automation trace (no indicator of anything but success).

### Steps to reproduce

see above

**Comment by nielsfaber** [comment]
What do you mean by 'returns success' ?
If I understand you correctly, you created an automation in which a service is called to disarm alarmo.
The service does not return anything, so I don't see how you can evaluate whether the call was successful or not.

**Comment by Mattheinrichs** [comment]
I’m probably making some bad assumptions here.
My issue was that everything looked correct with the automation trace (even though the system didn’t disarm). Made my debugging challenging.
(Side note - just started using your plugin , along with Ring keypad - it’s been amazing)

**Comment by Jeronimo1971** [comment]
I get also an error, while arming without code?? 
Error running action
Arming requires a code but none was given for alarm_control_panel.aqara_hub_m1s_9635_security_system

**Comment by nielsfaber** [comment]
@Jeronimo1971 this is not aqara project. Please take care before reporting an issue

**Comment by Jeronimo1971** [comment]
I don't think i has something to do with home assistant 2024.6.
Disarming whitout code error is dissapeard with update 2024.6.1 but the arm error is still there.
It's for example with the aqara hub (asks always after a code), but also "alarmo", no error but it does nothing!
