### ISSUE TITLE
Unable to disarm alarmo with Google

### ISSUE THREAD

**Issue by awptechnologies** [nielsfaber/alarmo#955]
### Alarmo Version

v1.10.1

### HA Version

2024.7.0.dev

### Bug description

I see the alarmo entity in google but there are no options. If i say arm or disarm google says i dont know which alarm system

### Steps to reproduce

Just try to arm or disarm

**Comment by nielsfaber** [comment]
You should report this bug in HA, not here. This seems not related to Alarmo.

**Comment by awptechnologies** [comment]
i figured it out with it knowing which alarm. Now when i say arm my security system to home it says it fails in google but alarmo shows it works. When trying to disarm it it says sorry something went wrong controlling alarmo
