### ISSUE TITLE
Alarmo integrate with other Alarm system

### ISSUE THREAD

**Issue by aLAN-LDZ** [nielsfaber/alarmo#958]
Integration of the SATEL alarm system with the alarmo system. In one sentence, the ability to unlock other alarms from the alarmo level. This would be a great extension of alarmo and the possibility of better security

In the alarmo www panel, in the actions section, I want to configure an action that will disarm my default alarm system:

- service: alarm_control_panel.alarm_disarm
  data:
    entity_id: alarm_control_panel.dom
    code: "1234"
    
I wrote something like this and it works without any problems. 

However, I would like to not provide anything in the code (for security reasons) and receive this data from the code "entered" by the user? 
I can somehow pass this (code enered in UI) to the code section and thus decode my real alarm

**Comment by nielsfaber** [comment]
Alarmo will not forward the entered code when executing an automation.
The code is treated as confidential and is encrypted by alarmo, so this information is not available for passing to an automation.
