### ISSUE TITLE
Master Card has no code option

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#96]
Hi,

I've added a new alarm card for the master, but I get no option to enter a code:
![image](https://user-images.githubusercontent.com/1751192/104884627-8f291700-59cb-11eb-90ee-3b23852f2209.png)

Both house  and garage have a code when you select the entity. Am I missing something again? :-)

Thanks,
Stefan

**Comment by nielsfaber** [comment]
Convenient for testing, but not for usage.
I guess you will not be able to arm then, as the code is still needed but never provided.
I will check this out, thanks for reporting!

**Comment by stefanolson** [comment]
Thanks. Yes, can't arm :-) I presume I should be able to do it through my custom app that I've written. Haven't tested that yet.

**Comment by stefanolson** [comment]
I can confirm that I can't Arm master through code either. I can arm house no problem at all, but master just ignores my request :-(

**Comment by nielsfaber** [comment]
This should be solved in v1.5.0.
Sorry for the inconvenience (to the point of being non-usable) :sweat_smile:

**Comment by stefanolson** [comment]
No worries, I really appreciate the time you've put in to making this work!  However, I can't actually find a way to get alarmed.  When I enter my alarm code and press arm on master nothing happens :-( Nothing in the log, even enter the wrong code.   Home works (although didn't seem to initially but that's working now)

**Comment by nielsfaber** [comment]
Can you share the properties of your alarm entities (from Developer Tools -> States)?

**Comment by stefanolson** [comment]
Sure:
Master:
disarmed

code_format: number
changed_by: Stefan
code_arm_required: true
arm_mode: null
open_sensors: null
bypassed_sensors: null
friendly_name: master
icon: 'mdi:shield-home'
supported_features: 0

Home:
disarmed

code_format: number
changed_by: Stefan
code_arm_required: true
arm_mode: null
open_sensors: null
bypassed_sensors: null
friendly_name: House
icon: 'mdi:shield-home'
supported_features: 2

Garage:
disarmed

code_format: number
changed_by: null
code_arm_required: true
arm_mode: null
open_sensors: null
bypassed_sensors: null
friendly_name: Garage
icon: 'mdi:shield-home'
supported_features: 0

**Comment by stefanolson** [comment]
Also, I am managed to trigger the home alarm when armed and that caused the master alarm to be triggered. So that's interesting..

**Comment by nielsfaber** [comment]
`supported_features: 0` suggests that neither away/home/night modes are enabled for your garage area. Please check that.

> Also, I am managed to trigger the home alarm when armed and that caused the master alarm to be triggered. So that's interesting..

That's intentionally.

I wrote a bit more about the behaviour of the Alarm Master: https://github.com/nielsfaber/alarmo#alarm-master

**Comment by stefanolson** [comment]
Ok, Garage now has away enabled, Thanks. now sorted!  Sorry that I missed that :-)

Regarding the master being triggered I was pleased at least that was all linking in properly.  Now I can get the rest of the alarm system working and attached to the sirens.

**Comment by stefanolson** [comment]
Arming master works, Disarming doesn't. When I disarm from the master alarm card nothing happens. If I manually go and disarm both house and garage then that works. Hopefully I'm missing  something :-)

**Comment by stefanolson** [comment]
To avoid confusion I'm going to close this issue because it is fixed and add a new issue for the disarming of master.
