### ISSUE TITLE
Alarm can no longer be disarmed by Alarmo Button

### ISSUE THREAD

**Issue by eyalspier** [nielsfaber/alarmo#963]
### Alarmo Version

v1.9.13

### HA Version

2024.6

### Bug description

When attempting to disarm, the following message is received:
Failed to call service alarm_control_panel/alarm_disarm. AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given

### Steps to reproduce

Click on disarm button

**Comment by eyalspier** [comment]
Many thanks - I'll use that in the interim!

**Comment by eyalspier** [comment]
Correct, 1.9.13

**Comment by cfitzge1** [comment]
This happened to me this morning as well, triggered my alarm and I wasnt able to turn it off without stopping my hass container

**Comment by eyalspier** [comment]
How can I update it? I don't have any option?

**Comment by JGPorteous** [comment]
Confirmed same issue.
HA Version
2024.6.0

Alarmo Version 
1.10.1

**Comment by nielsfaber** [comment]
Don’t create bug reports for old versions

**Comment by JGPorteous** [comment]
> How can I get the newer version running within the home assistant docker container? I don't have any update option there.

My HA didn’t offer me the new version.
I manually updated by selecting:
Settings -> System -> Updates -> Refresh

**Comment by eyalspier** [comment]
> > How can I get the newer version running within the home assistant docker container? I don't have any update option there.
> 
> 
> 
> My HA didn’t offer me the new version.
> 
> I manually updated by selecting:
> 
> Settings -> System -> Updates -> Refresh

I tried it, also tried removing and reinstalling alarmo but it still goes back to the old version. Is there anything else I could try?
