### ISSUE TITLE
Async_alarm_disarm() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by jeroenterheerdt** [nielsfaber/alarmo#964]
### Alarmo Version

 v1.10.2

### HA Version

2024.6.0

### Bug description

Whenever you disarm an alarm the error shows up and the alarm doesn't disarm.

### Steps to reproduce

Try to disarm the alarm manually or in an automation/script and see this error:
```AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given```

**Comment by YorkshireHillbilly** [comment]
+1 Can't disarm my alarmo 'Burglar Alarm'
`Failed to call service alarm_control_panel/alarm_disarm. AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given`

**Comment by jeroenterheerdt** [comment]
I had to downgrade to v1.10.0 to resolve this issue.

**Comment by nielsfaber** [comment]
@jeroenterheerdt Can you share more information? I'm looking for the following:
* How are you disarming? via a service call? via alarm panel card? via alarmo card? via MQTT?
* What are you disarming? alarmo master entity or normal area entity?
* What is exactly printed in the logs (including line numbers)?

**Comment by Nocsaron** [comment]
> @jeroenterheerdt Can you share more information? I'm looking for the following:
> * How are you disarming? via a service call? via alarm panel card? via alarmo card? via MQTT?
> * What are you disarming? alarmo master entity or normal area entity?
> * What is exactly printed in the logs (including line numbers)?

I'm having the same issue to. I'm disarming via an alarmo card. 

Here are the log outputs (I'm on mobile so sorry for what I know is terrible formatting. 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:53:24 AM (4 occurrences)
Last logged: 12:56:16 PM

[140320813223792] Unexpected exception
[140320769248416] Unexpected exception
[140320596645712] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 207, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given

**Comment by nielsfaber** [comment]
@Nocsaron Please update to latest alarmo version before posting an issue.

**Comment by PSfreak** [comment]
I have the same issue, Alarmo 1.10.1 HA 2024.6.0
Error: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given
When i downgraded to HA 2024.5.5 everything worked again

**Comment by nielsfaber** [comment]
@PSfreak Please update to latest alarmo version before posting an issue.

**Comment by PSfreak** [comment]
> @PSfreak Please update to latest alarmo version before posting an issue.

I dont have a update, where do i get it?

**Comment by nielsfaber** [comment]
@PSfreak the same way as all other updates, via HACS or here: https://github.com/nielsfaber/alarmo/releases

**Comment by PSfreak** [comment]
> @PSfreak the same way as all other updates, via HACS or here: https://github.com/nielsfaber/alarmo/releases

Thanks, everything is working now. 
Info: I was not offered an update through HACS, but manual worked fine

**Comment by jeroenterheerdt** [comment]
> @jeroenterheerdt Can you share more information? I'm looking for the following:
> 
> * How are you disarming? via a service call? via alarm panel card? via alarmo card? via MQTT?
   was disarming via service call, alarm panel card

> * What are you disarming? alarmo master entity or normal area entity?
  master entity

> * What is exactly printed in the logs (including line numbers)?
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:53:24 AM (4 occurrences)
Last logged: 12:56:16 PM

[140320813223792] Unexpected exception
[140320769248416] Unexpected exception
[140320596645712] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/init.py", line 207, in async_handle_alarm_disarm
await self.async_alarm_disarm(self.code_or_default_code(code))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given
```

I have resolved this by downgrading to v.1.10.0

**Comment by nielsfaber** [comment]
@jeroenterheerdt Are you sure you updated to v1.10.2 (and restarted HA) when this error occurred?
The error logging you shared suggests that you were running an older version.
Could you please retry updating to the latest revision?
Downgrading will not help tackling the issue.

**Comment by jeroenterheerdt** [comment]
updating to latest (again) seems to fix this. maybe some weird caching thing?

**Comment by jeroenterheerdt** [comment]
Turns out this was a core issue, not alarm https://github.com/home-assistant/core/pull/118961
