### ISSUE TITLE
Disarm MQTT not working

### ISSUE THREAD

**Issue by arnodu59115** [nielsfaber/alarmo#965]
### Alarmo Version

v1.10.2

### HA Version

2024.6.0

### Bug description

Hello, 

Since upgrading to version 1.10.2, I can no longer deactivate the alarm via MQTT (no problem with the panel).

No problem with activation via MQTT, only “disarm” is a problem. 

Can I downgrade to version 1.10.1 to see if it's this version that's causing the problem?

### Steps to reproduce

Info Zigbee2MQTT
info 2024-06-06 18:29:16MQTT publish: topic 'zigbee2mqtt/Clavier_Alarme', payload '{“action”:“disarm”,“action_code”:“****”,“action_transaction”:74,“action_zone”:23,“battery”:100,“battery_low”:false,“last_seen”:"2024-06-06T16:29:16. 469Z“,”linkquality“:98,”tamper“:false,”update“:{”installed_version“:131077,”latest_version“:131077,”state“:”idle“},”update_available“:false,”voltage":6000}'

**Comment by nielsfaber** [comment]
I can confirm the issue, I see it here as well.

**Comment by nielsfaber** [comment]
I released v1.10.3 which should resolve this issue. Please update and test if it works OK for you now.

**Comment by overdrivesFR** [comment]
Had the same issue since yesterday disarming with the NSPanel.
Works as intended with 1.10.3.

**Comment by Shaunpottie** [comment]
Same Issue, error at the bottom left of the screenshot
![Screenshot 2024-06-07 084014](https://github.com/nielsfaber/alarmo/assets/125748508/1ccd3e6f-e42c-4732-a0f3-bbed2d2d21de)

**Comment by Shaunpottie** [comment]
> I released v1.10.3 which should resolve this issue. Please update and test if it works OK for you now.

Please can you tell me how to update manually, I usually update when I get a notification.

I really don't want to uninstall and install and setup everything again!

**Comment by nielsfaber** [comment]
@Shaunpottie you can update via HACS. It should show that a newer version is available.
Updating is not the same as re-installing, there is no need for that.

**Comment by Shaunpottie** [comment]
> @Shaunpottie you can update via HACS. It should show that a newer version is available. Updating is not the same as re-installing, there is no need for that.

Thank you, I'm such an idiot, I never remember to check HACS. All working fine now again. Thank you again.

**Comment by arnodu59115** [comment]
Hello @nielsfaber , 

With version 1.10.3, I no longer have any problems with the disarm function.

Thanks for the quick fix :-)
