### ISSUE TITLE
Sensors open with delayed alarm

### ISSUE THREAD

**Issue by array81** [nielsfaber/alarmo#966]
In my configuration I set the alarm via keypad with a 10 second delay to be able to leave the house. After 10 seconds the alarm is activated. However, if I have an open sensor, I am only notified when Alarmo tries to activate the alarm when I have already left the house. Wouldn't it be possible in these cases (when an activation delay is chosen) to immediately check the sensors so as to immediately notify the problem?

**Comment by nielsfaber** [comment]
You can configure per sensor if it is allowed to be active during the exit delay or not.
Depending on the setting, arming would fail immediately or after the delay ends.
