### ISSUE TITLE
Alarmo not disarming

### ISSUE THREAD

**Issue by GeeGee-be** [nielsfaber/alarmo#969]
### Alarmo Version

V1.10.1

### HA Version

core-2024.6.1

### Bug description

No error when updating to cor 2024.6.1, but it is impossible to disarm. Arming is working fine. So we freaked out at night when our son came home after the update.
![IMG_8179](https://github.com/nielsfaber/alarmo/assets/76971374/63404a6d-1223-45bc-83e9-fc3374386cba)

### Steps to reproduce

Just try to disarm, it won’t work.
It seems it doesn’t except the code. See error in the picture.

**Comment by nielsfaber** [comment]
I don’t accept bug reports for older alarmo version. Please update.

**Comment by GeeGee-be** [comment]
Hi Niels,

Any reason why I can’t see the update notification in HACS?

I can’t seem to find another way than uninstall and redownload so it seems.
That should not be the way.

Thx

**Comment by nielsfaber** [comment]
I cannot help you with HACS, I can only say you are 2 releases behind (which were made specifically to tackle this issue).

**Comment by GeeGee-be** [comment]
Thx for the reply.
I did again the update and this time the update notification for Alarmo was
shown in Hacs.
I did the update of Alarmo and it works fine now.

Br
