### ISSUE TITLE
Edit Notification is empty

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#97]
In the beta 1.5.0b, when I try and edit an existing notification I get a  completely blank page:
![image](https://user-images.githubusercontent.com/1751192/104884998-28f0c400-59cc-11eb-9c73-7c8254550a01.png)

Presume this is a bug...

**Comment by nielsfaber** [comment]
Hi Stefan,
Could you check your browser logs for an error message?

**Comment by stefanolson** [comment]
I've cleared the browser cache now. (Ctrl+F5). it fixes the problem. So hopefully anyone else who sees this problem knows what to do. I'll close it.

**Comment by nielsfaber** [comment]
The version number of the frontend is always in the top right corner.
Cache refresh should only help if that was still at 1.4.1.
Which is strange because you were already able to set up areas, which is clearly an added feature in v1.5.0b.
I’m not convinced that there is no issue here..

**Comment by stefanolson** [comment]
Version # was right for sure.
