### ISSUE TITLE
AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by roinane** [nielsfaber/alarmo#970]
### Alarmo Version

v1.10.0

### HA Version

2024.6.1

### Bug description

While trying to disarm Alarmo, it does not disable but gives the error:
Service alarm_control_panel/alarm_disarm could not be called. AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given

### Steps to reproduce

1. Arm the Alarmo
2. Disarm the Alarmo

**Comment by dominic76** [comment]
Samme problem here.
