### ISSUE TITLE
Failed to Call Service

### ISSUE THREAD

**Issue by therealkeng** [nielsfaber/alarmo#975]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

1.10.1

### HA Version

2024.6.2

### Bug description

alarmo failed to call service alarm_control_panel/alarm_disarm. alarmobaseentity.async_alarm_disarm() takes 1 positional argument but 2 were given

### Steps to reproduce

Alarmo was set; tried to disarm and received the above error. The alarm stays set

Don't know if this is Alarmo or just a HA issue, but I don't see anything fixing this.

**Comment by therealkeng** [comment]
Apologies. I thought Alarmo would automatically update and assumed that it was the latest. I have updated to the latest version.

Thank you. Also, thank you for writing Alarmo.

**Comment by nielsfaber** [comment]
I closed your bug report because both items in the checklist were not actually checked. In the last week I received like 20 times the same bug report.

**Comment by therealkeng** [comment]
Thanks
