### ISSUE TITLE
Entity alarm_control_panel. not support this service.

### ISSUE THREAD

**Issue by ugoberenice** [nielsfaber/alarmo#977]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

1.10.3

### HA Version

2024.6.2

### Bug description

Good morning, since the last Home Assistant update, I have noticed that the alarm control panel is no longer working .
 When I click on the alarm activation button, I get this error: "Service call alarm_control_panel/alarm_arm_home failed. Entity alarm_control_panel.myhome does not support this service."
I

### Steps to reproduce

I tried to call the alarm service but everything seems fine to me. It's as if the alarm panel doesn't work with Alarmo.
Has anyone else had the same problem?

**Comment by nielsfaber** [comment]
It seems you have the ‘armed home’ mode disabled in alarmo.

**Comment by michaeltryl** [comment]
I cant arm my alarm in out. i have home activatet, but only arm out dont work
