### ISSUE TITLE
Can't remove area

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#98]
1.5.0b

So I've got into the notifications now, and trying to assign the notifications to the master area. It says leave empty to select the global alarm but empty is not an option since it was already assigned:
![image](https://user-images.githubusercontent.com/1751192/104885687-4a9e7b00-59cd-11eb-8156-4cb511a61c90.png)

Is there a workaround for that?

Thanks,
Stefan

**Comment by stefanolson** [comment]
Don't worry, can type it in and remove the text.

**Comment by nielsfaber** [comment]
You can click the X to clear the selection.
The question remains whether it’s desirable that your existing automations are all linked to the primary area you set up.
I guess in most cases you want to transfer them to the master (I called it global here?) alarm.

**Comment by stefanolson** [comment]
Yes, in all cases I do. But if it's only an upgrading issue then it will get resolved reasonably quickly. Whichever option you choose is not going to please everybody.
