### ISSUE TITLE
Missing Alarm control panel after updating

### ISSUE THREAD

**Issue by bubbarives** [nielsfaber/alarmo#981]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.3

### HA Version

2024.6.3

### Bug description

After updating to 2024.6.3 the alarm control panel disappeared, so I updated Alarmo thinking it would come back, but it did not. I had about a year-old version of Alarmo before updating.

### Steps to reproduce

send alarm change command and it says the alarm control panel missing.

**Comment by thogens** [comment]
Same here. No control panel. Can't reach configuration page anymore, as the link is dead.

**Comment by thogens** [comment]
I don't know why, but all of a sudden it work on my side. I think I tried to "refresh" the alarm page on my mobile phone and it began to work again. (On all devices)
