### ISSUE TITLE
custom notification by sensor type

### ISSUE THREAD

**Issue by DavidAntonin** [nielsfaber/alarmo#983]
Hi, I use Pushover for notifications because it can do different notification priorities and different notification tones. How to set different notifications for Environmental and Door sensors? Also for Environmental sensors I would like to use the highest priority notification.

**Comment by Jansen-AL** [comment]
That's a great idea. Would love the possibility to use different sounds with different sensors.

**Comment by thogens** [comment]
Great idea. For instance, I'd like to distinguish burglar and smoke alarm. 
For smoke, I'd like to switch all lights on and open window blinds. In case of burglar, I don't want to open the blinds ;-)
Any idea to make that happen?
