### ISSUE TITLE
Automation disarm

### ISSUE THREAD

**Issue by bdominik185** [nielsfaber/alarmo#984]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

V1.10.1

### HA Version

2024.6.4

### Bug description

I had automation to disarm alarm at set time. No longer working. Trace error and receive this:  Error: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given

### Steps to reproduce

N/a

### Relevant log output

```shell
Error: AlarmoBaseEntity.async_alarm_disarm() takes 1 positional argument but 2 were given
```

**Comment by nielsfaber** [comment]
I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))

Are you sure?

**Comment by matthew-mclaren** [comment]
I had this problem on a previous build. I just updated to v1.10.4, rebooted home assistant and now it's working again.
