### ISSUE TITLE
Disarming the alarm with an automation

### ISSUE THREAD

**Issue by neldonado** [nielsfaber/alarmo#99]
I am trying to setup an automation through home assistant to disarm the alarm. When I do so it will tell me I have the wrong code. This is how I have it setup:

`Event:
ios.action_fired`

`actionName: Turn off alarm`
`code: 123456 alarm_code`

Is there a different way I should be introducing the alarm code into the automation data field?

**Comment by nielsfaber** [comment]
Try putting the code between brackets.
The problem is that if you send it as a number, zeros at the start are removed.
So Alarmo treats a pincode as text.

**Comment by neldonado** [comment]
> 
> 
> Try putting the code between quotes.
> The problem is that if you send it as a number, zeros at the start are removed.
> So Alarmo treats a pincode as text.

I figured it out. I was putting the code in the trigger event instead of the action event. :D
