### ISSUE TITLE
Prevent Alarm Functionality from Being Blocked by Updates

### ISSUE THREAD

**Issue by Beau11999988** [nielsfaber/alarmo#990]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

 v1.10.3

### HA Version

2024.7.1

### Bug description

I have the issue that every time there is an update, I can't arm or disarm my alarm. Is it possible to prevent this function from being blocked when I haven't done the update yet?

The annoying thing is that if my alarm is on, I can't turn it off until after the update.

### Steps to reproduce

Running one version behind and trying to arm away.

**Comment by smarthomefamilyverrips** [comment]
@Beau11999988 you are not using latest version of alarmo 1.10.4 is latest and have some fixes for Homa Assistant version 2024.7.x

**Comment by Beau11999988** [comment]
Yes, I know. That is the problem. If I have an update, I can't arm or disarm the alarm. This is the second time it has happened. It is very inconvenient because last time, I had my alarm on, and when there was an update, I couldn't disarm the alarm. When I came home, I figured out that it was the update that made it impossible to disarm, and my alarm went off.

**Comment by smarthomefamilyverrips** [comment]
Ha so you are saying if there is a alarmo update available your current version of alarmo not letting you arm/disarm alarmo anymore until you do the update of alarmo till last version?

If this is the case personally I not have this problem at me also shows there is a new version of alarmo available for update,  but all of alarmo is still functional. I did think you did mean you could not arm/disarm anymore after you did do a Home Assistant update that is why is suggested to update to latest version.

**Comment by Beau11999988** [comment]
Okay, I have now installed the latest version. I can only try when there is a new update. If it is not working again, I will send a message here.
