### ISSUE TITLE
No Telegram notification in Alarmo - Bug or missing feature

### ISSUE THREAD

**Issue by kitty99hub** [nielsfaber/alarmo#992]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.7.7

### Bug description

Hi.

Many thanks for this great ALARMO integration :)
It is a real game changer in handling alarm systems in Home Assistant.

During configuring ALARMO I encounter a problem for my notifications....
Since I send all Home Assistant relevant notifications via Telegram (Channel), I would also realy like to send the ALARMO notifications via Telegram, but it seems it is not supportet by the ALARMO integration !?
When I configure a "notification action" in ALARMO, the Telegram notification bot is not available for selection!?

Ist that a bug or perhaps a missing feature...? I d'ont know and will realy appreciate any information and help.

Mans thanks

--> screenshot with availabilities under ALARMO and under HomeAssistant automations:
![image](https://github.com/nielsfaber/alarmo/assets/115743879/fb82eb82-dc6d-4861-a689-dff96135e7f0)

  

### Steps to reproduce

nz

### Relevant log output

```shell
nz
```

**Comment by kitty99hub** [comment]
Hi,
Does anyone have an idea?
I'm still looking for a solution and I'm wondering what other users are doing for Telegram notification...
Is there anyone here who also uses Telegram for their HA notifications and could tell me what it looks there like in ALARMO or what solution is used?
I would be very happy if I could somehow get further, or at least know if it's a missing function in Alarmo or a bug or maybe it just doesn't work for me.
many thanks
Best regards

**Comment by h3x89** [comment]
@kitty99hub I am using n8n with http endpoint and all my Home Assistant triggers point to that:

configuration.yaml
`rest_command:
  home_assistant:
    url: "http://192.168.3.159:5678/webhook/home_assistant"
    method: POST
    headers:
      Content-Type: application/json
      User-Agent: "Home Assistant Webhook"
    payload: >
      {
        "title": "{{ title }}",
        "priority": "{{ priority }}",
        "message": "{{ message }}"
      }`
      
 and here you have my alarmo action configuration:
 
![image](https://github.com/user-attachments/assets/c3fa88b0-0912-4a40-b894-b30107d20d9f)

**Comment by masi** [comment]
@kitty99hub You can use Alarmo actions to trigger any script you want. I think it should be possible to trigger the Telegram notification this way.

**Comment by Rico2303** [comment]
I have Telegramm bot available in alarmo but seems Not to Work. When using developer tool in ha I am able to use it and send Telegramm Message. So the "notify.telegrammusername" notification ist available and working well in other automations, but Not in alarmo. Any ideas?

From what I saw in Log:

[homeassistant.components.telegram_bot.bot] Error sending message: Can't parse entities: character '!' is reserved and must be escaped with the preceding '\'. Args: (1282734lXXXX, 'Alarm Event occured!\nDer Alarm wurde ausgelöst! Ursache: Some Example Sensor is open.'), kwargs: {'parse_mode': <ParseMode.MARKDOWN_V2>, 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'read_timeout': None, 'message_thread_id': None}
