### ISSUE TITLE
Action cannot be executed (arm_away when arm_home and alarm goes triggered)

### ISSUE THREAD

**Issue by kslcsdalsadg** [nielsfaber/alarmo#993]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.7.1 (frontend 20240705.0)

### Bug description

I have a action that changes the current arm mode from "armed_home" to "armed_away" when the alarm in "armed_home" state and the alarm is triggered but the action is never executed.
I have tried to test the action clicking the test button and is working, but doesn't work in other case.

![image](https://github.com/nielsfaber/alarmo/assets/31618496/05226293-2fbc-4466-be64-b0db72464462)

### Steps to reproduce

* Create an action that changes the arm mode from armed_home to armed_away when alarm triggered
* Set the armed_home mode
* Trigger the alarm
* The action is executed but can't be completed (see logs)

### Relevant log output

```shell
Home Assistant LOG

2024-07-09 12:10:55.934 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state armed_away from state triggered.
2024-07-09 12:10:55.935 DEBUG (MainThread) [custom_components.alarmo.mqtt] Published state 'triggered' on topic 'alarmo/state'
```

**Comment by nielsfaber** [comment]
If the alarm is triggered, it needs to be disarmed before it can be armed again.

**Comment by kslcsdalsadg** [comment]
And can't be forced?

**Comment by nielsfaber** [comment]
No this cannot be forced.
