### ISSUE TITLE
Errors after update - setup failed 

### ISSUE THREAD

**Issue by GRClark** [nielsfaber/alarmo#994]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.6.4

### Bug description

Alarmo not working or loading after recent update.  Stuck unavailable.  

### Steps to reproduce

No steps, just updated. 
![IMG_5154](https://github.com/nielsfaber/alarmo/assets/5118059/ab1a0356-13f3-421a-8ff2-852977f938c6)
![IMG_5155](https://github.com/nielsfaber/alarmo/assets/5118059/9d3ac753-525f-40f9-a3b0-33eac023a444)

**Comment by lostage** [comment]
Did you intend to close this? I'm having the same issue; restarting didn't help. I reverted to v1.10.3 to fix for now

**Comment by GRClark** [comment]
Noticed elsewhere the latest update requires July edition of HA and I’m
still on June.
