### ISSUE TITLE
Alarm disarming itself immediately after arming

### ISSUE THREAD

**Issue by sn4201** [nielsfaber/alarmo#996]
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.7.1

### Bug description

Starting 1-2 weeks ago, i have realised that my alarm no longer can successfully arm.  It had been working properly for months.  Now whenever the alarmo.arm function is called (either by automation, or by the control panel), alarmo immediately disarms afterward.  I'm not sure why or how to resolve it.  Updating to the latest alarmo and HA versions has not helped to fix.

![image](https://github.com/nielsfaber/alarmo/assets/109926731/3b6ccb6b-2fc1-4dca-aed7-d0223a8651f5)

### Steps to reproduce

Trigger alarmo.arm via any method: automation, control panel, etc.

### Relevant log output

```shell
2024-07-09 21:23:15.207 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state disarmed from state disarmed.
2024-07-09 21:23:55.878 WARNING (MainThread) [custom_components.alarmo.alarm_control_panel] Cannot go to state disarmed from state disarmed.
```

**Comment by Nicooow** [comment]
Same issue here

**Comment by tekride** [comment]
Same issue here too

**Comment by VNRARA** [comment]
You guys need to check your settings. It's possible that its set to cancel arm when certain sensors are in triggered/open state.
